### ISSUE TITLE
Close websockets on inactivity

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1017]
Currently websockets stay open indefinitely as long as the underlying TCP connection stays alive, this is a DoS vector since there's a limit to how many websockets we will serve. We should close inactive websockets after a timeout (related to #1001).

We need to investigate how pings work, the websocket I opened via `websocat wss://alpha.demo.sirion.io` stayed open for multiple hours without receiving visible pings, maybe `websocat` or any standard conform client answers them in the background. In that case pings should not be sufficient to keep a WS open. Only if there's a subscription or regular calls it should be kept open.

**Comment by justinmoon** [comment]
Would be nice if, when we hit the connection limit, we just drop the connection that's been open longest without activity

**Comment by justinmoon** [comment]
Call: 
- Max websocket connections could be a local config option. Current limit is 100 or so.
- We could also break all websockets after N minutes. Active clients should be able to re-open
