### ISSUE TITLE
Database Migrations

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#1038]
# **Work In Progress**

## Context
Upgrading applications that use persistent state is notoriously difficult, and Fedimint is no exception. Fedimintd uses Rocksdb for the server's database, which is a key/value store that persists the data on disk. Rocksdb is a fork from LevelDB, which both use LSM trees for data organization. 

 A "database migration" refers to transforming the on disk data structures (that was used with code version N) into new on disk data structures (that will work with code version N + i). 

In a traditional SQL database, this can be accomplished using a set of SQL scripts, similar to the following:

`CREATE TABLE table_n_plus_i ...`
`INSERT INTO table_n_plus_i SELECT * FROM table_n`
`DROP TABLE table_n`

The SQL scripts could then define transformations over the fields in the SELECT clause and predicates in the WHERE clause to properly create the new on disk data structures.

Since Fedimintd uses a key/value store instead of a SQL database, we will need to build on our own library/binary (ideally runs as part of fedimintd startup or separately) to do these transformations.

### Goals

- A user running with code version N + i, but with database structures of version N, can simply start fedimintd and the server will come up correctly with the correct data structures.
- i can be an arbitrary number. We should support upgrading the code from any version to any version, so that users never get stuck with a database that cannot be upgraded to the latest code. That said, supporting an arbitrary number of migrations will become un-maintainable. We will need a mechanism for limiting the complexity of migrations while still allowing users to upgrade to any version. 

### Non-goals

- Efficient in-place database migrations. We would like the ability to roll back to a previous version if the database migration fails for any reason. Because of this, we will need to make a new copy of the database. Depending on the size of the database and the transformations defined, this could take some time. 
- Live migrations. For now, while upgrading, the federation is expected to experience downtime. Handling differing consensus rules and differing versions amongst guardians is out of scope for now.

### Upgrade Process

- Coordinate shutdown of Federation at given Epoch
- Install new fedimintd binaries
- Start new fedimintd
- **Fedimintd migrates the DB contents and config before the federation starts**

This document is intended to only describe the last step of this process.

## Limiting the Complexity of Migrations
As mentioned in Goal 2, we should support upgrading fedimintd from any version to any other version. However, this implies supporting an exponential number of migrations as we add more versions (ex: 1->2, 1->3, 1->4, 2->3, 2->4, 3->4, etc). Defining all of these migrations in code would be burdensome. Below are two proposals for mitigating this problem.

1) Support migrations from version N to N+1. Loop from N to i to migrate to the latest version.
2) Support "groups" of migrations (i.e from version < N-5 to N). Can loop through each group to upgrade to the latest version.

Option 1 is the simplest for the developers of Fedimint as it only requires defining a migration between version N and version N+1. The drawback is that during the database migration, the user would need to loop over all upgrades to get to the latest version. This could involve doing multiple upgrades and making multiple copies of the database, which might be slow.

Option 2 adds a bit more complexity on the developers of Fedimint, but could be faster for the user during migration. This option would involve defining all migrations within a group of versions (ex 1->2, 1->3, 2->3, etc). Then, during database migration, the user would only need to loop over the groups, lookup the corresponding migration within the group, and apply it. In the example stated, a user upgrading from version 1 to version 3 would simply apply the 1->3 migration, instead of doing 1->2 and then 2->3 as in option 1.

## Transformations
When doing a database migration from version N to N + i, there are a number of transformations that can occur. These transformations reflect changes in the database schema from version N to N + i. Because we are using a key/value store, the number of possible transformations is reduced.

- **Addition**: A new key/value pair is introduced that did not exist in version N.
- **Removal**: A key/value pair in version N is no longer used in version N.
- **Key Modification**: The serialized key structure for a key/value pair has changed. Could be additional fields in the underlying struct, a change of datatype in a field in the underlying struct, or a removal of a field in the underlying struct.
- **Value Modification**: The serialized value structure for a key/value pair has changed. Could be additional fields in the underlying struct, a change of datatype in a field in the underlying struct, or a removal of a field in the underlying struct.

### Migrations
This section describes how the migration tool should handle the above transformations.

- **Addition**: Either backfilling the new key/value pair with a default keys/values OR do nothing since the new code will populate the new key/value pair.
- **Removal**: Safe to ignore when doing the migration to reclaim space in the DB.
- **Key Modification**: Must apply user-defined transformation from key version N to key version N + i.
- **Value Modification**: Must apply user-defined transformation from value version N to value version N + i.

During fedimintd startup, it will be the responsibility of the DB migration code to detect when a migration is needed, then apply all of the relevant transformations. These transformations will need to be provided by the developer that added the new feature in the new version.

## Open Questions
1) In order to apply a transformation from version N to version N+i, the fedimintd code will need to have access to the structs for the keys/values in the database for both version N and version N+i. Currently, we do not support this as the key and value structs are modified in place. Perhaps codegen is an option to preserve backwards compatability?

**Comment by jkitman** [comment]
Would the implementation just be a complete scan and rewrite of K/V pairs?

Can we support rollbacks in case a migration fails midway or the updated DB has errors?

**Comment by dpc** [comment]
> We should support upgrading the code from any version to any version, so that users never get stuck with a database that cannot be upgraded to the latest code.

This is already very difficult. Not only one needs to keep around the definition all all data structures, but also retain the knowledge of the ways old data worked. At least right now I don't see enough resources to commit to supporting things very far back.

It would be safer to commit to support only migrations N versions back (could be time based), to avoid creating wrong expectations.


> Because of this, we will need to make a new copy of the database. Depending on the size of the database and the transformations defined, this could take some time.

It is expected that storage might be the main limiting resource for busy federation, as we will be keeping the whole history of used nonces.

Possibly we should treat the nonces differently somehow? It might be the heaviest item, while we don't expect that particular data format to change often? Could we maybe store it in another file or something? Would it be worth it? Just thinking aloud.

**Comment by m1sterc001guy** [comment]
> This is already very difficult. Not only one needs to keep around the definition all all data structures, but also retain the knowledge of the ways old data worked. At least right now I don't see enough resources to commit to supporting things very far back.
> 
> It would be safer to commit to support only migrations N versions back (could be time based), to avoid creating wrong expectations.

This would makes things easier. I am ok with this as long as that's the expectation the we set. Do we think it is worth investing in codegen to make maintaining the API of the database easier?

> Possibly we should treat the nonces differently somehow? It might be the heaviest item, while we don't expect that particular data format to change often? Could we maybe store it in another file or something? Would it be worth it? Just thinking aloud.

Interesting. Yes we could potentially treat the nonces differently, or even make it optional to do an "in-place" migration. Alternatively we could migrate everything besides the nonces to the new db, then delete the nonces while we migrate those to save space.

**Comment by dpc** [comment]
> I am ok with this as long as that's the expectation the we set. Do we think it is worth investing in codegen to make maintaining the API of the database easier?

My main point is exactly about expectations. We should probably set them low at the beginning and if it turns out we can do better, we always can.

I'm not sure about the codegen. If we always use `De/Encodable` to serialize everything into the DB, then for migrations we just need to `copy+paste` a given `struct FooBar`, rename to `FooBar_v15`, and keep it around for time being. 
I think we should avoid migrations and postpone them as much as we can. So if we avoid them, maybe there will be less need for them (less benefit of investing in codegen).

It seems to me that every module (especially 3rd party) might want to do its own migration schedule & handling, while the core fedimint should have little need for migrations. I'm not sure how much can we enforce anything, when we don't always have control over the code.

For a lot of little-volume data, it makes more sense to have a:

```
enum FooBar {
  V15(...)
  V16(...)
  V17(...)
}
```

and handle upgrading inline. If just new fields were added or something, then having a whole big migration seems too heavy, if the code can just "read any previous versions" and "write always the latest one", etc.


I guess it comes down to ... there are small migrations, that can be relatively easily handled in flight, and there are "big migrations" (in which we change large amount of data and the structure of keys etc). And there are also independent modules.

The strategy of copy everything & rewrite everything seems reasonable for major version migrations, that we should try to do once a year or couple of years, which would include architectural changes, changes in interfaces between fedimint and its modules etc. For modules, we could maybe copy all the module keys out, then allow module to upgrade itself and restore/delete the copy.

**Comment by m1sterc001guy** [comment]
Outdated, closing
