### ISSUE TITLE
Fetched config has wrong port and protocol for guardian API

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1047]
#953 only made the domain configurable independently, not the protocol and port. A freshly fetched config from `{"members":[[0,"wss://alpha.regtest.sirion.io"]]}` leads to the following connect info:

```
{
  "connect_info": {
    "members": [
      [
        0,
        "ws://alpha.regtest.sirion.io:5001/"
      ]
    ]
  }
}
```

**Comment by justinmoon** [comment]
Closed by https://github.com/fedimint/fedimint/pull/1194
