### ISSUE TITLE
Mint Consenus Item could be just `Vec<BlindedSignatureShare>`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1053]
Currently it is `TieredMulti<(tbs::BlindedMessage, tbs::BlindedSignatureShare)>`. There is no reason to repeat (heavy) `BlindedMessage`s and shares can be mapped to `MintOutput` 1:1 by just order in the vec, so no need for tiering by `Amount`s either.

BTW. While at it we'd like to change the `fn combine` in mint module to reject consensus item **altogether** if:

* structurally incorrect (length wrong)
* **any** signature is wrong

Currently this is not the case. Structurally incorrect consensus item is throw away whole, but the nonces validity is track on per-item basis, which is slightly different.

**Comment by elsirion** [comment]
As long as we can load the `BlindedMessage`s belonging to the signature share from the database that's the right move (should generally be possible). Currently we use our contribution as reference for validating the signature shares (and waste a lot of bandwidth by doing so).

**Comment by justinmoon** [comment]
@dpc @elsirion @joschisan Is this issue still relevant after https://github.com/fedimint/fedimint/pull/3419?

**Comment by elsirion** [comment]
Related to both #3227 and #3419, obsolete now.
