### ISSUE TITLE
Only receive messages from expected epochs from network stack

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1080]
If a node is partitioned from the rest of the federation for a while it will receive the messages from many epochs in one burst. While every peer connection is ordered we might receive messages from epoch `n+100` from one peer while we have only received messages up to epoch `n` from others, so are still at epoch `n` ourselves. This would lead us to drop the messages from the future (an anti-DoS measure by HBBFT), losing them.

To fix this problem we have to be able to specify that we only want to receive messages up to a certain epoch (determined by the maximum amount of parallel epochs set in HBBFT).

**Comment by jkitman** [comment]
If we implement filtering out-of-order received messages we will still need to buffer them in memory as we do in `PeerConnectionMultiplexer`.  If that were the case, then we might as well just increase `max_future_epochs` in HBBFT which will likely be a more memory-efficient way to buffer the messages.

So I think we need to implement the buffering on the sender-side by keeping track of what epoch our peers are on and only sending messages from `n` epochs ahead.  If our send buffer gets full then we clear the buffer and the peer will need to restart their server to run the rejoin logic (or perhaps we can add the logic to skip ahead when a peer detects they have fallen too far behind such as if the internet is down for a while).

**Comment by jkitman** [comment]
Summing up discussion on how to improve the network stack:

- [ ] In I/O thread, wrap the underlying connection in a buffer to make sending async, drop the connection if the buffer fills up
- [ ] Don't dump the entire resend buffer at once, just send when the connection buffer has room, drop connection if resend buffer fills up
- [ ] Detect missed epochs on the receive side, use it to determine when to rejoin

**Comment by jkitman** [comment]
Won't fix, since we have a workaround of rejoining at any point.  Plus when we have a new consensus algorithm we won't have epochs anymore and it seems like a lot of unnecessary work to add this to the network stack.
