### ISSUE TITLE
Change Debug/Display on BlindingKey / SpendingKey etc. to output a fingerprint or something

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1098]
We don't want these leaking in the logs.

**Comment by noone1235** [comment]
hey, I would like to work on this issue. just have to change all the keys displayed in various logs to output fingerprint by hashing it to a smaller value using function right? and also where is the good place to find which logs are storing keys?

**Comment by dpc** [comment]
Yes, though you don't need to look for specific logs. Only `Display` and `Debug` trait impls need to be changed.

**Comment by dpc** [comment]
Looks done.
