### ISSUE TITLE
It's very easy to forget about `.commit_tx()`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1100]
I already forgot about calling it couple of times, and just found a bug in existing code that also forgot about it.

Maybe we should log a warning message on drop if `DatabaseTransaction` was not committed? Any other ideas?

**Comment by elsirion** [comment]
I don't know what's the right balance between verbosity and safety here. Not having to worry about aborting txs when leaving a function via a `?` operator is nice. We could probably introduce a `map_err` in front of every one of these that takes a closure which aborts the tx?

Maybe we could make the destructor log an error if a tx was dropped without being aborted?

**Comment by dpc** [comment]
> Maybe we could make the destructor log an error if a tx was dropped without being aborted?

That what I've been thinking too. Possibly a way to mark that the transaction is expected to be dropped uncommited, and then just log a warning. It's not going to change any behavior, just help us spot any mistake.

**Comment by m1sterc001guy** [comment]
As discussed on the call, in addition to the above, it will probably be good to create a read-only transaction so that we don't log this warning when its not necessary to commit.

**Comment by m1sterc001guy** [comment]
I sent out a PR that implements this. One problem that I ran into is that there are some transactions that are not committed or aborted, they simply go out of scope when there's an error (most times the function returns without the chance to rollback). I added a way to surpress the warning message if that's the case.

**Comment by m1sterc001guy** [comment]
Warning message added when write transactions are not committed in [this PR](https://github.com/fedimint/fedimint/pull/1161)

**Comment by justinmoon** [comment]
> Warning message added when write transactions are not committed in [this PR](https://github.com/fedimint/fedimint/pull/1161)

I just forgot to call `.commit_tx()` and spent a bunch of time debugging it. A warning is great improvement, but I wonder if we could someday have a "debug mode" in Fedimint where it would just panic if this happened. Would save time in development.
