### ISSUE TITLE
Gateway CLN Plugin Architecture

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#1103]
From @elsirion  cc @okjodom @justinmoon 

Re: gateway : I had a nice call with cdecker, he proposed to build the CLN integration as a very minimal plugin that can intercept HTLCs etc. and a separate daemon that speaks to it via some RPC interface. The plugin can decide what to do if the daemon isn't available (probably just tell CLN to proceed as if it wasn't intercepting them). This would give us multiple wins:

1. The safet-critical code that makes CLN not close channels would be a small RPC forwarder plugin
2. The daemon would be easy to restart without touching CLN
3. We wouldn't have to pass logs through CLN which tends to mangle them, attaching debuggers becomes easier
4. Dealing with CLN and LND would become much more similar

I'm not sure if you already came up with that independently, I think it was at least discussed at some point. But it seems like a solid plan, especially since it's coming from the author of the plugin system.

**Comment by justinmoon** [comment]
Should help with #1018

**Comment by justinmoon** [comment]
Context from call: Sometimes our response task to htlc events in the CLN crashes. This causes HTLC to remain open and eventually timeout. This causes (I think) our peer to force-close our channel. We should always respond and never cause timeouts in this way.
