### ISSUE TITLE
Add remove_by_prefix to database transaction trait

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#1111]
A common pattern is to "find_by_prefix" and then delete all the keys within that range. This is efficient since it requires deleting individual keys. Would be more efficient to support a "remove_by_prefix" that would delete an entire key range.

**Comment by elsirion** [comment]
The function already exists and has a default impl that's less efficient than it could be:

https://github.com/fedimint/fedimint/blob/2cd9dd90d361cfbbd81525280bb54d2964aef6d2/fedimint-api/src/db/mod.rs#L108-L120

It's more about replacing this impl with native implementations for DB impls that are used in production.

**Comment by justinmoon** [comment]
Here's the native function for rocksdb, mentioned by @m1sterc001guy in another thread https://docs.rs/rocksdb/latest/rocksdb/struct.WriteBatchWithTransaction.html#method.delete_range

**Comment by m1sterc001guy** [comment]
Huh, turns out delete_range is not supported when using Transactions, only when using WriteBatches. They look very similar (both are atomic) but I dont think WriteBatchs give the ability to rollback.

For docs [delete_range] is not supported in [Transaction](https://docs.rs/rocksdb/latest/rocksdb/struct.Transaction.html).

I'll implement this for SQLite but I think for Rocksdb the default implementation is already the most efficient we can do (uses Rocksdb prefix iterators to pull in the keys to delete, then deletes them one by one).

**Comment by dpc** [comment]
So I guess this is OK to close.
