### ISSUE TITLE
Introduce read-only DB transactions

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1114]
This will allow solving #1100 without too much overhead (read-only tx don't need to be committed or dropped).

Maybe we could even allow building RO sub-tx from RW tx to not get into problems with different types.

**Comment by m1sterc001guy** [comment]
Closing since, as discussed in the PR, adding an explicit trait is not necessary and creates type headaches. Instead, a warning message has been adding for write transactions that do not commit.
