### ISSUE TITLE
Rename things around `EpochHistory` and `OutcomeHistory`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1115]
*putting on my rename-stuff hat* 

I don't think these names are very conductive. Seems to me that hbbft naming might be spilling over the the higher layer unnecessarily, and "history", "outcome", "epoch" and so are overlapping in meaning.

We should try to (it's never easy, but we can try) to put a line between hbbft and Fedimint. Types and other symbols from `hbbft` should have the `hbbft::` prefix retained, so it's clear they are coming from the lower layer. If something is defined in fedimint's code, but is directly a hbbft-layer thing, it should have a prefix and be named `HbbftXyz`

The `EpochHistory` probably should be just `SignedX` where `X` is whatever we replace `OutcomeHistory` with.

Now `OutcomeHistory` ... maybe `EpochOutcome`? My understanding is that it contains all the effects aka outcomes aka results of a given epoch that the Federation came to consensus about, and later signs. The name should try to reflect that (or whatever better meaning we come up with).

```
pub type ConsensusOutcome = Batch<Vec<ConsensusItem>, PeerId>;
```

Maybe we should rename to `HbbftConsensusOutcome`, just to make it obvious that it's just an alias for something from hbbft.

Thoughts?

**Comment by jkitman** [comment]
Even better would be a refactor to merge `OutcomeHistory` and `ConsensusOutcome` into a single struct without the dependency on `Batch`.  I think the only reason I didn't use the same struct was to avoid having to add `hbbft` as a dependency in the `core` crate.

Agree on renaming `EpochHistory` to `SignedConsensusOutcome` or something similar.

**Comment by elsirion** [comment]
`EpochOutcome`, `SignedEpochOutcome` and `HbbftConsensusOutcome` sound good to me. I'm generally a fan of untangling HBBFT and eventually making consensus a trait object that can be replaced with a mock impl or different BFT consensus for experimentation.
