### ISSUE TITLE
Client inter-process locking

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1120]
At least for recovery process, we would like to lock the client and disallow any operations. In practice it should never be an issue, as the higher-level code (application with UI, etc. will probably take care of it), but just to be on a safe-side we should implement it.

Possibly a library like this could be used:

https://docs.rs/file-lock/latest/file_lock/

**Comment by justinmoon** [comment]
Call: only 1 write db connection allowed at-a-time which helps here ... perhaps opening db should lock it?

**Comment by justinmoon** [comment]
Relates to #1447

**Comment by justinmoon** [comment]
Status here @dpc @elsirion?

**Comment by dpc** [comment]
> dev-call: only 1 write db connection allowed at-a-time which helps here ... perhaps opening db should lock it?

Probably good enough then.
