### ISSUE TITLE
Add a "dummy" fedimint module to the fedimint repo

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1128]
The purpose is to have:

* template for other people to copy&paste&modify
* comments to help new developers get a sense of what is what

By having it alongside real modules we will know it's always up to date.

**Comment by elsirion** [comment]
I think it should be there but not wired up in the default server/client binary. There could be an example binary that attaches it to the federation for CI and example purposes. This of course all assumes finished modularization.

**Comment by dpc** [comment]
Yeap. We only want it to compile, and really use it.

**Comment by justinmoon** [comment]
Closed by https://github.com/fedimint/fedimint/pull/1195
