### ISSUE TITLE
Network stack fixes

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1136]
- [x] Do not block if peer is not reading from socket (#1149)
- [x] Do not buffer infinite number of epochs for disconnected peers since that is a DoS vector and will actually not help currently if too many messages are sent and processed at once (from more epochs than max parallel epochs) (#1149)
- [ ] Figure out when to rejoin if too many peers dropped messages for us

I think to remember there was a third problem we discussed @jkitman, feel free to add.

**Comment by jkitman** [comment]
The above two cases should drop the connection, disconnected peers should attempt to reconnect, possibly rejoining if too many connections were dropped.

**Comment by elsirion** [comment]
I think in the first case we'd merely disconnect while in the second we'd also drop all buffers, forcing the peer to rejoin consensus if too many of its peers do the same.

**Comment by jkitman** [comment]
I meant in the first case we need to disconnect and drop buffers only once our buffer fills up.
