### ISSUE TITLE
Limit number of e-cash notes per denomination

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1141]
#1140 introduces `max_target_denomination_sets` as the maximum number of e-cash notes issuable per denomination in one output. We need to figure out what this number should be in relation to the target number of notes per denominations on the client side and if there should be exceptions for the highest used denomination (to allow adaptive coin selection for increased privacy).

**Comment by jkitman** [comment]
I set it to default at 3 based on the amount of additional signing time it added https://github.com/fedimint/fedimint/pull/1072

But it obviously varies with the amount sizes too.

**Comment by elsirion** [comment]
I think this can be closed after the work @jkitman has been doing. There is still #116 which is hinted at here, but that's a separate issue (although it will interact with this one).
