### ISSUE TITLE
Clippy warnings in Mac builds

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1157]
We have been seeing [clippy fail in MacOS builds recently](https://github.com/fedimint/fedimint/actions/runs/3745639760/jobs/6360278862). It is unclear to me why it fails there but not on PRs. I tried to fix one of the symptoms in #1154, but there seems to be more broken. 

Theories:
* We don't run clippy on all relevant crates on PRs
* The rust/clippy version used for MacOS has other lints enabled

**Comment by dpc** [comment]
Non-nix github action automatically updated to new Rust release.

**Comment by dpc** [comment]
#1158

**Comment by justinmoon** [comment]
On `5a8000bf9cd8189054c253e89981e4d6a3f2a038` this is what I get when running `cargo clippy`:

```
error[E0599]: no method named `coefficients` found for reference `&threshold_crypto::PublicKeySet` in the current scope
  --> fedimint-api/src/encoding/tbs.rs:45:33
   |
45 |         for coefficient in self.coefficients() {
   |                                 ^^^^^^^^^^^^ method not found in `&threshold_crypto::PublicKeySet`

warning: unused import: `threshold_crypto::group::Curve`
 --> fedimint-api/src/encoding/tbs.rs:3:5
  |
3 | use threshold_crypto::group::Curve;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0599`.
warning: `fedimint-api` (lib) generated 1 warning
error: could not compile `fedimint-api` due to previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
```

**Comment by justinmoon** [comment]
When I run `just clippy` I get no problems on my Mac. Closing this.

**Comment by dpc** [comment]
For reference: [we are now running MacOS build including clippy](https://github.com/fedimint/fedimint/actions/runs/6381805833/job/17319066827) in the merge queue, so problems like this should no longer be happening.
