### ISSUE TITLE
Stop using `actions-rs`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1172]
See https://github.com/rust-bitcoin/rust-bitcoin/pull/1509#issue-1512287084 . We use actions-rs just in a handful of places, but still we should do the same.

**Comment by oleonardolima** [comment]
@dpc I was taking a look at this one, both rust-bitcoin and a bunch of other projects started using the [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain).

Is the initial idea to do the same and update it to use it? Or there is another alternative that would be good to check too?

**Comment by dpc** [comment]
I think I've seen `rust-toolchain` being recommended, yes.

**Comment by oleonardolima** [comment]
Great! I can take a look at this one then.

**Comment by oleonardolima** [comment]
@dpc I've created a PR changing the rust-toolchain, would you mind taking a look at it?
