### ISSUE TITLE
`distributedgen` logging nits

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1176]
The first warning should probably be logged via `tracing` and the second one should probably be a of level `debug`. 

```
[root@hcpp:/var/lib/fedimint]# distributedgen run … --password password
WARNING: Passing in a password from the command line may be less secure!
2022-12-30T11:18:36.243536Z  WARN fedimintd::encrypt: READ "./tls-pk"
```

**Comment by dpc** [comment]
> `WARNING: Passing in a password from the command line may be less secure!`

IMO, instead of bothering with this is as a warning, we should only accept password as env variables and make the user do the right thing. (`#[arg(env="FEDIMINT_PASSPHRASE")]` IIRC).

**Comment by justinmoon** [comment]
DPC mentioned that passwords show up in PS output and history files.

**Comment by justinmoon** [comment]
Dev call: decided to just use environment variables
