### ISSUE TITLE
Gateway CLI should be able to spend / reissue ecash

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1178]
@elsirion just spun up a federation, and sent me some ecash. I was setting up a gateway for the federation at the time, and wanted to have this gateway client sweep these funds. But `gateway-cli` doesn't support this. I think it probably should.

What I ended up doing was renaming the `gateway_dir/<id>.db` to `gateway_dir/client.db` and `gateway_dir/client.json`, and removing gateway stuff from latter file. Then `fedimint-cli` could work with them. When I swept the funds, I reverted the renaming and added back json fields.

**Comment by justinmoon** [comment]
Alternative hack: have external wallet generate invoice and pay it via this gateway.

**Comment by justinmoon** [comment]
We could just change the naming conventions so that `fedimint-cli` can work on the gateway configs & databases.

**Comment by m1sterc001guy** [comment]
Completed with https://github.com/fedimint/fedimint/pull/5825
