### ISSUE TITLE
Alternative block sources

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1187]
We should support an option to use Esplora / Electrum as block sources. This will help us deploy our early "dogfooding" federations more quickly.

- [x] electrum support https://github.com/fedimint/fedimint/pull/1363
- [ ] esplora support

**Comment by justinmoon** [comment]
Dev call: we already have a trait for this, easy to implement. All we need to look up is block height, block hash, and fee levels.

@dpc in dev call: maybe we should have a mode for "unsafe / non-production" that fills in some defaults to get people to play with it easier.

**Comment by oleonardolima** [comment]
@justinmoon I was taking a look at this one and got interested, is the esplora support a pressing issue?
I can take a look at this one but it might take some time 😁

**Comment by justinmoon** [comment]
> is the esplora support a pressing issue?

Esplora support would be very helpful. Also pretty straightforward to implement because it doesn't require a lot of familiarity with the overall system which takes time to learn.

Look at [this PR](https://github.com/fedimint/fedimint/pull/1363) for inspiration. Create a new `EsploraClient` struct. Implement `IBitcoindRpc` for it. Add a new entry to `BitcoindRpcBackend`. Send `reqwest::get(<url>)` to urls like `/api/tx/<txid>/merkleblock-proof`. This one gets the "txoutproof". You can use blockstream's public Esplora server at `https://blockstream.info/api/...`. [Here is the Esplora API documentation](https://github.com/Blockstream/esplora/blob/master/API.md). If you have any questions, post them in [discord](https://chat.fedimint.org/). And feel free to open a "[draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/)" pull request once you've made progress and want feedback.

In terms of testing, you could just test that it fetches the same values as the electrum implementation. Eventually we should probably run Electrum / Esplora servers inside our test environment, but that requires editing `flake.nix` which isn't easy. Maybe @dpc can help but he'll be pretty busy for the next 10 days.

**Comment by justinmoon** [comment]
Related to https://github.com/fedimint/fedimint/issues/1383
