### ISSUE TITLE
announce-address

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1188]
What type should distributedgen's `announce-address` type be? https://github.com/fedimint/fedimint/blob/d5c2295d3ae3d8c26f75ad2aa287a46ae5f57c62/fedimintd/src/bin/distributedgen.rs#L47

It's currently a `String` but it would be nice if we had a more precise type. I was going to say `url::URL` by later on we append a port to it https://github.com/fedimint/fedimint/blob/d5c2295d3ae3d8c26f75ad2aa287a46ae5f57c62/fedimint-server/src/config.rs#L556.

I ask because that appending a port to the announce address tripped me up last night when I was updating a regtest federation. @elsirion's regtest deployment scripts map try to expose the federation api as [wss://alpha.regtest.sirion.io/](https://github.com/elsirion/fedimint-signet/blob/master/machines/regtest.nix#L127-L135) but DKG always tacks a port on the end. So you have to edit the server config and remove the port so that the federation API returns client configs with the correct URL in them.

Thoughts @jkitman?

**Comment by jkitman** [comment]
@justinmoon I'd suggest we make it a `Url` which optionally allows for specifying a port, eliminate the `base_port` config option, and instead default to `4000` if no port is explicitly provided in the url.

**Comment by justinmoon** [comment]
dev call: get rid of offsets. ^^ sounds good.

**Comment by dpc** [comment]
Is `announce-address` really a best name? Is this for public hostname? `public_fqdn`?  That's more what I'd expect.

**Comment by justinmoon** [comment]
> Is `announce-address` really a best name? We don't really do any announcing anything. Is this for public hostname? `public_hostname`? `public_fqdn` or just `hostname`? That's more what I'd expect.

Not it is `api_url` and may include a port https://github.com/fedimint/fedimint/pull/1194/files#diff-1ade8041e9cbc0b8f7c938f524422ca94707ce88a5919b51cdcc7701ba107f5cR48
