### ISSUE TITLE
Get rid of all `println` / `eprintln`

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1191]
Use `tracing` instead. Have CI grep for these going forward.

CLI apps are exception.

**Comment by asifshiraz** [comment]
Seems like a number of println commands are already in client/cli and gateway/cli and the ones in keygen examples in crypto/tbs also seem useful as they are. Should I replace only the rest with the tracing commands? What about ones in build and dbtool.
![image](https://user-images.githubusercontent.com/7054246/212501641-6e4f9f27-fcaf-472e-8ba0-87cb68802556.png)

**Comment by dpc** [comment]
We should replace only ones that are not the real desired output of the command in question. Also good opportunity to review eprint vs print. `eprint` (stderr) should be used for mostly interactive prompts. Logging already goes to `stderr` so otherr than interactive prompts, there's probably no need for `eprint`.


Some resources for better understanding: https://julienharbulot.com/python-cli-streams.html

**Comment by justinmoon** [comment]
Closed by #1330
