### ISSUE TITLE
Unique default ports

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1199]
We currently use default ports that are likely to collide with other applications, e.g. `8080` for the gateway. We replace all such instances with ports less likely to collide with other applications.

**Comment by dpc** [comment]
Didn't #1194 just do that? Any other ports to take care of?

**Comment by justinmoon** [comment]
Off top of my head there's still this one https://github.com/fedimint/fedimint/blob/a3303bb2c73390df0b0ba609ffd22fbb189470fb/gateway/cli/src/main.rs#L20

**Comment by justinmoon** [comment]
Can we close this now? I can't find any more ports that need changing ...
