### ISSUE TITLE
New stable threshold key/id for authenticating configuration

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#1205]
I've been trying to aggregate issues related to the idea of adding a new stable threshold key/id to the federation for authenticating configuration.  We can handle these as tasks in roughly the following order:
- [x] Generate new threshold `auth_pk_set` (exchanging TLS certs would still be necessary for bootstrapping DKG)
- [x] Use the `auth_pk_set` as a stable id that all peers have contributed to
- #754
- [x] Expose an endpoint for retrieving consensus/client configs (which includes version) signed by the `auth_pk_set`
- #950
- [ ] Clients can consider the `auth_pk_set` the only "trusted" information, minimizing the serialized "connect info" (although they also need an endpoint to download the configs from)
- #614
- #755
- [ ] Support updating p2p certs or endpoints using the auth key share (cryptographic id) for each peer
- #744
- [ ] Changing peer membership could be handled by threshold-signing the new `auth_pk_set`

**Comment by dpc** [comment]
:100: :partying_face:
