### ISSUE TITLE
Let `TaskGroup` tasks return a value when joined

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1206]
There should be a spawn function that allows returning  a value from a `TaskGroup` task.

https://discord.com/channels/990354215060795454/1060599778410500206/1060603991819571270

![Screenshot 2023-01-05 at 19-49-24 Discord - A New Way to Chat with Friends   Communities](https://user-images.githubusercontent.com/84478054/210857690-a06cb47c-6b30-4298-9a24-8860ff7ff362.png)

**Comment by justinmoon** [comment]
Closed by https://github.com/fedimint/fedimint/pull/1591
