### ISSUE TITLE
IDatabase::begin_transaction should take `&ModuleRegistry`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1226]
Right now the code is cheating calling `all_decoders` which returns `ModuleDecoderRegistry` so it's not visible, but if wasn't for that, having to `.clone()` all the time would be poor API.

Ideally `DatabaseTransaction` would somehow be able to carry a `&ModuleDecoderRegistry` inside and not require cloning, but that will be a PITA for lifetime purposes.

Instead, we should change `ModuleDecoderRegistry` to:

```rust
struct ModuleDecoderRegistry(Arc<BTreeMap<ModuleKey, Decoder>>);
```

This `Arc` there will allow us to cheaply clone the whole thing without allocating or dealing with lifetimes, while the implementation of `DatabaseTransaction` can call `.clone()` on  `&ModuleDecoderRegistry` and let callers just pass `&` around.

Ping @m1sterc001guy  for feedback.

**Comment by m1sterc001guy** [comment]
This makes sense to me, I don't think I have anything else to add. I can provide review or take this on myself if you want.

**Comment by dpc** [comment]
@m1sterc001guy Feel free to take it if you want. My immediate todo list is already overflowing, ATM.

**Comment by m1sterc001guy** [comment]
@Maan2003 this is still applicable even after [1197](https://github.com/fedimint/fedimint/pull/1197/files) is merged right?

**Comment by Maan2003** [comment]
Nope, #1197 changes this so ModuleRegistry is just passed to Database at start.

**Comment by m1sterc001guy** [comment]
Yeah after reading your PR in more depth I noticed that. Are we ok with closing @dpc ?

**Comment by dpc** [comment]
Yes, if that's the case the problem is gone.
