### ISSUE TITLE
Generalize `ModuleRegistry`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1231]
We have multiple `ModuleRegistry` types, and it would be great to unify into one `ModuleRegistry<T>(BTreeMap<String, T>)` with all the `Deref`, `from`and other conversions that we might want.

Notably -  we also have `DecoderRegistry` which is keyed by `u16`. Something to think about.

**Comment by elsirion** [comment]
The `ServerModuleRegistry` is keyed for `ModuleId` too. Only the config stuff has string keys rn because that's how the config is saved.

**Comment by dpc** [comment]
@elsirion Makes me wonder if shouldn't key everything on `ModuleId`, and have in each a field `type : String`. which actually tells it which code to use. 

I think we vaguely discussed that we might want to have multiple instances of the same module. The initialization should really be "under key no 3, wallet module L1 BTC", under key no 4 mint module", "under key no 5 wallet module for Liquid BTC".

We don't want to copy-paste wallet module code just to change two functions in there.

Eventually, we wouldn't even have to hardcode any modules in the binary. The user in the UI would select "add new module", "pick type", "specify the required paramters" (wallet module would ask to pick which network to use), "assign free ModuleID", repeat until done.

On subsequent loads, the binary will go through each module, instantiate each key with the corresponding types and arguments.

**Comment by elsirion** [comment]
Good point, relates to what I discussed with @jkitman recently about running multiple module versions side by side (#1235) . I like having a name in the cfg for readability, but it's probably not really useful, we should get rid of it. The UI can always display a mapping of key to name.

I don't think running the exact same version of a module twice will be too relevant anytime soon. E.g. to support multiple assets in a Liquid wallet module we would rather have them all in one module than spawn a separate module per asset. That way e.g. the L-BTC for fees could be shared. Liquid/BTC will be sufficiently different to be separate modules imo (confidential assets signing logic etc.).

That being said, I like the idea of dynamic/per-federation module keys so we don't have to run a central registry to avoid conflicts.

**Comment by dpc** [comment]
If a module supports multiple passing an array of things it can do that's great, but I don't think this is going to be universal. Since we will support 3rd party modules, sooner or later someone will want to instantiate same code twice, or maybe phase our one instance for another, because of config. Or something. I think keeping this options open is a good idea. It also unifies registries.

I'd rename `ModuleKey` to `ModuleInstanceId` to make it clear that it enumerates over the instances of module of the federation, and not the type of the module. The `ModuleType` can stay as a short string, so module developers have easier time picking something unique.

So the binary will only register a set of types of modules it supports. Then the config will control what module instances (of which types) are actually configured.

**Comment by dpc** [comment]
Addressed in: https://github.com/fedimint/fedimint/pull/1269 https://github.com/fedimint/fedimint/pull/1286 (still pending, but will finish it)

**Comment by dpc** [comment]
Fixed #1364
