### ISSUE TITLE
Upstream HtlcAccepted, Onion, and Htlc structs to cln_plugin

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1245]
https://github.com/fedimint/fedimint/blob/b85aa04d76f5bbbe664453d9918fac06588dfc3a/gateway/ln-gateway/src/cln.rs#L33-L60

**Comment by mubarak23** [comment]
i want to believe this has been done @justinmoon

**Comment by elsirion** [comment]
From all I can find in https://github.com/ElementsProject/lightning/tree/master/cln-rpc this is still an open issue. 

Currently, `cln_rpc` uses functions that [consume and output JSON for hooks](https://github.com/ElementsProject/lightning/blob/21fcd4594b9db99017e6c6f4cca750566d1b2969/plugins/src/lib.rs#L198-L211). Ideally there'd be a way to register typed hooks where decoding/encoding is handled by the library and the library also supplies the structs representing specific hook callbacks.

```rust
    pub fn hook<C, F>(mut self, hookname: &str, callback: C) -> Self
    where
        C: Send + Sync + 'static,
        C: Fn(Plugin<S>, Request) -> F + 'static,
        F: Future<Output = Response> + Send + 'static,
    {
        self.hooks.insert(
            hookname.to_string(),
            Hook {
                callback: Box::new(move |p, r| Box::pin(callback(p, r))),
            },
        );
        self
    }
```

I don't know what a good API would look like, maybe a `Hook` trait that is implemented on the input type and has an associated type specifying the output type. I also don't know how all that fits into CLN's code generation philosophy, but worth a try imo if you have some experience designing rust APIs.

For reference: we use the `hook` feature for HTLC interception:

https://github.com/fedimint/fedimint/blob/b85aa04d76f5bbbe664453d9918fac06588dfc3a/gateway/ln-gateway/src/cln.rs#L138-L152

**Comment by m1sterc001guy** [comment]
We are planning on removing Core Lightning support post v0.5 https://github.com/fedimint/fedimint/issues/6218. 

Closing
