### ISSUE TITLE
distributedgen allows passing different values for federation_name

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1262]
I just setup a 2/2 federation using the setup UI.

I passed "1" as federation name for first guardian, and "2" for the second. DKG succeeded and these values made it to `consensus.json` so the 2 nodes have different `consensus.json` files.

**Comment by jkitman** [comment]
Right now the sole purpose of DKG is the keygen, so no other config will be passed around.  Other parts of the consensus config such as denominations could also be different.

I'm working on hashing the consensus configs then validating them with peers upon server start-up.

**Comment by justinmoon** [comment]
I think we can close this one after #1281
