### ISSUE TITLE
Setup UI: Testing

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1266]
We should test the setup UI by sending requests via curl. This will require some HTML "parsing" (well, `grep`ping for some values) but should be easier than driving a virtual browser to click on things.

**Comment by asifshiraz** [comment]
Do you prefer curl as a tool of choice, or just saying for simplification of the task? I can do this in selenium or webdriver if you want?

**Comment by elsirion** [comment]
It was mostly for simplicity's sake. I guess the challenges will be similar for both approaches, so I don't have a strong preference. If we can get selenium to work in a nix environment I'd be fully on board.

Selenium might have the benefit of being easier to migrate when we switch from our current server-side web app to a API+PWA approach assuming the frontend doesn't change too much.

What do you think @jkitman, @justinmoon, @dpc?

**Comment by jkitman** [comment]
Looks like we could even write the tests in Rust https://github.com/stevepryde/thirtyfour

I'm not sure whether it makes sense to write UI integration tests before some of the changes we want to make to the setup UI such as #1628 and #1893

**Comment by dpc** [comment]
IMO, this is low prio for now. UI tests are notoriously difficult subject, and I don't think we covered well more fundamental testing aspects. And we are yet to rewrite the whole thing anyway.

But since we're talking about it: If we are to make the setup UI a SPA or something, then we'll probably have to use some headless browser testing approach. I worked with `cypress` before and hated it. :D

**Comment by justinmoon** [comment]
IMO we shouldn't test our current UI since it's going to change heavily. Do https://github.com/fedimint/fedimint/issues/1893 first, test those endpoints, then write a good UI with some tests.

**Comment by okjodom** [comment]
> Do https://github.com/fedimint/fedimint/issues/1893 first, test those endpoints

This is the most sane approach we can take

> then write a good UI with some tests

Agreed. UI tests for SPA could be atomic functional/accessibility/localization tests on small units of the UI. Test framework TBD based on the framework we write the UI in. When the time comes, I'd vote for React or it's variants so we can do simple `jest` testing

With both good test coverage on SPA UI and the driving API, I'd expect that we have limited to zero need for UI integration tests needing Selenium or curl grep :) as discussed above

**Comment by okjodom** [comment]
subset of #2466

**Comment by justinmoon** [comment]
Let's close this in favor of https://github.com/fedimint/fedimint/issues/2466
