### ISSUE TITLE
Setup UI should generate connection string from server config, not client config

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1273]
https://github.com/fedimint/fedimint/blob/master/fedimintd/src/ui.rs#L63-L71

In order to present a connection string, it currently reads `client.json`. To me this seems a little odd, since the server isn't a client and doesn't really need to have a `client.json` cluttering it's datadir. I think it would be preferable to just read one of the server configuration files and derive a client config from it.

**Comment by elsirion** [comment]
We can just read the consensus config, transform it into client config and then do everything as before from there.
