### ISSUE TITLE
Setup UI should ask for "block confirmations required" instead of "finality delay"

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1277]
AFAICT you need need to wait N+1 blocks to execute a peg-in with a `finality_delay` of N

**Comment by justinmoon** [comment]
Thinking about this a little more, I think it does make sense. This is the number of blocks that the federation trails bitcoin. It's just slightly confusing from the client POV that you need to add 1 to it in order to execute peg-in.

**Comment by dpc** [comment]
Should we rename?

**Comment by justinmoon** [comment]
Let's just close for now. I can't think of a clearly better alternative.

**Comment by dpc** [comment]
I can. :D

In the UI we could show "peg-in / peg-out time (in blocks)", then substract 1 and put that into finality_delay.

**Comment by justinmoon** [comment]
I like that. Renamed the issue to just this.
