### ISSUE TITLE
Sanitize paths in api_endpoint

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1280]
We should not require modules to provide initial slash, and strip any slashes from beginning and end when we register, just to avoid silly, time wasting mistakes.

```
fn sanitize_module_endpoint_path(mut path: &str) -> &str {
    while let Some(new_path) = path.strip_prefix("/") {
        info!("Stripping leading / from the {path} from module");
        path = new_path
    }

    while let Some(new_path) = path.strip_suffix("/") {
        info!("Stripping trailing / from the {path} from module");
        path = new_path
    }

    path
}
```

use in `attach_endpoints` and `attach_endpoints_erased`.

**Comment by justinmoon** [comment]
These are json-rpc commands, not URLs. Make sure the commands are roughly lower-case letters and potentially underscore. Should be consistent with JSON-RPC conventions.
