### ISSUE TITLE
Use `SafeUrl` all over the code

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1298]
To help with accidentally exposing auth data in urls we use accross the code. [Original discussion](https://github.com/fedimint/fedimint/pull/1288#discussion_r1068517727)

**Comment by dpc** [comment]
Yeah, so 

```rust
use url::Url;

fn main() {
    let url = Url::parse("ftp://foo:bar@localhost").unwrap();
    println!("{url}, {url:?}")
}
```

Prints:

```
ftp://foo:bar@localhost/, Url { scheme: "ftp", cannot_be_a_base: false, username: "foo", password: Some("bar"), host: Some(Domain("localhost")), port: None, path: "/", query: None, fragment: None }
```

so we need a wrapper.

**Comment by dpc** [comment]
Fixed by #1419

**Comment by dpc** [comment]
We should use the type from #1419 everywhere. This might require some extra `impl`s to make it work in all sorts of places, but should be relatively easy to do.

**Comment by Aankirz** [comment]
Hey @dpc , I want to work on this issue can you pls assign this to me ?, 

thanks

**Comment by justinmoon** [comment]
Give it a try @Aankirz. Try to just find one place where this helps and make a PR for that. To make sure you're on the right track.

**Comment by cbergqvist** [comment]
Hope you don't mind me grabbing this. Felt like one of the more straightforward issues and no apparent progress for half a year.

**Comment by shaurya947** [comment]
It's a bit inconvenient that there isn't an `Into` or `From` to create a `SafeUrl` type from a `Url` type. Leaving this here so we can add that before closing this issue.

**Comment by dpc** [comment]
It should be possible to turn `Url` into `SafeUrl` with `From`/`Into`, but the other way around it should require some `to_unsafe` (or maybe something else as `unsafe` has specific meaning ... thought I guess this ship has already sailed with `Safe` in the `SafeUrl`...)

**Comment by cbergqvist** [comment]
See I'm still assigned to this. Can do some follow-up changes to #3133 in the suggested directions in the following days.

**Comment by cbergqvist** [comment]
Let me know if there's anything more you think should be done before closing this issue.
