### ISSUE TITLE
`ModuleGen` should have a typed and erased versions, like all other module types.

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1303]
Currently it has only erased version and it's kind of weird, that the user needs to deal with conversion to erased types in this one place.

**Comment by dpc** [comment]
I also need it to properly fix #1302

**Comment by dpc** [comment]
@mxz42 It might be already on your radar?

**Comment by dpc** [comment]
@mxz42 Right.

You don't mention a blanket `impl<T> IModuleGen for T where T: ModuleGen...` so mentioning it for completeness.

**Comment by mxz42** [comment]
this can be closed? @dpc
