### ISSUE TITLE
Setup federation UI placeholder colours too close to completed colours

### ISSUE THREAD

**Issue by humansinstitute** [fedimint/fedimint#1306]
![image](https://user-images.githubusercontent.com/42595944/212209148-80334b23-96c9-4349-9ffa-789f195d1b23.png)

As above field 1 is a completed field, field 2 is the placeholder 

When setting up a federation it is hard to tell the difference between the two which can lead to placeholders being left in and causing a failed setup.

**Comment by dpc** [comment]
Agreed. Generally we could use some extra contrast colors there one way or another.

**Comment by okjodom** [comment]
completed after #2559
