### ISSUE TITLE
UI defaults tweaks

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1308]
From the [@elsirion comment](https://github.com/fedimint/fedimint/pull/1300#issuecomment-1381087172)

> Re screenshot: p2p we don't speak websocket but a custom binary protocol over TLS, thus the schema should probably be fedimint://…

![Screenshot from 2023-01-12 16-01-26](https://user-images.githubusercontent.com/9209/212206557-5b0ed259-21ca-44d2-8e79-f6fff1a9aa59.png)

* [ ] We should probably default to 0.0.0.0:8173 and 0.0.0.0:8174 for both listening addresses It seems in most cases these will be public.

**Comment by okjodom** [comment]
completed after #2559
