### ISSUE TITLE
`module_decode_stubs` got to go

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1332]
No more new invocations of `module_decode_stubs`. It's a bit of effrot, but we can not be hardcoding modules all over the client in hundred little places. `ModuleDecoderRegistry` must come to everywhere from the very top of a binary, where it will be constructed from available `ModuleInitRegistry` + client config. For time being we can hardcode it - but in one place only - at the very top of the call-stack.

It's internally a  `Arc` which is `Send + Sync + Clone`, so it can be carried along, stored and passed everywhere, so other than some extra effort, there is no excuse to use `module_decode_stubs`: it can always be taken as an argument in a constructor, or an argument to a method, or stored somewhere, etc.

Please don't fix any existing invocations of it just yet, as I ... by mistake fixed a tone of good chunk in a PR I'm working on, before realizing that I should probably do it in another one. And I don't think reverting it now is worthwhile.

**Comment by justinmoon** [comment]
It seems that `module_decode_stubs` is gone. Closing.
