### ISSUE TITLE
api: Avoid relying on 404 http/jsonrpc for not found

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1335]
If `fetch_tx_outcome` API call is supposed to be able to return "not found", it should return `Option<TransactionOutcome>`.

This avoids extra handling of 404 error codes etc.

**Comment by dpc** [comment]
https://api.random.org/json-rpc/1/error-codes

From https://www.jsonrpc.org/specification#error_object

> The error codes from and including -32768 to -32000 are reserved for pre-defined errors. Any code within this range, but not defined explicitly below is reserved for future use. The error codes are nearly the same as those suggested for XML-RPC at the following url: http://xmlrpc-epi.sourceforge.net/specs/rfc.fault_codes.php

https://xmlrpc-epi.sourceforge.net/specs/rfc.fault_codes.php:

> -32700 ---> parse error. not well formed
> -32701 ---> parse error. unsupported encoding
> -32702 ---> parse error. invalid character for encoding
> -32600 ---> server error. invalid xml-rpc. not conforming to spec.
> -32601 ---> server error. requested method not found
> -32602 ---> server error. invalid method parameters
> -32603 ---> server error. internal xml-rpc error
> -32500 ---> application error
> -32400 ---> system error
> -32300 ---> transport error

Not really meant for http codes anyway.

**Comment by Maan2003** [comment]
I used http error code because the api endpoint isn't coupled with jsonrpc.

**Comment by dpc** [comment]
It works, got as this far. I just think we should `Option` the results of Apis we expect can return "not present" and avoid dealing with error codes for anything other than unexpected failures.

**Comment by justinmoon** [comment]
Call: @Maan2003 will check if this is already complete.

**Comment by justinmoon** [comment]
@dpc what status here?

**Comment by Maan2003** [comment]
this is solved, api methods return `Option` now. `Retry404` is gone.
