### ISSUE TITLE
`__api_endpoint` can't handle params arity

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1336]
```
method_call{method="/module/2/peg_out_fees"}: jsonrpsee_core::tracing: recv="{\"jsonrpc\":\"2.0\",\"id\":3,\"method\":\"/module/2/peg_out_fe
es\",\"params\":[[\"bcrt1qkhkzjqmh93y0hd98k3t0hwuvuswsshmltcud6d\",1200]]}"    
```

As you can see, we always send exactly one argument, even though `params` is already an array.

We should clean it up - at least to make writing other clients and tooling later easier.

**Comment by justinmoon** [comment]
>  parms arity

typo? "params array"?

**Comment by dpc** [comment]
> Arity is the number of arguments or operands taken by a function,

Not sure if I used it correctly though, but I thought I did. :)

**Comment by justinmoon** [comment]
ahh yea i forgot about the word "arity". that math degree really paying off 🤣

**Comment by douglaz** [comment]
This got even trickier now that inside `params` we also include an `auth` token. So today we have something like:

```json
{
    "jsonrpc": "2.0",
    "method": "somemethod",
    "params": [
        {
            "params": some_param_as_object_string_number_etc
            "auth": "somepassword"
        }
    ],
    "id": 1
}
```

A more sane approach perhaps would be:
```json
{
    "jsonrpc": "2.0",
    "method": "somemethod",
    "params": {
        "api_params": [param1_as_object_string_number_etc, param2_as_object_string_number_etc, ...],
        "api_auth": "somepassword"
    },
    "id": 1
}
```

**Comment by dpc** [comment]
Would it be possible to pass auth as http headers? Then the whole connection would be authenticated, we wouldn't have to repeat them in every call.

**Comment by dpc** [comment]
Yeah... I think when doing jsonrpc to bitcoincore the auth is actually basic http auth passed in http headers. Putting auth into jsonrpc body is very weird to begin with.

**Comment by dpc** [comment]
@maan2003 Isn't this fixed already? Please re-open if not.
