### ISSUE TITLE
React Native module for mint-client 

### ISSUE THREAD

**Issue by tanx** [fedimint/fedimint#134]
Hi everyone,

thanks for your work on minimint. I saw there was already an issue of creating a WASM client library in #61 ... this would work for web apps but unfortunately there doesn't seem to be a way to [load a .wasm module in react native](https://stackoverflow.com/questions/60673807/how-to-load-wasm-file-in-react-native) directly. This is because The JS runtimes on iOS and Android don't support wasm yet.

There seems be some initial work to polyfill this with [react-native-wasm](https://github.com/inokawa/react-native-wasm). But that does not really look production ready. This is also why BlueWallet has built a [React Native module](https://reactnative.dev/docs/native-modules-intro) for LDK called [rn-ldk](https://github.com/BlueWallet/rn-ldk). This approach compiles the rust code to native iOS and Android libraries and uses Java/Swift bindings to call into native code from the JavaScript environment. I would propose to create a similar module for react native apps for the mint-client module. An example of how to do this can be found [here](https://medium.com/@marekkotewicz/building-a-mobile-app-in-rust-and-react-native-part-2-hello-world-60970a7d194a).

Apart from having access to powerful native apis like QR code scanning on mobile, this way we could also leverage [Photon SDK ](https://docs.photonsdk.org/) to build mobile apps.

Curious to hear your thoughts. Thanks :)

**Comment by Maan2003** [comment]
> This is because The JS runtimes on iOS and Android don't support wasm yet.

that is not correct. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly#browser_compatibility

**Comment by tanx** [comment]
@Maan2003 thanks for the reply. I wasn‘t referring to browsers support. Wasm works fine there. I was referring to in-app JavaScriptCore runtime that React Native apps use. That doesn‘t have the same capabilities as browsers.

**Comment by tanx** [comment]
See also: https://github.com/react-native-community/jsc-android-buildscripts/issues/113

**Comment by Maan2003** [comment]
Oh, that makes sense. 

> This approach compiles the rust code to native iOS and Android libraries and uses Java/Swift bindings to call into native code from the JavaScript environment.

Ideally we can just have a library can be compiled to both wasm and a native module.

**Comment by justinmoon** [comment]
@futurepaul and I have been working on a [basic Flutter app](https://github.com/futurepaul/fluttermint) which connects to minimint federations. We have a [crappy little crate](https://github.com/futurepaul/fluttermint/blob/master/minimint-bridge/src/api.rs) that exposes functionality similar to `mint-client` to the Dart code of our app.

Once everything works smoothly we'll try to figure out how best to contribute this back ...

**Comment by elsirion** [comment]
No progress on a real TS/JS wrapper unfortunately, but @Kodylow built [`clientd`](https://github.com/fedimint/fedimint-clientd), which runs as a daemon and provides an API and comes with API wrappers for go, python and TypeScript.

You could build apps that ship the `clientd` binary, starts it and then uses it to interact with Fedimint. That's how all the early lightning UIs worked.

**Comment by maan2003** [comment]
that's how syncthing on android works, so this should work on mobile

**Comment by Kodylow** [comment]
Mutiny is written in rust so they just use the wasm builds of the fedimint crates

**Comment by dpc** [comment]
Closing as not actionable and stale.
