### ISSUE TITLE
Replace `get_last_epoch` api with `get_epoch_count`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1340]
The problem with the current API is that it's inclusive bound:  it has no way to represent "no epochs yet" (would be 0 with exclusive one).

Prior art: `bitcoind` has a `getblockcount`, not `getlastblock` :)

It might lead to subtle errors.

**Comment by dpc** [comment]
Same in the `IBitcoindRpc`

**Comment by dpc** [comment]
@jp1ac4 , please see what the existing endpoint is doing. What this issue is about is basically making it return `0` when it was previously returning `None` (or error) and `N + 1` where it was previously returning `Some(N)` + renaming it.

**Comment by jp1ac4** [comment]
Hi @dpc, thanks for the hint. Are any changes required to `fetch_last_epoch`, which I believe is using the `/epoch` endpoint?

**Comment by dpc** [comment]
We should rename everything to `fetch_epoch_count` and similar (to contain "count" and not "last"), just like `getblockcount` of `bitcoind`, then fix the code.

**Comment by ngutech21** [comment]
Issue can be closed because branch got merged
