### ISSUE TITLE
Prevent transaction replays

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1347]
For the mint use case this hasn't been relevant so far, but other modules (e.g. account systems) would benefit from a no-replay guarantee.

**Comment by dpc** [comment]
Observation: If we required "anti-DDOS/gas e-cash" to pay for every tx, we would get replay protection for free.

**Comment by justinmoon** [comment]
Why would "gas" tokens fix this? Could one just pay gas a second time to replay a transaction?

**Comment by evanlinjin** [comment]
> Why would "gas" tokens fix this? Could one just pay gas a second time to replay a transaction?

If I'm not mistaken, the nature of ecash itself is one-time-spend-all and not replayable. To spend a portion, you need to spend whole and issue more in outputs.

**Comment by evanlinjin** [comment]
Also, in regards to ddos attacks, I thought ddos attacks were already mitigated by fees.

Additionally, ecash requires storing additional data on the server for every note spent. We might as well just have a lookup for spent tx hashes.

**Comment by dpc** [comment]
> Also, in regards to ddos attacks, I thought ddos attacks were already mitigated by fees.

There are no fees inside the federation (right now). And if they were, we would prefer them not to be bitcoin itself (for various reasons). A second, pure utility token is preferred.

> Additionally, ecash requires storing additional data on the server for every note spent. 

Yes, it comes down the the same thing, but we probably want ddos notes anyway (for ddos protection), and as the storage requirements for federation grow linearly with the history, we don't want to store two things for the same tx if we don't have to.

But for time being, as an easier to implement measure we could do it. I'm just saying that once we have gas ecash, we wouldn't need it.
