### ISSUE TITLE
Stop using the consensus DB for submitted transactions

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1353]
Using the DB we also use for consensus to keep unconfirmed transactions is a potential security risk in combination with other bugs (e.g. #1316). To be on the safe side we should migrate to an in-memory unconfirmed transaction cache that:

1. Allows async submission and notification (probably via a channel)
2. Keeps transactions till they are confirmed in an epoch
3. Prevents re-submission of already confirmed transactions

**Comment by dpc** [comment]
Question: If the user submited a tx to `threshold_required` members, then one of them crashed and lost it (as it's not persisted now), is it still going to get confirmed? If not, then clients should re-submit, or we should implement fetching the "mempool" from other peers on start.

**Comment by elsirion** [comment]
> If the user submited a tx to `threshold_required` members, then one of them crashed and lost it (as it's not persisted now), is it still going to get confirmed?

Technically the one that crashed counts as malicious for security analysis, so assuming no one else is malicious it will get confirmed. I others are malicious consensus might stall completely (if f=1 for example).

> If not, then clients should re-submit

Clients need to handle tx that simply never happened (re-submit) or get rejected (try to re-claim inputs).
