### ISSUE TITLE
A proc macro for wasm-conditional maybe-Sync+Send bonds.

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1358]
We have bunch of duplication already for wasm vs non-wasm builds.

We could have a macro that takes care of it for us:

```
wasm_conditional! {
  fn main<T : $maybeSendSync> {
    unimplemented();
  }
}
```

On non-wasm32 targets this would make the bound `<T : Send + Sync + SomePlaceHolderTrait>` on wasm it would be `T : SomePlaceholderTrait>` where `impl<T> SomePlaceHolderTrait for T {}` (so it's implemented for all types), just so we can avoid handling conditionaly empty bound.

**Comment by dpc** [comment]
One reason I wanted this just got removed, so might be a low-prio work. Most of this is taken care by `#[async-trait]` but not when working on standalone functions.

**Comment by Maan2003** [comment]
You don't need a macro. 

```rust
#[cfg(target_arch = "wasm32")]
pub trait MaybeSend {}

#[cfg(not(target_arch = "wasm32"))]
pub trait MaybeSend: Send {}

#[cfg(not(target_arch = "wasm32"))]
impl<T: Send> MaybeSend for T {}

#[cfg(target_arch = "wasm32")]
impl<T> MaybeSend for T {}
```

**Comment by dpc** [comment]
@Maan2003 Oh. Right. Good idea, thanks. I wonder if I can use in every context, but possibly yes.

**Comment by Maan2003** [comment]
This is completed. we have these macros in fedimint_core::task.
