### ISSUE TITLE
Empty nix cross-compilation builds

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1367]
Reported upstream https://github.com/ipetkov/crane/issues/223

**Comment by dpc** [comment]
@justinmoon Looks like our cross-package are empty because we are building a plain `rlib`.

How do we integrate with mobile software? What type of binaries do we need? "cdlib"? More info here: https://users.rust-lang.org/t/what-is-the-difference-between-dylib-and-cdylib/28847

**Comment by justinmoon** [comment]
I forget the difference between these. Will revisit later. For now it's probably enough to just run `cargo check` to see if everything still compiles ...

**Comment by dpc** [comment]
Everything is being built, we just don't put the end binary in the resulting package (which then don't use for anything anyway, at least not yet).
