### ISSUE TITLE
Idea: Make a ecash-printing module for testing

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1368]
I had some problems described in #1333 due to how we fake injecting mint notes in tests.

Which made me think - now that we have injectable modules, how about we make a module that just prints ecash out of thin air. We can call it `UsFederalReserve`, and basically it would allow creating mint transaction outputs that are always valid. You want 100 sats? Here is the valid output.

Basically a Wallet module, without the hard parts. :D

We could enable this module in tests, and use it to get initial funds without hacking the mint module by writing to its database.

**Comment by dpc** [comment]
@jkitman How does this sound?

**Comment by elsirion** [comment]
How can we prevent it from ever been used in a release? Maybe panic if built in release mode (we are running tests in debug mode now iirc)?

**Comment by dpc** [comment]
As is in "accidentally"? We could make it panic unless certain env variable is passed that would be unlikely to happen in real deployment.

**Comment by jkitman** [comment]
> How does this sound?

I think we can improve the way we currently generate test notes, but seems a bit overkill as a new module.  Wouldn't we want to be testing the production mint module anyway?

BTW right now the fed is designed to panic if liabilities != assets, so for every ecash note there must be some pegged-in btc.

**Comment by dpc** [comment]
> BTW right now the fed is designed to panic if liabilities != assets, so for every ecash note there must be some pegged-in btc.

I think it can fake it in the audit function. :D

> Wouldn't we want to be testing the production mint module anyway?

IIUC mint needs a valid input first to output mints note. This module would kind of be a like wallet module that is cheating, so we don't have to fake peg-ins.
