### ISSUE TITLE
Add regtest electrs tests for peg-ins and peg-outs.

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1383]
We have electrs support but it's not well tested well, and without automated tests it is going to be hard to keep it functional.

https://github.com/fedimint/fedimint/pull/1363#discussion_r1072901329

**Comment by oleonardolima** [comment]
@dpc  I was taking a look at this one as it's somewhat related to adding the tests for Esplora backend #1187 #1564 , but I'm still a little lost on it:

- Is the idea to add/update tests for both fake and real services?
- Do we need to add new tests or just run the same tests in a different CI step, or the same but in a matrix way?

**Comment by dpc** [comment]
I don't think we need to run all `integrationtests` against electrs and/or esplora.

We probably would be fine if we took the test that does:

* peg-in
* block height change
* peg-on

and then ran it 3 times, against each backend (can be just a function called from 3 tests with a different parameters, for the lack of better parametrization).

We can probably adapt the `fixtures` in `integrationtests` to handle these new 2 cases (it returns error on the wrong backend right now).

I don't think we need to support "fake" electrs/esplora. The whole point is to test against "real" thing. Testing against a fake doesn't give us anything. In fake-using tests, we could just skip the test.

**Comment by oleonardolima** [comment]
Good, it's much clear now.

I'll take a deep dive into the existing tests that use bitcoind (on these scenarios) to get familiarity with the tests.

Also, I'll play with the try to use/add the electrs module to the nix environment, and esplora to check if it won't require a bunch of disk space for the indexes and really needs to be a nix module/pkg (a `cargo` call might be enough, for now at least).

Yes, I guess updating the fixtures will make it easier to select and test against each backend 😁

**Comment by jkitman** [comment]
@dpc @oleonardolima I've added tests for electrum because electrs was already a nix package, but esplora isn't.  Would either of you be interested in adding that to nixpkgs?  If so, I could help with adding it to our CI suite.

**Comment by oleonardolima** [comment]
> `@dpc @oleonardolima` I've added tests for electrum because electrs was already a nix package, but esplora isn't. Would either of you be interested in adding that to nixpkgs? If so, I could help with adding it to our CI suite.

@jkitman I saw your message on e-mail, not sure if you deleted it or it's just not showing for me 😅.

That's great, I wasn't able to get back to it in the last week, but will get back to it this week and I can focus on adding esplora to nixpkgs.

Another alternative would be to initially just install esplora manually during ci, I guess it would be a quick way to get more coverage and I could do that first, wdyt ?

**Comment by jkitman** [comment]
@oleonardolima Ah I deleted the message because I gave it a shot today :smile: 

I'm not really experienced in nix but realized since esplora is a fork of electrs, it should more or less work the same.  I think we prefer to go through nix just to ensure everyone can recreate the test env locally.

See https://github.com/NixOS/nixpkgs/compare/master...jkitman:nixpkgs:add-esplora-pkg

**Comment by justinmoon** [comment]
Agree with @jkitman. Think a nix package is the way to go. The only question for me is if our nix shell eventually gets too heavy and we need to split it up ...

**Comment by jkitman** [comment]
@justinmoon I think we can sub my repo for `nixpkgs.url` but there's probably a better way to do it.

**Comment by dpc** [comment]
> Also, would we be able to use this nix package ourselves before nixpkgs adds it? cc @dpc

Sure we can, and it's easy.

**Comment by dpc** [comment]
@jkitman https://github.com/fedimint/fedimint/pull/1797


We should make sure the nixpkgs we lock and the one you have as a base of your branch are relatively close to avoid rebuilding bunch of stuff twice.

**Comment by oleonardolima** [comment]
> @oleonardolima Ah I deleted the message because I gave it a shot today 😄

Cool! I'll follow your implementation and try to learn from it then 😁
