### ISSUE TITLE
After creating the federation succesfully the UI flickers

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1406]
After successfully creating federation the UI seems to be flickering (like the page is continuously restarting) and Copy button does seem to work (copying manually works thought).

**Comment by dpc** [comment]
@justinmoon

**Comment by justinmoon** [comment]
Think we just need to remove this line https://github.com/fedimint/fedimint/blob/b9eeb4f807ccfe864057b9fa34237fe6555d9711/fedimintd/templates/run.html#L4.

Previously DKG would be running in the background at this stage. Now DKG completes by the time it gets to this screen. But we should probably have a specific screen between the "enter connection strings" step and displaying the connection strings that can report progress and errors.
