### ISSUE TITLE
Run gateway plugin as OCI container via runc

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1436]
@dpc was just telling me how you can make an executable shell script that executes a `ln_gateway` OCI container with the `runc` container runtime. This could behave exactly like a normal executable, but could run on any distro that has `runc` installed.

Alternative to #1008 for making CLN plugin run on all linux distros.

**Comment by dpc** [comment]
```bash
#!/usr/bin/env bash

exec podman run $MOUNT_OPTS_ETC -q -i docker.io/fedimint/ln-gateway "$@"
```

This behaves very much like we were running `ln_gateway` process itself: stdio, stdout, stderr, etc. Though I'm hitting https://github.com/containers/podman/issues/14707 which makes ctrl+c not work.

Might try other stuff later too.

**Comment by dpc** [comment]
@justinmoon @elsirion Once #1452 lands, please create `ln-gateway` docker hub repos, so we can upload it there.

**Comment by justinmoon** [comment]
> @justinmoon @elsirion Once https://github.com/fedimint/fedimint/pull/1452 lands, please create ln-gateway docker hub repos, so we can upload it there.

Done

**Comment by dpc** [comment]
Bundling the binary like in https://github.com/fedimint/fedimint/pull/2036 seems to render this too much hassle.
