### ISSUE TITLE
gateway-cli: Non informative error when making a typo in password

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1437]
```
Enter gateway password: <MADE A TYPO HERE>

Error: 
```

**Comment by dpc** [comment]
Good first issue: Please verify if still an issue, fix is so, close the issue.

**Comment by isaack-njama** [comment]
Is there a recommended way to provide a password? I mean other than from the command line, considering the warning.

**Comment by elsirion** [comment]
> Is there a recommended way to provide a password? I mean other than from the command line, considering the warning.

Assuming you are talking about the "please don not pass it as a command line option" warning: you can also pass it as an environment variable.

https://github.com/fedimint/fedimint/blob/4c3a782bb1c3d17905abaf11a001c338b5a8b4d6/fedimintd/src/fedimintd.rs#L41-L42

**Comment by cbergqvist** [comment]
The situation regarding this has improved thanks to #2472. Current output is:
```
$ gateway-cli info
Enter gateway password:
Error: Bad status returned 401 Unauthorized
```
Could be closed IMHO.
