### ISSUE TITLE
ln-gateway: take password and federation to use as environment variables

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1438]
It's currently a pain to use in a best practice style. :)

**Comment by dpc** [comment]
And the connection url to gateway. (localhost:8080 is a meh default)

**Comment by justinmoon** [comment]
I don't think 8080 is still the default address. This is what I see in my help command now.

```
  -a, --address <ADDRESS>          The address of the gateway webserver [default: http://127.0.0.1:8175]
```

**Comment by justinmoon** [comment]
While you're at it, make sure to update tmuxinator so it doesn't print this warning out each time you call `gateway-cli`

```
WARNING: Passing in a password from the command line may be less secure!
```

**Comment by dpc** [comment]
Might have been when I was working with the old binary.

But we should still take federation id and password from the environment if we don't yet. (Please close if we do, sorry for the noise)

**Comment by justinmoon** [comment]
I don't think we support either of those, yet

**Comment by dpc** [comment]
There have been a lot of improvements w.r.t CLI handling.
