### ISSUE TITLE
Make modules plug-and-play

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#144]
It should be possible for users to easily choose which modules they want to use at compile time. Ideally users should be able to add modules from foreign crates.

I see 4 solutions of which 3 also fulfill the latter requirement::
1. **Feature Flags**: All modules have to live in this repository but can be activated via feature flags
2. **Macros**: Expose macros that take modules as input and build all the enums (transactions, inputs, outputs etc.) with one variant per module.
3. **Generics Hackery**: We could emulate [variadic generics](https://gist.github.com/PoignardAzur/aea33f28e2c58ffe1a93b8f8d3c58667) to a degree by having `MinimintConsensus` variants with 2 to e.g. 6 type parameters, each being a module (impl via macro). Alternatively (and even cooler) we could use advanced generics like [heterogenous lists](https://docs.rs/frunk/0.4.0/frunk/hlist/trait.HList.html).
4. **Dynamic Modules**: Make the `Module` trait object safe and work with `Box<dyn Module>` objects. I like this idea the least since it would remove a lot of the guarantees Rust's type system gives us.

**Comment by dpc** [comment]
Created rollout plan in #568 for #546 .

**Comment by dpc** [comment]
AFAUI @elsirion was satisfied with static-trait plugins from #625 , so I think we can close and modularization work will track it.
