### ISSUE TITLE
Gateway should drive forward interrupted lightning payments

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1441]
https://github.com/fedimint/fedimint/blob/ff4be41187f13cce62510e4a52b3dbbb9f558b9d/gateway/ln-gateway/src/lib.rs#L306

@elsirion: How would I use the `dbtool` to check if any such outgoing payments exist in a test deployment? Wondering how much of a problem this is in practice. Unfortunately we can't check for interrupted incoming payments until we fix this TODO https://github.com/fedimint/fedimint/issues/544.

**Comment by elsirion** [comment]
1. Find all steps of the operation in question that get persisted to disk, e.g. the first one for outgoing payments is written in `save_outgoing_payment` to `OutgoingContractAccountKey` with prefix `25` (hex). 
2. Query that prefix using `cargo run --bin dbtool -- <db_path> list '25'`. Key and value are separated by a space. Each pair is printed on a new line

Be aware that not every step is modeled correctly. We really need #1447.

**Comment by humansinstitute** [comment]
Hey guys - did this get picked up in the new lightning client rewrite or still outstanding?

**Comment by m1sterc001guy** [comment]
Yes this can be closed since we now have client NG https://github.com/fedimint/fedimint/issues/1447 in the gateway
