### ISSUE TITLE
Confusing gateway log statement in tests / tmuxinator

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1457]
When the gateway starts up in CLI tests or tmuxinator, it prints this:

```
2023-01-21T14:18:35.878Z UNUSUAL plugin-ln_gateway: Could not parse config: missing field `client_config` at line 260 column 1   
```

Which looks like a serious error (we wasted some time no this when trying to fix CI a couple days ago). But it isn't. The gateway attempts to load every JSON file in the config directory as a gateway config](https://github.com/fedimint/fedimint/blob/0ab8733a9d15d5c1871ea4b9208b9473bbc7fb79/gateway/ln-gateway/src/client.rs#L191-L220). But in tests / tmuxinator, `client.json` is in there which is not a gateway config.

I would suggest we move gateway stuff to it's own directory in `build.sh`. Also, gateway configs are stored as `<federation-id>.json` so we could probably further filter the JSON files to only filenames that are also valid federation IDs.

**Comment by justinmoon** [comment]
> I would suggest we move gateway stuff to it's own directory in build.sh

Looking a little deeper it seems that we already did this was fixed in `build.sh`, but wasn't fixed in `.tmuxinator.yml` where we still use `$FM_CFG_DIR`.

**Comment by m1sterc001guy** [comment]
All gateway configs are stored in Gatewayd's database now. So I do not think this is still an issue.
