### ISSUE TITLE
Stop using `XOnlyPublicKey`s

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1458]
The main argument for using x-only keys was that MuSig2, which we use for signature aggregation over transaction input keys, takes x-only keys as inputs and us throwing away one bit of information before that step might lead to malleability.

The MuSig2 spec is getting updated though to take normal public keys as input (bitcoin/bips@bbbeae1170612ee5d0c09d784f477797ab028b05) and as soon as ElementsProject/secp256k1-zkp#211 lands and gets adopted by ElementsProject/rust-secp256k1-zkp#48 we will be able to switch to normal public keys, which are widely considered the better choice, for this use case too.

**Comment by Kodylow** [comment]
Makes much more sense to do it that way. I'll undo my old XOnly changes and upgrade them to the new zkp once those land

**Comment by justinmoon** [comment]
Call: can the PR we're using for musig2 support normal public keys?

**Comment by elsirion** [comment]
It seems to me that https://github.com/BlockstreamResearch/rust-secp256k1-zkp/pull/48 has moved to (normal) compressed public keys instead of x-only ones. After #2667 we'll likely be able to move away from `XOnlyPublicKey`s in Fedimint transactions.
