### ISSUE TITLE
Build `dbtool` in CI/nix

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1459]
I just noticed I forgot to add a `flake.nix` entry in #1321.

**Comment by dpc** [comment]
Probably put into a `fedimintd` container as well (it already contains `fedimint-cli`)

**Comment by m1sterc001guy** [comment]
This should be fixed as of this PR https://github.com/fedimint/fedimint/pull/1523/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0
