### ISSUE TITLE
Combine `wait-invoice` and `fetch` CLI commands

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1463]
First time users of our CLI alway get confused by having to receive money over LN, which requires: 

(1) `ln-invoice` to generate invoice
(2) `wait-invoice` to wait for it to be paid and claim the funds in the contract
(3) `fetch` to get your balance to update

Perhaps we should just have `fetch` look for any `ConfirmedInvoies` in the DB and try to complete them. Then the flow would just require steps (1) and (3).

**Comment by jp1ac4** [comment]
Hi @justinmoon, I can take a look at this one.

**Comment by justinmoon** [comment]
Assigned

**Comment by justinmoon** [comment]
There's a question of who the audience is for this CLI. For developers, it can be nice to have a `fetch` command that makes the steps involved in ecash issuance and redemption a little clearer.

But for end-users, we might want to just fetch out updated balance and try to complete pending incoming contracts **any time the CLI starts up**?

**Comment by elsirion** [comment]
Implicit behavior like that is bad for CI testing. The CLI client is first and foremost a low-level tool for debugging and testing imo.

We could put the low level interfaces into a subcommand and build a high level interface next to it. The question is if it's worth it. Originally `clientd` was supposed to fill that gap: have a long-running daemon that drives forward payments in the background and can be queried via a CLI client (or an electron app too).

**Comment by justinmoon** [comment]
For now, perhaps we could remove the `wait-invoice` command and just have `fetch` look in the database for any `ConfirmedInvoiceKey` and try to claim the contracts using `claim_incoming_contract`? You'll see there is a long-standing TODO in `claim_incoming_contract` so save whether the invoice was paid or not. If you added this, then you could filter the `ConfirmedInvoiceKey` records using that. Also, you could just filter out any invoices that are expired.

**Comment by dpc** [comment]
> Implicit behavior like that is bad for CI testing. The CLI client is first and foremost a low-level tool for debugging and testing imo.

I don't know. It is useful in scripting, and operating the fedimint. Sometimes I'm a developer and need a precise behavior, and sometimes I'm a distracted user, who just wants to get the job done and doesn't remember all the low level details. Most Unix tools tries to be like that, IMO.

Seems to me like the default behavior should be user friendly and handy, while we should have commands and flags available to allow precise control and scripting.

So we probably want a standalone `wait-invoice`, while we could have `fetch` (just fetch notes) and `refresh` or `update` (doing bunch of things together that make sense for the user). Or we could add some flags to disable automatic extra-fetching behavior.

**Comment by elsirion** [comment]
This user-friendly client could also talk to a block explorer to automatically get peg-in proofs and drive forward peg-ins in the background.

**Comment by jp1ac4** [comment]
> You'll see there is a long-standing TODO in `claim_incoming_contract` so save whether the invoice was paid or not

I could try adding this in. Which DB key prefix would we use for that?

> Also, you could just filter out any invoices that are expired

I'll go with this approach in the first instance and then use the saved info from the DB if I manage to include that part.

**Comment by justinmoon** [comment]
`ConfirmedInvoiceKey` contains be able to return all `(ContractId, ConfirmedInvoice)` pairs in the local client database.

You can use `ConfirmedInvoiceKey.invoice.is_expired()` to filter out the expired invoices. Then use `ContractId` as the argument to `claim_incoming_contract()`.

**Comment by jp1ac4** [comment]
As discussed with @justinmoon, this is no longer required.

**Comment by justinmoon** [comment]
Will fix this in the new client
