### ISSUE TITLE
Don't show setup UI if config is present and the federation running

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1468]
Currently one can still see the forms, they just don't do anything anymore.

**Comment by justinmoon** [comment]
I tend to this this UI should evolve into more of an "admin ui" which includes "setup". Therefore, it should always run if user passes the flag for it. it should only allow setup to run if no configs are present. But once configs are present, then it should show things relevant to the operator of a federation -- e.g. how big is the spend book?

**Comment by okjodom** [comment]
completed after #2559
