### ISSUE TITLE
Server side logging improvements

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1469]
The request logging should have higher logging level

On the server side being able to see the requests that are being made is one of the most useful debugging tools.

Our default logging level is `info`, so we possibly should make it `info`. If anyone will not want to log them, they can override.

https://github.com/fedimint/fedimint/pull/1357/files#r1083315034

Also, we should use the `target` feature more often, and define `const LOG_TARGET_X : &str = ` and document (`./docs/...md`) a list of `targets` that one can enable and disable. AFAIU, the default "target" is the module name which is not very useful in real settings.

We should phase out usage of non-target-taged logging statements.

**Comment by dpc** [comment]
@Maan2003 @justinmoon @elsirion  Thoughts?

**Comment by elsirion** [comment]
> is the module name which is not very useful in real settings.

Why? So far I found it quite nice to work with, typically what I'm interested in is in one or two modules.

> Our default logging level is info, so we possibly should make it info. If anyone will not want to log them, they can override.

To me that feels too noisy, but useful. Maybe just make it debug and activate by default in our deployments?

I think eventually we might just want to log everything anyway and just filter after the fact (especially if we can send the logs to some log server with a nice UI). Maybe the `trace` and `debug` ones should get pruned more quickly in that case.

**Comment by justinmoon** [comment]
I defer to you guys on this. We need documentation about debugging tips and tricks. [I just learned of this `target` trick.](https://github.com/fedimint/fedimint/pull/1357/files#r1083334600)

**Comment by dpc** [comment]
> Why? So far I found it quite nice to work with, typically what I'm interested in is in one or two modules.

This works for developers like us, but not for external users (mint admins) that might not be able to navigate the source code.

While module is somewhat a category, there will be plenty of categories that are cross-module.

Also by committing to stable targets in constants, we make them more like an API that we consciously evolve. Renamings and refactoring will not break filters set by users (as much).

**Comment by dpc** [comment]
Ideally I'd like to be able to do `env RUST_LOG=db=trace,request=trace,debug` etc. to eg. correlate database queries with requests, and get very detailed information about each (arguments, results).

**Comment by dpc** [comment]
IIRC, everything can be hierarchical, so we can have

* consensus
* peers
  * send
  * recv
* db
* api

and so on.

**Comment by dpc** [comment]
#1571 is implementing the idea. Please provide feedback.

**Comment by dpc** [comment]
Closing. Followup moved to #2257
