### ISSUE TITLE
Create `DynClientModuleConfig` newtype

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1474]
Instead of the client module configs being `serde_json::Value`s internally, they could be already parsed an be a `Box<dyn IClientModuleConfig>` that allows encoding via `Encodable` as well as `serde`.

We already do this for module associated types (see `DynInput`, `DynOutput`, …), the only difference would be adding `serde` into the mix. We could even avoid that and just expose a from/to `serde_json::Value` fn (less complex than general serde support).

_Originally posted by @elsirion in https://github.com/fedimint/fedimint/pull/1434#discussion_r1083331166_

**Comment by elsirion** [comment]
Some progress was made in https://github.com/fedimint/fedimint/pull/2283. One outstanding idea that came up during that PR was including the data length in all `Dyn*` types so unknown ones can be ignored during decoding. With that change we could make the `ClientModuleConfig` a true `Dyn*`-type. Thoughts @dpc?

**Comment by dpc** [comment]
@elsirion 

Well. I'm sure we should prefix dyn types with a length, but w.r.t `ClientModuleConfig`:


```rust
pub struct ClientConfig {
    // ...
    /// Configs from other client modules
    pub modules: BTreeMap<ModuleInstanceId, ClientModuleConfig>,
}

pub struct ClientModuleConfig {
    pub kind: ModuleKind,
    pub version: ModuleConsensusVersion,
    #[serde(with = "::hex::serde")]
    pub config: Vec<u8>,
}
```

So each client config is somewhat different that a dyn type.

It is stored in a map keyed by `module_instance_id`, and has `kind` and `version` in there, which are also generic.

So do we want to turn that `config` into `config: DynClientConfig` and then there will be a redundant `module_instance_id` in there? I guess that works ...

**Comment by elsirion** [comment]
I think everything related to this got resolved by now.
