### ISSUE TITLE
Derive all client secrets from `Client`'s root secret

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1477]
If a client fails or is lost for whatever reason while waiting for confirmations to execute a peg-in, then you won't be able to complete the peg-in unless you saved a backup of your client db which contains the "tweak" used to create the deposit address from federation's public descriptor.

Now that the client has a [root secret](https://github.com/fedimint/fedimint/blob/5aefd0b57b6e38a109d8a6428ee44524a73a9cd2/client/client-lib/src/lib.rs#L150) we should consider deriving tweaks from this secret.

One question would be how to reset the tweak derivation index when recovering a client.

**Comment by elsirion** [comment]
> One question would be how to reset the tweak derivation index when recovering a client.

Wouldn't it be similar to the e-cash module? You have a gap limit and scan that many addresses beyond the last one that had some activity. Once you found the last generated address that way you can set the next derivation index to that plus one.

**Comment by justinmoon** [comment]
> Wouldn't it be similar to the e-cash module? 

Yes. But we can query the federation, right? Don't want to query bitcoin blockchain ...

**Comment by justinmoon** [comment]
While we're at it, we should do `OutgoingContract::user_key` and lightning invoice preimages, too.

**Comment by elsirion** [comment]
> Yes. But we can query the federation, right? Don't want to query bitcoin blockchain ...

I don't see a way around that, but it wouldn't be via `bitcoind`. The electrum protocol has the right API to retrieve the status of a lot of addresses efficiently.

**Comment by justinmoon** [comment]
I guess this doesn't have to be a trusted electrum server, right? If it lies to you then the worst that happens is basically DOS?

**Comment by elsirion** [comment]
I opened #1481 with a higher level description of the problem.

**Comment by justinmoon** [comment]
Changed the title of this issue to cover just deriving client keys from the root secret. https://github.com/fedimint/fedimint/issues/1481 can be about the backup side of things.

**Comment by justinmoon** [comment]
Remaining
- [ ] `payment_keypair` in `LightningClientModule::create_lightning_receive_output` ([link](https://github.com/fedimint/fedimint/blob/02e5d0e7c9f13a7be543ad9477fc6f53e364b8f7/modules/fedimint-ln-client/src/lib.rs#L865))
- [ ] ` user_sk` in `LightningClientModule::create_outgoing_output` ([link](https://github.com/fedimint/fedimint/blob/02e5d0e7c9f13a7be543ad9477fc6f53e364b8f7/modules/fedimint-ln-client/src/lib.rs#L667))
- [ ] `tweak_key` in `WalletClientModule::get_deposit_address` ([link](https://github.com/fedimint/fedimint/blob/02e5d0e7c9f13a7be543ad9477fc6f53e364b8f7/modules/fedimint-wallet-client/src/lib.rs#L489))

**Comment by justinmoon** [comment]
This is intertwined with https://github.com/fedimint/fedimint/issues/2977. By addressing this this without addressing https://github.com/fedimint/fedimint/issues/2977, we're adding more of a foot-gun since secrets will be re-used.

**Comment by dpc** [comment]
Mint and Wallet modules are now fully derived from root secret.

**Comment by elsirion** [comment]
Call: LNv2 has key derivation, recovery isn't implemented yet (but that's safe due to stateless recovery).
