### ISSUE TITLE
Handling peg-out failures

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1480]
I was just chatting with @elsirion about how the client library handles peg-out failures. For example, let's say the fee-rate changes and it never confirms?

He mentioned that he had chatted with @jkitman about this some time ago, but wasn't sure if the changes were ever implemented.

**Comment by jkitman** [comment]
I think there was some discussion captured here https://github.com/fedimint/fedimint/issues/233

We still need to "allow for user RBF" and "aggregate or queue transactions".
