### ISSUE TITLE
Merge `fedimint-api` and `fedimint-core`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1482]
I think we can do that now. Thoughts @dpc, @jkitman ?

**Comment by jkitman** [comment]
We would need to remove the dependencies on the modules first...but I think that is nearly possible now.

**Comment by elsirion** [comment]
To my knowledge the only things to move out (to the client lib imo) are `fedimint_core::outcome::legacy` and `fedimint_core::transaction::legacy`.

**Comment by dpc** [comment]
This would be a beautiful milestone to see.
