### ISSUE TITLE
Change SQLite to use WAL

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#1485]
By default, SQLite doesn't allow for multiple concurrent writers to the same database because SQLite just uses a file to store the data. It has been discovered that SQLite can actually support higher concurrency by enabling the Write-Ahead-Log and uses Optimistic Locking. Optimisitic Locking brings the transaction semantics in line with Rocksdb - essentially when the transaction commits, SQLite will check if any of the same pages have been touched by other transactions, and if they have both modified the same page, the transaction is aborted. Enabling the WAL is a prerequisite for using optimisitic locking. 

This will enable the Fedimint client to work better in concurrent environments and potentially also allow the same client to store multiple federation configurations inside the same database.

**Comment by m1sterc001guy** [comment]
Well, this is somewhat of a bummer. I didn't realize that the documentation I was looking at was actually for a branch of Sqlite from 2019. https://www.sqlite.org/src/doc/begin-concurrent/doc/begin_concurrent.md

We should still enable WAL and see how much that helps with concurrency. It occurred to me we can also get the same semantics as Rocksdb (failing at commit time) just by implementing it in fedimint-sqlite.

**Comment by elsirion** [comment]
I'd assume that whatever was present in 2019 is still supported by SQLite? It's known for its stability after all. Does this sound like what we might want: https://www.sqlite.org/wal.html ?

**Comment by m1sterc001guy** [comment]
It unfortunately hasn't been merged to their main branch yet. I tried using BEING CONCURRENT with our version of Sqlite and it does not work.

We should definitely turn on WAL though.

**Comment by justinmoon** [comment]
@m1sterc001guy Closing this since we removed sqlite
