### ISSUE TITLE
Ability to control logging level in ln-gatway

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1490]
Right now ln-gatway seems to be logging with a default level (`info`). Setting `RUST_LOG` to increase it is ignored. We should have a plugin option (I think I've seen something like that in the docs) to be able to control it.

**Comment by justinmoon** [comment]
@dpc found the env var. what is it?

**Comment by dpc** [comment]
`CLN_PLUGIN_LOG=debug`
