### ISSUE TITLE
Ability to get outgoing lightning contract refunds via CLI

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1491]
If you attempt to pay an invoice via `fedimint-cli` and a gateway claims an outgoing contract, but then fails to claim the preimage and doesn't cancel the contract, then I don't think there's any way to sweep the funds back via `fedimint-cli`.

**Comment by justinmoon** [comment]
@elsirion @m1sterc001guy Do we think this is irrelevant after the client-ng migration

**Comment by m1sterc001guy** [comment]
Yes I think we can close this.
