### ISSUE TITLE
Implement robust network stack with Tor integration

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#15]
The current network stack is fragile. If a connection dies the node goes down, killing all other node. This is obviously not viable for production. Instead a network stack that

* attempts to reconnect,
* caches messages that were not ACKed by the other side and
* uses Tor

would be nice.

**Comment by DON-MAC-256** [comment]
Might keep an eye on the official Tor Rust client: [arti](https://crates.io/crates/arti-client)

**Comment by elsirion** [comment]
Super cool project! I hope one day it will support running a hidden service too, doesn't seem the case right now. Till then we'll need a Tor daemon anyway and I feel like we might as well use it for outgoing connections since it's also more mature.

On a separate note, we might also want to have a simpler TLS based network stack (still with buffering etc.) for cases where participants know each other anyway (keeps latency down).

**Comment by justinmoon** [comment]
Arti just hit [1.0](https://blog.torproject.org/arti_100_released/** release), but it seems [client connections to Tor v3 services are still a long ways off](https://gitlab.torproject.org/tpo/core/arti/-/issues/67) unfortunately. Compiling tor C code is really annoying, especially on iOS and Android. Would be great to have pure-Rust implementation but seems seems deficient if we need server websocket port to be exposed as a tor service.

**Comment by jkitman** [comment]
@justinmoon Would we also need Arti to compile to WASM if we wanted mobile support?

**Comment by justinmoon** [comment]
> @justinmoon Would we also need Arti to compile to WASM if we wanted mobile support?

No. AFAIK all mobile platforms will should consume fedimint client via FFI and not WASM.

**Comment by elsirion** [comment]
> seems [client connections to Tor v3 services are still a long ways off](https://gitlab.torproject.org/tpo/core/arti/-/issues/67)

We do not necessarily need hidden service support, although it would be rather convenient for deployments. As long as the federation members have domains and TLS on their API endpoints the clients could just use Tor to reach them. So right now both seem feasible with different risks:

* Arti: missing features like on-demand circuit switching, general instability
* libtor: cross-compile problems, it generally being a hack

**Comment by justinmoon** [comment]
We built a robust network stack, and don't plan to integrate Tor for server-server connections in the foreseeable future. https://github.com/fedimint/fedimint/issues/2610 is the tracking client-server connections which is a different topic.
