### ISSUE TITLE
Gateways should account for routing fees when deciding whether to pay an invoice

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1519]
When user client's fund an outgoing contract, they currently [choose an amount that is 1% more than the invoice amount.](https://github.com/fedimint/fedimint/blob/8c12fe50e522aef3187d5edfc673f7943b969143/client/client-lib/src/ln/mod.rs#L92-L100) The gateway pays their routing fees from this fee and takes the rest as profit.

When deciding whether to pay an invoice or not, a gateway should take routing fees into account. Currently, it does not. [It just checks if the outgoing account isn't more than the invoice amount](https://github.com/fedimint/fedimint/blob/8c12fe50e522aef3187d5edfc673f7943b969143/client/client-lib/src/lib.rs#L1018-L1020). It should check `invoice_amount + expected_routing_fees >= contract_amount`. Left side is what gateway pays, right side is what it receives. Might want to also include a profit margin, but that's another topic.

**Comment by justinmoon** [comment]
Actually I think this is already enforced with the `maxfeelimit` parameter we send to the `pay` RPC to Core Lightning. The problem is that in practice routing doesn't work very well when we send the parameter on mainnet.

**Comment by elsirion** [comment]
Also, the % fee parameter is ignored for small payments that would have too low of a fee limit, which is actually an attack vector. Afaik the absolute fee limit option doesn't have this problem and we should use it.

**Comment by justinmoon** [comment]
Closing in favor of https://github.com/fedimint/fedimint/issues/524
