### ISSUE TITLE
Gateway handles requests serially

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1530]
Right now the gateway can't do 2 things at once.

For example, put a long sleep in `/pay_invoice`, pay an invoice via CLI inside tmuxinator, then call `gateway-cli balance`. It will hang until the sleep ends.

I'm guessing that `gateway-cli` hangs when anything is happening, and that perhaps the whole gateway can't handle concurrently requests.

**Comment by dpc** [comment]
Is it because there is only one actor handling traffic and it's handling everything serially?

**Comment by justinmoon** [comment]
I think so

**Comment by dpc** [comment]
Spawning multiple handling loops (in a loop) should take care of it and seems like an easy fix. We will have to pick some "concurrency level".

**Comment by dpc** [comment]
```
-        loop {                                                                                                
-            // Shut down main loop if requested                                                               
-            if loop_ctrl.is_shutting_down() {                                                                 
-                break;         
-            }                                                                                                 
                                                                                                               
-            let least_wait_until = Instant::now() + Duration::from_millis(100);
+        for _ in 0..32 {                                                                                      
+            loop {                                                                                            
+                // Shut down main loop if requested                                                           
+                if loop_ctrl.is_shutting_down() {  
+                    break;                                                                                    
+                }                  
                    
```

**Comment by justinmoon** [comment]
This is risky because the existing client was never intended for concurrent usage

**Comment by okjodom** [comment]
>```
> +        for _ in 0..32 {                                                                                      
> +            loop {                                                                                            
> +                // Shut down main loop if requested                                                           
> +                if loop_ctrl.is_shutting_down() {  
> +                    break;                                                                                    
> +                }    
>```
@dpc, this suggestion is not applicable unless we unless we change out messaging channel from webserver to processors, to use a 'many-to-many' pattern. We presently use an [mpsc::Receiver](https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html) which can have may senders, but the receiver can only be owned by one thread. A choking point, maybe

**Comment by m1sterc001guy** [comment]
This is fixed now :) https://github.com/fedimint/fedimint/pull/2654
