### ISSUE TITLE
Setup UI should accept the default values of fields from the command-line

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1532]
That would make setup scriptable and less tiresome, while still testing the UI.

**Comment by jp1ac4** [comment]
Hi, I could give this a try. Is it related to the `run-ui.sh` script?

**Comment by dpc** [comment]
@jp1ac4 Go for it. Yes, from the looks of it `run-ui.sh` starts N federations with their setup UI. 

We would just like to have env variables handled by clap that would carry all over the UI screen with connections strings etc. and populate them.

Note: We will probably at some point change how the UI will work altogether, but until then this would be a great improvement.

**Comment by justinmoon** [comment]
@jp1ac4 I can help you here. Have some changes that partially implement this. Can help you finish them off. Can also just explain how the setup UI works in general to help you get started with it. Ping me on discord and let's do a quick call.

**Comment by dpc** [comment]
Lots of this is already working, but there were few fields missing, IIRC.

**Comment by dpc** [comment]
:+1:

**Comment by dpc** [comment]
@jp1ac4 Awesome job!

**Comment by jp1ac4** [comment]
Thanks, @dpc :)
