### ISSUE TITLE
Prevent client from being used concurrently

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#1544]
There are numerous bugs that can result in issues if a mobile app developer attempts to call our client API concurrently.  For instance, you could call `spend_ecash` twice and then end up trying to double-spend the same ecash.

**Comment by okjodom** [comment]
Special case: We want the gateway client to support concurrency. See #1530

**Comment by dpc** [comment]
Probably this will get fixed by the new client API. @elsirion to confirm / be aware, but I'm closing as not actionable.
