### ISSUE TITLE
Client secret should support different secret sizes

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1547]
Currently it only allows 64 byte secret, but for example 12 word BIP39 mnemonic is 16 bytes and we should support that.

**Comment by elsirion** [comment]
BIP39 states

> The length of the derived key is 512 bits (= 64 bytes). 

so while the entropy entered into the key derivation function defined in BIP39 might be as little as 128bit, it is always expanded to 512bit. We *could* do something more custom since the HKDF used by `DerivableSecret` also has an extract step, but then we wouldn't be using BIP39.

**Comment by elsirion** [comment]
I think we mainly need to document this better so this question doesn't come up again.

**Comment by elsirion** [comment]
Fixed by #2529
