### ISSUE TITLE
Consensus and API versions

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1548]
It's not too early to start keeping track of versions as we've discussed before.

```
const CONSENSUS_VERSION : (u32, u32) = (0, 0); // consensus version + api sub-version; TODO: Package in `struct` with some helpers maybe.
const DB_SCHEMA_VERSION : u32 = 0;
```

Introduce API call to get API version:

```
fn get_api_version(&self) -> (0, 0)
```

Start actually incrementing these versions as we land patches that break compatibility. It's OK this will be happening every day. It's not like we're going to run out of numbers, and it will get us used to the idea.

Compare these versions on the client side and refuse to work when they don't match.

**Comment by justinmoon** [comment]
This would be a great exercise to just prepare for our first stable public API. To start being aware of all the subtle little things that require version upgrades. Just because we start using version numbers doesn't mean we're committing to support them indefinitely. But I think it could help us get to that point sooner.

**Comment by elsirion** [comment]
For API versions, where clients *ignore* new fields, we might want to use SemVer so certain updates are detectable by supporting clients but don't make old ones reject the new version? For consensus encoding this would be trickier, although adding a new module is kind of non-breaking from a client's PoV (just from the guardians'), so it might make sense there too.

**Comment by dpc** [comment]
@elsirion 

I think the semver-like thing works, but please give it some thought at some point.

So it would be

`CONSENSUS_VERSION, API_VERSION, API_REVISION`

.

Both client and the server will have to maintain certain amount of backward compatibility, and negotiate the maximum common version they support.

On connecting, client would send: `Vec<(CONSENSUS, API_VERSION, MIN_API_REVISION)>`, and server would find the maximum common `(CONSENSUS_VERSION, API_VERSION)`, where server has at least `MIN_API_REVISION`


Adding new APIs would only increment the `MIN_API_REVISION`.

**Comment by dpc** [comment]
See https://github.com/fedimint/fedimint/pull/1579

**Comment by justinmoon** [comment]
Did https://github.com/fedimint/fedimint/pull/1579 close this?

**Comment by dpc** [comment]
I'd keep this one open until we have actual compat checking on client side for api versions.

**Comment by elsirion** [comment]
TODO from call:
- [ ] Write module version to cfg
- [ ] FM consensus version
  - [ ] Add function returning supported versions
  - [ ] Add to cfg
- [ ] API version
  - [ ] Return from API endpoint for FM+each module
  - [ ] Also return consensus version, useful for parsing config
- [ ] FM Code version: keep git hash for now
  - [ ] Do we need p2p version once removed?

**Comment by dpc** [comment]
I'm looking into server-client api version negotiation. Each peer has an endpoint returning supported api version for core + each module. But then should client find one common version for each core/module that works with all peers, or should picking the version to use happen per `(guardian_id, core/module)`? 

Doing it per guardian would allow guardians greater flexibility w.r.t code upgrades, but then things like unifying responses from guardians will become much, much harder...

So I guess I'll do one api version that must work for all (or at least threshold) peers.

**Comment by dpc** [comment]
AFAIK everything has been implemented and we can create new issues for things we want to improve.
