### ISSUE TITLE
Add a `restart` command to tmuxinator environment

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1553]
Currently if you are running the tmuxinator dev environment, edit some code, and want to re-run it, you either need to kill and restart tmuxinator (slow) or manually to stop, rebuild, and restart what you changed (annoying). We should instead have one command that's easy to remember and run that just handles this for the developer.

- [x] Kill `fedimintd`, rebuild it, and re-run it **in the same pane** it currently runs in. See [this message](https://discord.com/channels/990354215060795454/1060246795004944466/1064727278568878160). I'm not sure exactly how this would work. This shell process would need to subscribe to some kind of signal to know `restart` has been requested. (#1589)
- [x] Stop the CLN plugin, rebuild it, and re-run it. See [this script](https://github.com/fedimint/fedimint/blob/master/scripts/gw-reload.sh).

The user should be able to run this command from any tmux pane.

**Comment by cdmoss** [comment]
Regarding the second item, I included gw-reload.sh at the bottom of the new restart-tmux.sh script, since that's script @justinmoon refers to. Is there something else that should be done?

**Comment by elsirion** [comment]
I don't think so, good point. Can re-open if there is anything left.
