### ISSUE TITLE
Review and avoid use of locks (`Mutex`, `RwLock`)

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1576]
If not handled with a lot of care ([always locking in same order, …](https://softwareengineering.stackexchange.com/a/418597)) `Mutex`es can easily lead to seemingly random deadlocks that are hard to debug. Especially with the code base evolving rapidly this is a major challenge since one might not always be aware of locks that are being acquired in other parts of the code when introducing changes.

We should remove all locks not strictly necessary for core features and formally reason about the ones that remain, explaining in comments why deadlocks cannot occur.

EDIT: more on deadlocks https://www.scs.stanford.edu/12au-cs140/notes/deadlock.pdf

**Comment by justinmoon** [comment]
Idea: lock mutex / guard in logger so when a deadlock happens at least we know what caused it

**Comment by dpc** [comment]
Rots in the backlog and if we have bugs of this kind we'll just have to fix them. I also don't recall any suspicious hangs for a long, long time.
