### ISSUE TITLE
Nix builds optimizations and CI

### ISSUE THREAD

**Issue by jurraca** [fedimint/fedimint#158]
Opening an issue to get towards a working solution for Nix and CI. CI runs take a long time, and cachix doesn't seem to actually cache things correctly.
We want:
- [ ] `nix-build` runs to accurately fetch dependencies from a cachix binary cache
- [ ] to be actually building the current source tree, not always master
- [ ] CI runs to be faster. Caching correctly will help, but the integrations tests are the longest running and need independent consideration.

I've been testing different approaches for the nix build:
- `naersk`, the current method, seems fine to me
- `crate2nix` seems interesting but it fails on fetching a particular dep `erased-serde` and I couldn't figure out why
- `cargo2nix` needs an override for `secp256k1-zkp-sys` (a dep of [secp256k1-zkp](https://github.com/fedimint/rust-secp256k1/tree/master/secp256k1-sys) )

Cachix wise, it does seem to be serving prebuilt dependencies, but only crates and not the library dependencies. I'm not sure why this is the case. I tested on a fork with a free account, so I may be hitting some kind of rate limit. 

I started a [draft PR](https://github.com/fedimint/minimint/pull/157) to address some of this, but it still needs investigation.

Generally, the time sink here is the integration tests, and I'm not sure how much Nix optimization will help.

**Comment by dpc** [comment]
This one is done, I belive.

[`crane`](https://github.com/ipetkov/crane) is used, seems to work well without issues.
