### ISSUE TITLE
Add statistics to gateway

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1583]
Statistics about incoming and outgoing payments wikk help the operators to manage liquidity.

**Comment by justinmoon** [comment]
New `gateway-cli` command would be a nice first step

**Comment by nassersaazi** [comment]
@elsirion is anyone hacking at this yet? would love to give it a shot (first time contributor🙂)

**Comment by justinmoon** [comment]
Go for it! Feel free to ask questions here or in [discord](https://chat.fedimint.org) if you have any.

**Comment by elsirion** [comment]
Closing as a duplicate of #2624 which is more detailed.
