### ISSUE TITLE
Allow LN payments to report partial success faster

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#1595]
During the demo with @justinmoon, we observed fedimint LN transactions take too long before giving users feedback in the mobile app.

We should figure out when to optimistically return a "success" via the client library, only reporting errors if something fails later.

**Comment by elsirion** [comment]
You don't have to be optimistic afaik, I wrote a patch I'm not sure I want to upstream in it's current form, but we could essentially return a few seconds earlier without trouble, just need to change some tests: https://gist.github.com/elsirion/d134fdc9d9c09d6f79d4f8d550e0c5da#file-early-return-patch-L67-L70
