### ISSUE TITLE
Investigate stalling when using small network buffers

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#160]
The problem in b1eceedbf40c43b95120370f69140fca8e100229 of PR #145 seems related to the small buffer size of the fake network. This is a bug since eve a buffer size of 1byte should work by internally buffering sent/received data (just less efficiently).

**Comment by dpc** [comment]
@elsirion Still valid? I'm aware you've been doing some even more advanced improvements lately, so maybe this is no longer a problem?

**Comment by jkitman** [comment]
Think we should investigate this before alpha, in case a client or peer could DoS with a message.

**Comment by justinmoon** [comment]
Still relevant? Was this part of the network stack removed during the AlephBFT migration @elsirion?

**Comment by elsirion** [comment]
The complexity of the network stack got reduced significantly by @joschisan, I don't think this is a concern anymore.
