### ISSUE TITLE
Improve performance of the Gateway main loop?

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#1603]
Consider using [async recv()](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Receiver.html#method.recv) to remove manual sleep in the [main gateway loop](https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/src/gatewayd/gateway.rs#L407). This might bring a performance improvement to the gateways since messages are handled on arrival, rather than after some arbitrary sleep timer schedule

For additional context, see [this suggestion by @mxz42](https://github.com/fedimint/fedimint/pull/1337#pullrequestreview-1269722967)

**Comment by mxz42** [comment]
I think it would be similar as in [`peers.rs`](https://github.com/fedimint/fedimint/blob/master/fedimint-server/src/net/peers.rs#L163-L169). We create a shutdown handler and then use `tokio::select` to choose where to make progress; also note the `while` loop for the shutdown check.
[Another similar example is used in `task.rs`](https://github.com/fedimint/fedimint/blob/master/fedimint-api/src/task.rs#L126-L148) 

also wrote up a [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2b09a0ae46dda2e88ca59f99eaed351d). I think it would work somewhat like this.

**Comment by mxz42** [comment]
a similar loop exists in the [HTLC interception](https://github.com/fedimint/fedimint/blob/d3f7d45e1dbf4fc016ba176bbbdd0bcf9af83c56/gateway/ln-gateway/src/gatewayd/actor.rs#L107)
