### ISSUE TITLE
Define maximum message sizes to avoid DoS on the network layer

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#162]
See https://github.com/fedimint/minimint/pull/145#issuecomment-1162124392

**Comment by dpc** [comment]
Might be relevant for people thinking about the issue: https://github.com/rust-bitcoin/rust-bitcoin/blob/97c680db8cc34cfb7b80c3f95a1ac40dacc15a1d/src/consensus/encode.rs#L322

**Comment by justinmoon** [comment]
What's the status on this one?

**Comment by justinmoon** [comment]
@elsirion What's the status on this one?

**Comment by elsirion** [comment]
TODO, needs research for correct bounds and changes in a lot of other places to not accidentally break consensus.

An easier first step would be to limit user input (e.g. max tx size etc.). That would protect against users but not other guardians. Next step would be deriving network message size bounds from these limits to also protect against other, malicious guardians.

**Comment by dpc** [comment]
Stale, old, and alephbft already has a max citem size.
