### ISSUE TITLE
Code coverage isn't being uploaded

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1622]
At some point we stopped uploading our test coverage to codecov.io. It appears that the output directory of `nix build -L .#debug.workspaceCov` doesn't have a `lcov.info` file anymore and it also can't be found in `target.tar.zst` which is the only file present. Looking at the logs I'm not even sure coverage tests are run. Could this be another silent breakage from `crane` changing its API similar to #1379 @dpc?

**Comment by dpc** [comment]
https://github.com/ipetkov/crane/issues/235 seems like the cause

For my own reference: `fix-codecov` WIP
