### ISSUE TITLE
Use a leader for federation setup

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#1628]
In order to make federation setup easier / less error-prone it makes sense to have a leader that everyone connects to, through this high-level UX flow:

1. All guardians start fedimintd which brings up a UI page
2. A leader publishes a URL to connect to
3. Guardians connect to the URL and send over their connection/auth info
4. The leader configures any consensus values (e.g. federation name, finality delay, etc)
5. After all guardians have connected, the leader shares the final consensus and connection/authentication info with all of them
6. Guardians may validate the connection/auth information of other guardians (published in a human-readable form over other trusted channels)
7. Once all guardians complete validation, they start DKG

Assuming all guardians successfully validated each other's auth info then the outcome of DKG can be trusted and the consensus config can be verified upon start-up, so there is no extra trust placed in the leader.

Tasks

- [x] Build new config API for admins (guardians)
- [ ] Replace DKG CLI with calls to the API
- [ ] Build new UI for #1893

**Comment by justinmoon** [comment]
Comments after another discord discussion:
* Setup flow should be password-protected
* (6) could happen by hashing all pubkeys together and displaying it as BIP39 words or emojis. Everyone confirms this is the same. Or do this in the form of a challenge. Or share connection strings like we do currently.

**Comment by justinmoon** [comment]
@jkitman this one done now?
