### ISSUE TITLE
Test network logic failure cases

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#163]
Extend `MockNetwork` to simulate connections dropping or having high latency and implement tests using that. See https://github.com/fedimint/minimint/pull/145#discussion_r902518714.

**Comment by matthiasdebernardini** [comment]
Are there any outstanding issues for this? #145  looks to be complete. Should close.

**Comment by elsirion** [comment]
This issue was actually created as a result of #145 and related PRs that introduced `MockNetwork` but didn't fully exhaust the possibilities of enhancing our test suite using it. `MockNetwork` could be used  to simulate all kinds of network conditions (latency, throughput, interruptions, …) and we should do that eventually.
