### ISSUE TITLE
Switch `is_valid_for_network` to `rust-bitcoin` implementation

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1658]
We have an old version from before the [patch landed in rust-bitcoin](https://github.com/rust-bitcoin/rust-bitcoin/pull/618):

https://github.com/fedimint/fedimint/blob/2af4e6a02f8ca4fb42165bfed263c681c225d9f4/modules/fedimint-wallet/src/lib.rs#L1638-L1647

But we should switch to [the rust-bitcoin version](https://docs.rs/bitcoin/0.29.2/src/bitcoin/util/address.rs.html#818-830) now.

**Comment by jp1ac4** [comment]
Hi, is the idea here to replace the contents of the `is_address_valid_for_network` function with a call to rust-bitcoin's `is_valid_for_network` function or rather to remove this function entirely and call the rust-bitcoin function directly elsewhere, e.g. in the `validate_output` function?

**Comment by elsirion** [comment]
Remove function entirely and just use the rust-bitcoin version of it instead.
