### ISSUE TITLE
Bech32 encoding for connect string

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1659]
> As a separate matter, now that we have the federation id in there taking up most of the bytes it might make sense to explore bech32 encoding of the whole string. This would get rid of json special characters and be more compact for binary data too. If bech32 is serialized in upper case it only uses 5.5 bit per character (so only an overhead of 10% for binary data compared to 100% for hex encoding+special characters forcing binary encoding).

_Originally posted by @elsirion in https://github.com/fedimint/fedimint/issues/1654#issuecomment-1426882261_

See also  #614

**Comment by jkitman** [comment]
Seems like the reduction is 242 -> 229 bytes for 10 peers, but I guess you get some error-correction too.
