### ISSUE TITLE
Some tests fails when run in parallel

### ISSUE THREAD

**Issue by asifshiraz** [fedimint/fedimint#1686]
Sometimes, (randomly) a test fails when all tests are run together, but run individually they all pass.

![Screenshot from 2023-02-15 03-35-15](https://user-images.githubusercontent.com/7054246/218885650-a2b49e95-fecd-4827-8269-f98da732b726.png)

View test execution results [in this gist](https://gist.github.com/asifshiraz/06ecf8ba3d543cc48e8c89cc1f087b85)

**Comment by jkitman** [comment]
Closing as a dup of #1400
