### ISSUE TITLE
Check peg-out tx validity

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1693]
When generating a transaction for a peg-out we should check if bitcoind accepts it. Currently we dont prevent user generated dust outputs for example.

**Comment by jkitman** [comment]
Is this the only thing we need to check for?  In which case we can validate before calling `submit_transaction`.

Currently we wrap bitcoin rpc so that we retry forever until a success occurs (to eliminate panics in server code and block instead).

**Comment by jkitman** [comment]
Another issue I just realized is that the federation's own change output could be below the dust limit.  In this case either we need to charge the users for the lost dust or run a negative balance.

**Comment by elsirion** [comment]
I think for change we actually took that into account:

https://github.com/fedimint/fedimint/blob/4380bfe02447673ab89f14b23a3c6a256591caee/modules/fedimint-wallet/src/lib.rs#L1414
