### ISSUE TITLE
Dependencies being rebuilt on any file change

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1706]
Reported upstream: https://github.com/ipetkov/crane/issues/242

Looks like the way I was doing filtering was not being used so filled a PR https://github.com/fedimint/fedimint/pull/1705 . I might want to convert things to `craneLib.mkCargoDerivation` and apply our own filtering instead.

**Comment by jkitman** [comment]
Fixed by #1705 I believe.
