### ISSUE TITLE
Disentangle API from `MinimintConsensus`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#172]
Currently the API task holds a reference to `MinimintConsensus` which thus has to be `Sync`. This is problematic for #79 and generally not a nice design imo. There should be some sort of accessor object that only requires access to the DB (which is already `Sync`).

**Comment by justinmoon** [comment]
What's the status here?

**Comment by elsirion** [comment]
It's still TODO as we are still passing module references/the consensus struct into the API handler closures, e.g.:

https://github.com/fedimint/fedimint/blob/08c3c35c6997c52fd7c443fcea6e91a70eec65ba/modules/fedimint-ln/src/lib.rs#L859-L865
