### ISSUE TITLE
Move logging utilities to fedimint-logging crate

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1722]
https://github.com/fedimint/fedimint/pull/1682#issuecomment-1436688811

**Comment by elsirion** [comment]
Either that or maybe just `fedimint-core`? I think everything depends on core anyway.

**Comment by jkitman** [comment]
Dependency-wise it could be in core, but I saw a thread where @dpc had concerns about that.

**Comment by justinmoon** [comment]
Pure libraries (e.g. external modules) don't need this so better to make a new crate and not put it in core which such libraries will depend on
