### ISSUE TITLE
Implement filtering and details on gatewayd info API

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#1725]
Today, `gateway-cli info` returns high level information on all connected federations. Consider supporting filters on gatway info api, so we can use cli or api call to get information about a specific federation served by the gateway.

**Proposal:**
- `gateway-cli info` continues to **return high level info** about all connected federations
- `gateway-cli info <federation-id>` should **return detailed info** about the federation identified. 
  - Details might include balance, summary of transactions, etc

**Comment by kushalnl7** [comment]
Hi @okjodom, I am interested in this. Can you please assign this to me so that I can try working on it?

**Comment by okjodom** [comment]
Go for it :)

**Comment by okjodom** [comment]
However, I recommend you wait for #1718  to land so you have a clean starting point requiring you to implement changes in one place only

**Comment by justinmoon** [comment]
You could also just branch off #1718 and then make a PR based on that. Should be compatible once #1718 gets merged.

**Comment by kushalnl7** [comment]
Sure, I will follow everything and then raise a PR. Thanks!

**Comment by okjodom** [comment]
Go for it! There should be no blockers for tacking this issue right away.

Afaik (assumption), @kushalnl7 dropped their interest in this issue by removing their own assignment. Go ahead and claim this issue, @oleonardolima.

And yes, there's tons of other good first issues in this space, so we won't run out of room to contribute :)

**Comment by oleonardolima** [comment]
@okjodom Great! I'll start working on it then 🚀

**Comment by oleonardolima** [comment]
Cool! I'll follow this path then

> why, what are your thoughts?
Ah, because by the other approach, I was thinking it could be multiple calls to existing routes, instead of passing a query parameter, that would need to handle and combine the data on cli client and I guess wouldn't be that great 😅

**Comment by oleonardolima** [comment]
@okjodom I got myself with two questions related to the tests:

- the specific tests for gateway-cli are those in cli-test.sh ?
- there are no tests yet related to the ln-gateway and rpc-client (besides the one for auth) ?

I was wondering at which place would be appropriate to add some tests related to the change 🤔, am I missing something ?

**Comment by okjodom** [comment]
We have no specific tests for the **gateway-cli**.
[cli-test.sh](https://github.com/fedimint/fedimint/blob/master/scripts/cli-test.sh) is meant to test the **fedimint-cli**, and not gateway-cli. However, you might find an instance where gateway-cli is applied in the course of testing fedimint cli.
> Opinion: I don't think we wan't a shell test for **gateway-cli**.

You probably noticed that **gateway-cli** uses an instance of this [`RpcClient`](https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/src/rpc/rpc_client.rs#L19) to interact with Gatewayd API. Now a similar instance of `RpcClient` is used in existing gatewayd [athentication_tests](https://github.com/fedimint/fedimint/blob/master/gateway/tests/tests/tests.rs#L37) thus there's already some coverage on the APIs from that angle. I'm [proposing an extensive gatewayd test suite](https://github.com/fedimint/fedimint/pull/1702) that would excersise  `RpcClient` API even further.
> Gap: Given `RpcClient` api surface is naturally tested by it's application in gatewayd tests, If we needed tests for **gatewayd-cli**, we'd scope them to testing of the CLI option parsing and error handling only.

Here is another related WIP, [simplifying the gateway test structure](https://github.com/fedimint/fedimint/pull/1703)

**Comment by justinmoon** [comment]
> the specific tests for gateway-cli are those in cli-test.sh ?

In the next week the way we test the CLIs is going to change a lot. We'll replace the `cli-test.sh` with some tests in Rust that call out the the shell. At that point would be a good time to write some tests for the `gateway-cli`. @Maan2003 working on this migration here FYI -> https://github.com/fedimint/fedimint/pull/1910.

**Comment by justinmoon** [comment]
I potentially good first step in this direction would be to allow naming gateways. Then you could do commands with `gateway-cli info <name>` where name is something you can remember. Pasting federation IDs isn't fun!

**Comment by oleonardolima** [comment]
> We have no specific tests for the **gateway-cli**.
> [cli-test.sh](https://github.com/fedimint/fedimint/blob/master/scripts/cli-test.sh) is meant to test the **fedimint-cli**, and not gateway-cli. However, you might find an instance where gateway-cli is applied in the course of testing fedimint cli.

Oh, I misunderstood it, thanks for the explanation. Yes, that was it I saw the usage of gateway-cli and inferred that 😅

> I'm https://github.com/fedimint/fedimint/pull/1702 that would excersise RpcClient API even further.

Good! I'll take a look at it.
   
   
 --
   
   
> In the next week the way we test the CLIs is going to change a lot. We'll replace the cli-test.sh with some tests in Rust that call out the the shell ...

Thanks, I'll check it and I'll give it a try on a test the change only for the Gatewayd API for now.

> A potentially good first step in this direction would be to allow naming gateways...

Good point, this seems really interesting 🤔

**Comment by oleonardolima** [comment]
@okjodom I'm not yet well aware of what info would be a must, should I focus on the balance and summary of transactions for now?

FYI: I'm hoping to open the PR later today (tonight) 😁

**Comment by okjodom** [comment]
> @okjodom I'm not yet well aware of what info would be a must, should I just focus on the balance and summary of transactions for now?
> 
> BTW: I'm hoping to open the PR later today (tonight) grin

ATM I'm only keen on seeing the filtering capacity.
> 
    gateway-cli info continues to return high level info about all connected federations. Info should include:
        - list of federations.
        - each federation in list should show federation id
    gateway-cli info <federation-id> should return detailed info about the federation identified. Info should include:
        - federation id
        - balance held in federation
        
 We will then build out these API further in future. For example, when we build transaction history and accounting within a federation, we might want to show that in the detailed `gateway-cli info <federation-id>`

**Comment by elsirion** [comment]
Dup of the already fixed #3815.
