### ISSUE TITLE
One time join codes

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1727]
Add a mechanism to optionally limit the times a join code can be used. This will never be bulletproof but might be useful to avoid temporary testing federations being used too widely.

**Comment by jkitman** [comment]
Join code currently being the `WsClientConnectInfo` string?

How would we implement that?

I think the more bulletproof way to implement will be as part of our DoS protection where we might require clients to present blinded tokens to make requests.  Join codes could allow a certain number of these tokens to be redeemed.

**Comment by elsirion** [comment]
> Join code currently being the `WsClientConnectInfo` string?

Yes.

> I think the more bulletproof way to implement will be as part of our DoS protection where we might require clients to present blinded tokens to make requests. Join codes could allow a certain number of these tokens to be redeemed.

I'd say don't over-engineer it for now, keeping the twitter masses at bay is orders of magnitudes easier than solving the DoS problems and solves a big problem already. I could imagine just including a random 64bit number that can be supplied to the federation and guardians will only answer with the config once for every number. So any client that wants to limit signups can require this number in the join code and use the federation to deny entry if re-used (e.g. posted on twitter). You could still easily build a website to generate new join codes on the fly, but someone *would have to do that* and it would still slow down spread since it's more cumbersome.

**Comment by jkitman** [comment]
So this would be generated and enforced by each guardian independently without consensus?

Currently I think most API requests assume a threshold of peers answer the same, however now that the config API can validate success from only one guardian that should work in theory, but could create availability issues.

**Comment by elsirion** [comment]
> So this would be generated and enforced by each guardian independently without consensus?

Yes, that's the idea. As long as we use threshold querying that should work: you burn your fetch config token with t of n guardians, next time someone uses it with a different set of t there will not be enough left anymore to return a config instead of the error "token was already used".
