### ISSUE TITLE
Add connect string encoder/decoder to `fedimint-cli`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1730]
Since we now use bech32 encoding for federation connect strings we should have a way to inspect and manipulate them.

**Comment by justinmoon** [comment]
What would an "encoder" take as input? JSON?

**Comment by elsirion** [comment]
Probably best to do it that way, just the JSON representation of `WsClientConnectInfo`. You are right that this probably doesn't generalize well.

**Comment by justinmoon** [comment]
@jp1ac4 just start with the decoding side of this. Let us know if you have any questions.

**Comment by jp1ac4** [comment]
Is the encoding part also required? Perhaps it could take `federation_id` and a list of `url`s as arguments?

**Comment by justinmoon** [comment]
That sounds useful @jp1ac4. I'd say give it a try.

**Comment by justinmoon** [comment]
@jp1ac4 Closing this because it looks done. Let me know if I'm wrong!

**Comment by jp1ac4** [comment]
Hi @justinmoon, I think the only thing that might remain is to optionally pass JSON to the encoder instead of the `--id` and `--urls` arguments, but not sure if this is required.
