### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1732]
Last summer we ran some tests to see how many transactions-per-second fedimint could achieve with various settings.

It would be useful to have tests like these and run them periodically.

**Comment by jkitman** [comment]
We do have latency tests.  I think for the initial fedimints that will probably be the performance point to optimize for rather than throughput.

In other words, we should worry more about how long it takes to perform a single payment rather than how many payments per second we can achieve.

**Comment by douglaz** [comment]
yes, fedimint-load-test-tool provides many test options that can easily be run locally or remotely by anyone
