### ISSUE TITLE
Bring `threshold_crypto` into `fedimint` org ?

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1746]
Currently we're running with:

```
threshold_crypto = { git = "https://github.com/jkitman/threshold_crypto", branch = "upgrade-threshold-crypto-libs" }
```

Given how integral part it is, we should do something about it. 

Do we expect it join with the upstream, or stay forked forever? If so, should we create `fedimint_threshold_crypto`? Make a new repo in github org for it? Or make a crate inside `fedimint/fedimint`?

**Comment by dpc** [comment]
@jkitman @elsirion

**Comment by jkitman** [comment]
I think it was created by the Honey Badger folks, but the projects pretty much died in 2020.

We forked them them under the `fedimint` repo.  We should upstream my changes to those forks, the only thing preventing us has been the `mock_crypto` in `threshold_crypto` being broken after some lib upgrades that we never got around to fixing.

**Comment by dpc** [comment]
> We should upstream my changes to those forks, the only thing preventing us has been the `mock_crypto` in `threshold_crypto` being broken after some lib upgrades that we never got around to fixing.

Technical debt. :moneybag:

**Comment by elsirion** [comment]
Let's still move it into the org and track the tech debt.

**Comment by jkitman** [comment]
We can close, maybe one day we'll have time for #515
