### ISSUE TITLE
Check where we can move trait bounds to remove redundancy

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1752]
E.g. @mxz42 noticed the following, but there are more instanced like that:

> right, so we could move the `'static` bound into the trait `IntoDynInstance` where the associated type is defined: `type DynType: 'static`?

_Originally posted by @mxz42 in https://github.com/fedimint/fedimint/pull/1661#discussion_r1116284227_

**Comment by dpc** [comment]
Done AFAICT?
