### ISSUE TITLE
Linter improvements

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1756]
- [ ] [Unused macro arguments](https://github.com/fedimint/fedimint/pull/1748#pullrequestreview-1312726737)
- [ ] [Unused error enum variants](https://github.com/fedimint/fedimint/pull/1718/commits/386b16e8b457325baefc95724df73bc3b2836d59)

**Comment by dpc** [comment]
> [Unused error enum variants](https://github.com/fedimint/fedimint/pull/1718/commits/386b16e8b457325baefc95724df73bc3b2836d59)

In a `pub enum` one never knows if a variant is really unused, as any downstream consumer might be actually using it.

> https://github.com/fedimint/fedimint/pull/1748#pullrequestreview-1312726737

I couldn't find this one being implemented. And when thinking about it - it might be tricky, as there might be reasons why an argument in a macro doesn't get expanded etc.

Anyway - I don't think there's going to be anything actionable here for foreseeable future.

**Comment by justinmoon** [comment]
> In a pub enum one never knows if a variant is really unused, as any downstream consumer might be actually using it.

Sure, but if an enum represents errors produced by us, then no downstream consumer should have any business using them if we never produce that error ourselves

**Comment by dpc** [comment]
There's no way for linter to figure it out though. If it's a public enum anyone can create it (even downstream create) and pass it anywhere (even another downstrem crate). There might be cases where private fields or inner-private structs make it impossible, but these are corner cases, lots of complexity to figure it out. Maybe it is even implemented for some of such cases.
