### ISSUE TITLE
Partial client config check

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1769]
We need to ensure that clients that support only a subset of modules kinds that the federation is running can still interact with it.

I've noticed that the client side config verification is not compatible with it, as for every module it needs to call `ModuleGen::hash_client_module`.

This usage of json for module config keeps getting in a way, but nothing obvious comes to my mind when thinking about self-describing, deterministic encoding that would work in it's place.

I think what I'm going to do is to add a map of hashes `ClientConfig`, so for modules that the client doesn't support, it will just trust the provided config *for that one hash*.

**Comment by dpc** [comment]
@jkitman

**Comment by jkitman** [comment]
That seems okay with me.

There may be certain cases where a new module deprecates an old module, but we could flag that as a change in the old module.

**Comment by dpc** [comment]
> There may be certain cases where a new module deprecates an old module, but we could flag that as a change in the old module.

Probably the global config should include some generic datastructure describing deprecations.

**Comment by dpc** [comment]
I think I've fixed most of the issues, and we're able to run a vanilla LN gateway code against a federation with modules the LN gateway doesn't know about.
