### ISSUE TITLE
CI should check that our core-lightning plugin shuts down when lightningd does

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1771]
Currently our plugin sometimes keeps running after lightningd ends ... which causes port conflicts and generally is very annoying when it happens

**Comment by elsirion** [comment]
Could this be a timing issue where one task is uncooperative but the task group only kills it after ~10s?

**Comment by justinmoon** [comment]
> Could this be a timing issue where one task is uncooperative but the task group only kills it after ~10s?

I don't think so. Sometime it is never stopped. The is the the extension sometimes doesn't seem to know that lightningd has stopped.

**Comment by m1sterc001guy** [comment]
I believe this PR fixes the issue: https://github.com/fedimint/fedimint/pull/2061

I haven't seen the extension running now after `lightningd` is killed. But we should still update CI to verify this.

**Comment by m1sterc001guy** [comment]
@justinmoon @Maan2003  do we have any checks like this with devimint?

**Comment by justinmoon** [comment]
I don't think so. Let's close since it hasn't happened recently. I remember it used to happen pretty consistently. Reopen if you disagree!
