### ISSUE TITLE
gateway-cln-extension should have an option to log to file

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1774]
When debugging problems with core-lightning plugins, you can't always depend on the logs showing up in STDOUT. 

There should probably have an environment variable like `FM_CLN_EXTENSION_LOG_FILE` which will add additional tracing subscriber which writes to file.

**Comment by justinmoon** [comment]
Related to https://github.com/ElementsProject/lightning/issues/6039

**Comment by dpc** [comment]
We are not planning to focus on CLN, so this is less important and rots in the backlog.
