### ISSUE TITLE
Test that canceling HTLCs actually cancels HTLCs

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1779]
In our lightning integrations, we send messages to the CLN / LND to cancel, or ignore HTLCs. We don't have test coverage checking that these behave as we expect.

**Comment by justinmoon** [comment]
Also test behavior around lightningd restarts https://discord.com/channels/899980449231814676/900323681098690604/1079646322036060261

**Comment by SumantxD** [comment]
@justinmoon can you assign me this issue , i would like to work on it.

**Comment by justinmoon** [comment]
@SumantxD Go ahead and start working on it. Please ask questions in the [discord](https://chat.fedimint.org/). This is a relatively difficult issue!

**Comment by m1sterc001guy** [comment]
I don't think this is worth doing now. The plan is to ship LNv2 by default in v0.6 which does not use HTLC interception.
