### ISSUE TITLE
Why isn't `ModuleGen` using associate types?

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1809]
It should use associated concrete types instead of dyn types. `IModuleGen` is the dyn type version.

**Comment by justinmoon** [comment]
Note: this is called `ServerModuleGen` now ...

**Comment by elsirion** [comment]
For illustration, see how `ClientModuleGen` returns a concrete type from `init` which is only converted to a `Dyn*` type in the generic impl of `IClientModuleGen`, while for the server both `ServerModuleGen` and `IServerModuleGen` return the `Dyn*` type.

https://github.com/fedimint/fedimint/blob/5187fa673a4335ee0c5544f3dd1040de3f2979a7/fedimint-client/src/module/gen.rs#L31-L50

https://github.com/fedimint/fedimint/blob/5187fa673a4335ee0c5544f3dd1040de3f2979a7/fedimint-core/src/module/mod.rs#L565-L571

**Comment by dpc** [comment]
Looks fixed to me.
