### ISSUE TITLE
Out of date: docs/dev-running.md

### ISSUE THREAD

**Issue by dhruv-1001** [fedimint/fedimint#1814]
I recently setup fedimint for [dev testing](https://github.com/fedimint/fedimint/blob/master/docs/dev-running.md), and noticed that this doc is out of date. The output of these commands looks different now. Is it something that is planned to be updated at some specific release?
If not, I would like to update this doc.

**Comment by elsirion** [comment]
Thx for letting us know, it's really hard to keep in sync manually and ideally we could automatically test some of it. I'd be more than happy if you could update it! :smiley:

**Comment by dhruv-1001** [comment]
Cool! On it.
