### ISSUE TITLE
Is nix caching working?

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1821]
I noticed that we built stuff in #1820 although it only included a change to the docs folder. Why doesn't nix recognize that nothing changed in the crates and just use the cached artifacts? Maybe filtering is broken?

![Screenshot 2023-03-06 at 11-19-23 fix replace broken fedimint-dummy link · fedimint_fedimint@b3ebec7](https://user-images.githubusercontent.com/84478054/223083228-8e0cf512-b2f4-4f29-bb82-11932840cb36.png)

We are using all our cachix storage, but I don't see how 20GB wouldn't be sufficient to at least keep the latest master build around which can typically be heavily reused by PRs, so wouldn't be evicted from the cache imo. If this is the problem though we could 5x storage for ~2x cost.

**Comment by dpc** [comment]
I tried with:

```
> nix build -L .#workspaceBuild
...
> echo "foo" >> docs/building-new-modules.md
...
> nix build -L .#workspaceBuild
```

The last command completes immediately. Possibly the build of the branch without your commit was not in the cache. It might have been stale or something.
