### ISSUE TITLE
Clean up DB expect boilerplate

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#1829]
Currently we have `213` instances of `.expect("DB error")` style calls in our code, this introduces a lot of useless boilerplate in our code.

In most cases we just want to get an `Option<(K, V)>` or a `Iter<(K, V)>` so perhaps we can add those as helper functions to our database trait?

@elsirion @m1sterc001guy What do you guys think about this?

**Comment by m1sterc001guy** [comment]
> The thinking behind setting a flag during insert and checking it during commit is that this would allow us to support other DBs that don't support optimistic concurrency control. Essentially the public wrappers would swallow any error during insert time and always fail at commit time, which would expose consistent semantics to the higher layers, regardless of the underlying db.

Thinking about this a tad more, one scenario where this might be problematic is if there is some code that relies on reading from the existing transaction before it is committed. If `insert_entry` fails silently, this might result in the wrong thing happening. Perhaps it is better just to panic there as well.

**Comment by elsirion** [comment]
I'm very much in favor of this and optimistic DBs don't really work with the current code base anyway. The question would be if bubbling up DB error everywhere just to support optimistic DB tx is worth it, I kinda doubt it.
