### ISSUE TITLE
Don't copy config files in test environment

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1857]
Instead just pass the full path to each invocation https://github.com/fedimint/fedimint/pull/1851#pullrequestreview-1335336570

**Comment by ayush-ranjan-official** [comment]
please assign this issue to me

**Comment by Maan2003** [comment]
this is not a good first issue. Referring to original config file is not easy due to nix and it is horrible to debug.

**Comment by ayush-ranjan-official** [comment]
@elsirion I was currently working on this one, please re-assign me.

**Comment by dpc** [comment]
Detail, not worth keeping around.
