### ISSUE TITLE
`description` parameter to `ln-invoice` should be optional

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1863]
It's optional in lightning invoices, so it should probably be optional in our CLI as well.

**Comment by elsirion** [comment]
> It's optional in lightning invoices

[It is indeed not optional](https://github.com/lightning/bolts/blob/master/11-payment-encoding.md#requirements-3), but I'd be open to just using some default description like most other wallets.

![Screenshot 2023-03-11 at 10-04-05 bolts_11-payment-encoding md at master · lightning_bolts](https://user-images.githubusercontent.com/84478054/224475514-361454dd-adaf-473e-8da0-c86b20a8539a.png)
