### ISSUE TITLE
`gatewayd` / `gateway-cln-extension` startup race condition

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1876]
`gatewayd` can't start if `FM_GATEWAY_LIGHTNING_ADDR` set and `gateway-cln-extension` not running. We shouldn't have a race condition like this. Either one should be able to startup first.

**Comment by elsirion** [comment]
I think it comes down to having some reconnect logic, a lot like with the API client. This will also help when CLN+extension get restarted but not `gatewayd` (otherwise `gatewayd` would just crash I assume?).

**Comment by justinmoon** [comment]
note: talk to @Maan2003 about websocket client reconnect struct etc ...

**Comment by justinmoon** [comment]
- would need to retry connecting somewhere in gatewayd
- remove `await_gateway_cln_extension` and put a sleep in `gateway-cln-extension`'s `main()` to trigger this

**Comment by m1sterc001guy** [comment]
I'll look into this

**Comment by m1sterc001guy** [comment]
I think there's probably two improvements that should be done here:

1) Fix the race condition on startup (this is easy, we can add a simple loop that retries).
2) Refactor `gatewayd` to have proper error handling when the connection to the lightning node dies. Currently the connection to the lightning node is a `Arc<ILnRpcConnect>` and the Arc is simply cloned to other actors that need to do lightning RPCs. If the connection dies we don't currently have a way of reconstructing the lightning connection. `Gatewayd` doesn't actually crash, it simply won't work currently.
