### ISSUE TITLE
Can't source build.sh from `nix develop`

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1883]
On an m1 mac running stock zsh:

```
$ source scripts/build.sh 
Run with 'source ./scripts/build.sh [fed_size] [dir]
Setting up env variables in /var/folders/97/q5fc74fx3zs0rqkk9_9lb5q00000gn/T/kye9B
direnv: unloading
error: could not find `Cargo.toml` in `/Users/justin/fedi` or any parent directory
cp: misc/test/bitcoin.conf: No such file or directory
cp: misc/test/lnd.conf: No such file or directory
cp: misc/test/lightningd.conf: No such file or directory
cp: misc/test/electrs.toml: No such file or directory
```

Seems like `SRC_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"` is misbehaving. I think this is because `"BASH_SOURCE[0]` isn't defined in zsh ...

**Comment by elsirion** [comment]
Do we want to support ZSH? It's not POSIX compliant afaik, so a lot more things might not work (even if we found a workaround for this particular problem).

**Comment by justinmoon** [comment]
> Do we want to support ZSH?

I don't think so. Don't know how to address this, but people will run into this after https://github.com/fedimint/fedimint/pull/1870 because our docs will suggest people source this file.

**Comment by justinmoon** [comment]
call: we should define which shells we support ... we won't support ***everything***

**Comment by justinmoon** [comment]
Call: direnv explicitely doesn't start a new (bash) shell?

**Comment by justinmoon** [comment]
Closing this. It works fine in bash for me. Feel free to re-open if you disagree.
