### ISSUE TITLE
CI should run all tests and report all errors

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1894]
One pain point in our CI right now is when a PR has a clippy problem, and a test problem. Only the clippy problem gets reported in the first run. Then the test problem shows up as soon as the clippy problem is fixed. It would be better if both problems showed up on the first run ...

In a perfect world our CI would run all the tests and report all failures.

This could be a bunch of work so this is pretty low priority I think, but figured I'd make an issue for it ...

**Comment by dpc** [comment]
This would go against what the GH Actions do and offer, and unless GH Actions have some settings for it (which I'm not aware), does not seem worthwhile.
