### ISSUE TITLE
`distritubedgen run` certs parameter is confusing

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1897]
I was thinking that these [certs](https://github.com/fedimint/fedimint/blob/86cf965b1dd124ab518e972cf89caca0907a8934/fedimintd/src/distributed_gen.rs#L75-L78) would be TLS certs. But they're actually [these things](https://github.com/fedimint/fedimint/blob/d3d3ced6496bb7e663e143ba222ab9cfecf16c02/fedimint-server/src/config/io.rs).

Would be nice if we had a better name for ^^ in the CLI. Not urgent ... Naming is hard ... just making note while this is fresh in my mind.

**Comment by justinmoon** [comment]
@jkitman Do you think this `distributedgen` tool will just be removed with the new config API?

**Comment by jkitman** [comment]
Yep, the connection strings will be going away as soon as we have a replacement UI.

**Comment by justinmoon** [comment]
Closing
