### ISSUE TITLE
Grpc type reflection : Support jump to definitions

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#1906]
Gateway defines a lightning rpc interface using grpc types in [gatewaylnrpc.proto](https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/proto/gatewaylnrpc.proto), which passes through [potobuf compiler](https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/build.rs#L8:L12) and auto-generates Rust types in a corresponding **gatewaylnrpc.rs** (somewhere in source / build output tree).
The developer experience that interact with these autogen types is somewhat lacking right now, as we cannot jump to type definitions, i.e. the autogenerated **gatewaylnrpc.rs** is not reachable by F12 keypress.

We should look to improve the dev experience here by supporting grpc type reflection and jump to def

**Comment by Maan2003** [comment]
https://github.com/rust-lang/rust-analyzer/issues/3767

**Comment by justinmoon** [comment]
Ideally we wouldn't need IDE-specific fixes for this

**Comment by dpc** [comment]
Stale, not sure if anyone cares. Reopen if so.
