### ISSUE TITLE
Error on nix develop when setting up dev environment with multipass on M1 Mac

### ISSUE THREAD

**Issue by otech47** [fedimint/fedimint#1911]
I followed the Mac OS guide here: https://github.com/fedimint/fedimint/blob/master/docs/macos.md

![Screenshot 2023-03-14 at 1 39 04 PM](https://user-images.githubusercontent.com/4914611/225091579-7710b4d9-90de-40f0-afec-45351f16534e.png)

followed all the commands but got hung up on the `nix develop` command with this error:

![Screenshot 2023-03-14 at 1 40 14 PM](https://user-images.githubusercontent.com/4914611/225091632-5b73e34c-115d-4e77-803a-10e54311e42d.png)

hopefully the fix is easy? if so would like to add troubleshooting to docs for this

Other technical details:

`Mac OSX Ventura 13.0.1`

![Screenshot 2023-03-14 at 1 44 20 PM](https://user-images.githubusercontent.com/4914611/225092755-33f975d3-6ba5-4033-b8cf-ef24a4bfbcf0.png)

**Comment by justinmoon** [comment]
@dpc look like sepgrep won't work on an m1 linux vm 😬

**Comment by dpc** [comment]
Should be easy to fix, but we need to unblock the CI first.

You can try locally in `flake.nix`:

```
                ] ++ lib.optionals (!stdenv.isAarch64 || !stdenv.isDarwin) [
                  pkgs.semgrep
                ];
```

Turn `||` into `&&`, I guess?

**Comment by otech47** [comment]
yep that worked. so that's just a logical bugfix? meant to only include that package on non-Mac and non-arch64 machines?

if so PR fix here: https://github.com/fedimint/fedimint/pull/1918

**Comment by dpc** [comment]
> yep that worked. so that's just a logical bugfix? meant to only include that package on non-Mac and non-arch64 machines?

The scripts are written in a way that if this binary isn't there, it will just skip using it. 

But which platforms support and which don't is a bit of a guesswork. We could dig into nixpkgs source code and figure it out, but seems like a waste of time, so we'll land #1918 and CI will check it anyway.

**Comment by justinmoon** [comment]
> yep that worked. so that's just a logical bugfix? meant to only include that package on non-Mac and non-arch64 machines?

It was the line "package <semgrep> ... in <path> is not supported on `aarch64-linux`" that gave us that conclusion. Certain packages are only packaged for certain platforms ...
