### ISSUE TITLE
Explicitily test a case where ln gateway checks a contract status and gets "pending decryption"

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1920]
This going wrong leads to hard to debug flaky failures and got broken second time as it's timing dependent (after I fixed it the first time in #1798)

**Comment by dpc** [comment]
@okjodom @jkitman

**Comment by jkitman** [comment]
Looks like the changes you made to `await_preimage_decryption` should work, but is it timing out or something?

**Comment by dpc** [comment]
> 00:01:56 fedimint-test-latency> 2023-03-14T20:26:20.784152Z  WARN buy_preimage_from_federation_await_decryption{out_point=OutPoint { txid: 65cca7f04e57154594504fa6a3d368a7b3fa6eaacf3a3c2b99c7bf2a25e49043, out_idx: 0 } contract_id=8aa0a6a4ae3029a00a6577063fef03e7c3b080d25dfad95aebc3c653aa147132}: ln_gateway::actor: Failed to decrypt preimage. Now requesting a refund error=Output outcome error: Transaction rejected: TransactionReplayError(65cca7f04e57154594504fa6a3d368a7b3fa6eaacf3a3c2b99c7bf2a25e49043)

**Comment by m1sterc001guy** [comment]
We have a variation of this test in LNv2 (where the decryption fails client side). Don't think its worth spending more time on it for LNv1.
