### ISSUE TITLE
Verify that MPP / AMP payments don't cause problems for the gateway

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1938]
We think that the our invoices set flags to signal that we DON't accept AMP / MPP payments. We should verify this. Perhaps have a tests that try to do MPP / AMP and assert that the node will refuse to pay it because our invoice doesn't signal support.

**Comment by justinmoon** [comment]
I think we could create an automated test for this. 

Spawn 2 lightning nodes between the payer and recipient gateway. Paying node and gateway have direct channels to both of these nodes, but not to eachother. Then try to send payments greater than individual channel balances but less than sum of the 2 channel balances forcing mpp / amp. Perhaps there's also some more manual way of telling the node to use AMP / MPP ...

**Comment by dpc** [comment]
@m1sterc001guy Please reopen if still a problem.

**Comment by m1sterc001guy** [comment]
During invoice creation we indicate that MPP/AMP is not supported, so this is fine to close.

We are considering supporting this in LNv2 but need to carefully consider some edge cases.
