### ISSUE TITLE
Investigate adding `.vscode` config folder

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1942]
We might be able to suggest plugins (e.g. rust-analyzer, flake, etc)

We could also potentially configure these to use the LSP in our nix environment, not some random potentially incompatible one the plugin might try to download on its own.

Relevant discord thread https://discord.com/channels/990354215060795454/1085675353315479613

**Comment by justinmoon** [comment]
Alternatively, just explain in developer docs that VSCode should be started inside nix shell ...

**Comment by elsirion** [comment]
Might also help with #1906 by setting `rust-analyzer.cargo.loadOutDirsFromCheck = true`, see https://github.com/rust-lang/rust-analyzer/issues/3767#issuecomment-609441539

**Comment by dpc** [comment]
I think we largely solved VSCode problems by using `target-nix` in Nix shell to not interfere with the default `target/`.
