### ISSUE TITLE
Daily build fails

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1952]
Both `cargo udeps` and `cargo audit` fail in the [daily check](https://github.com/fedimint/fedimint/actions/runs/4433903728). I noticed it due to #1898 when trying to build all outputs of our flake.

TODO:
- [ ] remove unused deps #1962
- [x] update deps with vulnerabilities

**Comment by justinmoon** [comment]
I asked @GetPsyched to look into this
