### ISSUE TITLE
Allow overwritting modules to be instantiated during dkg

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1956]
Currently when setting up the federation the following code:

```
    /// Return legacy initialization order. See [`LegacyInitOrderIter`].
    pub fn legacy_init_order_iter(&self) -> LegacyInitOrderIter<M>
    where
        M: Clone,
    {
        for hardcoded_module in ["mint", "ln", "wallet"] {
            if !self
                .0
                .contains_key(&ModuleKind::from_static_str(hardcoded_module))
            {
                panic!("Missing {hardcoded_module} module");
            }
        }

        LegacyInitOrderIter {
            next_id: 0,
            rest: self.0.clone(),
        }
    }
```

makes it so that `"mint", "ln", "wallet"` will the 3 module instances. For users of their own modules there is no way currently than changing this code to have their own modules.

We should allow passing some `--extra-module-instance <kind> --extra-module-instance <kind>` in the command line that gets passed as `Vec<ModuleKind>` and chained to the `legacy_init_order_iter` to make things more flexible, at least until the UI allows setting up extra modules.

**Comment by ayush-ranjan-official** [comment]
please assign me, I want to work on this issue.

**Comment by ayush-ranjan-official** [comment]
How can I allow multiple line parsing such as `--extra-module-instance <kind> --extra-module-instance <kind>` using clap. please help.

**Comment by m1sterc001guy** [comment]
> For users of their own modules there is no way currently than changing this code to have their own modules.

For now, won't users still need to change the code to include the actual code for the module (DKG and the module business logic)? Are we planning on supporting some sort of dynamic linking in the future?

**Comment by elsirion** [comment]
Sure, but afaik all the CLI stuff lives in our repo and is just imported when you build your custom `distributedgen` (where you attach all your modules):

https://github.com/fedimint/fedimint/blob/master/fedimintd/src/bin/distributedgen.rs#L1-L6

**Comment by justinmoon** [comment]
call: maybe we should migrate default modules to these mechanics

**Comment by dpc** [comment]
I was mistaken and `LegacyInitOrderIter` actually implements returning all extra modules, so I think we don't have to touch this one for time being.
