### ISSUE TITLE
Update `tonic_lnd` to use `u64` to represent amounts, no `i64` as it does currently

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1961]

**Comment by elsirion** [comment]
Do you have some more context? Is this an upcoming change or something we want to change and upstream?

**Comment by justinmoon** [comment]
Ideally we could change this in upstream. Problem is that LND itself seems to use i64 to represent amounts, so maybe it's a bad idea. Right now we're having to do conversions between i64 (which `tonic_lnd` uses) and u64 (which we use). Not great.

**Comment by elsirion** [comment]
`TryInto` + expect sounds reasonable to me depending on what guarantees do they give us about the signedness.

**Comment by okjodom** [comment]
`i64` is inherited from lnd and now I think `tonic_lnd` should faithfully proxy lnds api
