### ISSUE TITLE
Document how to get connection string using `websocat`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1986]
`websocat` has `--jsonrpc` . It should be possible to make a call to a fedimint member at a given address and get a connection string from them, which makes it easier to connect and use automatically set up federations etc. without juggling client json configs etc. and even installing `fedimintd-cli`

**Comment by elsirion** [comment]
Afaik the API endpoint only gives you a full config you can then use to create a connection string from using `fedimint-cli`. We could add an endpoint for the connection string though with warnings not to use it to connect clients (you'd be trusting the one server responding).

**Comment by dpc** [comment]
Isn't there any downgrade in trustlessness between:

> you'd be trusting the one server responding

and

> endpoint only gives you a full config you can then use to create a connection string

?

**Comment by dpc** [comment]
Verification of ensuring the user is connected to federation they think they are is something we'll have to drive over and over, on different levels.

**Comment by justinmoon** [comment]
We have an unauthenticated endpoint for this. You can run `fedimint-cli dev api invite_code` and get an invite code. Closing.
