### ISSUE TITLE
Turn `tmuxinator` into re-usable `regfed`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1987]
The goal here is to make something that is fully (re-)usable on it's own, even when it's outside `fedimint` repo, that allow quickly setting up a running a N-of-M regtest federation.

It should be a script or a binary that when launched:

* Creates an tmpdir for all the relevant files (can be overriden with a `REGFED_DIR` env or `--dir`).
* Initializes all the daemons we use (bitocoind, LN, ...) in the right order etc. (here is the majority of the logic); by default it should take them from `PATH` (so just `bitcoind`, `bitcoin-cli`, etc.) but it should be possible to overwrite with `REGFED_BITCOIND_BIN=...` (or `--bitcoind-bin=`).
* Makes them output logs to `$REGFED_DIR/out/program`.
* Initializes federation with `fedimintd` (again, default to one from `PATH`, allow overwritting with `$REGFED_FEDIMINTD_BIN=...`; outputs written to `$REGFED_DIR/out/fedimintd-N`
* specificailly does not run `cargo` anywhere

Now, given such a `regfed` command we can turn our current `tmuxinator` into a simple wrapper like:

```
cargo build --all
export REGFED_FEDIMINTD_BIN=./target/debug/fedimintd
export REGFED_DIR=(mktmp ...)
regfed &
pid=...

mprocs --config .regfed-mprocs.yaml

# put in a bash trap EXIT
kill "$pid"
rm -Rf $REGFED_DIR
```

where `.regfed-mprocs.yaml` would mostly just `tail -f $REGFED_DIR/out/...` with appropriate title.

This is not very far from what we are already doing and the important difference is separating the core of it from our building system etc.

Thanks to this, we'll be able to expose it as nix flake output and people should be able to e.g.:

```
nix run github:fedimint/fedimintd#regfed -- --fedimintd_bin=./target/debug/fedimint
```

to start `fedimintd` with their own set of modules.

**Comment by dpc** [comment]
Notably, for start it wouldn't have to be Rust binary, and could be bunch of shell scripts, if only they stop doing `source ./otherscript.sh` and instead use a `source ${REGFED_SRC:-.}/otherscript.sh`. Then it should be easy to wrap them in a script that does:

```
exec env REGFED_SRC=${pkgs.regfed}/share ${pkgs.regfed}/share/regfed
```

or something.

**Comment by Maan2003** [comment]
mostly same implementation #1910

**Comment by justinmoon** [comment]
@dpc While devimint isn't exactly as suggested here, I think it accomplishes most of this and we can track future improvements separately. Closing.
