### ISSUE TITLE
Tmuxinator should run a gateway on the LND node, too

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1995]
We forgot to add [this](https://github.com/fedimint/fedimint/pull/1719/files#diff-9233a92d25c448c1e76d944bea5aa907318e0754477f53da48ee4df5f1807f9dR49) back when cherry-picking from https://github.com/fedimint/fedimint/pull/1719.

This way you can send lightning payments through either node.

**Comment by dhruv-1001** [comment]
I'll take on this one. Please assign them both to me. Thanks!

Just to clear this up, right now there is only one `gateway` using `cln`, and it have a channel with external `lnd` node. This issue expects to add another `gateway` to the federation that uses `lnd` and have a channel with same external `lnd` node. Am I missing something?

**Comment by justinmoon** [comment]
Add another pane to tmuxinator. Run `gatewayd` and connect it to `lnd` by passing [this subcommand](https://github.com/fedimint/fedimint/blob/55622707fd08e9a1dd1dda9db5da81b2f1b660ec/gateway/ln-gateway/src/bin/gatewayd.rs#L49-L62)

**Comment by justinmoon** [comment]
You'll also want to add the `switch_to_lnd_gateway` / `switch_to_cln_gateway` bash function https://github.com/fedimint/fedimint/pull/1719.

**Comment by justinmoon** [comment]
When you run `switch_to_lnd_gateway` / `switch_to_cln_gateway`, try running `fedimint-cli list-gateways` to see what changes. Ask any questions on discord!

**Comment by justinmoon** [comment]
Just realized the cli-tests don't run a LND gateway either :(

**Comment by m1sterc001guy** [comment]
This PR opens up a API for manually switching which Lightning node `gatewayd` will use without restarting `gatewayd` https://github.com/fedimint/fedimint/pull/2019

**Comment by justinmoon** [comment]
Sorry I took this one over @dhruv-1001. I was debugging gatewayd and noticed that it wasn't working at all for incoming LND payments, and in the process of fixing that I pretty much had this issue all fixed.

**Comment by dhruv-1001** [comment]
No problem @justinmoon. I learned a few things while working on it, so it's all good. 🚀
