### ISSUE TITLE
Option to run LND gateway without providing TLS cert or macaroon

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2000]
Depends on this issue getting fixed on our fork of `tonic_lnd` https://github.com/Kixunil/tonic_lnd/issues/24#issue-1456681893

**Comment by justinmoon** [comment]
@m1sterc001guy @okjodom Is this one unblocked after https://github.com/fedimint/tonic_lnd/pull/7?

**Comment by m1sterc001guy** [comment]
Closing this, I don't think it is worth spending time on. Our devimint setup works fine as is and in production gateway operators should always use a cert and macaroon
