### ISSUE TITLE
Determine how to build the (new) admin UI

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#2003]
Not sure where the best place is to put this, but we have several things to figure out before building the UI

- Where should the code live?  In the fedimint repo?  In the fedimint project?
- How should we write and test the UI?  A React PWA seems preferred.
- Should the UI access the APIs via the WASM compiled fedimint library?  Or why not?
- Should we unify the code with the current `mintgate` project?

@okjodom

**Comment by okjodom** [comment]
> Where should the code live? In the fedimint repo? In the fedimint project?

Inside fedimint repo is preferred for tighter dev loop and iteration. We'd want the version of the API and the SPA to be in lockstep

**Comment by okjodom** [comment]
> Should the UI access the APIs via the WASM compiled fedimint library? Or why not?

- We'll explore applicability of wasm vs vanilla api calls from UI clients to server

**Comment by okjodom** [comment]
> Should we unify the code with the current mintgate project?

- No. Don't unify these. But we can share common libraries, frameworks, API protocols, design guide.
-  FM default/standard UIs should feels the same. Devs should be able to jump from one to the other to contribute

**Comment by jkitman** [comment]
> The test part would be interesting to discuss. UI testing seems a bit annoying from what I hear, so maybe focus on testing the API first?

Yes, I'll be testing the new API directly, adding UI tests is still TBD whether it's worth it, but there are JS test frameworks we could use.

**Comment by jkitman** [comment]
Going to close this as complete
