### ISSUE TITLE
Add signet option to Admin UI

### ISSUE THREAD

**Issue by garyray-k** [fedimint/fedimint#2013]
in the Admin UI:
<img width="342" alt="Screenshot_2023-03-23_at_2 10 12_PM" src="https://user-images.githubusercontent.com/39040273/227308422-a3afc65a-420c-43c7-85c4-d3846e89339b.png">

Elsewhere in the code there is this enum match:
```rs
match network {
        Network::Bitcoin => Currency::Bitcoin,
        Network::Regtest => Currency::Regtest,
        Network::Testnet => Currency::BitcoinTestnet,
        Network::Signet => Currency::Signet,
    }
```

Support for all options is desired.

**Comment by justinmoon** [comment]
I think we should still implement this. The new setup UI will still take a while.

**Comment by jp1ac4** [comment]
I could take a look at this.

**Comment by garyray-k** [comment]
👏 🙌

-GK
________________________________
