### ISSUE TITLE
Allow bitcoind configuration change in Admin UI

### ISSUE THREAD

**Issue by garyray-k** [fedimint/fedimint#2014]
Currently, this configuration is changed using ENV variables when running fedimintd, but the network setting (testnet/regtest/mainnet/signet) is configurable using radio buttons.

<img width="425" alt="Screenshot 2023-03-23 at 2 19 34 PM" src="https://user-images.githubusercontent.com/39040273/227310458-82c6af86-5aee-43aa-a75b-84915848a111.png">

Expected: Allow for configuration of bitcoind settings via Admin UI

**Comment by elsirion** [comment]
Either that or the network should just be auto-detected. There were good reasons to not let Admin UI users play around with such deployment related settings, @dpc can explain it better/point to the old discussion iitc.

**Comment by jkitman** [comment]
Should probably wait for the new admin UI to fix this

**Comment by dpc** [comment]
> There were good reasons to not let Admin UI users play around with such deployment related settings, @dpc can explain it better/point to the old discussion iirc.

IIRC we mostly cared about ability to inject these from the environment, so it's possible to automate and provision the infrastructure without guardian-user necessarily have to worry about it.

But being able to override from the UI is totally fine.

**Comment by dpc** [comment]
This rots in the backlog and doesn't even seem all that needed, IMO.
