### ISSUE TITLE
Improve error "Failed to start cln plugin"

### ISSUE THREAD

**Issue by Maan2003** [fedimint/fedimint#2027]
It doesn't provide a reason. 

for me it was due to running two lightningd in parallel.

https://github.com/fedimint/fedimint/blob/46487a37b463a7f45f10ce7f6218583e8ef5d371/gateway/ln-gateway/src/bin/cln_extension.rs#L194-L196

**Comment by isaack-njama** [comment]
I'd like to work on this issue

**Comment by justinmoon** [comment]
Go for it @isaack-njama

**Comment by masikotimo** [comment]
Hey @justinmoon  picking up on this too, is it okay ?

**Comment by justinmoon** [comment]
Go for it @masikotimo

**Comment by justinmoon** [comment]
(not going to assign this to anyone ... anyone can give it a shot)

**Comment by justinmoon** [comment]
I think https://github.com/fedimint/fedimint/pull/2181 basically closed this. `cln_plugin::Builder::new()` returns `Option` so there isn't anything more we can say. We aren't given an error message.
