### ISSUE TITLE
Upstream backend choice feature flags to esplora client

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2032]
> It's annoying that we depend on OpenSSL again through `esplora-client` which uses the default TLS backend of `reqwest` which currently is native TLS (aka OpenSSL on most systems). Imo `esplora-client` should expose feature flags to choose the backend instead.

_Originally posted by @elsirion in https://github.com/fedimint/fedimint/issues/2031#issuecomment-1483773887_

**Comment by elsirion** [comment]
Opened bitcoindevkit/rust-esplora-client#44

**Comment by elsirion** [comment]
My PR in BDK got merged, not sure about the release schedule on their side, but should land in [`v0.5.0`](https://github.com/bitcoindevkit/rust-esplora-client/milestone/5?closed=1) eventually.

**Comment by jkitman** [comment]
Closing as tracked by #2325
