### ISSUE TITLE
Make extra LN gateway route hints optional

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2038]
While testing I found out that CLN apparently has problems with seeing itself as the first hop of a route hint and won't route (complains that it can't find *itself*). This sounds similar to the limitation that CLN can't pay itself.

To work around that in small testing networks with only two Lightning nodes we should add a config option or command line flag to the gateway that makes it start as if no extra route hints were available.

A separate issue is why did this not occur in CI so far? The CLN version in the test setup was `v0.12.1`. Or do we start the gateway so quickly that the channel isn't open yet, so not returned as a route hint?

**Comment by m1sterc001guy** [comment]
This was fixed with https://github.com/fedimint/fedimint/pull/2956
