### ISSUE TITLE
Use typos-cli instead of spellcheck to check for typos

### ISSUE THREAD

**Issue by ngutech21** [fedimint/fedimint#2051]
When calling 'just spell' cargo spellcheck is used to check the code for typos. Spellcheck shows a lot of false positives and is therefore IMHO not very helpful.
In the last 2 weeks I fixed a lot of typos by using 'cargo typos-cli' https://github.com/crate-ci/typos
Its very fast and it  doesn't show any false positives. 

Additionally there is a github action to check PRs for typos: https://github.com/marketplace/actions/typos-action

**Comment by elsirion** [comment]
Sounds pretty good, does it already succeed with the current code base? If so or if only minor fixes are needed we should run it in CI.

We probably wouldn't use the action directly but rather run it in nix, which has synergies with making it what `just` runs.

**Comment by ngutech21** [comment]
> Sounds pretty good, does it already succeed with the current code base? If so or if only minor fixes are needed we should run it in CI.
> 
After this PR #2076 gets merged typos doesn't report anymore errors

**Comment by ngutech21** [comment]
fixed by #2162
