### ISSUE TITLE
Investigate speed improvements of switching to AlephBFT

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#2056]
As brought up [here](https://github.com/fedimint/fedimint/discussions/1791#discussioncomment-5140650) we can probably speed up HBBFT by removing threshold encryption and only waiting for `f + 1` ABA instances (rather than `2f+1`).

Alternatively we can switch to [AlephBFT](https://github.com/fedimint/fedimint/discussions/2086) which is the better long-term solution.

**Comment by justinmoon** [comment]
No longer relevant
