### ISSUE TITLE
Failing test: test::password_hashing_works

### ISSUE THREAD

**Issue by gotlougit** [fedimint/fedimint#2077]
Hello, I've just begun to get the developer setup complete and ran `cargo test` on the repo, but I observed that the second test was failing.

Attached log:
```
running 2 tests
test tests::encrypts_and_decrypts ... ok
test tests::password_hashing_works ... FAILED

failures:

---- tests::password_hashing_works stdout ----
thread 'tests::password_hashing_works' panicked at 'assertion failed: `(left == right)`
  left: `"$argon2id$v=19$m=8,t=2,p=1$HVwJovQIaTEXAkPyXl3MqQ$+MeiEZswPa1JlqwlHw8oB/fvjY2gzj+21E/AE09TZUE"`,
 right: `"$argon2id$v=19$m=19456,t=2,p=1$HVwJovQIaTEXAkPyXl3MqQ$pQ1T/qsHMGBWxQFLSZ4hqBUfLInIAQzPWIQiVNt4UNI"`', crypto/aead/src/lib.rs:154:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::password_hashing_works

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `-p fedimint-aead --lib`
```

I am not sure if I have inadvertently messed up while setting up a dev environment or if this is a genuine issue that may have arisen during the changing of some related code, so I'd like to know if this is a good issue to solve as a first PR. 

Thanks for your help!

**Comment by justinmoon** [comment]
Thanks for sharing @gotlougit.

**Comment by jkitman** [comment]
@gotlougit If you look at `$m=19456` and `$m=8` that's the number of hash iterations.  You probably were running with the `FM_TEST_FAST_WEAK_CRYPTO` flag set incorrectly.

**Comment by jkitman** [comment]
@gotlougit can you give info on how to reproduce, otherwise I will close the issue?

**Comment by gotlougit** [comment]
I have not been able to reproduce this issue on my end again, so I am closing myself.
