### ISSUE TITLE
Add `version-hash` command to `gateway-cln-extension`

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2081]
All our other binaries have it ...

**Comment by oleonardolima** [comment]
I can give it a try 😁 

IIRC gatewayd already has this command, so it would be needed to add it here?

https://github.com/fedimint/fedimint/blob/64a418ea521ec1cd896d2d67ba0ad593145afb0e/gateway/ln-gateway/src/lib.rs#L64-L84

**Comment by justinmoon** [comment]
Hmm I guess gatewayd does have it https://github.com/fedimint/fedimint/blob/29a9aa8c704df4a3255a3f32d887f94955913d34/gateway/ln-gateway/src/bin/gatewayd.rs#L59-L64

`gateway-cln-extension` could use it [here](https://github.com/fedimint/fedimint/blob/29a9aa8c704df4a3255a3f32d887f94955913d34/gateway/ln-gateway/src/bin/cln_extension.rs#L46)
