### ISSUE TITLE
tmuxinator is broken as of latest commit: 722fd8e34

### ISSUE THREAD

**Issue by gotlougit** [fedimint/fedimint#2102]
I had cloned and run `just tmuxinator` in the nix environment, only I noticed that window 0 had not opened. `fedimintd` was also not running properly, there was an error in it.

I've obtained logs and am attaching them to this issue in order to help better illustrate what I am talking about. Hope this helps in fixing the bug!

**Comment by gotlougit** [comment]
[logs.zip](https://github.com/fedimint/fedimint/files/11149536/logs.zip)

**Comment by Maan2003** [comment]
This is a combination of #2085 and #1910 
```
Error: exit status: 2
command: /home/gotlou/Code/rust/fedimint/target/debug/fedimint-cli --data-dir /tmp/nix-shell.qrnaP5/fm-bHie/cfg switch-gateway 03de51e572d322563057bc841880127da103167056fce6f90bcbc94b8508eeab88
stdout:

stderr:
error: unexpected argument '03de51e572d322563057bc841880127da103167056fce6f90bcbc94b8508eeab88' found

Usage: fedimint-cli switch-gateway --pubkey <PUBKEY>

For more information, try '--help'.
```

**Comment by Maan2003** [comment]
how is CI still passing?
https://github.com/fedimint/fedimint/blob/master/scripts/lib.sh#L170
