### ISSUE TITLE
Support cross compilation with ARM

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#2111]
I recently tried to install `gatewayd` on a raspberry pi and realized that our packages don't currently support compilation to ARM. Hopefully isn't too hard to get working since we already support Android which is ARM.

**Comment by justinmoon** [comment]
In particular, this was regarding the [debian packaging](https://github.com/fedimint/fedimint/pull/2036) correct @m1sterc001guy?

**Comment by justinmoon** [comment]
<details>
<summary>I tried and failed to build https://github.com/fedimint/fedimint/pull/2110 on m1:</summary>

```
justin@justins-laptop fedimint % nix bundle --bundler github:NixOS/bundlers#toDEB .#gatewayd


warning: Using saved setting for 'extra-substituters = https://fedimint.cachix.org' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = fedimint.cachix.org-1:FpJJjy1iPVlvyv4OMiN5y9+/arFLPcnZhZVVCHCDYTs=' from ~/.local/share/nix/trusted-settings.json.
error: builder for '/nix/store/maqq77bl9ich1wni8nkvr57ig6nlq9kj-deb-single-gatewayd-bin-gatewayd.drv' failed with exit code 1;
       last 10 log lines:
       > Alas, could not find an ar that can handle -D option. Try installing recent gnu binutils. Aborting. {:level=>:error}
       > Traceback (most recent call last):
       > 	7: from /nix/store/jha3x9769rqy3xmz1q9h7prg79fd97mb-fpm-1.13.1/bin/fpm:20:in `<main>'
       > 	6: from /nix/store/jha3x9769rqy3xmz1q9h7prg79fd97mb-fpm-1.13.1/bin/fpm:20:in `load'
       > 	5: from /nix/store/fzdw68dhpgnv7b4kxigksbrmp8afy5gn-fpm-1.13.1/lib/ruby/gems/2.7.0/gems/fpm-1.13.1/bin/fpm:7:in `<top (required)>'
       > 	4: from /nix/store/psv0v0cdzn5hgkdi1khl7nz5za5v7lnf-ruby2.7.4-clamp-1.0.1/lib/ruby/gems/2.7.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
       > 	3: from /nix/store/fqkfy12q45nimxiw6mipidi89axvvm7h-ruby2.7.4-fpm-1.13.1/lib/ruby/gems/2.7.0/gems/fpm-1.13.1/lib/fpm/command.rb:574:in `run'
       > 	2: from /nix/store/psv0v0cdzn5hgkdi1khl7nz5za5v7lnf-ruby2.7.4-clamp-1.0.1/lib/ruby/gems/2.7.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
       > 	1: from /nix/store/fqkfy12q45nimxiw6mipidi89axvvm7h-ruby2.7.4-fpm-1.13.1/lib/ruby/gems/2.7.0/gems/fpm-1.13.1/lib/fpm/command.rb:487:in `execute'
       > /nix/store/fqkfy12q45nimxiw6mipidi89axvvm7h-ruby2.7.4-fpm-1.13.1/lib/ruby/gems/2.7.0/gems/fpm-1.13.1/lib/fpm/package/deb.rb:462:in `output': gatewayd-bin-gatewayd: ar is insufficient to support source_date_epoch. (RuntimeError)
       For full logs, run 'nix log /nix/store/maqq77bl9ich1wni8nkvr57ig6nlq9kj-deb-single-gatewayd-bin-gatewayd.drv'
```
</details>

**Comment by justinmoon** [comment]
Tried running it again on m1, and still getting the `Try installing recent gnu binutils` warning. Tried replacing `pkgs.llvmPackages.bintools` with `binutils` in the flake `buildInputs` but same error.

The `ar is insufficient to support source_date_epoch` part of the error in particular might be a clue.

**Comment by dpc** [comment]
What exactly did you run? I thought cross-compilation to different targets was working on your machine already?

**Comment by justinmoon** [comment]
```
nix bundle --bundler github:NixOS/bundlers#toDEB .#gatewayd
```

**Comment by dpc** [comment]
Probably not worth a trouble right now to investigate, but just leaving some context.

`.#gatewayd` is a native output, so this would need to go through a remote builder or something. But with a remote builder I think it should work on macos (because it actually builds on remote Linux)

Only the `.#cross.<target>.<name>` outputs use a (our custom) cross-compilation system, so these might work now.

O wonder if `nix bundle --bundler github:NixOS/bundlers#toDEB .#cross.<target>.<name>`, but I'm not even sure what it would mean. It would probably package cross-compiled binaries in a deb that is meant to be installed on Linux ...

**Comment by elsirion** [comment]
There seems to be a hacky solution: https://github.com/NixOS/bundlers/issues/8#issuecomment-1512638576

But currently we only have cross targets for client packages (whatever that means exactly), so we'd need to first cross-compile all FM binaries to the targets we want to package for (I guess mostly armhf for Raspberry Pis).

**Comment by dpc** [comment]
Would be nice, but doesn't seem like a priority and it's been in a backlog for more than a year.

**Comment by elsirion** [comment]
I had success compiling a `fedimintd` docker container on an ARM server recently and then moving the tar ball over to a raspberry pi. Just having a separate ARM build server and publishing official ARM builds might be the way to go.
