### ISSUE TITLE
Gateway UI: Update validation logic in connect federation experience

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#2126]
The connect federation form in the Gateway Admin UI has outdated validation logic since the federation connect info has changed. We should update this logic to do lightlweight validation of the input string assumed to be an encoded `WsClientConnectInfo`

Look at these source files:
- Connect federation UI: https://github.com/fedimint/fedimint/blob/master/gateway/ui/src/components/ConnectFederation.tsx
- Gateway deserialization of string to `WsClientConnectInfo`: https://github.com/fedimint/fedimint/blob/master/gateway/ln-gateway/src/lib.rs#L319:L321

![Image](https://user-images.githubusercontent.com/11217077/230050582-71f09d8b-5319-4057-97c6-9e3bbadba9b6.png)

**Comment by okjodom** [comment]
cc @naiyoma

**Comment by naiyoma** [comment]
Hey I'd like to work on this
