### ISSUE TITLE
Gateway UI: Theming

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#2129]
The goal is to create a consistent and visually appealing theme that will enhance the user experience. By introducing a theming framework, we can easily make updates and changes to the app's appearance without having to update every component individually.

Ref:
- https://chakra-ui.com/docs/styled-system/customize-theme
- https://chakra-ui.com/docs/styled-system/advanced-theming

**Comment by isaack-njama** [comment]
I would like to work on this

**Comment by okjodom** [comment]
closing as duplicate of #2464
