### ISSUE TITLE
Migrate "tmuxinator" developer playground to use mprocs

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2136]
We have a dev playground we call "tmuxinator" because it uses a tmux tool by the same name. This issue is to re-write that using [mprocs](https://github.com/pvolok/mprocs). The motivation is that it could be easier to script and customize. Also, it could be easier to use for developers who use tmux already in their development workflows.

This is a good first issue because you'll get to experience all the different services in the test environment, as well as our [new framework](https://github.com/fedimint/fedimint/issues/2101) for spawning these services.

As background, [this script ](https://github.com/fedimint/fedimint/blob/597e3eca13740645dc475a2295e3fbb9dd540f66/scripts/tmuxinator.sh) spawns all daemons needed for this environment on [this line](https://github.com/fedimint/fedimint/blob/597e3eca13740645dc475a2295e3fbb9dd540f66/scripts/tmuxinator.sh#L25). Then it starts up tmux using a configuration defined in [this file](https://github.com/fedimint/fedimint/blob/597e3eca13740645dc475a2295e3fbb9dd540f66/.tmuxinator.yml). It creates 4 windows -- a user shell for playing with CLI, fedimintd instances, lightning nodes and gateways, and bitcoind -- which just tail log files that are written to by [this](https://github.com/fedimint/fedimint/blob/master/fedimint-bin-tests/src/main.rs#L565-L578) which spawns all these daemons. Try to replicate or improve this basic experience.

**Comment by mxz42** [comment]
> This issue is to re-write that in Rust using [mprocs](https://github.com/pvolok/mprocs). 

rewrite it in rust? I thought we'd just use the tool as in the [usage of mprocs](https://github.com/pvolok/mprocs#usage) with that `mprocs.yaml` file?

**Comment by justinmoon** [comment]
> 

Typo, thanks.

**Comment by gotlougit** [comment]
I would like to take a stab at fixing this issue

**Comment by justinmoon** [comment]
Give it a try!
