### ISSUE TITLE
Add test for version-hash

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2137]
After https://github.com/fedimint/fedimint/pull/2100, all our binaries should have a `version-hash` command which will print the git hash they were compiled with.

Write a test that gets the current get hash, then calls `<binary> version-hash` for each of our binaries and asserts that each one returns the correct hash.

Bonus points: write this test in rust using [fedimint-bin-tests](https://github.com/fedimint/fedimint/tree/master/fedimint-bin-tests). Since this framework is brand new, feel free to ask @Maan2003 for help or questions in Discord.

**Comment by raman2402** [comment]
can I work on this @justinmoon ?

**Comment by justinmoon** [comment]
Go for it

**Comment by vnprc** [comment]
Is this still needed? fedimint-bin-tests appears to be gone

**Comment by Maan2003** [comment]
Fedimint bin tests is renamed to devimint

**Comment by vnprc** [comment]
I have some running code but there are a few issues that require clarification:
1. which binaries?
A quick look in `/target/debug` shows the following executable files:
- dbtool
- devimint
- faucet
- fedimint-cli
- fedimintd
- gateway-cli
- gateway-cln-extension
- gatewayd
- recoverytool

`dbtool`, `devimint`, `faucet`, and `recoverytool` do not support the `version-hash` command. Should I leave them out?

2. Should we disable the password prompt for `gateway-cli version-hash`?

```
$ gateway-cli version-hash
Enter gateway password:
version: ea79f46a6e6cbd2eeb69f765ab6659df32fcc110
```
It accepts any password and responds in a different format than the other supported binaries. I don't believe there's a good reason to gate this command with a password so we should consider updating this binary to behave the same as the other supported binaries. This is probably outside of the scope of this ticket.

3. fedimint-cli and fedimintd return a bogus placeholder git hash `01234569afbe457afa1d2683a099c7af48a523c1`. This could be caused [here](https://github.com/fedimint/fedimint/blob/master/fedimint-build/src/lib.rs#L16) or perhaps [here](https://github.com/fedimint/fedimint/blob/master/flake.nix#L93). I could use some help understanding why this happens and how it impacts development of this test.

**Comment by vnprc** [comment]
https://github.com/fedimint/fedimint/pull/2682
