### ISSUE TITLE
try build rocksdb in nix separately

### ISSUE THREAD

**Issue by Maan2003** [fedimint/fedimint#2166]
we can override the build script of crates. See https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts

we should try doing this for rocksdb and cache it.
This should help in reducing the fresh build time a lot with `cargo build`

cc @dpc

**Comment by dpc** [comment]
I don't understand. We already point the rocksdb crate at the rocksdb static c library, which avoids building the c code altogether, so it's just some relatively lightweight bindgen now. Am I missing anything?

**Comment by Maan2003** [comment]
Sorry, This is not relevant now. 
just noticed the page, and recalled my horror of 5 minutes rocksdb builds everytime.

**Comment by elsirion** [comment]
Yep, fixed in #799.

**Comment by Maan2003** [comment]
I definitely got long rocksdb build times after that. Maybe we had to remove that when switch to our fork of rocksdb?

**Comment by dpc** [comment]
@Maan2003 During a normal `cargo build`? I just checked and at least it looks like it takes a one second on my machine. Used to take minute or more.

**Comment by Maan2003** [comment]
Yes, now it is fixed. But it was not same a few months ago  (after #799)
