### ISSUE TITLE
add trailing spacing check in precommit hook

### ISSUE THREAD

**Issue by Maan2003** [fedimint/fedimint#2167]
some editors also remove trailing whitespace [example](https://github.com/fedimint/fedimint/pull/2165/files#diff-deb9bb56fb122db0b605aa5b63f95a4665c905b18dd670e1fa6c877576a94ff1L32-R32). We should avoid such useless diffs.

See check_eof in precommit-hook for inspiration

**Comment by SumantxD** [comment]
@Maan2003  I have tried to solve the issue here is the PR https://github.com/fedimint/fedimint/pull/2179

**Comment by justinmoon** [comment]
Closed by https://github.com/fedimint/fedimint/pull/2179
