### ISSUE TITLE
remove codecov comment 

### ISSUE THREAD

**Issue by Maan2003** [fedimint/fedimint#2177]
We don't need codecov comments now that we have it working correctly as a CI workflow

**Comment by justinmoon** [comment]
What is "codecov comments"?

**Comment by Maan2003** [comment]
like https://github.com/fedimint/fedimint/pull/2173#issuecomment-1500558627

**Comment by dpc** [comment]
Oh, you don't want to see it? I kind of don't mind them. I minded tons of these annotations about parts of code that were not tested. One comment per PR seems kind of reasonable.

Thoughts?

**Comment by elsirion** [comment]
I think we can keep them, good reminder to test our code :laughing: Only downside for me is getting notifications about my own PRs for now reason.
