### ISSUE TITLE
Add federation API endpoint that returns the client config

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#218]
To join a federation users have to acquire the configuration somehow. The easiest way is to create an API endpoint that returns it from each federation member. That way users can also cross-check that all members are on the same page.

An open question is the handling of LN gateways. Currently the final client config contains exactly one LN gateway, but it's none of the federation's business really which gateways users use. We could either:

* Return a pure `minimint::config::ClientConfig` and let the user client figure out how to transform it into a `ClientAndGatewayConfig`
* Wait for #200 (or similar PR with `Vec` instead of `Option`), return a `ClientAndGatewayConfig` without a GW and let the user client insert it.

**Comment by justinmoon** [comment]
I will update #200 to use `Vec`. That makes more sense.

**Comment by elsirion** [comment]
Closed by #269
