### ISSUE TITLE
Get rid of openssl

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2200]
The only thing that prevents us from cross-compiling the whole codebase (instead of just client packages) is openssl (which is harder to get for cross-compilation targets).

Seems like:

https://github.com/bitcoindevkit/rust-esplora-client/pull/44

might fix it. I'm not sure if there's any other dependency that pulls it in.

**Comment by justinmoon** [comment]
I feel like we should almost add a CI check to make sure that openssl isn't in our `Cargo.lock`. It keeps sneaking back in.

**Comment by oleonardolima** [comment]
Unfortunately `clippy` does not have a lint for something like "disallowed dependencies" (https://rust-lang.github.io/rust-clippy/master/index.html#cargo), as it would be simpler with the `.clippy.toml`. I guess it might be a good feature to propose there.

**Comment by elsirion** [comment]
We don't need special tooling for this, `grep`ing the `Cargo.lock` file should be sufficient to make sure we don't depend on openssl.

**Comment by dpc** [comment]
Note: we already have a place that does something kind of line that: https://github.com/fedimint/fedimint/blob/21ffb6deb9a8aa7cb3710674e086cd066b75b6a0/misc/git-hooks/pre-commit#L38
