### ISSUE TITLE
Include fedimint-bin-tests in codecov reports

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2213]
https://github.com/fedimint/fedimint/pull/2147#pullrequestreview-1383460372

This will be tricky because `fedimint-bin-tests` spawns binaries like `fedimintd` and `gatewayd` so Codecov will need a way to see what codepaths are being hit inside the binary. 

Related: https://github.com/taiki-e/cargo-llvm-cov

**Comment by dpc** [comment]
Rots in the backlog and is not all that important, IMO.
