### ISSUE TITLE
Faucet UI

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2214]
Last summer I build a very basic little faucet UI for fedimint: https://github.com/fedimint/faucet. It's very useful when working with fedimint clients.

Let's re-write it in Rust and over time make it look a little better. Also, we should serve it inside tmuxinator / mprocs. 

I spend a little time trying to port it to Rust recently but it doesn't work yet: https://github.com/justinmoon/faucet-rs. Could be useful starting point. It’s a very direct port of the old one. Uses a rust port of the Jinja2 templating tool that the old UI used, written by it's author: https://github.com/mitsuhiko/minijinja.

**Comment by oleonardolima** [comment]
@justinmoon I got interested in this one, would it be needed to use Jinja2 or could it be rewritten in something else ?

I was taking a look at https://github.com/leptos-rs, and it might be interesting to use it as it's entirely Rust, wdyt?

**Comment by justinmoon** [comment]
You can use whatever you like. Ideally the code wouldn't be too complex, and it would be easy to deploy. Writing entirely in Rust helps with deployment because you just get one binary at the end. Give it a shot!

For starters, just try to make it be able to mine blocks with the regtest node in tmuxinator / mprocs. Once the faucet has a balance, try to get it to pay an invoice created with `fedimint-cli ln-invoice` by doing RPC with one of the two lightning nodes in tmuxinator / mprocs.

Make sense?

**Comment by justinmoon** [comment]
Somewhat relevant https://monadical.com/posts/shades-of-rust-gui-library-list.html

**Comment by Maan2003** [comment]
note: leptos is a frontend framework, we are mostly writing a backend here.

also I love rust ui, but it has a long way to go. I would be surprised if it supported scanning qr codes and display qr codes.

**Comment by oleonardolima** [comment]
> For starters, just try to make it be able to mine blocks with the regtest node in tmuxinator / mprocs. Once the faucet has a balance, try to get it to pay an invoice created with `fedimint-cli ln-invoice` by doing RPC with one of the two lightning nodes in tmuxinator / mprocs. Use tmuxinator / mprocs as your backends. You'll need to get relevant environment variables somehow. Ping `@Maan2003` on discord and he can help!
> 
> Make sense?

Sure! I'll try to start with these features

> note: leptos is a frontend framework, we are mostly writing a backend here.

Yep, I was thinking of it mostly for the front-end/templating side of it.

> also I love rust ui, but it has a long way to go. I would be surprised if it supported scanning qr codes and display qr codes.

Good point! I've not used it yet, but that might be a bottleneck of it, I'll check it

**Comment by justinmoon** [comment]
Agree with Manmeet's comments. I think https://github.com/justinmoon/faucet-rs is a good direction. Uses Axum which we're familiar with, and a Rust port of the templating engine old version of faucet supports. This thing is very simple so so we shouldn't need much more than that.

**Comment by EthnTuttle** [comment]
is this still relevant? and if so, should it move to the UI repo?

**Comment by justinmoon** [comment]
I'm going to close this for now. Doesn't seem like there's much need. If anyone sets up a mutinynet federation they can use https://alpha.fedi.xyz/ or https://faucet.mutinynet.com/.
