### ISSUE TITLE
Rename `ContractUpdateKey`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2218]
Semantically the output outcomes of the LN module are contract updates, thus I propose renaming the key `LightningOutputOutcomeKey` in line with the value struct saved under the key. Thoughts @mxz42?

https://github.com/fedimint/fedimint/blob/724ab5313826dff6c45ec9d829977d3d950c6c2e/modules/fedimint-ln-common/src/db.rs#L42-L52

**Comment by mxz42** [comment]
sounds good I think. 
Are you proposing a general connection between the `key` and the `value` in naming? There'd be many keys/values to change.

If we rename this, we should also take a look at the [`WalletOutputOutcome`](https://github.com/fedimint/fedimint/blob/master/modules/fedimint-wallet-common/src/db.rs#L119-L123) and [`MintOutputBlindSignatures`](https://github.com/fedimint/fedimint/blob/master/modules/fedimint-mint-common/src/db.rs#L90-L94) in the mint module.

**Comment by justinmoon** [comment]
Closing this. Renames that take this long aren't happening!
