### ISSUE TITLE
`FM_PID_FILE` is extremely brittle

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2236]
I'm debugging [consensus upgrade test hanging in CI](https://github.com/fedimint/fedimint/actions/runs/4705699872/jobs/8346429730) and it looks like it comes down to `tail --pid=$pid /dev/null` hanging indefinitely.

I started looking at the code and I'm not 100% sure what's wrong, but the way we're using `FM_PID_FILE` is extremely brittle. Multiple processes are appending text to it, which I don't think is guaranteed to be atomic (outputs from multiple processes could possibly arrived mixed, which can especially mess up with lines of numbers), but at minimum ordering there is not guaranteed in the presence of multiple processes writing to it when running in parallel (`command &`) and having multiple tasks access it as well. 

@jkitman @Maan2003

**Comment by justinmoon** [comment]
It seems like the only things that still need that are `upgrade-test.sh` and `setup-test.sh`. Once they're re-written in rust, i think we can completely remove FM_PID_FILE.

**Comment by justinmoon** [comment]
`$FM_PID_FILE` was removed by https://github.com/fedimint/fedimint/pull/3007
