### ISSUE TITLE
Deduplicate database transaction raw-to-typed functions

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2247]
I needed to implement `find_by_prefix_sorted_descending` for `ModuleDatabaseTransaction` to make the new client use the improved coin selection from @douglaz. While doing so I noticed that we have quite some redundancy in the code mapping the `raw_*` functions to their typed equivalents in the man database transaction types we use.

## Easy fix

To not introduce any more redundancy in fda679ac315c210332d4a7ade9fe5d4d4a71b655 I extracted the `find_by_prefix_sorted_descending` code into a separate function, independent of database transaction types:

https://github.com/fedimint/fedimint/blob/fda679ac315c210332d4a7ade9fe5d4d4a71b655/fedimint-core/src/db/mod.rs#L2263-L2292

and then just called this function in the actual `impl`s for the database transaction types:

https://github.com/fedimint/fedimint/blob/fda679ac315c210332d4a7ade9fe5d4d4a71b655/fedimint-core/src/db/mod.rs#L1120-L1135

I think this is the least we should also do for the other functions to avoid redundancy in functional code.

## Better fix

The approach of creating separate functions deduplicates the functional code, but adds a lot of boilerplate/function signature duplication. This is less of a problem since the compiler will generally complain about inconsistencies there but it's still not ideal for refactoring.

Another idea would be a trait containing these typed functions as default impls which is implemented for all transaction types. This trait would have some functions that return the inner `&mut dyn ISingleUseDatabaseTransaction`, decoders and commit tracker that have to be implemented for each database transaction type and then the other default impls use these.

```rust
trait DatabaseTransactionExt {
    /// This is the only fn that has to be implemented on types to impl that trait
    fn get_inner_ref(&mut self) -> (&mut dyn ISingleUseDatabaseTransaction, ModuleDecoderRegistry, &mut CommitTracker);

    /// Default impl that doesn't have to be implemented on types
    #[instrument(level = "debug", skip_all, fields(key = ?key_prefix))]
    pub async fn find_by_prefix<KP>(
        &mut self,
        key_prefix: &KP,
    ) -> impl Stream<
        Item = (
            KP::Record,
            <<KP as DatabaseLookup>::Record as DatabaseRecord>::Value,
        ),
    > + '_
        where
            KP: DatabaseLookup,
            KP::Record: DatabaseKey,
    {
        debug!("find by prefix");
        let (tx, decoders, _) = self.get_inner_ref();
        let prefix_bytes = key_prefix.to_bytes();
        tx.raw_find_by_prefix(&prefix_bytes)
            .await
            .expect("Error doing prefix search in database")
            .map(move |(key_bytes, value_bytes)| {
                let key = KP::Record::from_bytes(&key_bytes, &decoders)
                    .expect("Unrecoverable error reading the DatabaseKey");
                let value = decode_value(&value_bytes, &decoders)
                    .expect("Unrecoverable error decoding the DatabaseValue");
                (key, value)
            })
    }

    // Other functions …
}
```

Implementing this trait on e.g. `ModuleDatabaseTransaction` would look as follows:

```rust
impl DatabaseTransactionExt for ModuleDatabaseTransaction {
    fn get_inner_ref(&mut self) -> (&mut dyn ISingleUseDatabaseTransaction, ModuleDecoderRegistry, &mut CommitTracker) {
        (self.isolated_tx.as_mut(), self.decoders.clone(), self.commit_tracker)
    }
}
```

**Comment by douglaz** [comment]
Another refactoring could be changing `find_by_prefix(prefix)` to `find_by_prefix(prefix, direction)` with `Direction::Forward` or `Direction::Reverse` (or even `Direction::None` to keep the current behavior).

(Instead of direction we could use `Ordering::Ascending`, etc)

Then we can make `find_by_prefix_sorted_descending` return `find_by_prefix(prefix, Direction::Reverse)` or just let everyone call `find_by_prefix(prefix, direction)`.

I thought doing this at first but it would change much more code than necessary and would introduce  `Direction::Forward` which isn't really necessary right know.

**Comment by elsirion** [comment]
I think we already implicitly rely on `Direction::Forward` being the default mode, it might just not be documented well. At least we rely on deterministic ordering I think that's the same for all guardians.

**Comment by dpc** [comment]
I believe I largely already took care of it in one of the past refactors. Please reopen if that's not the case.
