### ISSUE TITLE
Split fedimint-bin-tests into tests and test / dev environment tooling

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2260]
`fedimint-bin-tests` currently does 2 separate things:
1. Test / developer environment setup e.g. spawning daemons, funding wallets, and creating lightning channels
2. Tests against this environment which replaced the old shell script integration tests

I would propose:
- [x] Make (1) a library which contains binaries (currently it's just a binary)
- [x] The binary in (1) can spawn mprocs UI on it's own
- [x] Rename (1) to something like `devimint`
- [ ] Move (2) into the `integrationtests` crate

**Comment by garyray-k** [comment]
Relevant: https://github.com/fedimint/fedimint/pull/2349

**Comment by jkitman** [comment]
Think we can close, we are going to keep the tests in devimint/tests
