### ISSUE TITLE
Module consensus configs are not signed over currently

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2266]
```
    /// All configuration that needs to be the same for modules
    #[encodable_ignore]
    pub modules: BTreeMap<ModuleInstanceId, JsonWithKind>,
```

There was no good way to encode that free-form json, so for time being we skipped it, IIRC.

**Comment by jkitman** [comment]
We should improve the `Encodable` macro to avoid my hack there.

**Comment by dpc** [comment]
Just occured to me that we should probably just not use `Json` for any of that stuff. We could use `Vec<u8>` to have nested `Encodable` in an `Encodable`.

**Comment by elsirion** [comment]
> We could use `Vec<u8>` to have nested `Encodable` in an `Encodable`.

Why would that be useful? Deriving `Encodable` already automatically calls encode on all members.

**Comment by dpc** [comment]
> > We could use `Vec<u8>` to have nested `Encodable` in an `Encodable`.
> 
> Why would that be useful? Deriving `Encodable` already automatically calls encode on all members.

@elsirion 

Because it acts as a simple encapsulation evolope, without the need to know what's inside to decode the whole message.

Bitcoin consensus encoding is not self-describing, so you need to know in advance what type each field is and have decoder implementations for all types.

The client might want to use a federation, for which it doesn't have all the client module implementations. By encoding all module configs as `Vec<u8>` we allow the clients to treat these configs as binary blobs for the purpose of config verification. If the client does have implementation, it will feed it the `Vec<u8>` and module will be able to decode it. If it doesn't - it will simply verify the content and ignore it.

This `Vec<u8>` basically introduces an extra `lenght` field, which allows the decoder to skip what's inside it if they don't understand it.

Now that I think of it - I wonder if we should do the exact same thing in the consensus level. It's less necessary, as by definition all peer need to have code for each active module, but e.g. if anyone ever needed to replay the epoch history of a federation, and they don't necessary have all the modules, it would allow them to skip data they don't know and care about.

**Comment by elsirion** [comment]
Makes a lot of sense @dpc, sorry for being a bit dense :laughing: 

> Now that I think of it - I wonder if we should do the exact same thing in the consensus level (dyn-outputs/input/ci).

We definitely should!

**Comment by elsirion** [comment]
I think talking this through lead to a lot of good insights (#2281, #2283, #2299) but the original issue is actually not an issue, so closing. If something wasn't covered by the child issues/PRs I'd rather open a new one.
