### ISSUE TITLE
API for configuring Gateway fees

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#2271]
After #2246 , we can introduce an API for configuring gateway fees. Ideally, this should be a configuration per federation served by the gateway.

Related to #524

**Comment by techsavvyash** [comment]
hey team,
I'd like to take a dig at this one?

**Comment by m1sterc001guy** [comment]
@okjodom's PR isn't merged yet which I think makes this difficult. Looking at the PR, I'm not sure if we have agreement on how we want to express fees in the gateway. I think I agree with @justinmoon that incoming and outgoing fees should be expressed differently but I haven't thought about this too deeply. Maybe we should discuss some proposals for this first?

**Comment by justinmoon** [comment]
We need answers to [these questions](https://github.com/fedimint/fedimint/pull/2246#issuecomment-1518923916). We should write out a plan first, then write the code.

**Comment by okjodom** [comment]
> We need answers to [these questions](https://github.com/fedimint/fedimint/pull/2246#issuecomment-1518923916). We should write out a plan first, then write the code.

Ack. Perhaps we use one of the deep dive sessions to discuss the plan? Gateway fees is next in priority, after all the UI and client project we have happening

**Comment by justinmoon** [comment]
Let's discuss this thursday!

**Comment by elsirion** [comment]
We discussed fees last deep dive, but I don't remember much regarding the API to set them, if anyone else has notes would be nice to add here.

**Comment by okjodom** [comment]
closed by #3154
