### ISSUE TITLE
Add `status` endpoint

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2275]
I'm currently baby sitting a handful of test fedimntd federations. I would like to have some basic monitoring to tell me when any of federation members is down etc.

Currently I'm using http request with jsonrpc payload to ask for `getepochcount`, which works OK, but does not detect a federation member falling out of consensus.

What would be nice is to have a `status` endpoint that would respond with something like:

```
{
  epoch_count: 1234,
  consensus: "down", // or: "pending", "ready"
  peers_total: 3, // total number of other peers in federation
  peers_offline: 0, // number of peers that are down/disconnected
  peers_desync: 0,  // number of peers either offline or more than 1 epoch behind
}
```

possibly we can add some fields in the future. This way even simple http-based monitoring tools should be able to assert that jsonrpc response body has `peers_desync: 0` string in it, and each federation peer will act as it's own monitor for the whole federation.

**Comment by jkitman** [comment]
Actually I just added that here, although in a follow-up I can add additional useful info
https://github.com/fedimint/fedimint/pull/2272

**Comment by dpc** [comment]
@douglaz

**Comment by dpc** [comment]
@jkitman 

W.r.t. tracking each peer knowing which other peers can't sync: I was hoping that we don't have to query other peers actively, and that each peer passively and naturally will be able to keep a simple accounting of last epochs that other peers contributed to, etc.

E.g. in `handle_message`? It seems like we should be able to tell which peerid sent message about which epoch (`peer_msg.epoch()`). So we should be to just record that in some `peer_last_known_epoch: Arc<BTreeMap<PeerId, AtomicU64>>` and thus know which peers are are roughly in sync, and which seem to be lagging or not saying anything.

**Comment by elsirion** [comment]
We could also add a function to the network stack that lets us query which peers are connected. That would give us the following connection states:

* Disconnected
* Connected
* Contributing sending incorrect messages (wrong epoch)
* Contributing sending correct messages
* Recently produced an epoch

**Comment by dpc** [comment]
AFAIK @douglaz already had the code for the network stack that was keeping track of connection status with the peer, and it looked reasonably to me. So that was nice.

As for switching the consensus - I bet that everyone are too optimistic about how quickly it will happen, and if it doesn't take too much modifications (which I don't think it will), having the passively tracked will not make switching any more difficult.

I want to avoid peers having to call each other via APIs. It seems more work comparing to just passively keeping track of other peers (which is near free). It's another active interaction that can create issues/requirements.

BTW. @elsirion @jkitman I don't think currently peers ever call each other via API, and only talk over p2p. I think in the past I've set up some Federations that were exposing API address that were reachable by external clients, but not by other peers (because they were all behind TLS endpoint). We might want to keep it this way, as it might allow Federation to use VPNs/firewalls etc. to fend themselves off from DoS etc. With this new Federation setup, I hope we're doing everything over the p2p endpoint still.

**Comment by douglaz** [comment]
I've talked to @elsirion and he gave me some ideas, I'll play with them a bit and see how well it works in practice
