### ISSUE TITLE
Make max websocket connection configurable

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2276]
- [x] Make it a server config option
- [ ] Allow configuring this limit from the environment / CLI
- [ ] Increase the default from <s>100</s> 1000

**Comment by justinmoon** [comment]
> Isn't that here https://github.com/fedimint/fedimint/blob/master/fedimint-server/src/config/mod.rs#L152-L153

Looks like it.

[Default seems to be 1000](https://github.com/fedimint/fedimint/blob/fccd7396a5f294e61dc503b5446911823d74e720/fedimint-server/src/config/mod.rs#L58). Should we raise it a little higher? @elsirion @dpc

**Comment by elsirion** [comment]
I think the default is ok, wouldn't mind increasing though. But more importantly @dpc mentioned that we should be able to configure that limit via the environment.

**Comment by dpc** [comment]
Note: we need to increase ulimit  I guess, to have more open file descriptor. Defaults might be quite low (1k).

**Comment by dpc** [comment]
https://users.rust-lang.org/t/ballpark-number-of-mostly-idle-tcp-connections-that-async-server-can-handle/92910 I asked the community what to expect.
