### ISSUE TITLE
Review use of `SerdeEncodable`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2281]
See if you can just implement `En/Decodable` for all foreign types?

**Comment by elsirion** [comment]
It doesn't seem to be used anywhere anymore and can be removed afaik.

**Comment by dpc** [comment]
@elsirion Do we have it implemented for the crypto types encoded in module configs? I had to use it in a couple of places in #2283 . Not sure if I missed anything, but I think they are just not implemented, so removing `SerdeEncodable` now will block me.

**Comment by elsirion** [comment]
Only saw that later, will check if decodable is easy to impl there.

**Comment by elsirion** [comment]
While writing 60767d2da7d710a16f6c9f65517bc3b8bbcf4c8d I noticed the many `tiered.map(|(k, v)| (k, v.0)).collect()` hacks necessary to work with `SerdeEncodable`, this makes me even more certain that we want to get rid of it.

For now I could directly impl `Encodable`/`Decodable` for all structs, but in the future with external modules that won't always be the case and I think I should just add some options to the derive macros that let you specify custom encode/decode functions, just like `#[serde(with = "…")]`.

**Comment by dpc** [comment]
> For now I could directly impl `Encodable`/`Decodable` for all structs, but in the future with external modules that won't always be the case and I think I should just add some options to the derive macros that let you specify custom encode/decode functions, just like `#[serde(with = "…")]`.

IMO, we should have impl `Encodable`/`Decodable` for every crate we are using and need it. We can use conditional compilation and optional modules to make it feasible. After all `fedimint-core` is not general purpose, but fedimint-specific.

**Comment by elsirion** [comment]
> IMO, we should have impl `Encodable`/`Decodable` for every crate we are using and need it.

Sure, but we can only reasonably maintain this for default modules. For external modules the annotation would be useful.
