### ISSUE TITLE
Authenticate legacy setup UI

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2294]
Non-guardians shouldn't be able to use setup UI. I think this could work similarly to the [gateway RPC server](https://github.com/fedimint/fedimint/blob/9223781ec30895f1b74330aa9290cf3dc7d9fddf/gateway/ln-gateway/src/rpc/rpc_server.rs#L30-L47), but using [HTTP Basic Auth](https://docs.rs/tower-http/latest/tower_http/validate_request/struct.ValidateRequestHeader.html#method.basic) from that same tower-http library?

This change will be short-lived, given we'll be re-implementing the setup / admin UIs soon.

**Comment by justinmoon** [comment]
I guess this could also happen on the deployment side and not in our code? cc @dpc

**Comment by elsirion** [comment]
> I guess this could also happen on the deployment side and not in our code?

As long as API and Admin UI run on different ports that should work and iirc last time I set up a federation that was the case. Then the reverse proxy in front can enforce basic auth for one but not the other. If they shared the same port it might get more involved filtering which paths to protect in the reverse proxy.

**Comment by justinmoon** [comment]
One annoying thing with HTTP Basic Auth is that you need a username __and__ password. Username isn't really useful in our case. We really just need a password.

**Comment by jp1ac4** [comment]
I could take a look at this one. Should the username be an empty string and the existing password as found in `FM_PASSWORD` be used?

**Comment by elsirion** [comment]
> One annoying thing with HTTP Basic Auth is that you need a username **and** password. Username isn't really useful in our case. We really just need a password.

That might be a minor inconvenience for the time being, yet I don't think it's worth getting into implementing authentication ourselves (login form, setting+checking cookies, …). The average guardian will have to enter these credentials exactly once.

**Comment by justinmoon** [comment]
Yea, I think we should focus on having a solution in the new SPA. The first step in that is to create a password and pass that to every API call, so it's already somewhat solved.

See [this discord post](https://discord.com/channels/990354215060795454/1099601943124512799/1099601943124512799) post to see current towards a prototype

**Comment by justinmoon** [comment]
Legacy UI is dead and buried
