### ISSUE TITLE
Include binary length when encoding `Dyn*` module types

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2299]
If the module struct encodings are prepended with a length of the following data unknown modules can be skipped when decoding. See https://github.com/fedimint/fedimint/issues/2266#issuecomment-1518509747.

**Comment by elsirion** [comment]
Implemented in #2742.

The next step would be creating a `Unknown<dyn_type_b ase_name>` struct for each dyn type and decoders for these that get used in e.g. the dbdump or recovery tool where we don't mind not understanding everything.

**Comment by justinmoon** [comment]
Call: this one might be closable
