### ISSUE TITLE
Newlines added when copying multi-line text in mprocs

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2300]
First, run mprocs with `just fed-shell`. Then, generate a long string that spans multiple lines, select it, and then press "c" to copy it:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/4335621/233811674-3707ea4f-4dc9-49c1-885c-3294fdcba482.png">

When I paste this string, I get the following text with linebreaks:

```
AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABCEugU0FOLagwr2NaNai2VNvDxe0vfNXss7bfggLQVK2wa1W5
PmtX7Dm72XyraGBSljmIadzJagAwofdsWXYDdPi0ErRGfwOs/Qp9D9RZYLGetUCm46xl3Z6dR0f55+RGSLQEJ9atIW9
JJmJOPYc/lg==
```

So I can't just paste the output back into the `fedimint-cli reissue` command without manually editing the linebreaks.

[Asked this question upstream in mprocs repo, too](https://github.com/pvolok/mprocs/issues/79).

**Comment by elsirion** [comment]
Slightly related: copying doesn't work for me at all, if anyone has a idea why please lmk (I'm just piping stuff I want to copy into tmp files for now :laughing:).

**Comment by garyray-k** [comment]
From upstream repo:
<img width="916" alt="Screenshot 2023-04-30 at 10 47 26 AM" src="https://user-images.githubusercontent.com/39040273/235359416-91ab5d3a-84a5-4abd-be9f-bcde3b90cc2c.png">
