### ISSUE TITLE
lnd: Switch to asynchronous SendPaymentV2 gRPC method

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2301]
We are currently using the [lightningrpc.SendPaymentSync](https://lightning.engineering/api-docs/api/lnd/lightning/send-payment-sync#grpc) gRPC API. According to the docs, "This RPC is intended to be consumed by clients of the REST proxy" which is not what we're doing.

Should we move to the [routerrpc.SendPaymentV2](https://lightning.engineering/api-docs/api/lnd/router/send-payment-v2) gRPC method which returns a stream?

**Comment by elsirion** [comment]
Closed by #2750
