### ISSUE TITLE
New Guardian UI Code Foundations

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2307]
There are some things we'll need to accomplish regardless of decisions we make for the design. Let's do some brainstorming here and then break it out into more issues once we've made some progress:

- [x] How to do routing? I noticed that Gateway UI doesn't have (might not even need?) a router. Guardian UI probably does need one because there's 2 different parts of the app (setup and admin) and setup is a step-by-step onboarding flow.
- [x] How to share components with Gateway UI? I think that stuff like buttons, forms, containers, etc should be shared between the 2 UIs. Making re-usable components should be easy -- there already are some like [<Button />](https://github.com/fedimint/fedimint/blob/master/gateway/ui/src/components/Button.tsx) in Gateway UI. But where to put the shared components in the source tree?
- [ ] Should the Typescript code have a [workspace](https://classic.yarnpkg.com/lang/en/docs/workspaces/) like the rust code does? Imagine that would help with ^^.
- [ ] Password currently needs to be sent with every JSON-RPC request to the config API inside the "params" field. Should the user be able to come back and still be logged in? If we want this behavior we would need to persist the password client-side somehow. Or perhaps it would be better to force user to re-enter the password for every session? Then no more changes are required.
- [ ] How to manage the transition from old to new UI? Old UI runs when `FM_LISTEN_UI` environment variable is set, and currently blocks the config API from running. `fedimint-bin-tests`'s `tmuxinator` command always [sets this variable](https://github.com/fedimint/fedimint/blob/b01810900b6a771644cc9943b460aa1231fbbe35/fedimint-bin-tests/src/federation.rs#L36) so I needed to comment this out while prototyping this new UI. We need a way to tell this command whether or not to run the legacy setup UI. In general, I think we should try to get to feature parity with legacy setup UI ASAP so we can get rid of it and iterate on this new, stronger foundation.
- [ ] Will any config APIs need to change? I haven't noticed anything yet, but it's something to keep an eye on.
- [x] Rename the `gateway-ui` nix shell to `web` or `ui` so it's clearer that it can be shared by both Gateway and Guardian UIs.
- [ ] CI builds the static files, but doesn't serve them (yet). Just make sure everything still builds. Perhaps this is already happening for Gateway UI. Not sure. Should probably only do this if the PR touched this part of the code.
- [ ] CI makes preview deployments on pull requests touching any Gateway or Guardian UI. Could use a tool like Vercel for this. The big question is what federation it should run against? Or whether we can provide a usable mock API like the Gateway UI has. This will be harder for Guardian UI because you need multiple clients to really test it, and we currently envision separate "leader" and "follower" roles for these clients. Perhaps the mock could use indexeddb / localstorage to enable multiple clients running in the same browser to coordinate? The alternative would be to have CI run regtest federations for these pull requests. But this is a fair amount of infrastructure work, I expect it would take a couple weeks once we decide to do it. Expectation to start could be that reviewers just run it locally.
- [ ] Should fedimintd serve these static files (like https://github.com/fedimint/fedimint/pull/2104) or should this be delegated to deployments?
- [ ] Tabs or spaces? I see the Guardian UI is currently configured to use tabs, but in my experience spaces are more popular.
- [ ] WASM or typescript config API client? [My little prototype](https://github.com/fedimint/fedimint/compare/master...justinmoon:fedimint:guardian-ui) demonstrated that Typescript client is pretty easy to get started. 
  - [ ] If we go with Typescript client 
    - [ ] How to catch specific JSON-RPC errors. The server needs to send better JSON-RPC error codes I imagine.
    - [ ] Should we export Typescript types from Rust using something like [ts_rs](https://docs.rs/ts-rs/latest/ts_rs/)?
  - [ ] If we go with WASM, we'll need some more build tooling using something like [wasm-pack](https://rustwasm.github.io/wasm-pack/).
- [ ] How to handle PRs to federation APIs which break these UIs? Wouldn't want to force backend-focused devs (e.g. @jkitman) to write frontend code whenever the behavior of an API changes.

**Comment by garyray-k** [comment]
> WASM or typescript config API client?

TypeScript. A TS example/default Guardian UI will make it more approachable for web devs and beginners to iterate/modify for their tinkering. As excellent as Rust is, TS/JS is still the most prominent entry-level language. Unless we do it in Python... hehe

**Comment by garyray-k** [comment]
> Tabs or spaces? I see the Guardian UI is currently configured to use tabs, but in my experience spaces are more popular.

It doesn't matter, as long as it's consistent. IDEs can make spaces act like tabs, I'm not sure of the other way around. Someone with a screen reader may have a preference.
Just my two sats

**Comment by justinmoon** [comment]
> It doesn't matter, as long as it's consistent. IDEs can make spaces act like tabs, I'm not sure of the other way around. Someone with a screen reader may have a preference. Just my two sats

One thing I would want to figure out if we use tabs is how to get GitHub to display tabs with 4 spaces instead of 8 like it does for the [gateway UI code we've merged already](https://github.com/fedimint/fedimint/blob/master/gateway/ui/src/components/ConnectFederation.tsx).

**Comment by jkitman** [comment]
I don't think we need a super-strict split of backend and frontend.  I can make some small UI changes and vice-versa.

**Comment by garyray-k** [comment]
Related: https://github.com/fedimint/fedimint/discussions/2361

**Comment by EthnTuttle** [comment]
This would be good to review as a group.

**Comment by justinmoon** [comment]
I don't think this is relevant anymore
