### ISSUE TITLE
Manual recovery option for failed federations

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2309]
Currently, when more than `f=n-t` guardians are shut down in an uncoordinated manner (without calling the `upgrade` API endpoint) it can happen that some are shut down *while* processing an epoch while others are already finished, resulting in some guardians being on different epochs than others.

This poses a problem when restarting since restarts from such a failed state (>`f` offline = failed/stalled federation) requires a quorum of `t` guardians to agree on the epoch the federation is in. If the guardians can agree out of band that the most up-to-date epoch any guardian observed actually happened they should be able to recover manually though.

For this to be practical we need an API endpoint that allows manual approval/application of epoch outcomes, either by specifying the trusted epoch hash and letting `fedimintd` fetch the epoch from its peers or by giving it whole epoch outcomes. I'm not sure what the optimal design is, either would work imo, the former being slightly more convenient.

CC: @jkitman @dpc

**Comment by jkitman** [comment]
Seems okay...but we should never start from an older epoch or we will get an inconsistent database.
