### ISSUE TITLE
Modularize integration test framework

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2315]
* The [test framework](https://github.com/fedimint/fedimint/tree/master/integrationtests/tests/fixtures) defined inside [integrationtests](https://github.com/fedimint/fedimint/tree/master/integrationtests) should probably become a library that could be consumed by external module developers. Perhaps it could live in the same crate as `"(1)"` defined in [this issue](https://github.com/fedimint/fedimint/issues/2260) about splitting `fedimint-bin-tests`.
* The test framework would need to be modularized. AFAIK there is currently no way to add or remove modules.

**Comment by jkitman** [comment]
Thinking about this we need to go through the following:

- [ ] Remove the old `FakeFed` making sure we already have enough unit/integration test coverage
- [ ] Make `fedimint-testing` module-agnostic
- [ ] Refactor `integrationtests` fixtures into `fedimint-testing` and module-specific tests
- [ ] Improve the fixtures / mocks so we can get more out of our test framework
