### ISSUE TITLE
Add `fn kind(&self) -> ModuleKind` to client module traits (and possibly others)

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2319]
> I don't know what's the exact reason for it. Is it for `ModuleDecoderRegistry`? We could add `fn kind(&self) -> ModuleKind` to `Decoder` instead?

_Originally posted by @dpc in https://github.com/fedimint/fedimint/pull/2270#discussion_r1175853326_

**Comment by dpc** [comment]
Still relevant. Looking at it.

```rust
#[derive(Debug)]
pub struct ModuleRegistry<M, State = ()> {
    inner: BTreeMap<ModuleInstanceId, (ModuleKind, M)>,
    // It is sometimes useful for registries to have some state to modify
    // their behavior.
    state: State,
}
```

Stil there.

You know what? I think it's fine as is. Especially that I later added `state: State` so the idea that the registry is going to be some plain map from `instance_id` to `M` doesn't make sense to me now.

Closing.
