### ISSUE TITLE
`consenus_decode` somewhere is supectible to DoS

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2328]
I made a mistake somewhere w.r.t encode/decode mismatch, and in CI test I've seen failures with allocation failing trying to allocate some absurd amount of memory. It's a clear sign that somewhere, we're taking untrusted input and trying to allocate a collection of such capacity or something like that.

Unfortunately I've lost that CI run now, but I'm confident it was there.

We should probably port https://docs.rs/bitcoin/latest/bitcoin/consensus/encode/trait.Decodable.html#method.consensus_decode_from_finite_reader as well. And generally think about this problem.

**Comment by elsirion** [comment]
The collection issue was solved in #2766, creating  #4395 to track further improvements.
