### ISSUE TITLE
Intermittant cli-test error with string comparison

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2341]
I have twice seen this error when running `scripts/cli-test.sh`:

```
Error: Peg-out address received 0.000005 BTC, expected 0.00000500
```

The two numbers are equal, but padded differently with zeros.

**Comment by garyray-k** [comment]
It's not a string comparison?
https://github.com/fedimint/fedimint/blob/86c66355b1dcc10f0784bc938abcfc84d7a77083/devimint/src/main.rs#L260

The `Amount` type: https://docs.rs/bitcoin/latest/src/bitcoin/amount.rs.html#515 doesn't seem to do string compare for equality checks.

**Comment by garyray-k** [comment]
<img width="1047" alt="Screenshot 2023-04-30 at 9 35 08 AM" src="https://user-images.githubusercontent.com/39040273/235355762-a50600ba-56c5-4d20-aee9-5f5baf0e1559.png">

It seems something else may be flaky.

**Comment by garyray-k** [comment]
<img width="597" alt="Screenshot 2023-04-30 at 9 44 41 AM" src="https://user-images.githubusercontent.com/39040273/235356166-d86f5645-546a-4ac5-8566-1870a36ace5e.png">
Reproduced. M1 MacOS running 13.3.1

**Comment by elsirion** [comment]
This is a funny one, the expected value is hard-coded in the error message, so I assume the expected value just differs sometimes (maybe timing issues?):

https://github.com/fedimint/fedimint/blob/26649c0ad3c604e8446704e0ed0fbb733d4d1c31/devimint/src/main.rs#L259-L263
