### ISSUE TITLE
Generate invoices with route hints for multiple gateways

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2366]
If a mint has 2 gateways, the client might want to generate invoices containing one route hint for each gateway. This way, the gateways basically compete to receive the payment based on who has the better liquidity / connections. Which gateway actually receives the payment might be helpful to an algorithm scoring the performance of gateways.

**Comment by elsirion** [comment]
@joschisan does this seem feasible with the new LN architecture? It probably won't make it into the old one.

**Comment by joschisan** [comment]
To my understanding this is feasible. When we encrypt the preimage we do not specify a refund key, hence we can send the same encrypted preimage to multiple gateways (though, at any given moment only one gateway can fund a decryption contract for this decryption contract). Then we should be able to supply all gateways as route hints and the sender can try them one by one.

**Comment by joschisan** [comment]
> @joschisan can correct me, but I think this is actually slightly harder with the new architecture since the client now needs to tell multiple gateways about the contract (whereas with the old architecture it didn't need to do that).

That is correct

**Comment by m1sterc001guy** [comment]
LNv2 requires the gateway to generate the invoice, which makes this issue no longer relevant. Closing
