### ISSUE TITLE
Update `ui.md` with any new instructions for new UI

### ISSUE THREAD

**Issue by garyray-k** [fedimint/fedimint#2369]
With the new UI being hacked on currently, post merge, we should update the `ui.md` to reflect any new/updated instructions.

Originated from: https://github.com/fedimint/fedimint/pull/2351

**Comment by elsirion** [comment]
Is this still relevant since the UI was moved to a different repo?

**Comment by justinmoon** [comment]
There is no `ui.md` file anymore. Closing.
