### ISSUE TITLE
Complete gatewayd test suite

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2393]
https://github.com/fedimint/fedimint/pull/1702 introduced a test suite, but the tests themselves are mostly un-implemented

**Comment by justinmoon** [comment]
Would be also good to have tests where we crash gatewayd, lnd, and cln during an operation and make sure things resolve cleanly.

Related to https://github.com/fedimint/fedimint/issues/1560 which I'll close and track here.

**Comment by okjodom** [comment]
#3188 merged the proposed test suite and gateway client-ng test suite after client-ng migration. his fills in the gaps identified in the proposal

> Would be also good to have tests where we crash gatewayd, lnd, and cln during an operation and make sure things resolve cleanly.

Ack, as an extension to the combined gateway test suite. But we will identify scenarios on a case by case
