### ISSUE TITLE
Reconsider wallet randomness

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#2397]
Currently we XOR all the random contributions to come up with a random number.  However, this is really easy for a malicious peer to game and force the contribution to be a random number of their choice.  This could be particularly dangerous when we switch to Taproot since FROST requires that random nonces are unique or the private key may be leaked.

**Comment by EthnTuttle** [comment]
Does FROST break if just one peer uses a malicious/self-selected "random" number?

**Comment by jkitman** [comment]
IIRC in both ECDSA and Schnorr if you reuse a nonce you expose the private key (I meant Schnorr signing of Taproot addresses not FROST which is how you perform m-of-n DKG).

In current multisig nonce reuse would reveal the private key of one of the guardians.  With Taproot this would reveal the private key of the entire multisig.

**Comment by elsirion** [comment]
We don't use the randomness beacon anymore.
