### ISSUE TITLE
Provide a way to get tweaked config hash after starting consensus

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/fedimint#2418]
During the setup flow, we get tweaked config hashes for each peer so that they can be verified out of band. However, if one peer starts consensus before sharing their tweaked hash, there are not rpc calls to get it after that. That makes it really difficult to help other peers verify and start consensus. We should have an rpc method available after verifying that allows you to get that tweaked hash again.

**Comment by jkitman** [comment]
Fixed by https://github.com/fedimint/fedimint/pull/2423
