### ISSUE TITLE
Retiring `tmuxinator`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2426]
Since we got `mprocs` now, can we remove `tmuxinator`? It seems like unnecessary maintenance burden to keep both (and possibly adds confusion for newcomers).

**Comment by justinmoon** [comment]
The only problem with mprocs is that you can't easily [copy text strings](https://github.com/fedimint/fedimint/issues/2300) with it. So I still end up using tmuxinator pretty frequently. I don't think the maintainence burden is too high, but this is probably confusing to new contributors.
