### ISSUE TITLE
Modules are not hashed into consensus hash

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#2427]
We stopped using modules in the consensus config hash.  This could be a vulnerability during verification if public key sets are unverified between peers.

**Comment by elsirion** [comment]
I would have thought that we don't need that hash hack anymore, as the new client config encoding allows serializing the raw bytes of module configs when hashing the client config. Did we forget to remove `#[encodable_ignore]`? Maybe I'm missing something?

**Comment by jkitman** [comment]
Nevermind, we are encoding it.
