### ISSUE TITLE
Code sharing and common code for UI projects

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/fedimint#2429]
With #2360 coming close to being mergeable, we're going to have the start of a reusable set of UI components, theme values, and utilities. Since there will be other UI projects in this repository (i.e. `gateway/ui`) it would be ideal if it was easy to share and reuse code across these projects. There are a few ways this could be organized:

1. One folder that all UI projects live in
2. A `package.json` / `yarn.lock` in the root directory that points to the various folders that frontend projects are nested in

Both of these approaches will require some kind of monorepo code sharing solution. Some of the options here are:

* [Yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/)
* [PNPM workspaces](https://pnpm.io/workspaces)
* [Turborepo](https://turbo.build/repo)

The last thing we might want to figure out is publishing a UI library for future fedimint UI projects. This would allow folks working outside of the repository to pull in the Chakra-based UI library and make things that still have the same look & feel of a fedimint UI. I'll defer that to a future issue since that would require setting up an npm organization and coming up with a build & release pipeline. But however we organize the projects now would lay the groundwork for having that package.

**Comment by okjodom** [comment]
[Lerna](https://lerna.js.org) would be an alternative to **Turborepo**. Both build on top of Yarn or PNPM workspace primitives

**Comment by wbobeirne** [comment]
Not speaking from personal experience but it seems to be pretty broadly disliked these days. Not sure where the frustrations come from, but it's gotten a lot of "never use again" votes on State of JS: https://2022.stateofjs.com/en-US/libraries/monorepo-tools/#monorepo_tools_experience_marimekko. Not to say that public sentiment is everything!

**Comment by elsirion** [comment]
> Is there any reason the gateway UI is a separate project

The gateway and guardian are two totally separate roles, so ideally a gateway that isn't a guardian doesn't see the irrelevant UI elements (the same is true the other way around). In addition to not seeing them, ideally we don't transmit unnecessary business logic over the wire. Idk if that means the projects have to be separate or not.

**Comment by okjodom** [comment]
> Idk if that means the projects have to be separate or not.

The projects have to be separate for the reasons you've listed above, plus, we have [future designs to bundle UI into binaries](https://github.com/fedimint/fedimint/pull/2104). I'm sure we'd only want to bundle guardian set-up + admin UI into fedimintd, and only gateway admin UI into gatewayd

**Comment by wbobeirne** [comment]
Sounds good to me, but feel free to raise a flag if turborepo isn't doing the job.

**Comment by garyray-k** [comment]
Thanks for sharing the discussion here.

I imagine an npm package or blog write up or two explaining how to use a fedimintjs library to build and interact with x/y/z modules of a federation.

What are some of the other pieces there could be UI for? It seems each crate would have some demo or pattern for it.

**Comment by okjodom** [comment]
> I imagine an npm package or blog write up or two explaining how to use a fedimintjs library to build and interact with x/y/z modules of a federation.
> 
> What are some of the other pieces there could be UI for? It seems each crate would have some demo or pattern for it.

not sure I understand the question...

**Comment by okjodom** [comment]
Tempted by this blog to switch from Yarn to pnpm : https://nhost.io/blog/how-we-configured-pnpm-and-turborepo-for-our-monorepo

However given I've made some progress in setting up Turborepo + Yarn, I'll just get it done and then find time to experiment with Turborepo + pnpm, see how they compare for a small UI workspace like ours
