### ISSUE TITLE
Need additional API information from running federation server to build UI

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/fedimint#2451]
In order to build a UI for federation guardians that uses the API in `net/api.rs`, we'll need some more information. Some things we're missing:

* [x] #2990
* [x] ~Connection string (we can construct QR code client-side, no need for image)~
  * Added in #2423 
* [x] #2988
* [x] #2989

**Comment by justinmoon** [comment]
Related to https://github.com/fedimint/fedimint/issues/2948

**Comment by EthnTuttle** [comment]
Blocks: https://github.com/fedimint/ui/issues/140

**Comment by justinmoon** [comment]
Let's not do blocks for MVP. That isn't very useful. Anyone who cares about this can just read the logs.

**Comment by elsirion** [comment]
This all seems to be about extending APIs too, so can be backported quite easily and released as a minor version.

**Comment by wbobeirne** [comment]
We've got it all now, thanks.
