### ISSUE TITLE
Investigate server-side validation for Guardian UI

### ISSUE THREAD

**Issue by garyray-k** [fedimint/fedimint#2462]
Not an issue per say, but since we accept raw user input, we should look carefully at the validation of this input on the server side to prevent anything here: https://owasp.org/www-project-top-ten/

> I'm not sure if there is, but reviewing this makes me wonder about the security of some of these inputs. Fedimints operate in a trust-minimized way, but inputs from users are always an attack vector. Just pondering.

_Originally posted by @garyray-k in https://github.com/fedimint/fedimint/pull/2360#discussion_r1186956263_

**Comment by jkitman** [comment]
What do you mean by input validation?

All API calls are parsed from JSON into Rust structs using our serde library, so I believe most attacks would need to be carried out at that level.  I don't think there's any APIs in which we accept arbitrary strings from users and insert them into the DB which would expose potential DB-injection attacks.

**Comment by elsirion** [comment]
The only two structs submitted by users are afaik `PeerServerParams`

https://github.com/fedimint/fedimint/blob/448e56dd7bc293996f22f77d18bf3ae23d49c040/fedimint-core/src/admin_client.rs#L200-L212

and `ConfigGenParamsRequest`

https://github.com/fedimint/fedimint/blob/448e56dd7bc293996f22f77d18bf3ae23d49c040/fedimint-core/src/admin_client.rs#L237-L242

I see two possible problems:

* The `name` field is just a string but afaik we have more stringent requirements. But iirc these are met by normalizing the name.
* Implementations of `ServerModuleGenParamsRegistry` may not properly validate, although I also think that `serde` should take care of most cases there.

What might be interesting is testing if `Url`s are reachable and allowing correcting them in case of faulty setups.

**Comment by jkitman** [comment]
@elsirion these aren't exactly users either, these are guardians during the semi-trusted setup.

**Comment by elsirion** [comment]
Agreed, but one guardian being able to manipulate the other's `fedimintd`s would still be bad. But I also don't see this possible rn, at most they could DoS by making the configgen fail in the end (which is already the case). But e.g. preventing XSS in the name etc. is a front end issue imo.

**Comment by justinmoon** [comment]
Let's close. If there's something more concrete, create new issue.
