### ISSUE TITLE
[WIP] Issues found while stress/load testing fedimint

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#2484]
Using https://github.com/fedimint/fedimint/pull/2482

(Not necessary these are real issues, just tracking here for further discussion)

1. ~~Easily reached DEFAULT_CONFIG_DOWNLOAD_LIMIT~~
2. Easily reached DEFAULT_MAX_CLIENT_CONNECTIONS
3. Easily got https://github.com/fedimint/fedimint/blob/e9b5ee1dbfd7f2d389aa86a5f1b453509e474e8e/fedimint-core/src/module/mod.rs#L215 with DB error `Resource busy` when downloading configs
4. Connect: avg 4s/request for 1000 simultaneous users/requests
5. 51 reissue_notes: avg 7.809437966s, median 9.640151282s, max 12.396871518s, min 1.413375904s
6. 20 gateway_pay_invoice: avg 9.849404165s, median 9.844139367s, max 15.717665416s, min 5.362578855s

**Comment by m1sterc001guy** [comment]
> with DB error Resource busy when downloading configs

i think this is happening because of the one-time join codes. Without one time join codes this shouldn't be a problem. Maybe we should just serialize this API if one time join codes is active since there shouldn't be many accessing the federation anyway.

**Comment by justinmoon** [comment]
Is (1) still a problem after https://github.com/fedimint/fedimint/pull/2454? At least the default now shouldn't be enforcing the download limits ...

**Comment by douglaz** [comment]
> Is (1) still a problem after #2454? At least the default now shouldn't be enforcing the download limits ...

Yes, it was fixed

**Comment by douglaz** [comment]
Most of testing is done and issues have been fixed. Will open new issues for new problems
