### ISSUE TITLE
Cannot clear block confirmation amount

### ISSUE THREAD

**Issue by garyray-k** [fedimint/fedimint#2489]
In the Guardian UI, become a leader and try to delete the value of "block confirmations" text input.
It will prohibit you, likely because it would make the value less than the allowed amount.
This is bad UX, we should invalidate the form and disable the "Next" button (or some other similar pattern), instead of prohibiting the user from deleting the value completely.

To reproduce:
1. Follow the steps in `fedimint-ui/apps/guardian-ui/README.md` (after merging #2485) to set up a test mint
2. Try to delete the complete value of the "Block confirmations" input

**Comment by pnav1023** [comment]
Hey I'd like to work on this

**Comment by justinmoon** [comment]
Call: this is resolved

**Comment by EthnTuttle** [comment]
https://github.com/fedimint/fedimint/pull/2560
