### ISSUE TITLE
Make `fedimint-mint-client` -> `handle_cli_command` instance aware

### ISSUE THREAD

**Issue by garyray-k** [fedimint/fedimint#2490]
Address the FIXME comment here:

https://github.com/fedimint/fedimint/pull/2368#issuecomment-1543581817

https://github.com/fedimint/fedimint/blob/6527cc2b07ce3fad1ac5c19dd6f7c27b732a5786/modules/fedimint-mint-client/src/lib.rs#L511-L515

**Comment by dpc** [comment]
Stale, I don't think it applies anymore.
