### ISSUE TITLE
`pay_invoice` is not idempotent on the gateway side

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#2496]
All APIs that the gateway exposes should be idempotent. `pay_invoice` is not idempotent, which causes issues for the Lightning client. This required us to put the API request in the transition function in this PR https://github.com/fedimint/fedimint/pull/2486, when it should be in the trigger function.

**Comment by justinmoon** [comment]
What exactly isn't idempotent?

**Comment by m1sterc001guy** [comment]
When the gateway retrieves the `OutgoingContract` from the federation, if it has already been paid, it will try and retrieve the `IncomingContract` again. This contract will have a value of 0msats, which causes the gateway to error.
