### ISSUE TITLE
`devimint dev-fed` should fund new cli client

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2507]
Probably best to wait for https://github.com/fedimint/fedimint/pull/2416 and just do a peg-in

**Comment by justinmoon** [comment]
https://github.com/fedimint/fedimint/pull/2509 does this but only in tmuxinator / mprocs, not via devimint which would be better

**Comment by jp1ac4** [comment]
Hi @justinmoon, I could give this a try if you think it's beginner-friendly.

I think I got something working using the following change:
```diff
diff --git a/devimint/src/lib.rs b/devimint/src/lib.rs
index 06897f113e..d5a0a1a427 100644
--- a/devimint/src/lib.rs
+++ b/devimint/src/lib.rs
@@ -223,6 +223,12 @@ pub async fn dev_fed(process_mgr: &ProcessManager) -> Result<DevFed> {
         "starting dev federation took {:?}",
         start_time.elapsed()?
     );
+    fed.pegin(10_000).await?;
+    let note = cmd!(fed, "spend", "10000000").out_json().await?["note"]
+        .as_str()
+        .context("note must be a string")?
+        .to_owned();
+    cmd!(fed, "ng", "reissue", note).run().await?;
     Ok(DevFed {
         bitcoind,
         cln,
```
Is this the sort of thing you had in mind?

**Comment by justinmoon** [comment]
That would work, but I think it would be better to add a method like that `fed.pegin` which would exercise https://github.com/fedimint/fedimint/pull/2416. You call `fedimint-cli ng deposit-address` and `fedimint-cli ng await-deposit`. Then just call that. So we don't need to use the old client at all.
