### ISSUE TITLE
`gateway-cli info` should show the balance for each federation

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2508]

**Comment by m1sterc001guy** [comment]
We can then remove the `balance` command. Always kind of a pain to run `info` just to get the federation id then run `balance` right after

**Comment by jp1ac4** [comment]
Would this require an extra field in the `FederationInfo` struct?

**Comment by justinmoon** [comment]
> Would this require an extra field in the `FederationInfo` struct?

Yes I think so

**Comment by jp1ac4** [comment]
I think I've got this working using the following change to `get_info`, together with adding `.await` as needed elsewhere:
```diff
diff --git a/gateway/ln-gateway/src/actor.rs b/gateway/ln-gateway/src/actor.rs
index 8c9b04f833..ab355c245b 100644
--- a/gateway/ln-gateway/src/actor.rs
+++ b/gateway/ln-gateway/src/actor.rs
@@ -655,11 +655,13 @@ impl GatewayActor {
         Ok(self.client.summary().await.total_amount())
     }
 
-    pub fn get_info(&self) -> Result<FederationInfo> {
+    pub async fn get_info(&self) -> Result<FederationInfo> {
         let cfg = self.client.config();
+        let registration = self.registration.lock().expect("poisoned").clone();
         Ok(FederationInfo {
             federation_id: cfg.client_config.federation_id,
-            registration: self.registration.lock().expect("poisoned").clone(),
+            registration,
+            balance: self.get_balance().await?,
         })
     }
 }

```
(It was necessary to move the `registration` part to avoid an error about threads.)

Does that look about right?

**Comment by jp1ac4** [comment]
Thanks. I'll try to create a PR in the next few days (will be travelling a bit).

Should the PR also remove the `balance` command or would that be done separately?

**Comment by jp1ac4** [comment]
I was having some trouble with the test `gatewayd_shows_info_about_all_connected_federations` failing.

I'll have to leave this issue for now so in case someone else wants to give it a try feel free.

**Comment by builtbymartink** [comment]
I'd love to take a crack at this one. Seems like an isolated component that may be good as my first issue.

**Comment by justinmoon** [comment]
@builtbymartink go for it!
