### ISSUE TITLE
Test gateway re-registration

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2516]
The lightning gateway is supposed to re-register itself every 10 minutes. @okjodom this would be a great thing to cover in your new gateway tests. Should probably make `GW_ANNOUNCEMENT_TTL` a variable passed in to `gatewayd` so we can set the value much lower than 10 minutes for a test.

**Comment by okjodom** [comment]
Covered by `test_gateway_register_with_federation`
