### ISSUE TITLE
Validate JSON received by API

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/fedimint#2545]
Was testing https://github.com/fedimint/fedimint/pull/2494/files
Ran a single UI instance. Followed the leader flow.
Chose some values, but I think choosing 1 for the Federation size is the issue.
No other values were abnormal.
`2023-05-17T01:45:46.319402Z ERROR connection{remote_addr=127.0.0.1:58670 conn_id=2}: net::api: API handler panicked, DO NOT IGNORE, FIX IT!!! path="run_dkg"`
See logs1

Pulled `master` and still seeing failures. This time running `just run-ui` and then working up until DKG runs.
See logs2

[Archive.zip](https://github.com/fedimint/fedimint/files/11493409/Archive.zip)

P.S Sorry, not a lot of time to dig into this tonight.

**Comment by EthnTuttle** [comment]
OK, pulled more complete logs of fedimintd and they're from the tmp dir. 
[Archive.zip](https://github.com/fedimint/fedimint/files/11493571/Archive.zip)

**Comment by EthnTuttle** [comment]
```
thread 'tokio-runtime-worker' panicked at 'Invalid mint params: Invalid module params

Caused by:
    missing field `local`
```

The API should not panic if it gets bad data.
I think https://github.com/fedimint/fedimint/pull/2540/ is somewhat related but we should consider fuzz tests for the API to make sure it doesn't panic under adversarial conditions.

CC: @jkitman

**Comment by jkitman** [comment]
This is happening within DKG itself.  We catch the panic so the API doesn't actually crash.

The bigger problem is we aren't validating the JSON at the time it is passed it, but we only parse it during DKG.
