### ISSUE TITLE
`connect-info` after a `join-federation` should work

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#2556]
From an UX standpoint, it's surprising that `fedimint-cli connect-info` will fail:
```
{
  "error": "CliError",
  "kind": "GeneralFederationError",
  "message": "cannot read connect string",
  "raw_error": "No such file or directory (os error 2)"
}
```
If I've joined through `fedimint-cli join-federation`

**Comment by justinmoon** [comment]
That `[connect-info` ](https://github.com/fedimint/fedimint/blob/62dd3992b05c5d85eee4bea50929ba18c52fd1d6/fedimint-cli/src/lib.rs#L888-L901)command is completely incorrect. It reads a file that our test environment writes.

Right now it's impossible to generate a connection string from a client config. To implement this command we would either need to:
- Save the connection string we used to join
- Add a way to derive a connection string from client config
- Add an API for fetching a connection string

**Comment by justinmoon** [comment]
Call: consider making the download token an `Option`. Then connection string would be derivable from config

**Comment by okjodom** [comment]
use `fedimint-cli invite-code`
