### ISSUE TITLE
Make lightning gateway registration TTL relative

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2573]
Currently it uses an absolute timestamp for timeouts, which requires well-synchronized clocks (especially questionable for clients). With relative TTLs akin to DNS this won't be a requirement anymore.

Probably best to start from here

https://github.com/fedimint/fedimint/blob/e6d3133609745761bed52acf0ebb959c1599d4fc/modules/fedimint-ln-common/src/lib.rs#L196-L197

changing the type to a TTL type. From there on the compiler will tell what else needs to be changed.

The TTL type would probably be a combination of an `Instant` to track time since entry was added and a `Duration` signifying the remaining lifetime when the entry was added.

When an entry is submitted via the network only the remaining lifetime (original lifetime - time since entry was created) is submitted and the recipient tracks the receive time themselves. Once `time_since_receive > remaining_lifetime_on_receipt` the entry times out and is removed.

**Comment by a-moreira** [comment]
hey @elsirion, I'd like to tackle this task, if possible.
I tried implementing this using this struct (naming still temporary):
```
#[derive(Debug, Clone, Serialize, Deserialize, Hash, Decodable, Eq, PartialEq)]
pub struct GatewayLifetime {
    pub start_time: Instant,
    pub time_to_live: Duration,
}
```
then
```
...
 pub valid_until: GatewayLifetime, 
```

but first issue is that `Instant` is not `Serialize`able with serde. I'm gonna think of a workaround. What do you think?

**Comment by elsirion** [comment]
Do you even need to serialize it? The thing that should be transmitted over the wire should always be the remaining TTL, i.e. `time_to_live - (now - start_time)`. So maybe a custom serde impl that only serializes this remaining TTL would work, making the inner fields a private implementation detail?

This assumes that the struct is only serialized for being sent over the wire and never saved for longer. If that isn't true we'd need [two different serde implementations for the parent struct (see `#[serde(with = "…")]`)](https://serde.rs/field-attrs.html#with).

If you ever need to actually serialize a time, look into `SystemTime`. [It's good to be aware of the difference between `Instant` and `SystemTime` anyway](https://doc.rust-lang.org/std/time/struct.SystemTime.html).

**Comment by a-moreira** [comment]
This works for the Serde part:
```
use std::time::Instant;
use serde::{Deserializer, Serializer};

#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub struct GatewayValidity {
    start_time: Instant,
    time_to_live: Duration,
}


impl Serialize for GatewayValidity {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let remaining_ttl = self
            .time_to_live
            .checked_sub(self.start_time.elapsed())
            .unwrap(); // Ensure non-negative remaining TTL
        serializer.serialize_u64(remaining_ttl.as_secs())
    }
}

impl<'de> Deserialize<'de> for GatewayValidity {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let remaining_ttl_secs = u64::deserialize(deserializer)?;
        let start_time = Instant::now();
        let time_to_live = Duration::from_secs(remaining_ttl_secs);
        Ok(GatewayValidity {
            start_time,
            time_to_live,
        })
    }
}
```

and now it lacks `Encodable` and `Decodable`. What do you think?

**Comment by elsirion** [comment]
Looks good, for the encodable/decodable impl you probably want to encode the absolute time+TTL. Please double-check my thinking, but serde is used for short-lived network communication between devices with possibly unsynchronized clocks, while encoding is used to save to the local DB, so the reference clock stays the same but the data is persisted for a longer time.

It's a bit dirty for it to be so implicit.

**Comment by justinmoon** [comment]
@a-moreira It's probably best to try finishing https://github.com/fedimint/fedimint/pull/3149 before tackling another issue

**Comment by a-moreira** [comment]
@justinmoon done! was a little busy last week, but now I'm back at this.

@elsirion ok, I'm gonna think about it

**Comment by elsirion** [comment]
I talked to @tvolk131 and he'll take a look at this too :)

**Comment by a-moreira** [comment]
@elsirion ok, I can see the solution is already here #3289 
I'll look for another issue to try :-)
