### ISSUE TITLE
Enforce import structure through `rustfmt`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#258]
Currently different editors lead to different import structures, we [should enforce one](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#Module%5C%3A). Would also be good to explore rustfmt options a bit further.

**Comment by jkitman** [comment]
For some reason that link doesn't work, do you mean `group_imports`?

Should be trivial to add to the `rustfmt.toml`.

**Comment by justinmoon** [comment]
> For some reason that link doesn't work, do you mean `group_imports`?
> 
> Should be trivial to add to the `rustfmt.toml`.

He meant to suggest "[imports_gransularity](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#imports_granularity) > Module"
