### ISSUE TITLE
Audit functionality extremely slow

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2605]
On alpha.fedi.xyz federation, we've noticed very long time to process epoch. [I did some performance debugging.](https://github.com/fedimint/fedimint/pull/2603):

```
May 30 23:36:59 alpha-mutinynet-01 fedimintd-start[1499533]: 2023-05-30T23:36:59.724463Z  INFO consensus: Processing items from missing epoch 71498                                                                  
May 30 23:36:59 alpha-mutinynet-01 fedimintd-start[1499533]: 2023-05-30T23:36:59.724684Z DEBUG process_consensus_outcome{epoch=71498}: timing: Operation timing name=process_module_consensus_items duration_ms=0    
May 30 23:36:59 alpha-mutinynet-01 fedimintd-start[1499533]: 2023-05-30T23:36:59.724701Z DEBUG process_consensus_outcome{epoch=71498}: timing: Operation timing name=build_verification_caches duration_ms=0         
May 30 23:36:59 alpha-mutinynet-01 fedimintd-start[1499533]: 2023-05-30T23:36:59.724707Z DEBUG process_consensus_outcome{epoch=71498}: timing: Operation timing name=process_transactions duration_ms=0              
May 30 23:36:59 alpha-mutinynet-01 fedimintd-start[1499533]: 2023-05-30T23:36:59.791507Z DEBUG process_consensus_outcome{epoch=71498}: timing: Operation timing name=add sig to prev duration_ms=58                  
May 30 23:36:59 alpha-mutinynet-01 fedimintd-start[1499533]: 2023-05-30T23:36:59.798441Z DEBUG process_consensus_outcome{epoch=71498}: timing: Operation timing name=finalize_process_epoch duration_ms=73           
May 30 23:37:08 alpha-mutinynet-01 fedimintd-start[1499533]: 2023-05-30T23:37:08.349480Z DEBUG process_consensus_outcome{epoch=71498}: timing: Operation timing name=process_consensus_outcome duration_ms=8624
```

and after scratch head and adding more timing info (already squashed in the #2603) I've found the culprit:

```
May 31 01:56:11 alpha-mutinynet-01 fedimintd-start[1507456]: 2023-05-31T01:56:11.628170Z DEBUG process_consensus_outcome{epoch=71676}: timing: Operation timing name=audit duration_ms=8255
```

What's puzzling is that when using `iotop`, I'm not seeing any heavy load on the storage, and the problem surfaces as one cpu being 100% busy. Which suggests it's a CPU heavy computation, and not IO itself.

Disabling audits helped a lot and now we process the whole epoch outcome in about 30ms:

```
May 31 02:56:06 alpha-mutinynet-01 fedimintd-start[1512128]: 2023-05-31T02:56:06.678274Z DEBUG process_consensus_outcome{epoch=73105}: timing: Operation timing name=process_consensus_outcome duration_ms=30
```

IMO, the audit functionality as is, is always going to be slow. It seems like on every epoch it reads almost whole history of the federation, just to throw it away. It also seems like purely development functionality. If the code was tested thoroughly, there's no need to check all the balances on all epochs, all the time, given how expensive it is.

TODO:

* [ ] investigate why audit is soo slow and why is it a CPU, not IO problem;
* [ ] disable auditing by default (keep running in tests, and maybe when certain env variable is enabled); maybe run it periodically instead, randomly so only one peer at the time is taking the hit, while other ones can process the epoch without delay?

**Comment by dpc** [comment]
Ping @elsirion @m1sterc001guy

**Comment by elsirion** [comment]
> I think each module could just sum up their assets and liabilities each epoch and persist that. This way, you'd only need to load stuff from the last epoch. Might be interesting to measure which module was the slow one ...

The mint module already does that, my hunch is that the ln modules doesn't and as contracts accumulate it gets slower.

I think now that we have DB transactions we can actually run the check in the background using a database snapshot (I think starting a dbtx would result in that). I'm not a fan of deactivating it completely, it's good to have some defense in depth, but I agree that the current state of affairs isn't good either.

**Comment by jkitman** [comment]
We should probably implement something similar for the LN module as we do for the Mint module.  There is an additional reason to keep the audit function around: some federations may choose to operate at a profit.

**Comment by bradleystachurski** [comment]
As a heads up to other viewers, I've started working on this issue. If anyone with permissions wants to assign my way, that'd be great 🙏
