### ISSUE TITLE
Ensure modules can compile on their own

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#262]
Right now if you run `cargo test -p minimint-wallet` it will fail to compile because of features `native,tokio/sync` missing.

We should ensure that modules can be compiled and tested independently.

**Comment by justinmoon** [comment]
What's the status on this one? Would be nice to check these in CI if we don't already.

**Comment by jkitman** [comment]
I don't think we check this, but @dpc might know better.

**Comment by elsirion** [comment]
We don't test this rn. This would require additional steps in CI.

**Comment by dpc** [comment]
Let's keep it, but it's low prio.

**Comment by justinmoon** [comment]
We should check on other crates that might be used externally like `fedimint-bin-tests`. Made another issue [here](https://github.com/fedimint/fedimint/issues/2255#issue-1675510604) but closed it in favor of this one.

**Comment by elsirion** [comment]
I think this mostly works now since tests are run per-crate for parallelism. Let's re-open if the problem shows up again.

**Comment by dpc** [comment]
> I think this mostly works now since tests are run per-crate for parallelism. Let's re-open if the problem shows up again.

Confused. We specifically try to compile everything as a workspace to avoid doing any rebuilds.

**Comment by elsirion** [comment]
I remembered seeing tests being run per module, something like this but with more parallelism with nextest:

https://github.com/fedimint/fedimint/blob/9a20e325fe3af83c83b8c75eb7627cd41d1e7262/scripts/tests/test-cov.sh#L10-L30

I'd read this code as tests being built independently of each other, but maybe everything is built before and cached?
