### ISSUE TITLE
Implement Lightning reconnection

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#2625]
#2622 regresses gatewayd functionality by removing Lightning re-connection logic from gatewayd. After successful migration Gateway NG, #2600 , we should  the re-implement LN reconnection logic

**Comment by justinmoon** [comment]
Would we be able to handle this internally within structs with impl `ILnRpcClient`? 

Would be nice if it was an internal implementation detail of node-specific clients and not part of the gateway itself.
