### ISSUE TITLE
HTLC filtering on the edge

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#2626]
#2622 moves htlc filtering into gatewayd by changing the gRPC api spec of `route_htlcs`. After successful migration Gateway NG, #2600 , we should  consider efficiency gains to lightning service providers by filtering htlcs within `LightningGateway` service

**Comment by m1sterc001guy** [comment]
Ideally this should be designed to support multiple `gatewayd` processing subscribing to HTLCs from a service provider.

**Comment by m1sterc001guy** [comment]
Core Lightning support will be removed post v0.5 https://github.com/fedimint/fedimint/issues/6218, which is the only issue this applies to. Closing
