### ISSUE TITLE
Possible inconsistent UTXO wallet state

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#2635]
Currently guardians independently check if a UTXO exists in a block.  If our bitcoin RPCs are behaving correctly and there isn't a large chain split, this shouldn't be an issue, but if not we could enter a state where the federation is not in agreement about what UTXOs it controls.

This is tricky because we cannot simply await until a pending UTXO is confirmed because we don't know what block it will be mined in.  Ultimately we might want to broadcast a confirmed UTXO in consensus.

https://github.com/fedimint/fedimint/blob/master/modules/fedimint-wallet-server/src/lib.rs#L966-L975

**Comment by elsirion** [comment]
>  If our bitcoin RPCs are behaving correctly and there isn't a large chain split, this shouldn't be an issue, but if not we could enter a state where the federation is not in agreement about what UTXOs it controls.

Well, that's a basic assumption. If we have a chain split deeper than `finality_delay` we can be stolen from anyway and all bets are off. `bitcoind` having a bug would be a good reason to stop the federation just to be safe.

> we cannot simply await until a pending UTXO is confirmed because we don't know what block it will be mined in

I don't really get that: we only consider blocks that are buried `finality_delay`, unless there's a deep chain split all `bitcoind` nodes that are aware of a block should agree on the transactions included in it.

**Comment by jkitman** [comment]
`bitcoind having a bug would be a good reason to stop the federation just to be safe`

I'm saying we have no way to detect this when recognizing a change UTXO, if say the esplora server stops reporting valid txs but bitcoincore still works it could split the fed.

**Comment by dpc** [comment]
This is largtely superseded by #5585 I believe.
