### ISSUE TITLE
Switch from HBBFT to atomic broadcast abstraction based on Aleph BFT

### ISSUE THREAD

**Issue by joschisan** [fedimint/fedimint#2638]
- [x] Merge  https://github.com/fedimint/fedimint/pull/2621

- [x] Merge https://github.com/fedimint/fedimint/pull/2679

- [x] Merge https://github.com/fedimint/fedimint/pull/2678

- [x] Merge https://github.com/fedimint/fedimint/pull/2680

- [x] Merge https://github.com/fedimint/fedimint/pull/2677

- [x] Merge https://github.com/fedimint/fedimint/pull/2739

- [x] Work out final Broadcast API to simplify the recovery logic for mid session crashes. Please find a sketch of the current design here: https://github.com/fedimint/fedimint/issues/2661

- [x] Switch to the atomic broadcast abstraction. Remove rejoining logic and clean up fedimint-server.

- [x] Remove the concept of rejecting transactions after the ordering from the client; invalid transactions are discarded but never saved as rejected.

- [ ] #3343

**Comment by m1sterc001guy** [comment]
> Wrap database transaction into a read write lock to enable a single database transaction per session with read only access by the API and read/write access by the consensus

I'd be against adding any locks to the database layer as the database is responsible for taking care of concurrency. It sounds like you just want a wrapper on top of `DatabaseTransaction` that forbids writes?

**Comment by joschisan** [comment]
We need need to have two handles to a database transaction, such that one handle allows writes to the transaction while the other handle can only read. We want to be able to keep the database transaction open for several minutes before we commit it.

**Comment by justinmoon** [comment]
@joschisan Can we close this one and track smaller issue going forward?

**Comment by elsirion** [comment]
I created https://github.com/fedimint/fedimint/issues/3343, everything else appears to be done already.
