### ISSUE TITLE
`Gatewayd` unique identifier

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#2639]
Today we currently use the `node_pub_key` as the identifier of a `Gatewayd` instance. But it is possible for multiple `gatewayd` instances to share a single lightning node (i.e in the LSP case like Zebedee). `switch_active_gateway` should use this identifier instead of the public key of the lightning node.

We can probably use the public key of the `redeem_key` as this identifier.

**Comment by elsirion** [comment]
> We can probably use the public key of the `redeem_key` as this identifier.

Yes, that not being the case seems like a bug to me.

**Comment by m1sterc001guy** [comment]
I was mistaken, we actually do already use the `redeem_key` as an identifier:

`
pub fn to_gateway_registration_info(
        &self,
        route_hints: Vec<RouteHint>,
        time_to_live: Duration,
        api: Url,
    ) -> LightningGateway {
        LightningGateway {
            mint_channel_id: self.mint_channel_id,
            mint_pub_key: self.redeem_key.x_only_public_key().0,
            node_pub_key: self.node_pub_key,
            api,
            route_hints,
            valid_until: fedimint_core::time::now() + time_to_live,
            fees: self.fees,
        }
    }
`

I thought `mint_pub_key` was identifying the federation, not the gateway. This should probably just be renamed.
