### ISSUE TITLE
`Gatewayd` should not re-construct the `LightningGateway` registrations

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#2651]
Currently, when `info` is called on `gatewayd` it will return all of the federations that this gateway is registered with. However, it builds these registrations itself, rather than querying each federation. This is problematic because when it re-creates a `LightningGateway`, it now has the wrong timestamp since we're using `now() + TTL` as the time that the registration is valid for.

Ideally I don't think that `info` should return the exact `LightningGateway` structure. Some of this data is repeated across registrations and makes the output difficult to parse.

**Comment by justinmoon** [comment]
Potentially we could just save this to db and return with CLI
