### ISSUE TITLE
`Gatewayd` NG implement backup/restore

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#2652]
With the migration to using client NG, we did not implement backup/restore for `gatewayd`. Since `gatewayd` is a collection of clients, it is important to be able to back these up and restore them so operators do not loose their funds.

**Comment by elsirion** [comment]
Not sure if you meant that or only exposing an API, but currently only the e-cash module has a real backup/recovery implementation. We should make the other modules recoverable in general (deterministic peg-in tweaks, LN user redeem keys, etc. and scanning for contracts belonging to us).

**Comment by m1sterc001guy** [comment]
> Not sure if you meant that or only exposing an API

Yes, I meant implementing the already exposed API for backing up/restoring the gateway's ecash.

**Comment by justinmoon** [comment]
https://github.com/fedimint/fedimint/issues/2650 and this will be complicated to do at same time

**Comment by m1sterc001guy** [comment]
Fixed with https://github.com/fedimint/fedimint/pull/5908
