### ISSUE TITLE
fedimint-ln-client's select_active_gateway doesn't respect gateway expiry

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2664]
Once we've saved a gateway as the "active" one, we never again check it's "expiry". This makes channel management less effective because clients will never download a new registration which might contain new route hints.

https://github.com/fedimint/fedimint/blob/772c23c4dccdf2fa96fb508a1336a1725e9d98c0/modules/fedimint-ln-client/src/lib.rs#L179

**Comment by m1sterc001guy** [comment]
We have removed the active gateway, so this is no longer relevant.
