### ISSUE TITLE
Support migration through gateways

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#2689]
In case of major changes such as changing the guardian membership the easiest method of migration is to send assets through the gateways.  We will need to add the following features:

- [ ] Gateways do not use LN for fed-to-fed ecash tx
- [ ] Gateways have dynamic fees set to near-zero for migrations
- [ ] Clients have a migration mode where they will attempt to send all funds to new client's ecash through a gateway that supports migration
- [ ] Federation UI can report on progress of migration

@elsirion

**Comment by elsirion** [comment]
Related to #2633

**Comment by elsirion** [comment]
Dup of more up-to-date #3549
