### ISSUE TITLE
Upstream `tonic_lnd` feature changes

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#2718]
We currently maintain our own fork of `tonic_lnd`. Ideally, we should just depend on an upstream repo so that we do not need to explicitly maintain a separate repo and can just bump versions when we need to. 

We need to merge this https://github.com/Kixunil/tonic_lnd/pull/29 upstream to get rid of our current fork.

**Comment by okjodom** [comment]
Changes should include:
- [ ] Support for LND `routerrpc` : https://github.com/lightningnetwork/lnd/blob/0d8d0fd261402ac7b00deec4b01d5f6183302858/lnrpc/routerrpc/router.proto
- [ ] Support for LND `invoicesrpc` : https://github.com/lightningnetwork/lnd/blob/0d8d0fd261402ac7b00deec4b01d5f6183302858/lnrpc/invoicesrpc/invoices.proto
- [ ] Allow node connection via (non-https) IP addresses : https://github.com/Kixunil/tonic_lnd/issues/17
- [ ] Feature selection for minimal RPC dependency: https://github.com/Kixunil/tonic_lnd/pull/29

**Comment by garyray-k** [comment]
This impacts the environment variable for gatewayd `FM_LND_RPC_ADDR`. Would it be worth doing a check server side to make sure it's not an IP?

**Comment by okjodom** [comment]
> Would it be worth doing a check server side to make sure it's not an IP?

That would be surfacing a limitation of our connector library to gatewayd logic. I think we should continue to consider IP addresses similar to any other malformed `FM_LND_RPC_ADDR` values that a user can set when configuring gatewayd.

**Comment by justinmoon** [comment]
Call: we switched to just better-maintaining our fork. haven't attempted to upstream yet.

**Comment by okjodom** [comment]
Fedimint fork is now [published to crates.io](https://docs.rs/fedimint-tonic-lnd/latest/fedimint_tonic_lnd/) and is significantly ahead of the original upstream. We should continue supporting this fork long term, and not try upstreaming changes

**Comment by justinmoon** [comment]
Agreed @okjodom
