### ISSUE TITLE
Very slow tests

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2741]
```
test catch_up_via_block_download has been running for over 60 seconds
test crash_recovery has been running for over 60 seconds
```

Locally they take forever for me, while the CI seems to be handling them somewhat faster.

**Comment by dpc** [comment]
```
    for _ in 0..4 {
        // we clear the message queues
        federation.reset_connections();

        let handles = vec![
            federation.start_broadcast(0, 0),
            federation.start_broadcast(1, 0),
            federation.start_broadcast(2, 0),
        ];

        sleep(Duration::from_secs(60)).await;

        for (broadcast_handle, decision_handle) in handles {
            decision_handle.abort();
            assert!(broadcast_handle.await.unwrap() == Shutdown::MidSession(0));
        }
    }
```

:rofl: . @joschisan . Is this supposed to be like that? We can't have tests that take 4 minutes...

**Comment by joschisan** [comment]
Yes they are supposed to be that long but where not supposed to run in CI, I only used them for testing when I developed the broadcast locally. The long times comes from completing an entire session.

**Comment by dpc** [comment]
@joschisan Do you want to make them conditional on some env variable or something, so you can only when it makes sense?

**Comment by joschisan** [comment]
right now lets just disable them, I approved you pr for this. I will work out something like that later.
