### ISSUE TITLE
2nd fedimint user to pay lightning invoice via a gateway receives "successful payment" response

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2746]
In [making gateway payments idempotent](https://github.com/fedimint/fedimint/pull/2695), we might have made them a little too idempotent! If 2 users pay the same invoice through the same gateway, the 2nd user will receive a "payment successful" response even though they didn't pay the invoice.

To solve this I think the `/pay_invoice` API endpoint might need a secret which the gateway can use to determine if calls to pay a previously paid invoice are from them same client that paid it (return "invoice paid"), or a different client (return error).

This is low priority.

**Comment by elsirion** [comment]
There are two sub-problems imo:

1. How to prevent users from locking up funds in contracts for invoices that were already paid (federation-local)
2. How to prevent the described problem even for gateways serving multiple federations

If the gateway detects double-payment it could refund the second contract out of goodwill with an error code indicating double payment (it could also just take the money though … so this is more of a UX fix and not a fundamental security fix).

**Comment by m1sterc001guy** [comment]
> To solve this I think the /pay_invoice API endpoint might need a secret which the gateway can use to determine if calls to pay a previously paid invoice are from them same client that paid it (return "invoice paid"), or a different client (return error)

For this, could we generate an ephemeral keypair and send the public key/signature to the gateway for each `pay_invoice` invocation? For the first `pay_invoice` request that the gateway receives, it could validate the signature and save the public key in the database, indexed by the contract id. Then for subsequent requests to `pay_invoice`, the gateway can enforce that the client provides a signature to the already saved public key (that way other users can't get the preimage for an already paid invoice).

I don't think this solves all of the above problems that @elsirion mentioned, but it should prevent leaking the preimage to users that did not pay the invoice. It would introduce a signature verification though which might add latency.

**Comment by m1sterc001guy** [comment]
@joschisan in case he has some ideas on how to solve this

**Comment by elsirion** [comment]
> For this, could we generate an ephemeral keypair and send the public key/signature to the gateway for each `pay_invoice` invocation?

Even more pragmatically we could generate some secret that is just sent with the API request and associated with that instance of the invoice payment. This secret could be the hash of a static secret derived from the module root secret and the payment hash, meaning it would be unique but deterministic for each user-invoice pair. If anyone else tries to do anything with an invoice that has stuff going on under a different secret the GW cancels the contract (if any) or just returns an error.
