### ISSUE TITLE
Publish linux binaries

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2768]
https://github.com/fedimint/fedimint/issues/1008 added support for building binaries which can run on any linux distribution. As we move closer to a release, we should add a CI job to publish these as a GitHub release.

**Comment by dpc** [comment]
Need to verify if https://github.com/fedimint/fedimint/pull/2885 did it.

**Comment by elsirion** [comment]
Technically they are being published :stuck_out_tongue_winking_eye:, but there [seems to be something wrong](https://github.com/fedimint/fedimint/pull/2885#issuecomment-1664083922), would be good to reproduce on a non-NixOS machine.

**Comment by justinmoon** [comment]
Call: maybe updating nixpkgs fixed?

**Comment by dpc** [comment]
I tried `fedimintd` and `fedimint-cli` on Debian in a VM now and both worked (tried `--help`).
