### ISSUE TITLE
Prefix serialized e-cash with federation ID

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2783]
When serializing e-cash we currently rely on the user to remember to which federation it belongs. To be able to give better error messages we should include the federation id so that incompatible federations can be detected. Otherwise the federation would just complain that the signatures are invalid.

**Comment by justinmoon** [comment]
Future idea: it may eventually be useful have a serialization that includes also includes the connection string. This way a recipient could join if they aren't already a member and withdraw over lightning so long as they have compatible fedimint client libraries.

**Comment by elsirion** [comment]
Just add one URL from which the config can be fetched and that's a connection string. That's the cool thing about config signing: we only need the federation id and one pointer to the config.

**Comment by shaurya947** [comment]
Hey folks, does this entail extending the `SpendableNote` struct with additional field(s) representing the federation?

https://github.com/fedimint/fedimint/blob/9233ed33f695004d598c5cde9f25edb6a3a56d38/modules/fedimint-mint-client/src/lib.rs#L1267

What should be added, just the Federation ID?

And just so I understand, serialization happens in two use cases:
- CLI output for `spend` command
https://github.com/fedimint/fedimint/blob/9233ed33f695004d598c5cde9f25edb6a3a56d38/fedimint-cli/src/client.rs#L177
- Writing notes to the DB, as well as when preparing backups, which happens through serde
https://github.com/fedimint/fedimint/blob/9233ed33f695004d598c5cde9f25edb6a3a56d38/modules/fedimint-mint-client/src/lib.rs#L1304

Did I get anything wrong or am I missing anything?

**Comment by elsirion** [comment]
We don't care about the federation id when saving notes to the DB, so it's only about serialization of out-of-band spent e-cash notes. So I think `spend_notes` should return some new `OOBNotes` struct instead of `TieredMulti<SpendableNote>`:

https://github.com/fedimint/fedimint/blob/1f2db129c5590df22fe3d0dfb77bfeeec9e92180/modules/fedimint-mint-client/src/lib.rs#L105-L110

where `OOBNotes` (name up for discussion) would be something like

```rust
struct OOBNotes {
    federation: FederationId,
    notes: TieredMulti<SpendableNote>,
}
```

and implements `serialize`, `Deserialize`, `FromStr` and `Display` (we couldn't do this with `TieredMulti<SpendableNote>` because both the type and traits are foreign types in the mint module).

This would also entail changing [`validate_notes`](https://github.com/fedimint/fedimint/blob/1f2db129c5590df22fe3d0dfb77bfeeec9e92180/modules/fedimint-mint-client/src/lib.rs#L115C14-L115C28) and [`reissue_external_notes`](https://github.com/fedimint/fedimint/blob/1f2db129c5590df22fe3d0dfb77bfeeec9e92180/modules/fedimint-mint-client/src/lib.rs#L81C14-L81C36) to accept that new type and validating that the federation matches.

Idk if modules are currently aware of the federation id, so maybe that needs to be patched into the constructor [`MintClientGen::init`](https://github.com/fedimint/fedimint/blob/1f2db129c5590df22fe3d0dfb77bfeeec9e92180/modules/fedimint-mint-client/src/lib.rs#L466-L484) (it's kind of a factory pattern I guess).

**Comment by shaurya947** [comment]
Thanks for the thorough explanation @elsirion. I'd like to first take a minute to verify my high-level understanding of the system design with you:

- Guardians are running the `fedimint-server` crate through `fedimintd` (behind some UI).  They are also running the server crates for all the modules (such as `fedimint-mint-server`, `fedimint-wallet-server` etc.) that are provided to the `Fedimintd` builder during compilation. This means that only "apps" whose server modules are incorporated by **all** the guardians are available to the federation.

- Ordinary members of the federation are running just the client crates of all the modules (such as `fedimint-mint-client`, `fedimint-wallet-client`, etc.). They are either using `fedimint-cli`, or mobile apps, or some web UI, to communicate with the guardians' nodes
  - For those running mobile apps or using the web UI, how do they get all the functionality present in the module client crates? Are those crates bundled into the mobile app, for example?

- Under normal circumstances, ordinary members of the federation wouldn't transact with each other directly. They would instead transact through the guardians. **Therefore we don't need to worry about the "in-band" use cases.**

- In cases where connection with the guardians cannot be established, ordinary members may transact directly "offline"/"out-of-band" by quite literally transferring instances of e-cash notes as serialized bytes over bluetooth, airdrop etc. **This is the main use case we need to worry about here.**

Is the above correct or am I misunderstanding some parts?

So in the out-of-band case, we just want to make sure that the member who received an e-cash note offline knows which federation it is associated with, so they can later verify it with the guardians when connection is established (and hence we also need to update the verification functions to be federation-aware like you mentioned).

**Comment by elsirion** [comment]
Sounds correct, this is the most important part:

> members may transact directly "offline"/"out-of-band" by quite literally transferring instances of e-cash notes as serialized bytes over bluetooth, airdrop etc. This is the main use case we need to worry about here.

In all other cases the protocol itself already makes sure we deal with the correct federation. We want to extend that to out-of-band transfers.

**Comment by shaurya947** [comment]
Roger that. I will begin work and report back when I have progress. Feel free to assign to me :slightly_smiling_face:

**Comment by shaurya947** [comment]
Put up #3024 I think it's ready for review!
