### ISSUE TITLE
Gateway option to "withdraw everything"

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2785]
Currently it's a little error-prone because you have to guess the fees that will be charged.

**Comment by justinmoon** [comment]
Call: the lightning and wallet clients should be able to do this in general

**Comment by justinmoon** [comment]
Was just discussing this with @Kodylow. I think we could modify `WithdrawPayload` used by the gateway webserver to allow users to sweep their whole wallet. We could just say `withdrawal_amount = balance_amount - fee_amount` if the user requested a sweep.

**Comment by okjodom** [comment]
> if the user requested a sweep

Sounds good but I'm not sure I understand how the API change would capture user intent to sweep

**Comment by Kodylow** [comment]
Add a param for `sweep: bool`

**Comment by justinmoon** [comment]
@okjodom raises a good point: we could have the client fetch the fee and calculate the amount required to sweep which wouldn't require a change to the withdraw RPC.

The [peg_out_fees](https://github.com/fedimint/fedimint/blob/23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b/modules/fedimint-wallet-server/src/lib.rs#L634-L662) RPC requires user to provide address and amount. Amount is tricky because that creates circular dependency -- we're calling `peg_out_fees` because we're trying to calculate the amount. Would we just send the user's entire balance as the amount parameter to `peg_out_fees`? Then there's a small chance we'd over-pay our fee if removing the fee amount causes us `varint` serialization of the transaction to be smaller. But that will basically never happen.

**Comment by elsirion** [comment]
> Add a param for `sweep: bool`

I think the CLN way is a bit more elegant: allow the string `all` as a valid parameter and make the amount an enum over `all` or a concrete amount.

@justinmoon we could just loop and double-check that the estimated fee is still the same after subtracting the fee from the withdraw amount and break if either the fee stays the same or we hit some iteration limit.
