### ISSUE TITLE
Gateway 500 errors on zero satoshi invoice

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/fedimint#2788]
Hitting `/pay_invoice` with a contract to a zero amount LN invoice returns a 500 error with no body. This should probably return a 4XX error with a message explaining it can't pay zero amount invoices.

**Comment by m1sterc001guy** [comment]
We should verify the amount on the gateway side.

Just curious, how did you discover this? Right now, the new LN client will prevent the creation of 0-amount contracts. 

![image](https://github.com/fedimint/fedimint/assets/1859166/361bb55f-b217-4798-a27e-76a1d8eae5f3)

On the gateway side, we do check if the amount is "present" in the invoice, I'm just not sure if this will return `None` if the amount is explicitly set to 0.

![image](https://github.com/fedimint/fedimint/assets/1859166/c3af80c4-619d-4d9a-afab-78c6802a5ec7)

**Comment by wbobeirne** [comment]
It's very possible this has since been fixed, I encountered this on the Fedi Alpha federation which is running older code (I think it's this tag? https://github.com/fedimint/fedimint/tree/fedi-alpha-1-compat)

**Comment by wbobeirne** [comment]
Ah, I also realized that I wasn't sending zero msats, I was sending an amount that rounded down to zero, so < 500 msats. Perhaps that's related to how this happened?

**Comment by elsirion** [comment]
> amount that rounded down to zero

Under which circumstances are we rounding amounts? :grimacing: That sounds broken when paying an invoice.

**Comment by wbobeirne** [comment]
That was just a UI thing since it displays in satoshis.
