### ISSUE TITLE
Dynamic meta fields

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2791]
Fedimint has the ability to communicate additional config, a.k.a. meta fields to clients. Meta fields are not related to consensus inside the federation but clients validate that they get the same value from all guardian servers, so these fields follow the same trust model as the rest of Fedimint.

These meta fields being part of the config and agreed upon poses a problem though: editing them means changing consensus config on the server side and regenerating the client config signature. This process is very brittle.

There should be a way via the admin API to propose changes to meta fields and vote on these. This could be the precursor to more general config updates, but is much simpler since the server does not care about the value of meta fields at all, so no live consensus changes are necessary.

**Comment by elsirion** [comment]
> Should this be implemented separately from the ability to modify consensus-required fields?

It's certainly simpler because no migration of running consensus rules is necessary, the field simply changes. It might be seen as a precursor to more general dynamic consensus parameters, but that too far away to worry about it.

The basic idea would be to have guardians propose changes via consensus and if a quorum is reached they return the updated value. If there is temporary inconsistency (at most a few seconds) that's ok as long as we use the correct query strategy that will re-try fetching the config/meta fields till it gets the right answer from a quorum of guardian servers.

To make them dynamic we should likely take them out of the client config for now and make them a new API endpoint since we are not prepared to deal with client config changing in arbitrary ways.

**Comment by dpc** [comment]
I accidentally created https://github.com/fedimint/fedimint/issues/4087 which is a dup of this one. Might be useful to read through because I described it in a very "how should it work" way.

My main motivation was that implementing this should be relatively easy, while problems due to lack of it keep adding up.

On the call @elsirion said that he would prefer to make it a part a core consensus because it doesn't generate inputs and outputs, but I have some arguments pro-module:

* it becomes a separate crate(s) with all the benefits: better compilation granularity and caching, easier to understand (all relevant code next to each other),
* easier to rotate into a different thing if we ever want to make significant changes.

The fact that doesn't produce inputs and outputs is not a problem, IMO.

**Comment by elsirion** [comment]
> easier to rotate into a different thing if we ever want to make significant changes.

It would also avoid us having to do a consensus upgrade right now, which I'd really like to avoid for 0.3, we have enough on our plate already.

The main problem we'd be facing is that there is no way you can add a module to a running federation right now without totally understanding what you do (you'd be manually editing all the configs). Changing this sounds like even a bigger project than attempting a consensus upgrade.

**Comment by dpc** [comment]
> The main problem we'd be facing is that there is no way you can add a module to a running federation right now without totally understanding what you do (you'd be manually editing all the configs). Changing this sounds like even a bigger project than attempting a consensus upgrade.

I don't understand. Old Federations will just ignore the new module (as it's not instantiated), old clients will ignore it too. The existing external metadata can keep being utilized until phased out completely.

**Comment by dpc** [comment]
Notes from internal discussion we had at Fedi: Mostly the design outlined in https://github.com/fedimint/fedimint/issues/4087 makes sense, thought the consensus seems to be that having all metadata as one key of a "dynamic consensus meta module" where the value is just a string containing a Json seems preferable, as it guarantees that approved consensus switches atomically and "makes sense", while splitting it into multiple key-values . The module could still implement arbitrary keys, "just in case" but it's unclear if it's "over-engineering" or "future-proofing".

**Comment by joschisan** [comment]
Just wanted to mention here that the client config is not signed anymore and can be modified as long as the guardian api endpoint set remains unchanged. So a crude solution that does not require any consensus centralisation is to enable the guardian UI to change meta fields and tell guardians to agree on the changes beforehand and that a threshold of 2f+1 has to do it somewhat simultaneously as the client config cannot be downloaded as if less then 2f+1 endpoints return different values (the call to download it will not fail though it will hang).

**Comment by elsirion** [comment]
> I am not aiming at retrofitting old federations

That would be rather annoying for existing federations I guess, although they likely are used to the override meta, so not a big deal sort term. But long term we should not disadvantage old federations, that would send a signal to wait with setting one up.

**Comment by dpc** [comment]
>  But long term we should not disadvantage old federations, that would send a signal to wait with setting one up.

I don't even know if changing behavior of existing Federations that already use external meta would be a good idea.

BTW. Isn't introducing a new core consensus item technically a consensus breaking change (hard-fork, not a soft-fork)? It's probably possible to weasel-in such a change, under the condition that no peer will actually use it until the whole Federation is up to date, but technically...

And I think I would rather have this feature implemented and working on new Federations than delay the whole thing until everything is figured out how to backport it and enable existing Federations to use it.

**Comment by joschisan** [comment]
> BTW. Isn't introducing a new core consensus item technically a consensus breaking change (hard-fork, not a soft-fork)? It's probably possible to weasel-in such a change, under the condition that no peer will actually use it until the whole Federation is up to date, but technically...

All guardians need to be upgraded in synchrony as described above. 

The hard fork soft fork dichotomy does not work for us. Softforks occur when we tighten the consensus rules, however in our case that means that an old guardian would accept a transaction that the new version does not accept - hence the created session outcomes and db states would be different. The old guardian would stop working at the end of the session when it produces a session outcome header that is different to everybody else. 

Therefore, we only have hardforks since relaxing and tightening of the consensus rules would cause old guardians to diverge.

**Comment by elsirion** [comment]
> And I think I would rather have this feature implemented and working on new Federations than delay the whole thing until everything is figured out how to backport it and enable existing Federations to use it.

I then let's go the module route and figure out how to add modules after the fact in 0.4. Since we need to keep around the old meta infra for a bit I'd propose to have an order of precedence:
1. New module if present
2. Meta fields from client config
3. Meta override file if present

**Comment by dpc** [comment]
WIP: https://github.com/fedimint/fedimint/pull/4513

**Comment by elsirion** [comment]
After https://github.com/fedimint/fedimint/pull/4513 is merged we should still impl a default fetch function with fallbacks to the legacy ways of fetching meta fields.

**Comment by justinmoon** [comment]
Should we close this now?
