### ISSUE TITLE
Devimint + mprocs doesn't always cleanly shut down

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2838]
Sometimes if I start mprocs with `just mprocs` and the close it with `ctrl-a q y`, some processes like `fedimintd` or `lnd` continue to run indefinitely.

I think there's 2 separate problems here:

* More reliably stop child processes
* Communicate to user when devimint fails to stop child processes. Currently, you have scrutinize logs for port conflicts to diagnose this problem.

**Comment by Maan2003** [comment]
There should be `ProcessManager::wait_all_dead` that should wait for all processes to die. (store all pids in ProcessMangaer)
and this function should be called at end of main() in devimint

**Comment by justinmoon** [comment]
> There should be `ProcessManager::wait_all_dead` that should wait for all processes to die. (store all pids in ProcessMangaer) and this function should be called at end of main() in devimint

I made a little prototype of this: https://github.com/justinmoon/fedimint/tree/devimint-shutdown

I used a crate called [sys_info](https://crates.io/crates/sysinfo) to see if process with some `pid` were still alive. This crate seems unreliable, though, because sometimes during shutdown it will report that the number of processes has increased. Might be better to just have `ProcessManager` store child processes.

I think part of the problem here is that we redirect the output of `devimint dev-fed` to `/dev/null` so when you leave mprocs, you don't see any output. We could have `mprocs.sh` call something like `devimint wait-shutdown` like we do on startup and use a file to communicate progress.

**Comment by douglaz** [comment]
one test is exiting mprocs without waiting the normal startup after running:
```bash
$ just mprocs && for i in $(seq 0 100); do killall -0 devimint  bitcoind electrs esplora lnd lightningd fedimintd gatewayd fedimint-cli faucet; echo $i;sleep 1;done
./scripts/mprocs.sh
Run with 'source ./scripts/build.sh [fed_size] [dir]
Setting up env variables in /tmp/nix-shell.7rPUBK/fm-Mb3j
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
Killing fedimint processes
gatewayd: no process found
fedimint-cli: no process found
faucet: no process found
0
gatewayd: no process found
fedimint-cli: no process found
faucet: no process found
1
fedimint-cli: no process found
2
fedimint-cli: no process found
3
fedimint-cli: no process found
4
fedimint-cli: no process found
5
fedimint-cli: no process found
6
fedimint-cli: no process found
7
fedimint-cli: no process found
8
9
10
11
fedimint-cli: no process found
12
fedimint-cli: no process found
13
fedimint-cli: no process found
14
fedimint-cli: no process found
15
fedimint-cli: no process found
16
fedimint-cli: no process found
17
fedimint-cli: no process found
18
fedimint-cli: no process found
19
fedimint-cli: no process found
20
fedimint-cli: no process found
21
fedimint-cli: no process found
22
devimint: no process found
bitcoind: no process found
electrs: no process found
esplora: no process found
lnd: no process found
lightningd: no process found
fedimintd: no process found
gatewayd: no process found
fedimint-cli: no process found
faucet: no process found
23
```
So it takes 23 seconds for devimint to kill all the processes. But what if something happens during initialization? like it keeps waiting a fedimint to startup or if it exits with an error? then it seems it will never kill anything

**Comment by dpc** [comment]
Good enough after https://github.com/fedimint/fedimint/pull/2873 ?

**Comment by justinmoon** [comment]
Yea let's close. If it still happens, we can re-open.
