### ISSUE TITLE
Make tools compatible with unknown modules

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2849]
Now that #2299 is solved we should make tooling (dbtool, recoverytool, maybe fedimint-cli, …) compatible with unknown modules.

**Comment by dpc** [comment]
Clarification: The #2299 enables parsing consensus history (well... consensus items) without having corresponding modules. Normal client operation without certain modules should have been possible for a while now:

https://github.com/fedimint/fedimint/blob/becd7cd9300a663f6ebba407dc2f43cf486bb83d/fedimint-client/src/lib.rs#L1362C10-L1362C11

So it should be mostly about db/recovery tools.

**Comment by dpc** [comment]
Looking into it.

**Comment by dpc** [comment]
I think it's been handled in most tools already, and core code changed to make graceful handling the default and natural way. Closing. We'll have to keep it in mind for time being, eventually add some tests (with time, as things mature).

**Comment by justinmoon** [comment]
I haven't seen any issues with this recently 👍
