### ISSUE TITLE
Rename all references of "minimint" to "fedimint"

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#286]
I think we've agreed it would be best to just rename the repo "fedimint".

This change will be very disruptive to rebases. We should do any similarly disruptive changes like #258 at the same time (separate PRs, though).

IIRC @Kodylow had expressed interest in doing this.

**Comment by Kodylow** [comment]
will do this tonight, pr incoming

**Comment by Kodylow** [comment]
see PR #293
