### ISSUE TITLE
Add coverage reporting

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#288]
Add coverage reporting to CI so we can track how good our test coverage is.

**Comment by NicolaLS** [comment]
should we use [codecov](https://github.com/marketplace/codecov) for that ?

**Comment by Maan2003** [comment]
I have used https://github.com/taiki-e/cargo-llvm-cov locally, they also have a CI example in README

**Comment by elsirion** [comment]
> I have used https://github.com/taiki-e/cargo-llvm-cov locally, they also have a CI example in README

Their CI example also uploads to codecov, so that's probably the way to go if we want an integrated experience (instead of just pushing results to some GH pages site).

**Comment by NicolaLS** [comment]
I'll give that a go then

**Comment by NicolaLS** [comment]
Completed by #365, #377 respectively
