### ISSUE TITLE
Reactivate `test_gateway_client_pay_invalid_invoice` for real LN tests

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2906]
> I agree that the documentation is misleading, but this invoice is doubly not payable by a real LN node:
>
> 1. The (recipient) node id is a randomly generated key, so there will be no route to that node.
> 2. The payment hash/preimage is hard-coded and not known to any of the real LN nodes
>
> The `INVALID_INVOICE_DESCRIPTION` hack was only necessary because the mock LN implementation cannot detect the first two problems with it, so we helped it a bit (thinking about it, we could also have matched the payment hash instead).
> 
> So this test should be able to run in both mock and real scenarios. What was the reason to deactivate it? If it's flakiness I'm pretty sure the problem is only masked by deactivating the test.

_Originally posted by @elsirion in https://github.com/fedimint/fedimint/issues/2904#issuecomment-1665166880_

**Comment by justinmoon** [comment]
It's a confusing test because there is nothing "invalid" about the invoice. It just can't be paid. Should rename test and add a comment about what's going on.
