### ISSUE TITLE
Lightning client should resubmit refund transactions if they fail to be submitted/accepted

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#2912]
If for any reason, a refund transaction needs to be submitted to the federation, and that process fails (perhaps the federation is offline), we do not currently retry. This could result in lost funds. 

Ideally I think the state machines should retry until the transaction is accepted (with backoff delay and long timeout).

**Comment by elsirion** [comment]
Unless a transaction is fundamentally invalid it should be re-submitted. That's a bug, fix in #2915.
