### ISSUE TITLE
Check API+consensu version in client

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2922]
Blocked on https://github.com/fedimint/fedimint/issues/2506

Two considerations:
* Checking compatibility on first join: easy
* Checking compatibility on each startup: needs discussion how to do this without blocking too long @justinmoon

**Comment by dpc** [comment]
@elsirion Already implemented in https://github.com/fedimint/fedimint/blob/becd7cd9300a663f6ebba407dc2f43cf486bb83d/fedimint-client/src/lib.rs#L1347 ?

**Comment by elsirion** [comment]
Then I just didn't fully remember, I knew we did *something* but wasn't sure if that was all and didn't want to get started till https://github.com/fedimint/fedimint/issues/2506 was sorted out to avoid conflicts.
