### ISSUE TITLE
RPC command to expose audit

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2948]
The [guardian UI](https://github.com/fedimint/ui/tree/master/apps/guardian-ui) would like to be able to display how many bitcoins are held by the federation.

A good way to achieve this would be to add an authenticated RPC command exposing the most recent [Audit](https://github.com/fedimint/fedimint/blob/6175f2fcb9d0446623a23eee4914bbb845f25111/fedimint-core/src/module/audit.rs#L7-L10) -- which includes all asserts and liabilities of the federation per-module.

**Comment by bradleystachurski** [comment]
I'll start investigating. Feel free to assign my way.

**Comment by justinmoon** [comment]
[Here](https://github.com/fedimint/fedimint/blob/6175f2fcb9d0446623a23eee4914bbb845f25111/fedimint-server/src/net/api.rs#L506-L513) is an example of an existing authenticated RPC command
