### ISSUE TITLE
Dependency audit 

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#295]
Before really deploying this, we'll need to really audit our dependencies. Let's use this issue for any notes related to this

**Comment by justinmoon** [comment]
I was just looking at `reed-solomon-erasure` crate and saw a concerning "Merged several PRs ... Not fully reviewed as I am no longer maintaining this crate" note for version 5.0 [in the changelog](https://github.com/rust-rse/reed-solomon-erasure/blob/2e134f6de13ca672cf185556c020ab997221b300/CHANGELOG.md#500).

**Comment by dpc** [comment]
If you are already going to spend the effort on reviewing stuff, consider using `cargo-crev` to publish the results. [There are some plans to use it for rust-bitcoin](https://github.com/rust-bitcoin/rust-bitcoin/pull/1098) already.

**Comment by justinmoon** [comment]
Just noticed that `hbbft` is compiled by the client crate ... which is silly

**Comment by dpc** [comment]
> Just noticed that hbbft is compiled by the client crate ... which is silly

`cargo tree -p mint-client` says we need to move `hbbft` dep from `fedimint-api` to `fedimint-server`.

**Comment by jkitman** [comment]
Think this is closed by https://github.com/fedimint/fedimint/pull/2187
