### ISSUE TITLE
Regressing in `fedimint-cli info`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2973]
When switching to the new client we didn't notice [the regression in the info command output](https://discord.com/channels/990354215060795454/990354215878688860/1141552028452126861). We still have the old schema in our docs and should restore it:

https://github.com/fedimint/fedimint/blob/7123a025343c025f589a33e44ddd4bc601c6d8e1/docs/dev-running.md?plain=1#L28-L43

**Comment by shaurya947** [comment]
Just tried playing around using `mprocs` and ran into this. Would be happy to give this a shot! Going to investigate today and report back findings :slightly_smiling_face:

**Comment by shaurya947** [comment]
Opened #2995

Checks seem to pass. I tried to follow the code/commit style of the project but would appreciate any feedback, this being my first PR here :slightly_smiling_face:
