### ISSUE TITLE
Some race condition in peg-in tests

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2974]
```
 fedimint-test-all> 00:04:43 ---- on_chain_peg_in_and_peg_out_happy_case stdout ----
fedimint-test-all> 00:04:43 thread 'on_chain_peg_in_and_peg_out_happy_case' panicked at 'assertion failed: `(left == right)`
fedimint-test-all> 00:04:43   left: `Failed("Failed to claim: SubmitRejected(\"Federation rpc error {general => Received errors from 1 peers), 1 => Rpc error: ErrorObject { code: ServerError(400), message: \\\"Unknown block hash in peg-in proof: 38ce3ae24e621977181279f2913675693962340450deb35a5d0835ecb675bab7\\\", data: None }), }\")")`,
```

https://github.com/fedimint/fedimint/actions/runs/5887796866/job/15967798258?pr=2951

**Comment by dpc** [comment]
@elsirion I bet you'll immediately know what could have caused it, as you were recently refactoring these tests.

**Comment by elsirion** [comment]
I was already doing some debugging on the side, but it's really hard to reproduce and seems unrelated to my most recent changes there and more related to #2861. I'll try what you suggested on discord: `nix run nixpkgs#cpulimit -- -i -l 50 <test-command>`

**Comment by elsirion** [comment]
Might also be related to  #2936

**Comment by elsirion** [comment]
Maybe not fully fixed after all :( https://github.com/fedimint/fedimint/actions/runs/5904630245/job/16018403747?pr=2967

**Comment by dpc** [comment]
> Maybe not fully fixed after all :( https://github.com/fedimint/fedimint/actions/runs/5904630245/job/16018403747?pr=2967

This looks it was killed mostly due to how long building the workspace took.

![image](https://github.com/fedimint/fedimint/assets/9209/5e55d0c9-5630-43d5-8c4b-c47f1158970f)

**Comment by dpc** [comment]
Hopefully https://github.com/fedimint/fedimint/pull/3002 did it.
