### ISSUE TITLE
DB Migration test sometimes fail

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2985]
https://github.com/fedimint/fedimint/actions/runs/5896978906/job/15995811365?pr=2983

I've seen it before. Weird.

Happens randomly, not too often. I suspect it has something to do with this tests being run 3 times, around the same time for each of the backends: bitcoind, electrs, esplora.

**Comment by dpc** [comment]
@m1sterc001guy

**Comment by dpc** [comment]
LOL. So I think we were just missing to check-in ln validate migrations, which would lead the tests to create them every time on the flight?

We should figure out how to prevent such a mistakes in the future.

**Comment by elsirion** [comment]
Damn, I might have messed that up. I remember deleting and re-generating that snapshot recently, maybe I didn't stage it correctly?

**Comment by m1sterc001guy** [comment]
Sorry for missing this. So the root cause was that CI was re-creating the backups every time?

Perhaps we should add a check or a test that verifies all the files exist. Then we can add an environment variable for disabling this check to be able to re-generate the files locally.
