### ISSUE TITLE
Removing link-arg=-fuse-ld=lld breaks local build on x86_64 linux

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#3000]
On linux x86_64 running `cargo build` errors with

```
clang-11: error: linker command failed with exit code 137 (use -v to see invocation)
```

Reverting this [commit](https://github.com/fedimint/fedimint/commit/53e028b88376910678f458dea37880d29a292092) allows the build to succeed.

I would post a revert PR, but I'm likely missing context since the linked commit/PR passed CI and reduces the size of the release build.

**Comment by dpc** [comment]
Seems unlikely that CI is passing and no one else reported any issue yet. Are you using Nix shell?

**Comment by elsirion** [comment]
I failed to reproduce with current master (1f2db129c5590df22fe3d0dfb77bfeeec9e92180):

```shell
nix develop
cargo clean
cargo build --workspace
```

Works just fine on my end.

**Comment by bradleystachurski** [comment]
Thank you both for the quick responses!

> Are you using Nix shell?

Yes, but this smells like a problem with my setup if others can't reproduce. I'll keep investigating.

For reference, I'm having the issue with the same master (https://github.com/fedimint/fedimint/commit/1f2db129c5590df22fe3d0dfb77bfeeec9e92180).

**Comment by dpc** [comment]
Try with `nix develop --ignore-environment`. If that still doesn't work, it would have to be some cargo's global/user-level config somewhere trying to pull in a different clang or something.

**Comment by bradleystachurski** [comment]
@dpc thanks for your help troubleshooting!

The root issue was a local one, OOM. The new build process used all of my dev box's mem, but increasing the swap mem allowed the build to succeed locally.

More context in discord [thread](https://discord.com/channels/990354215060795454/990354215878688860/1143258198548164781).
