### ISSUE TITLE
Is `bitcoin-cli getblockcount` a lie?

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3001]
When I run `bitcoin-cli getblockcount` it returns `804203` right now, shouldn't that mean that I can only get a block hash for block `804202`? But in fact I can run `bitcoin-cli getblockhash 804203` and get `00…226138` as the result. When I then in turn run `bitcoin-cli getblock 00…226138` the output contains the line `"height": 804203`.

If `getblockcount` is in fact just a confusingly named `getblockheight`, then #2872 introduced some inconsistency because every implementation of `IBitcoindRpc::get_block_count` but the `bitcoind` one adds 1 to the height returned by the underlying API:

Bitcoind:
https://github.com/fedimint/fedimint/blob/1f2db129c5590df22fe3d0dfb77bfeeec9e92180/fedimint-bitcoind/src/bitcoincore.rs#L52-L54

Electrum:
https://github.com/fedimint/fedimint/blob/1f2db129c5590df22fe3d0dfb77bfeeec9e92180/fedimint-bitcoind/src/electrum.rs#L53-L55

Esplora:
https://github.com/fedimint/fedimint/blob/1f2db129c5590df22fe3d0dfb77bfeeec9e92180/fedimint-bitcoind/src/esplora.rs#L56-L61

Mock (doesn't need +1 because we actually use the count):
https://github.com/fedimint/fedimint/blob/1f2db129c5590df22fe3d0dfb77bfeeec9e92180/fedimint-testing/src/btc/mock.rs#L246-L248

This could explain CI failing peg_in tests (tracked in #2974, problem for #2967).

What I think happens is that the federation always lacks behind one block more than announced as `finality_delay` and thus the tests don't generate enough blocks for the peg-in to succeed and it times out.

EDIT: More confirmation from the bitcoin core help:
```
[elsirion@btc-2:~]$ bitcoin-cli help getblockcount
getblockcount

Returns the height of the most-work fully-validated chain.
The genesis block has height 0.

Result:
n    (numeric) The current block count
```

**Comment by dpc** [comment]
![image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Paris_Tuileries_Garden_Facepalm_statue.jpg/600px-Paris_Tuileries_Garden_Facepalm_statue.jpg)

**Comment by dpc** [comment]
How the hell I didn't notice for so long?!

I guess in indexers we usually just try to get the next block hash by height anyway, and never pay too much attention to `getblockcount` anyway.
