### ISSUE TITLE
Client and gateway should coordinate outgoing payment timeouts

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#301]
[See comment](https://github.com/fedimint/minimint/pull/269#discussion_r922680852)

**Comment by elsirion** [comment]
The comment link doesn't seem to work, what's the context exactly? I could see two things we need to fix:

* Collaboratively fail the payment if the gateway can't find a route so the user doesn't have to wait till the timeout hits
* Let the gateway communicate some minimum/maximum timeout for invoices

**Comment by justinmoon** [comment]
here's a screenshot lol

<img width="831" alt="image" src="https://user-images.githubusercontent.com/4335621/182177908-326d2af1-05f4-4a1a-8684-31448c7db6f8.png">

**Comment by m1sterc001guy** [comment]
I don't think this is an issue anymore. We now call `pay_invoice` asynchronously via the client state machine framework. So there is no timeout anymore (but we also don't block on this since it called asynchronously). Closing this issue.
