### ISSUE TITLE
Future proof arguments to `ClientModuleInit::init`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#3025]
I noticed we keep tweaking these, adding, removing refactoring arguments there, forcing changes in downstream implementations.

Maybe we should pass one:

```rust 
struct ModuleInitArgs {
  // all fields private
}
```

than then has:

```rust
impl ModuleInitArgs {
  pub db(&self) -> &Database {
    // ...
  }

  pub fn api_version(&self) -> ApiVersion  {
    // ...
  }

  // other methods
}
```

then we can add new fields, deprecate old ones etc. without breaking the Api.

We probably should do it in some other module API traits methods as well, but need to be careful not to go overboard with it. Things that have multiple arguments that historically changed.

**Comment by justinmoon** [comment]
Was this closed by https://github.com/fedimint/fedimint/pull/3254 and https://github.com/fedimint/fedimint/pull/3255?

**Comment by dpc** [comment]
Yes
