### ISSUE TITLE
Add docker container tag for tagged versions

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/fedimint#3043]
It'd be nice if tagged releases had containers with a matching tag. For instance, instead of specifying an image as `fedimint/fedimintd:480ccb5cca9890bb3aa4cda41c7ff7d5d19fc357` , it'd be nice to be able to do `fedimint/fedimintd:0.1.0-rc1` instead

**Comment by dpc** [comment]
Note: mutable tags are tricky because locally docker will cache them, so by getting `latest-release` you might get past release that was latest when you downloaded it.

BTW. We do tag `:master` already like that, in case it helps anyone with `:latest-release` or something.

**Comment by elsirion** [comment]
Fixed by #3044
