### ISSUE TITLE
Set consensus versions to 1 on master and releases/v0.1

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3052]

**Comment by elsirion** [comment]
Imo master should go straight to 2, so each time we branch off master is just incremented but the release branch doesn't need incrementing?

**Comment by justinmoon** [comment]
We need to figure out what to do with master's breaking changes. It would be weird to leave it at "consensus version 2" across multiple breaking changes.

**Comment by elsirion** [comment]
On master you are on your own I'd say, we don't want to track breaking-ness of changes there or  a lot of PRs will need an extra review round.

A good argument against my approach described previously: when making the next release old, incompatible master federations will look like the new release. So maybe master should just get `<int_type>::MAX` as the version?

**Comment by justinmoon** [comment]
> On master you are on your own

Agreed. We'd just like a way for clients to recognize these incompatible master versions. Something like the `MAX` idea would accomplish this.

**Comment by dpc** [comment]
> Imo master should go straight to 2, so each time we branch off master is just incremented but the release branch doesn't need incrementing?

I don't know if I understand.

I guess if we don't want try to increment consensus version on every breaking change the release process should look :


* Before the release, increment the consensus, making all the past dev work incompatible with the new release.
* Branch the `master` to release branch. 
* Make the rc release, tag, start testing and getting feedback.
* [Optional] If additional changes are needed, merge them on master first, backport to release branch. If the change break consensus, increment the consensus version on both master and release branch (keep in sync!). In a way: during rc window, we need to behave like we should/will in some future, where we track every breaking change.
* Make a final release, wait for things to settle down.
* Increment the consensus version on master again, making all the future dev work incompatible with new the last release.


Notably, once the release is out, and we did the post-release master consensus version increment, we should not make any consensus breaking changes to release branch anymore. We should rather cancel and recall the whole release.

**Comment by dpc** [comment]
> I guess it works... but intuition tells me we will regret it eventually. :D

After thinking a bit more about it... Maybe it will be fine.

**Comment by justinmoon** [comment]
Closed by https://github.com/fedimint/fedimint/pull/3054 and https://github.com/fedimint/fedimint/pull/3053
