### ISSUE TITLE
Redundant block height proposals for height 0

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3063]
The propose and process consensus item of the wallet module is slightly inconsistent. While we propose a consensus block count of 0[^1] when no blocks have been mined yet, we consider such proposals redundant because `process_consensus_item` considers the block count to be 0 if no consensus has been achieved yet:

https://github.com/fedimint/fedimint/blob/928e6257f92756f1741da42528ccf427537886ad/modules/fedimint-wallet-server/src/lib.rs#L357-L375

Possibly we should just not propose until the consensus count would be 1 and also not default to 0 in `process_consensus_item`.

Reported in fedimint/ui#158.

[^1]: Even though the count should always be at least 1 due to the genesis block this is possible because we subtract the finality delay using `saturating_sub`.

**Comment by dpc** [comment]
I think https://github.com/fedimint/fedimint/pull/3205 fixes it.
