### ISSUE TITLE
Admin UI needs RPC for unencoded module configs

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/fedimint#3067]
The `config` endpoint in `net` returns module configs encoded in a way that's difficult to read in the admin UI: https://github.com/fedimint/fedimint/blob/23a297cc1ea74050813efc2333c2b53c37ef13b2/fedimint-server/src/net/api.rs#L498-L511

For the purposes of an admin UI, we don't need the consensus config with signatures, we just want a dumb json object that we trust. We'll want a new endpoint that just returns that instance's local configs as a JSON blob, or a parameter to change the serialization / new key on this existing endpoint.

**Comment by elsirion** [comment]
Apparently closed by #3072 already?
