### ISSUE TITLE
RPC to get current bitcoin block height from wallet module

### ISSUE THREAD

**Issue by wbobeirne** [fedimint/fedimint#3069]
The admin UI would like to show the current block height that the wallet module's bitcoin node is at, so we'll need an endpoint for getting that. It might be nice to just get the entirety of `getblockchaininfo` in case anything else is needed (`chain`, `bestblockhash` etc.), but I also don't want to ask for more than we need.

**Comment by dpc** [comment]
Since we support different bitcoin node backends getting all the data might be extra work or just not possible (backend just doesn't have it). We can either not do it, or just skip data that isn't there. Just worth pointing out.

**Comment by dpc** [comment]
@wbobeirne Just took a peek trying to quickly do it, and it seems [there's already `block_count`](https://github.com/fedimint/fedimint/blob/946944531c58600447a2e35e5583bcaeb7eab80b/modules/fedimint-wallet-server/src/lib.rs#L618).

**Comment by dpc** [comment]
Hmmm... actually looking at the implemenation it looks like it returns "the current Federation consensus on what's the main block count is", which is slightly different.

**Comment by wbobeirne** [comment]
🤦 thanks for pointing that out, I assumed that all API endpoints lived in `api.rs` files ala `fedimint-server`, didn't think to check in the `*-server/lib.rs` files.

Definitely in favor of more non-consensus information rpcs for the admin dashboard though, since ideally this information could be used for diagnosing differences between various guardians. But good to know we can also grab the consensus block count.
