### ISSUE TITLE
Audit RPC endpoint should be instance-id aware

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3071]
Our module system is built to allow multiple instances of the same module running concurrently. As a result, we can't just use "module types" as keys to lookup information regarding modules because there may be 2 different instances of these modules. We should modify `audit` RPC method introduced [here](https://github.com/fedimint/fedimint/pull/2999) to use module instance IDs as keys instead of module types.

**Comment by bradleystachurski** [comment]
After making these changes to the `audit` endpoint, would this be the anticipated flow to ensure the UI can still map net assets of all instances of a given kind?

- fetch modules mapping instance ID -> kind using the `config` rpc
- associate the instance ID returned from the `audit` rpc to a kind, then group by kind and sum net assets

**Comment by elsirion** [comment]
I'd propose returning the module kind directly so only one round-trip is needed, unless that's too complicated or consumers likely keep an instance->kind mapping around anyway:

```json
{
  "net_assets": 0,
  "module_summaries": {
    0: {
      "kind": "mint",
      "net_assets": -50000000
    },
    1: {
      "kind": "wallet",
      "net_assets": 50000000
    },
    2: {
      "kind": "ln",
      "net_assets": 0
    }
  }
}
```

**Comment by wbobeirne** [comment]
+1 to @elsirion's note, we have to do that extra round trip and mapping for the `versions` endpoint which is kind of annoying, it'd definitely be nice to make it as simple to consume as possible!
