### ISSUE TITLE
Remove fedimint-core/src/client.rs

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3086]
Lots of commented-out code in https://github.com/fedimint/fedimint/blob/master/fedimint-core/src/client.rs

Edit: doesn't even seem like `FederationApi` is used anywhere?

**Comment by a-moreira** [comment]
hey @justinmoon, I wanted to contribute and opened this PR: https://github.com/fedimint/fedimint/pull/3146.
Is this what the intended modification? :-)

**Comment by justinmoon** [comment]
Thanks!
