### ISSUE TITLE
Expose helpful info about available modules from CLI

### ISSUE THREAD

**Issue by shaurya947** [fedimint/fedimint#3119]
Once #3118 gets merged we'll have the ability to call arbitrary commands that are specific to custom, non-default modules. As such it would be helpful to have a command that exposes all the available modules (both instance IDs + kinds) so it's easy to figure out which modules can be interacted with in a session.

Furthermore, it might also be worth investigating ways to make the `module` subcommand smarter such that it can use all the available modules to return more helpful error messages or even have something akin to an autocomplete etc.

**Comment by 15IITian** [comment]
I understood some part that we require a new command that list all the modules  available ( default and non-default ) .
If yes, please guide how to start with it.

**Comment by dpc** [comment]
> I think a `fedimint module list` command would be good, then I'd use `fedimint module <module> <command> <args…>` for custom module commands. What do you think @dpc, I know you wanted shorter commands, but I think if we keep the shortcuts while allowing arbitrary commands to be called this way that would be ok.

Generally sounds good to me, short is good, but not most important.

> There should also be two optional, mutually exclusive flags `--federation` and `--client` that display the theoretically supported list of modules of the client and federation respectively, while the normal command only shown the modules supported by both.

I'm no sure if it's necessary. Client knows about modules it doesn't support, so could still list them with some info.

```
> fedimint-cli module list
{
   "0": {
     "kind": "bazinga",
     "status": "unsupported",
    },
   "1": {
      "kind": "mint"
      "status": "recovery",
      "progress": {
         "complete": 41,
         "total": 666
       }
       /// possibly some other most important fields
    },
    "2": {
       "kind": "wallet",
       "status": "active",
       // possibly more
    }
}
```

**Comment by elsirion** [comment]
> I'm no sure if it's necessary. Client knows about modules it doesn't support, so could still list them with some info.

Good point! I was thinking about making the CLI output human readable by default in the future, but we can make this a future problem. We use JSON everywhere anyway for now.

**Comment by 15IITian** [comment]
After deep dive into the code , I have deduced some conclusions , Please do tell what I am missing out -> 
 * There is `ServerModuleRegistry` struct which contains all the server-related modules ( I think server== federation)
* same for `ClientModuleRegistry` struct containing client-related modules things.
* There are functions defined on them in `fedimint-core/registry.rs` file which can be used to iterate over the modules data.

**Comment by 15IITian** [comment]
> I'm no sure if it's necessary. Client knows about modules it doesn't support, so could still list them with some info.
means `fedimint-cli module list` should show all the client unsupported modules .

**Comment by 15IITian** [comment]
> I'm no sure if it's necessary. Client knows about modules it doesn't support, so could still list them with some info.

@elsirion 
please tell what is the final layout of the command?

**Comment by elsirion** [comment]
@dpc's suggestion was to show the union of federation-supported and client-supported modules and just annotate this fact such that a user could filter the output for the modules that are supported by both client and federation (e.g. using `jq`).

**Comment by 15IITian** [comment]
Thanks for clarification.

**Comment by 15IITian** [comment]
in json -> what fields other than `module kind` and `moduleInstance ID`  do I have to include?

**Comment by elsirion** [comment]
I guess at least a status field would be nice for now, it could be

```rust
enum ModuleStatus {
    Active,
    NotSupportedByFederation,
    NotSupportedByClient,
}
```

for now and later extended to 

```rust
enum ModuleStatus {
    Active,
    Recovering,
    NotSupportedByFederation,
    NotSupportedByClient,
}
```

to indicate if it can actually be used. But the whole recovery is a bit in flux right now and that might be a bit too complex for you rn, so let's just do the first three states.

**Comment by 15IITian** [comment]
![image](https://github.com/fedimint/fedimint/assets/133089376/2b151275-210f-4030-872b-cae57ae6e9b7)


do we require `list as compulsory command` or not?

**Comment by dpc** [comment]
> NotSupportedByFederation

How can a module be not supported by Federation? If Federation returned it they have to support it, no?

**Comment by 15IITian** [comment]
Yeah , I think it must be `Supported_by_federation` and similar for client one

**Comment by dpc** [comment]
If it's `active` or `recovering` it must have been supported by the client. So AFAICT there are 3 possible state currently: unsupported (by the client), recovering, active.

**Comment by 15IITian** [comment]
If modules from `client module registry` -> client modules -> active = true 
`clientconfig` -> federation modules -> not getting how to find whether , it is client_supported or not ??

**Comment by 15IITian** [comment]
`enum ModuleStatus` - must be strict right?
as have to output all fields .

**Comment by dpc** [comment]
No idea what you just asked about. :D

**Comment by 15IITian** [comment]
![image](https://github.com/fedimint/fedimint/assets/133089376/dfc736fb-4614-43fd-9925-0067e0b36fef)

To access client-supported modules -> I try to take `modules` field from the `client` variable -> as  `modules: ClientModuleRegistry` which has a function `iter-modules`  to  get all modules.

But `Client` struct fields are private and I  found no such function to iterate over modules .

**Comment by elsirion** [comment]
@dpc Why not list modules supported by the client in principle but not the federation?

**Comment by elsirion** [comment]
Good point, I have the opposite problem, I always forget that instances exist and not only kinds :see_no_evil:
