### ISSUE TITLE
Consolidate API endpoints between a module's client and server

### ISSUE THREAD

**Issue by shaurya947** [fedimint/fedimint#3120]
Currently, despite having a `-common` crate that's shared by a module's client and server crates, the API endpoints are repeated as strings separately in the two crates. This seems somewhat brittle and error-prone.

https://github.com/fedimint/fedimint/blob/ac448d7192577e6a820f4286013a371d0864143b/modules/fedimint-dummy-client/src/api.rs#L20

https://github.com/fedimint/fedimint/blob/ac448d7192577e6a820f4286013a371d0864143b/modules/fedimint-dummy-server/src/lib.rs#L438

Wondering if there's a way to create an enum of available endpoints within the `-common` crate and produce a string representation of each endpoint using a macro.

**Comment by elsirion** [comment]
Even just having a rust module that contains them as constants would help imo. Not sure what an enum would add.

**Comment by tvolk131** [comment]
I can take this!
