### ISSUE TITLE
Remove "ng" terminology from client

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3142]
A couple months ago we re-wrote our client. We used the acronym "ng" to stand for "next generation" because @elsirion is a Star Trek nerd 😛. At this point we should remove this terminology from the code because it's not informative.

I just noticed that `fedimint-cli` has a `handle_ng_command` function. There are probably other instances.

**Comment by a-moreira** [comment]
hey @justinmoon I'd like to tackle this, if possible. if it's just about removing all instances of `ng`, I will start right now 😃

**Comment by a-moreira** [comment]
@justinmoon https://github.com/fedimint/fedimint/pull/3149
I picked the name "common.rs" for the file that holds the code previously in "mod.rs", but I can change that, or re-organize it another way.
