### ISSUE TITLE
Expose Gateway State

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#3158]
The gateway can now be in a few different "states" depending on what is happening with the gateway. For example, it will be useful for the UI to know if the lightning connection is down or if the gateway still needs to be configured.

**Comment by okjodom** [comment]
Would this API also show state for the underlying FM client(s)?

**Comment by m1sterc001guy** [comment]
No, this only exposes the gateway's state. This is mainly to communicate whether or not we're connected to the lightning node, gateway needs configuring, etc.
