### ISSUE TITLE
Publish all dependencies as crates.io packages

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#3168]
We can't publish Fedimint to nixpkgs because git dependencies are not supported:

```
> source = "git+https://github.com/dpc/rust-secp256k1-zkp/?branch=sanket-pr#f29b1b8c442d4b8a42547ce36d3987aaedf94224"
> source = "git+https://github.com/fedimint/threshold_crypto#9b0eeec8f23f41a385174c0d84290cbf8d88a656"
> source = "git+https://github.com/fedimint/tonic_lnd?branch=lnd-client-features#500b5c5bfee9f96f63a4e6f3ffccdbe0a82cea1e"
> source = "git+https://github.com/fedimint/tonic_lnd?branch=master#d0c8f1fea035dbfae9398aa388664112bc4dfd2a"
```

And generally, if it is to be a proper release than a Rust project should have all deps published on crates.io

**Comment by elsirion** [comment]
Can't we just publish `fedimint-*` versions for these?

**Comment by dpc** [comment]
We can if there's no other way, but good oportunity to verify if we could get off a patched fork.

**Comment by justinmoon** [comment]
Current list of git dependencies is `secp256k1-zkp`, `ring` (we're ready to get off our fork https://github.com/fedimint/fedimint/issues/2583), and `ldk-node`

**Comment by m1sterc001guy** [comment]
In the only release version of `ldk-node`, they use an old version of the `time` crate which has a potential segfault  https://github.com/lightningdevkit/ldk-node/pull/146

This is flagged by our build system as a security vulnerability.

This has been fixed on master but there hasn't been another release of `ldk-node` since the fix.

**Comment by justinmoon** [comment]
@m1sterc001guy I begged for new release on LDK Discord https://discord.com/channels/915026692102316113/1009456808181649489/1172274149964664872

**Comment by TonyGiorgio** [comment]
Is this still partially a concern? At least for the wasm tests here? 

```
fedimint-wasm-tests git:(v0.2.0) grep "source =" Cargo.lock | grep -v "registry+"
source = "git+https://github.com/bitcoindevkit/rust-esplora-client.git?rev=54de8118c40c6a2cf80591d8991cf578bdfb51c4#54de8118c40c6a2cf80591d8991cf578bdfb51c4"
source = "git+https://github.com/rust-bitcoin/rust-miniscript/?rev=2f1535e470c75fad85dbad8633986aae36a89a92#2f1535e470c75fad85dbad8633986aae36a89a92"
source = "git+https://github.com/briansmith/ring?rev=ef36b9371e0ec5d465db024bb15930c5dc499dbd#ef36b9371e0ec5d465db024bb15930c5dc499dbd"
source = "git+https://github.com/dpc/rust-secp256k1-zkp/?branch=sanket-pr#f29b1b8c442d4b8a42547ce36d3987aaedf94224"
source = "git+https://github.com/dpc/rust-secp256k1-zkp/?branch=sanket-pr#f29b1b8c442d4b8a42547ce36d3987aaedf94224"
source = "git+https://github.com/fedimint/threshold_crypto#9b0eeec8f23f41a385174c0d84290cbf8d88a656"
```

I don't see any more references to `sanket-pr` in the codebase, it's lingering in `fedimint-wasm-tests`. Does that cargo.lock simply need to be updated? Can we get a 0.2 cargo publish if that's ready?

**Comment by elsirion** [comment]
All the relevant 0.2.0 crates are already published, see for example [`fedimint-client`](https://crates.io/crates/fedimint-client). The WASM tests just aren't something for external consumption, so we didn't even notice.
