### ISSUE TITLE
Client sometimes fails successful transactions when offline

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3173]
The new client has the goal to gracefully handle temporary failures like network interruptions, but I discovered at least one place where it can fail when going offline at the wrong time

Let's take the example of the state machine responsible for issuing new e-cash:

https://github.com/fedimint/fedimint/blob/ff3ad0658d4d16c2fa5ed30d91611f019374ab82/modules/fedimint-mint-client/src/output.rs#L162-L182

If *anything*, including network failure, goes wrong here the state machine goes into a failed state. What should happen instead is something similar to what the transaction submission state machine does: if the error is retryable wait for a bit and then try again.

https://github.com/fedimint/fedimint/blob/ff3ad0658d4d16c2fa5ed30d91611f019374ab82/fedimint-client/src/transaction/sm.rs#L196-L203

We need to check all state machines for similar mistakes to make sure everything works even with flaky internet connections.

**Comment by justinmoon** [comment]
2 things to do here:
- [ ] Go through all the trigger functions and make sure we're retrying retryable errors
- [ ] Make sure we've correctly identified which jsonrpsee errors are retryable
