### ISSUE TITLE
`fedimint-cli dev invite-code` broken in mprocs

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3178]
and I don't see how the current impl could ever work since the client is restarted for every command, resetting the internal state that's not persisted to DB. Maybe we should just save the invite code to the DB so this functionality can be implemented properly.

**Comment by justinmoon** [comment]
> Maybe we should just save the invite code to the DB so this functionality can be implemented properly.

The only problem with this is that at some point we'll properly implement single-use or expiring invite codes, which would break here. But perhaps we could cross that bridge when we come to it.

**Comment by justinmoon** [comment]
call: this should be removed and re-added with a non-dev command
