### ISSUE TITLE
Flakey `/connect-fed` behavior in CI

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#3187]
CI [failed](https://github.com/fedimint/fedimint/actions/runs/6180508721/job/16777069322) calling [`/connect-fed`](https://github.com/fedimint/fedimint/blob/f595557314ec122c1eb5536675223b7155ea24cd/gateway/ln-gateway/src/ng/tests.rs#L750). The failing job is code coverage at the build and run [step](https://github.com/fedimint/fedimint/blob/bc96ea8e0b93fab5ed846ed221f001b1b41991fc/.github/workflows/ci-nix.yml#L180), however other CI steps passed while testing the same code path. I haven't been able to repro locally.

```
fedimint-workspace-lcov> ---- test_gateway_configuration stdout ----
fedimint-workspace-lcov> Error: error sending request for url (http://127.0.0.1:19947/connect-fed): error trying to connect: tcp connect error: Connection refused (os error 111)
fedimint-workspace-lcov> Caused by:
fedimint-workspace-lcov>     0: error trying to connect: tcp connect error: Connection refused (os error 111)
fedimint-workspace-lcov>     1: tcp connect error: Connection refused (os error 111)
fedimint-workspace-lcov>     2: Connection refused (os error 111)
fedimint-workspace-lcov> Stack backtrace:
fedimint-workspace-lcov>    0: <core::result::Result<(), anyhow::Error> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, ln_gateway::rpc::rpc_client::GatewayRpcError>>>::from_residual
fedimint-workspace-lcov>              at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1961:27
fedimint-workspace-lcov>    1: {async_block#0}
fedimint-workspace-lcov>              at ./src/ng/tests.rs:750:5
```

**Comment by m1sterc001guy** [comment]
I think there might be a race condition while starting the webserver. I'll add a retry

**Comment by m1sterc001guy** [comment]
I've still seen this issue in some other tests, so I'm re-opening

**Comment by m1sterc001guy** [comment]
Fixed with https://github.com/fedimint/fedimint/pull/3267
