### ISSUE TITLE
`fedimint-cli dev api` usability is meh.

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#3194]
Took more forever to get config from the server for debugging purposes.

First #3192 , so I had to get the invite code from `$FM_DATA_DIR`.

But then I couldn't figure out what is the syntax for aguments, and Justin had to tell me it should be:

```
fedimint-cli dev api config '"fed114znk7uk7ppugdjuytr8venqf2tkywd65cqvg3u93um64tu5cw4yr0n3fvn7qmwvm4g48cpndgnm4gqq4waen5te0xyerwt3s9cczuvf6xyurzde597s7crdvsk2vmyarjw9gwyqjdzj"'
```

but that fails with:

```
> fedimint-cli dev api config '"fed114znk7uk7ppugdjuytr8venqf2tkywd65cqvg3u93um64tu5cw4yr0n3fvn7qmwvm4g48cpndgnm4gqq4waen5te0xyerwt3s9cczuvf6xyurzde597s7crdvsk2vmyarjw9gwyqjdzj"'
2023-09-14T21:32:32.288091Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-09-14T21:32:32.288097Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-09-14T21:32:32.288633Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
{
  "error": "CliError",
  "kind": "GeneralFailure",
  "message": "Federation rpc error {general => Received errors from 1 peers: peer-1: Rpc error: ErrorObject { code: ServerError(400), message: \"Download token not found\", data: None }), 1 => Rpc error: ErrorObject { code: ServerError(400), message: \"Download token not found\", data: None }), }",
  "raw_error": "Federation rpc error {general => Received errors from 1 peers: peer-1: Rpc error: ErrorObject { code: ServerError(400), message: \"Download token not found\", data: None }), 1 => Rpc error: ErrorObject { code: ServerError(400), message: \"Download token not found\", data: None }), }"
}
```

which Justin explained to me is because invite-code is per-peer. So the right invocation is actually:

```
fedimint-cli dev api --peer-id 0 config '"fed114znk7uk7ppugdjuytr8venqf2tkywd65cqvg3u93um64tu5cw4yr0n3fvn7qmwvm4g48cpndgnm4gqq4waen5te0xyerwt3s9cczuvf6xyurzde597s7crdvsk2vmyarjw9gwyqjdzj"'
```

At very least we should add some examples to `fedimint-cli dev api --help`

In addition, if the invite-codes are per-guardian, then maybe we should check it somewhere for better usability.

E.g. we could embed the `PeerId` in `InviteCode` as a field, or `url` could be a map/list. Just so we can return a better error ("this invite code is for a different peer).

BTW. It seems to me like the server side is not checking `InviteCode::id` at all, which probably is not a best way to handle it. We should return `incorrect federation id`, possibly preventing some weird confusion attacks etc. Created #3195 for that.

**Comment by justinmoon** [comment]
It's very difficult to pass auth to `fedimint-cli dev api <rpc>` as well. I've been trying to do this for about 15 minutes and can't figure it out ...

**Comment by justinmoon** [comment]
https://github.com/fedimint/fedimint/pull/3749 should help with ^^

**Comment by justinmoon** [comment]
dev call: we could attempt to parse as json, if that fails then just transform it into a json string.
