### ISSUE TITLE
Allow disconnected peers to reconnect

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#320]
We should expect peers will temporarily disconnect (e.g. for upgrades or network outages) from consensus.  In order to reconnect and catch up to consensus, we need to:

-  We save a signed epoch history to the DB in a hashlist (so if peers don't contribute sigs we ban them but can verify via the hashes)
- Upon restart we request the `next_epoch` from all peers (including our own)
    - If a threshold `2f+1` respond with the same epoch, go with that (this is the case when we are all restarting)
    - If not, then consensus is on-going so peers may be on different epochs, wait for them all to respond with a timeout of 1min, then take the `max(next_epoch)` so long as it falls within bounds of the last signed history (within `f+3` epochs) to prevent malicious peers from delaying us too long
   - If that doesn't work then manual intervention is required to determine what to do with the epoch that was only partially saved by consensus
- Download all the epochs we've missed and process them as we can validate their signatures

Remaining tasks:
- [x] Allow downloading consensus history
- [x] Allows peers to resync up to consensus
- [x] Handle consensus restarts
- [ ] Defend consensus history API against malicious peers (see #449)
- [ ] Handle rejoining with only `2f` peers
- [ ] Prevent send buffers from stopping consensus

**Comment by justinmoon** [comment]
Should we delete consensus history from the DB once everyone has it?

**Comment by jkitman** [comment]
> Should we delete consensus history from the DB once everyone has it?

It might be useful to have a signed record of the history that others can download, maybe there could be a configurable history size limit.

We could detect whether everyone has a past epoch once they contribute to consensus, so it would be probabilistically cleaned up.  Or we'd have to periodically make requests to all other peers.

**Comment by jkitman** [comment]
After chatting with @elsirion we will not delete the history for now.  Long-term we should sign the entire state of the database in order to checkpoint the history for nodes that need to join.

**Comment by justinmoon** [comment]
@jkitman What's the status on this one?

**Comment by jkitman** [comment]
I think we can close since we are tracking the remaining network issues separately.
