### ISSUE TITLE
Wallet module spamming epochs on zero height or something

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#3202]
The reason for https://github.com/fedimint/fedimint/issues/3102 is that wallet modules is spamming with epochs (generating them endlessly) for some reason. If I can get   https://github.com/fedimint/fedimint/pull/3201 to fail i'll be able to debug. :D

**Comment by dpc** [comment]
Actually I've found it: https://github.com/fedimint/fedimint/actions/runs/6193900461/job/16816547661

**Comment by dpc** [comment]
Last thought before sleep: sending same block height view should be consensus illegal. Probably the other part can't respond fast enough and so result if vote y is always None. Peer need to remember last vote and not submit lower vote, reject proposals of others like that as well.

**Comment by justinmoon** [comment]
Is this related to https://github.com/fedimint/fedimint/issues/3063? I saw this same problem with running setup UI against a federation using regtest bitcoin node that hadn't mined a block yet. So this seems like the same issue.

**Comment by dpc** [comment]
Yes. Looks the same.
