### ISSUE TITLE
(client-ng): support dbdump with the new client

### ISSUE THREAD

**Issue by joschisan** [fedimint/fedimint#3204]

**Comment by m1sterc001guy** [comment]
I don't think we completed this right? Maybe the issue just needs to be renamed

**Comment by m1sterc001guy** [comment]
@elsirion the new client uses the db to save data for the state machines. Do you think this is worth exposing via `dbtool`? I think this data might be kind of hard to interpret, since its contextual to the state machine.

**Comment by justinmoon** [comment]
> 
I don't think we completed this right?

Oops

**Comment by elsirion** [comment]
> I think this data might be kind of hard to interpret, since its contextual to the state machine.

We need a decoder registry I guess so we can decode module-specific data.

We kinda already do that for the server side, but not very elegantly/extensible. So ideally the `dbtool` would become something one initializes with a custom set of modules when forking Fedimint like the main `fedimintd` and `fedimint-cli`. It would also need a config file or at least instance-kind mapping.
