### ISSUE TITLE
Port "legacy" integration tests

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3234]
https://github.com/fedimint/fedimint/pull/3213 removed a bunch of integration tests. On dev call we said that the most important ones had already been ported, and that we should port remaining useful tests "sometime". This issue is to make sure we don't forget!

---
Investigation 2024-03-06

Referencing https://github.com/fedimint/fedimint/pull/3216/files (`integrationtests/tests/tests.rs`) vs https://github.com/fedimint/fedimint/tree/7a36cafa295ce30528ac1917575cb82ce8965907 (latest master)

- Missing
  - ~ecash_cannot_double_spent_with_different_nodes~: not needed since coverage in `cannot_replay_transactions` is sufficient
  - ~limits_client_config_downloads~: not present anymore
  - ~rejoin_consensus_split_peers~: not needed anymore due to aleph bft
- Ported
  - cannot_replay_transactions
    - https://github.com/fedimint/fedimint/pull/4550
    - https://github.com/fedimint/fedimint/blob/4926eab064755dfab092fafa5e5e6f9e06e147e4/devimint/src/tests.rs#L2061
  - audit_negative_balance_sheet_panics
    - https://github.com/fedimint/fedimint/blob/7a36cafa295ce30528ac1917575cb82ce8965907/modules/fedimint-dummy-tests/tests/tests.rs#L65
  - can_have_federations_with_one_peer
    - https://github.com/fedimint/fedimint/blob/af73efdb64c0e2c614353764d7e92d8a4ef4aebe/scripts/tests/test-ci-all.sh#L108
  - unbalanced_transactions_get_rejected
    - https://github.com/fedimint/fedimint/blob/7a36cafa295ce30528ac1917575cb82ce8965907/modules/fedimint-dummy-tests/tests/tests.rs#L113
  - rejoin_consensus_single_peer
  - rejoin_consensus_threshold_peers
  - ecash_can_be_recovered
    - https://github.com/fedimint/fedimint/blob/4926eab064755dfab092fafa5e5e6f9e06e147e4/devimint/src/tests.rs#L1224
  - can_get_signed_epoch_history
    - implicitly tested in backup and recovery
    - https://github.com/fedimint/fedimint/blob/4926eab064755dfab092fafa5e5e6f9e06e147e4/devimint/src/tests.rs#L1224
  - ecash_backup_can_recover_metadata
    - https://github.com/fedimint/fedimint/pull/4617
    - https://github.com/fedimint/fedimint/blob/10a9bd2a9b927725bfab698600625b43742a0c47/modules/fedimint-mint-tests/tests/tests.rs#L205
  - ecash_in_wallet_can_sent_through_a_tx
    - note selection covered in https://github.com/fedimint/fedimint/blob/2befd3c631c0a92201171b8f14a99068d69b2c07/modules/fedimint-mint-client/src/lib.rs#L1783
    - spending covered in https://github.com/fedimint/fedimint/blob/10a9bd2a9b927725bfab698600625b43742a0c47/modules/fedimint-mint-tests/tests/tests.rs#L49
- ~Open questions~
  - ~runs_consensus_if_tx_submitted~: not needed anymore
  - ~runs_consensus_if_new_block~: not needed anymore

**Comment by justinmoon** [comment]
Status here?

**Comment by m1sterc001guy** [comment]
I think @douglaz ported these?

**Comment by douglaz** [comment]
> I think @douglaz ported these?

I think there are still some tests that could be ported

**Comment by bradleystachurski** [comment]
I'm going to start looking into any remaining tests to port.

**Comment by bradleystachurski** [comment]
For future readers the timeline might be confusing. I'm editing the description to keep track of outstanding tests to port.

**Comment by bradleystachurski** [comment]
All of the missing integration tests have been ported or are not possible to port, so we can close this.

@elsirion after our discussion yesterday about `ecash_in_wallet_can_sent_through_a_tx`, I did more investigation and we test note selection in `fedimint-mint-client`, so there's no need to create a followup issue.

**Comment by justinmoon** [comment]
Great work @bradleystachurski 🎉
