### ISSUE TITLE
`just test-ci-all` fails locally on linux x86-64

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#3259]
Running `just test-ci-all` locally consistently fails for `backend_test_*` on [master](https://github.com/fedimint/fedimint/tree/20c85475d522d447c481120d9065025590d5bc84).

```
Some tests failed. Full job log:
Seq     Host    Starttime       JobRuntime      Send    Receive Exitval Signal  Command
1       :       1695303761.978       0.029      0       63      0       0       always_success_test
7       :       1695303793.687      43.157      0       12842   0       0       lightning_reconnect_test
9       :       1695303804.610      43.655      0       12246   0       0       load_test_tool_test
8       :       1695303799.537      74.386      0       14958   0       0       devimint_cli_test
5       :       1695303782.622     117.121      0       10977   0       0       latency_test
6       :       1695303787.740     115.105      0       15324   0       0       reconnect_test
4       :       1695303777.588     249.151      0       5774    100     0       backend_test_esplora
3       :       1695303772.046     260.084      0       63010   100     0       backend_test_electrs
2       :       1695303767.002     284.655      0       93649   100     0       backend_test_bitcoind
```

CI is working for `Build on linux`
https://github.com/fedimint/fedimint/actions/runs/6260474673/job/16998577685

Mac users aren't reporting any issues, however other users are observing failed tests locally (Discord [thread](https://discord.com/channels/990354215060795454/990354215878688860/1154223019603005551)).

**Comment by dpc** [comment]
@fedimint/infra

**Comment by douglaz** [comment]
I think this is a different issue

**Comment by dpc** [comment]
Too many issues. :D

**Comment by dpc** [comment]
Probably: https://github.com/fedimint/fedimint/pull/3269

**Comment by justinmoon** [comment]
Call: was consistently failing for @bradleystachurski but not only 10% of time ... decreasing parallelism in `cargo nextest` can help fix this because it's fighting over bitcoind lock

**Comment by bradleystachurski** [comment]
`just test-ci-all` is consistently passing locally, thanks to https://github.com/fedimint/fedimint/pull/3589 and likely several other improvements since this issue was created.

We can open a separate issue if we start observing failures again.
