### ISSUE TITLE
Gateway registrations should use `gateway_id` instead of `node_pub_key` on server side

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#3290]
See https://github.com/fedimint/fedimint/pull/3288/files#r1336124666

**Comment by tvolk131** [comment]
I can take this! It looks relevant to what I've already been working on in #3288 and #3289

**Comment by m1sterc001guy** [comment]
Fixed in https://github.com/fedimint/fedimint/pull/4114
