### ISSUE TITLE
`client.json` obsolete?

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/fedimint#3292]
When experimenting with fedimint-cli and modules, it seems that the `client.json` file is no longer used since the config is sourced from the `client.db/` directory.

**Comment by EthnTuttle** [comment]
fedimint-client/src/lib.rs

Line1515

```rs
        Some((_, config)) => {
            // TODO: Enable after <https://github.com/fedimint/fedimint/pull/2855>
            // assert!(
            //     config_source.is_none(),
            //     "Alternative config source provided but config was found in DB"
            // );
            Ok(config)
        }
        ```

**Comment by justinmoon** [comment]
In particular, this file is saved to disk during the devimint setup process. But now that configs are stored in the DB when joining a federation, `fedimint-cli` we no longer needs or uses this file so I think it would be OK to just stop saving it to disk.

**Comment by Maan2003** [comment]
i found a reference
https://github.com/fedimint/fedimint/blob/023c8f11e146b120712856888c11b14b2a16d153/devimint/src/federation.rs#L193
