### ISSUE TITLE
`fedimintd` must check `consensus.json.version` against its current consensus version.

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#3299]
Right now it doesn't.

**Comment by justinmoon** [comment]
Should it be a hard error if they're different? Or a warning?

**Comment by dpc** [comment]
Hard error, at least ATM. It basically means you're running wrong version of the code (incompat. with consensus it is driving to drive).

**Comment by mubarak23** [comment]
@dpc can you give more context to this.

**Comment by dpc** [comment]
https://github.com/fedimint/fedimint/pull/5766 already implements this as a part of its logic.

**Comment by elsirion** [comment]
I think given the direction of making Fedimint upgradable more smoothly, we should not have these static tests anymore. Even having the version in the `consensus.json` is questionable now.

**Comment by Kodylow** [comment]
from call: we should remove this from the config and it should live in the database
