### ISSUE TITLE
Make `devimint` usable as an external tool

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#3307]
Devimint expect series of things to be lighned up by the mprocs shell and alikes, and does a poor job currently detecting and reporting when things are not like they should be which already wasted hours of my life and will inevitably waste time of other people.

Here is how it can be fixed.

Compile devimint. Start it with:

```
./target/debug/devimin dev-fed
```

**outside of dev shell altogether**. No reproducible environment, no scripts prepared for you. Almost empty shell.

Observe how it failed. Can you fix it just looking at the output? No? Find the code responsible add error context, checks, whatever. Keep fixing until the error/message tells you reasonably well what is wrong.

If you can, fix the external condition (e.g. `export PATH:path/to/som/binary/it/wants`) and try again. You should get a different error. Can you fix it now?

Keep looping in this nested loop until you have a federation running and you can do things with it.

**Comment by justinmoon** [comment]
Assigning this to you @Maan2003

**Comment by humansinstitute** [comment]
@Maan2003 any updates here?

**Comment by Maan2003** [comment]
Yes #3321 fixes this
