### ISSUE TITLE
Build database inspection tool

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#331]
The tool should be able to dump the DB contents in human readable form or possibly JSON (for automatic filtering). It should also be able to display all entry types in the DB (i.e. all unique 1-byte prefixes). That way we can add a CI task that checks that at least after a federation is stopped all DB entries can be decoded by the tool (so it doesn't accidentally diverge).

The tool should probably live in its own crate and be monolithic for now (no module separation). If someone feels like overengineering it we could also build plugins per module, so that the decoding of module DB entries gets routed to the respective plugin (e.g. via JSON RPC through stdin/out like core lightning does).

**Comment by rndhouse** [comment]
As I understand the plan might be to create a new command line tool called `dbdump`. The code should live in the `fedimint/minimint` repository (simpler for the time being).

From elsirion on discord:

> it could be a separate crate for the base `dbdump` binary and then there'd be separate plugins like `dbdump-server`, `dbdump-mint`, `dbdump-ln`, `dbdump-wallet` and `dbdump-client`.
These plugin executables could live in the respective repos to have access to all the structs that are typically private
and the main `dbdump` executable would open the DB and delegate to these plugins.

The plugins (e.g. `dbdump-mint`) would be aware of data types and not necessarily have a handle on the DB.

Getting access to the DB from `dbdump`:

> The DB is actually a file/folder. We just switched from sled to rocksdb so idk exactly, but it definitely lives in the file system
It's an embedded DB though, so no server
you just open the file

> The execution flow would be:
> 1. run dbdump
> 2. run all dbdump-* executables in PATH
>   * These plugins speak JSON RPC via stdin/out
>   * On start they register which prefixes/data types they support
> 3. The user input (prefix type, binary prefix) is delegated to the respective plugin for encoding
> 4. The DB is queried using the encoded key prefix
> 5. The outputs are sent to the plugin for decoding/re-encoding to JSON
> 6. The JSON is output to stdout

**Comment by justinmoon** [comment]
Eventually it would be great to have a time-traveling debugger. Some way to have a slider UI you could move to cycle through epochs/transactions and see the changes to database in any given epoch/transaction. Obviously this is a ways down the road, but would be really useful IMO.

**Comment by chadat23** [comment]
Only time will tell how it'll play out, but I'd be happy to have a go at this.

**Comment by justinmoon** [comment]
@chadat23 @rndhouse can you two double-team this one?

**Comment by justinmoon** [comment]
@chadat23 wont be able to help err. All yours @rndhouse.

**Comment by rndhouse** [comment]
@elsirion @justinmoon Hello,

I'd like to make this kind of change in the way database key prefixes are managed:
https://github.com/fedimint/fedimint/pull/663

Please let me know what you think.

**Comment by rndhouse** [comment]
I won't have time to work on this anymore. I'll share what i have so far in a draft PR this weekend.

**Comment by elsirion** [comment]
Maybe @m1sterc001guy can take this over? Might be helpful for your DB work anyway.

**Comment by m1sterc001guy** [comment]
Yep I can take this over.

**Comment by m1sterc001guy** [comment]
DB Dump tool has been added. Closing
