### ISSUE TITLE
`fedimint-cli dev decode-notes`

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3310]
It would be handy to have a CLI command which can decode ecash and show the federation ID / denominations contained inside

**Comment by justinmoon** [comment]
Call: add this to `validate`

**Comment by justinmoon** [comment]
Call: perhaps we could add this functionality to the `validate` command. But we'd still want to be able to validate an invalid or spent ecash.

**Comment by elsirion** [comment]
We have this functionality in the form of the `split` command in `fedimint-cli` (#3879). What this doesn't do is print the spend key and federation signature separately, but that wasn't part of the issue description.
