### ISSUE TITLE
Devimint should set a `FM_INVITE_CODE` env var

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3316]
I was just writing a little script that needed the invite code and had to read it from `invite-code` file on-disk. Would be nice if an environment variable was exported for this.

**Comment by EshaanAgg** [comment]
Hi! I want to work on this issue. 

I was browsing the codebase and trying to see how I could resolve this issue. I was able to find the code related to the exporting of `env` variables in `devimint`, but wasn't able to able to find where the `invite-code` is stored and how I can access it. Any pointers? 

PS. I am a new contributor here so would appreciate any help :)

**Comment by justinmoon** [comment]
- https://github.com/fedimint/fedimint/blob/479bebe32648841c203993eed925462caebd65ce/devimint/src/bin/faucet.rs#L108
- https://github.com/fedimint/fedimint/blob/479bebe32648841c203993eed925462caebd65ce/fedimint-server/src/config/io.rs#L29
- https://github.com/fedimint/fedimint/blob/479bebe32648841c203993eed925462caebd65ce/devimint/src/federation.rs#L124

**Comment by okjodom** [comment]
devimint first sees the invite code within the [dev-fed subprocess](https://github.com/fedimint/fedimint/blob/54528e8662f2b2a65d48578f07a28d0af7d52bd6/devimint/src/federation.rs#L118C1-L128C46). The challenge is to write a global env var from within this subprocess

**Comment by justinmoon** [comment]
I don't think we need to we need to have devimint rust program write the env var. Could just `user-shell.sh` read the `invite-code` file after devimint completes and export an env var based on it.

**Comment by dpc** [comment]
> devimint first sees the invite code within the [dev-fed subprocess](https://github.com/fedimint/fedimint/blob/54528e8662f2b2a65d48578f07a28d0af7d52bd6/devimint/src/federation.rs#L118C1-L128C46). The challenge is to write a global env var from within this subprocess


We don't really need to modify the running's devimint's env.

Downstream should use:

```
eval "$(devimint env)"
```

to set env variables. (I"d love to have `devimint exec` for it as well).


> Could just user-shell.sh read the invite-code file after devimint completes and export an env var based on it.

user-shell.sh is just another thing that I'd like to get rid of. It just makes downstream consumption outside of Fedimint repo harder to coordinate.
