### ISSUE TITLE
Client coin selection should fail if it can't make correct change

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#332]
For example, in the current `tmuxinator` setup we have a minimum denomination size of 1 sat. If client tries to pay a 1 msat lightning invoice, it will submit an unbalanced transaction to the federation:

```
$ ln2 invoice 1 test test
$  mint_client ln-pay lnbcrt10p...
...
thread 'main' panicked at 'Not enough coins: MintClientError(ApiError(RpcError(RestartNeeded("Networking or low-level protocol error: WebSocket connection error: connection closed"))))', client/cli/src/main.rs:188:18
```

The federation logs will have the following error:

```
thread 'tokio-runtime-worker' panicked at 'Could not submit sign request to consensus: TransactionError(UnbalancedTransaction { inputs: Amount { milli_sat: 1000 }, outputs: Amount { milli_sat: 1 }, fee: Amount { milli_sat: 0 }})', minimint/src/net/api.rs:118:22
```

**Comment by jkitman** [comment]
Alternatively/additionally modules could require a denomination to be available (msat for lightning, sat for wallet).

We should also validate that denominations are canonical.
