### ISSUE TITLE
`list_gateways` hangs if there are no registered gateways

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#3320]
I noticed that if the client calls `list_gateways`, the API call just hangs and then returns error after ~60 seconds if there are no registered gateways. If there are no registered gateways, this should just immediately return an empty vector

**Comment by elsirion** [comment]
This seems to be a regression since `0.1`, I was running the `0.1` release and was debugging why there are no gateways and this didn't happen.

**Comment by m1sterc001guy** [comment]
I cannot reproduce this, when I try I am getting the expected error of `Could not find any gateways`. I'll close this (we can reopen if seen again)
