### ISSUE TITLE
fedimint-cli/gateway-cli should show how much was pegged-in

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#3324]
Currently there is no easy easy to figure out how much a client has pegged-in the past. This makes it difficult, specially for the gateway, to do accounting of its funds in a given federation.

It would also be good to account the peg-outs.

**Comment by justinmoon** [comment]
Kinda related to https://github.com/fedimint/fedimint/issues/569. We have an operation log now, but it's not exposed in `fedimint-cli` or `gateway-cli` at all which would be very helpful ...

**Comment by elsirion** [comment]
`fedimint-cli` already has this imo (but we should add an option to see more pages):

https://github.com/fedimint/fedimint/blob/cdd2b23679fb8605a1fb904953c98bb3b7a3caa2/fedimint-cli/src/client.rs#L125

**Comment by justinmoon** [comment]
TIL!

**Comment by douglaz** [comment]
But note there are not amounts on the operation:
```bash
$ fedimint-cli list-operations
2023-10-04T22:16:51.989583Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-10-04T22:16:51.989847Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-10-04T22:16:51.989930Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
{
  "operations": [
    {
      "id": "e2059e1d107fd874c6ad852829d5d31b3d1e5b8b07d87db630e2fa022d4bf35b",
      "creation_time": "2023-10-04T22:16:07.000000000",
      "operation_kind": "wallet",
      "operation_meta": {
        "Deposit": {
          "address": "bcrt1qmvd6rpkf729czmhzuxe84xahf773ln6dtc3rljr58j0e6vftlekqxjdh9r",
          "expires_at": {
            "secs_since_epoch": 1696458367,
            "nanos_since_epoch": 827251531
          }
        }
      },
      "outcome": "Claimed"
    }
  ]
}
```

**Comment by m1sterc001guy** [comment]
We could just save this info to the db on successful peg-in/peg-out?
