### ISSUE TITLE
Trying to build on latest branch

### ISSUE THREAD

**Issue by kevkevinpal** [fedimint/fedimint#333]
getting this error when running `./scripts/tmuxinator.sh`

----

--- stderr

  error occurred: Command "clang++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-apple-darwin" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "/Users/kevkevin/.cargo/registry/src/github.com-1ecc6299db9ec823/zstd-sys-1.6.3+zstd.1.5.2/zstd/lib" "-I" "/Users/kevkevin/DEVDIR/minimint/target/release/build/libz-sys-57a75a2365cf5f11/out/include" "-I" "/Users/kevkevin/DEVDIR/minimint/target/release/build/bzip2-sys-b8921dc728d6fa78/out/include" "-I" "." "-Wall" "-Wextra" "-std=c++17" "-Wsign-compare" "-Wshadow" "-Wno-unused-parameter" "-Wno-unused-variable" "-Woverloaded-virtual" "-Wnon-virtual-dtor" "-Wno-missing-field-initializers" "-Wno-strict-aliasing" "-Wno-invalid-offsetof" "-msse2" "-std=c++17" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DOS_MACOSX" "-DROCKSDB_PLATFORM_POSIX" "-DROCKSDB_LIB_IO_POSIX" "-DROCKSDB_SUPPORT_THREAD_LOCAL" "-DHAVE_UINT128_EXTENSION=1" "-o" "/Users/kevkevin/DEVDIR/minimint/target/release/build/librocksdb-sys-311825dfd59458ee/out/rocksdb/db/repair.o" "-c" "rocksdb/db/repair.cc" with args "clang++" did not execute successfully (status code exit status: 1).
  
----
  
  I've noticed that it started happening after this commit 5fa9e99d8b66ff46873577d57e34096dfebc692d
  
  It seems to be an issue with `repair.cc` in rocksdb, not too sure much else but the change in that one commit definitely started the issue
  
  I'm on a 2016 Macbook Pro, OSX: Monetary Version 12.3.1
  
  I can provide more info aswell if needed

**Comment by elsirion** [comment]
Was there any more context given for the error? Maybe in the previous lines?

**Comment by dpc** [comment]
We made a lot of improvements in building system since then. Please open new issues if anything is still wrong.
