### ISSUE TITLE
JSON-serialization of fedimint-client states in snake_case

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3332]
When client operation log is exposed to something (e.g. via gateway HTTP API) we will have CapitalCase keys and values as you can see in the screenshot below. [With serde we can annotate these structs to make them serialize as snake_case ](https://serde.rs/attr-rename.html).

![image](https://github.com/fedimint/fedimint/assets/4335621/d8e4b563-7b90-4692-9cfa-00aaa2a35c50)

**Comment by EshaanAgg** [comment]
Hi! I would like to work on this issue.

**Comment by elsirion** [comment]
Reopening till we verify that the commit actually fixes this.

**Comment by elsirion** [comment]
Needs investigation if we got all the structs
