### ISSUE TITLE
Re-enable federations of fewer than 4 guardians

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3333]
https://github.com/fedimint/fedimint/pull/3313 introduced initial support for AlephBFT. One simplification we made to just complete the switch was removing the ability for federations of fewer than 4 guardians.

This issue is to add back this functionality.

**Comment by justinmoon** [comment]
My understanding is that we won't support 2/2 or 3/3 federations @joschisan @elsirion?

**Comment by joschisan** [comment]
Correct
