### ISSUE TITLE
AlephBFT panic

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#3345]
`just mprocs` fails for me:

```
        assert!(bytes.len() <= BYTE_LIMIT);
```

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: bytes.len() <= BYTE_LIMIT', fedimint-server/src/atomic_broadcast/data_provider.rs:105:9
stack backtrace:
```

I "fixed" it with:

```
> git diff HEAD
diff --git a/fedimint-server/src/atomic_broadcast/data_provider.rs b/fedimint-server/src/atomic_broadcast/data_provider.rs
index 29b1a167b7..27008ff086 100644
--- a/fedimint-server/src/atomic_broadcast/data_provider.rs
+++ b/fedimint-server/src/atomic_broadcast/data_provider.rs
@@ -9,7 +9,7 @@ use tokio::sync::watch;
 use crate::LOG_CONSENSUS;
 
 // This limits the RAM consumption of a Unit to roughly 10kB
-const BYTE_LIMIT: usize = 10_000;
+const BYTE_LIMIT: usize = 100_000;
 
 #[derive(
     Clone, Debug, PartialEq, Eq, Hash, parity_scale_codec::Encode, parity_scale_codec::Decode,
```

but it suggests some deeper issues that can result in a DoS.

**Comment by joschisan** [comment]
So the issue is that line 91 in data provider needs to be copied and pasted between 73 and 74. On the same topic, what is the maximum number of bytes of  a u64 integer with bigsize? More then 8 bytes? Then line 63 needs to be updated accordingly.

**Comment by joschisan** [comment]
What is happening here is that we want to create a vector of ConsensusItems that encodes within at most BYTE_LIMIT bytes. This is our submission every single round so every 250ms. We assert that we have bound the length of the encoding correctly which I obviously did not do.

**Comment by dpc** [comment]
> On the same topic, what is the maximum number of bytes of a u64 integer with bigsize

```
			_ => {
				0xFFu8.write(writer)?;
				(self.0 as u64).write(writer)
			},
```

9 bytes.
