### ISSUE TITLE
Backport some rust-API-breaking commits to v0.1

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#3356]
https://github.com/fedimint/fedimint/pull/3351#issuecomment-1758435425

* [x] backport https://github.com/fedimint/fedimint/pull/3254
* [x] backport https://github.com/fedimint/fedimint/pull/3255
* [x] backport https://github.com/fedimint/fedimint/pull/3205
* [x] backport https://github.com/fedimint/fedimint/pull/3351

**Comment by elsirion** [comment]
Finished in  #3373
