### ISSUE TITLE
Backport all devimint fixes to 0.1

### ISSUE THREAD

**Issue by Maan2003** [fedimint/fedimint#3387]
- #3247

**Comment by elsirion** [comment]
Didn't work automatically https://github.com/fedimint/fedimint/pull/3247#issuecomment-1761726000

**Comment by elsirion** [comment]
Do you want to target getting them into v0.1.3? #3400

**Comment by justinmoon** [comment]
> Do you want to target getting them into v0.1.3? #3400

Yes let's target that
