### ISSUE TITLE
AlephBFT panic: RocksDB commit "ResourceBusy"

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3391]
```
thread 'main' panicked at 'This is the only place where we write to this key: Resource busy: 
```

Fedimint version: 0c7357bf87891c45037ccc766f4fb1eb5e6c65d8
Full log: https://gist.github.com/elsirion/e9cb408a58fdfef27de8fbefbab54601#file-fedimintd-log-L207

The panic appears to come from here:

https://github.com/fedimint/fedimint/blob/5f533fefc82355a42ac0b0c3c8cdc6da47700754/fedimint-server/src/consensus/mod.rs#L95-L113

Is it possible that this fn is being called in parallel? Otherwise I'm very confused about this error. Am I correct to assume that this error indicates a write conflict @m1sterc001guy? Any ideas @joschisan?

**Comment by joschisan** [comment]
How did you trigger this ?

**Comment by m1sterc001guy** [comment]
Yes `Resource Busy` indicates a write-write conflict

**Comment by elsirion** [comment]
I just ran mprocs, I doubt it would restart on crash, this is the full log of that guardian, I guess a restart would show up?

**Comment by joschisan** [comment]
> Yes `Resource Busy` indicates a write-write conflict

can we find out which key triggered the conflict?

**Comment by joschisan** [comment]
Nvm I think I got it.

**Comment by elsirion** [comment]
Very curious, looking forward to a summary/PR :smiley:

**Comment by joschisan** [comment]
https://github.com/fedimint/fedimint/pull/3393

**Comment by elsirion** [comment]
Closing since #3393 is merged and we can reopen if the problem shows up again.
