### ISSUE TITLE
AlephBFT warning at session switch

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3404]
These warnings are shown every single time we switch sessions:

![2023-10-16-162042_3840x2160_scrot](https://github.com/fedimint/fedimint/assets/84478054/ad8291f7-5898-453e-8de7-ede840e48897)

Given they show up *normally* they should probably be downgraded to a debug message. This would need to be done upstream I fear, so maybe we can also check if there is a way of filtering input to AlephBFT from the network once we finish an epoch?

**Comment by justinmoon** [comment]
dev call: should this be closed after a PR disabling alephbft logging?

**Comment by elsirion** [comment]
Can't see them in the log anymore, fixed by #3625
