### ISSUE TITLE
Lightning client should retry payments in refund case

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3405]
If the gateway is offline when the lightning client attempts an outgoing payment, the user is put into a refund state where it waits for N block confirmations and then it gets a refund from the federation.

But if the Gateway comes back online, the client could retry the payment but currently doesn't.

**Comment by m1sterc001guy** [comment]
Hmm I've been thinking about this more and I'm not sure if its desirable. If we retry the payment until the lightning gateway comes back online, this effectively locks the user's funds in the escrow contract until either the gateway comes back online, or the timeout occurs. Retrying the payment over and over again inside the state machine might result in unexpected behavior, like the payment being successful minutes or hours later.

Perhaps the lowest hanging fruit here is to just ping the gateway to confirm it is available before locking funds in the outgoing contract? That way the only way funds should get stuck is if the gateway goes offline between this "availability check" and the funding of the outgoing contract.

**Comment by m1sterc001guy** [comment]
Or I suppose we could do both. Add an availability check to confirm the gateway is online, at which point we've "committed" to using that gateway. Then we retry the payment until either it is successful, the contract is canceled, or the timeout has occurred.

**Comment by elsirion** [comment]
If we implemented a fix for https://github.com/fedimint/fedimint/issues/2746 that associates a public key with every outgoing contract (before the preimage is decrypte) we could add an authenticated API endpoint to the GW that lets users request a cancellation of the contract by the GW.

**Comment by m1sterc001guy** [comment]
IMO the client should retry for some timeout, at which point it should request a cancellation (with some retries + backoff). The thinking is that, after a certain amount of time, the user isn't going to expect the payment to succeed and it might result in a weird user experience.

With the availability check that we recently added though, I don't think this is a high priority.

**Comment by m1sterc001guy** [comment]
Not worth investigating with LNv2 shipping in v0.6 by default. Closing.
