### ISSUE TITLE
Delete multipass setup instructions

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3414]
https://github.com/fedimint/fedimint/blob/master/docs/macos.md

These multipass instructions were added over a year ago and the contributor who added them hasn't been active since then. They were added because some of us were having issues with Nix on MacOS, but it's gotten **much** smoother since then so I think these instructions are more harm than good.

Also, someone just reported an issue following these in [Discord](https://discord.com/channels/990354215060795454/1163857712388505740/1163857712388505740).

**Comment by justinmoon** [comment]
Alternatively, we could keep these instructions but just discourage their usage unless contributor has tried and failed to setup Nix on the Mac

**Comment by elsirion** [comment]
Let's just delete, if someone wants to maintain them they can get them back from the git log.

**Comment by justinmoon** [comment]
Closed by https://github.com/fedimint/fedimint/pull/3428
