### ISSUE TITLE
Migrate everything to Nix-flake based setup

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#345]
TODO:

* [x] fix all the stuff that I missed and broke; see #342 
* [x] integration tests should run as  as a job in `ci-nix.yaml` running something like: `nix develop .#integrationTests --command <someshellscript>` 
* [x] why are all the packages depending on `integrationtests`? Tests should depend on other code, no?
* [ ] move Markdown lint into `git-precommit` and `.#ci`
* [x] switch to using `buildjet-8vcpu-ubuntu-2004`
* [x] https://github.com/fedimint/minimint/pull/342#discussion_r942720926
* [x] https://github.com/ipetkov/crane/discussions/59#discussioncomment-3370974
* [x] run clippy in the nix-ci somewhere.

**Comment by dpc** [comment]
Seems like the markdown is implemented as an github action script, and I don't see a benefit of trying to migrate it.

**Comment by justinmoon** [comment]
What about the WASM [job](https://github.com/fedimint/fedimint/blob/8d7b5144ad0deb2085dce466466efdf0a6245ba3/.github/workflows/rust.yml)?

On related note, someday we should add CI jobs to build client library for ios & android targets. 

Also, should we run things like clippy and rustfmt on wasm / ios / android targets? [Here](https://github.com/fedimint/fedimint/pull/430/files#diff-518eaa39776f4437cb64e868e4a31b14a31449a3e6e864e2e4048b8b8a591454R8) cargofmt is displaying an error during code review but CI still passes.

**Comment by dpc** [comment]
I've git a roadblock for WASM. Closing this in favor of #441 . For other things we should create separate issues as well, I think.
