### ISSUE TITLE
Gateway's "connect federation" flow should check network

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3450]
We should check that federation and gateway are using same network. @Kodylow [reported](https://discord.com/channels/990354215060795454/1096102512169328753/1166140519479513149) that he was able to connect a mutinynet gateway to a mainnet federation.

**Comment by okjodom** [comment]
Is there a better way to check federation `bitcoin::Network` than checking individual module configurations? I also suspect there is a missing a validation to ensure all modules declare the same network

**Comment by justinmoon** [comment]
I would check the network for the lightning module's network since the gateway is a companion service for the lightning module.

**Comment by okjodom** [comment]
Tasks:
- [x] Gatewayd should support configuring of a network
- [x] Gateway should expose it's configured network via info api
- [x] Gatewayd should ensure all connected federations are on the same configured network
- [ ] Gatewayd should ensure connected lightning node / service is on the same configured network
