### ISSUE TITLE
Allow specifying BIP32 `Xpriv` for root secret when building `fedimint-client`

### ISSUE THREAD

**Issue by shaurya947** [fedimint/fedimint#3451]
Currently, `fedimint-client` is built using a random root secret as observed here:

https://github.com/fedimint/fedimint/blob/14f44c0f7890694bfb52e945c7a1d8c1f91c39f3/fedimint-client/src/lib.rs#L1681

The consumer who is building the client can choose between either a [`PlainRootSecretStrategy`](https://github.com/fedimint/fedimint/blob/14f44c0f7890694bfb52e945c7a1d8c1f91c39f3/fedimint-client/src/secret.rs#L64) (which is just random 64 bytes) or [`Bip39RootSecretStrategy`](https://github.com/fedimint/fedimint/blob/14f44c0f7890694bfb52e945c7a1d8c1f91c39f3/fedimint-bip39/src/lib.rs#L12) (which uses [rust-bip39 crate](https://github.com/rust-bitcoin/rust-bip39) to generate a random 12-word mnemonic and convert it to bytes).

Since `fedimint-client` is designed to be composable by other apps, front-ends, CLIs, etc. there arises a very valid use case whereby the _thing_ that's composing `fedimint-client` would like to have control over the root secret for the `fedimint-client` instance. For example, a CLI app might run several instances of `fedimint-client` on behalf of a user who is a part of several federations of varying versions. In such a case, the CLI app might want to have its own root BIP-39 seed that the user backs up once, and be able to initialize `fedimint-client` instances using `m/44'/0'/i'` xpriv derivations where `i` would the index that the CLI app maintains internally for each `fedimint-client` instance.

To address such use cases, we propose:
- adding a new `RootSecretStrategy` that utilizes the [`Xpriv`](https://github.com/rust-bitcoin/rust-bitcoin/blob/1eb6e0c7d85fbc5e3f265de069b91be2cb722359/bitcoin/src/bip32.rs#L69) type as the `Encoding` associated type.
- enhancing the builder API for `fedimint-client` to allow specifying an `Xpriv` from which to obtain the root secret.

**Comment by dpc** [comment]
BIP39 utilizes ECC to be able to asymmetrically derive pub and priv keys, and my understanding is that because of that it's not suitable for general-purpose secret derivation. Or something like that. 

https://github.com/fedimint/fedimint/blob/14f44c0f7890694bfb52e945c7a1d8c1f91c39f3/crypto/derive-secret/src/lib.rs#L7

Having said that `DerivableSecret::new_root` could be initialized with about anything random, so it should be possible for the outer application to derive the secret how it sees fit and pass it to `fedimint-client` instance.

I don't remember the details of the Encoding thing ... let me look around.

**Comment by dpc** [comment]
Doesn't `PlainRootSecretStrategy` already allow it?

**Comment by shaurya947** [comment]
Thanks for the comments @dpc 

> Having said that DerivableSecret::new_root could be initialized with about anything random, so it should be possible for the outer application to derive the secret how it sees fit and pass it to fedimint-client instance.

This is accurate. So is your suggestion to just bypass the `RootSecretStrategy` trait altogether for the use case that I mentioned, and make `fedimint-client` be able to directly take a `DerivableSecret`?

> Doesn't PlainRootSecretStrategy already allow it?

AFAICT, `PlainRootSecretStrategy` necessitates that the `Encoding` be 64 bytes. So if a composer of `fedimint-client` did want to use BIP-32 Xpriv's those would are 78 bytes (or anything else that's not 64 bytes for that matter).

**Comment by otech47** [comment]
approach ack

**Comment by otech47** [comment]
not sure if this makes sense or is too restrictive/cumbersome for the use case, but the `DerivableSecret` seems to follow a similar idea of derivation paths with the `child_key` pattern. Could there be a way to "map" the BIP32 derivation structure onto the `DerivableSecret` directly?

Your approach seems simple enough... but just wondering since the client is already capable of deriving child keys after the root secret is seeded with any random bytes (could be BIP39 mnemonic) maybe there's a way that they mesh together

For example a bitcoin wallet app that already uses BIP32 to derive keypairs could just seed the fedimint client with the same root entropy but then still be able to reason about which derivation paths are being used for each federation's ecash?

Almost seems like BIP39 was implemented directly into fedimint/crypto/derive-secret already but it's not 100% clear how to adapt it

**Comment by otech47** [comment]
after reading BIP32 + 43 + 44 more thoroughly, I think my musings above ^ are mostly irrelevant

but if you do go with a `Bip32RootSecretStrategy`, maybe it would be good to recommend in the code comments what derivation path a composer might use...

for example existing bitcoin HD wallets may wonder whether to use `m/44'/0'/i'` but if they are already using that convention for normal wallet accounting and don't want to expose the chain of secrets to another piece of software like fedimint, it might be more prudent to use a derivation space with a different [BIP44 cointype](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#user-content-Registered_coin_types) like `m/44'/100000'/i'

or perhaps if BIP44 isn't relevant to how fedimint uses this secret maybe a different [BIP43](https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki#user-content-Purpose) purpose value should be used like `m/54321'/0'/i'`

**Comment by shaurya947** [comment]
> So is your suggestion to just bypass the RootSecretStrategy trait altogether for the use case that I mentioned, and make fedimint-client be able to directly take a DerivableSecret?

I guess this isn't really doable with the current architecture because `fedimint-client` stores the secret material (what is represented by a `RootSecretStrategy`'s `Encoding`), and not the `DerivableSecret` itself—and there wouldn't be a way to go backwards.

> but if you do go with a Bip32RootSecretStrategy, maybe it would be good to recommend in the code comments what derivation path a composer might use...

Good point! Different purpose or cointype seems prudent.

**Comment by shaurya947** [comment]
I guess the problem is that right now `fedimint-client` stores the secret material from which the `DerivableSecret` is generated—not the `DerivableSecret` itself. So while `DerivableSecret` itself can be an arbitrary number of bytes, the secret material needs a corresponding `RootSecretStrategy` whereby the type of the secret material is strictly specified as an encoded type. So if we want to work with the current architecture, we'd either have to:
1. make a "bring your own secret material" compatible with `PlainRootSecretStrategy` which means the secret material must be 64 bytes
2. make a "bring your own secret material" compatible with `Bip39RootSecretStrategy` which means the secret material must be a 12-word mnemonic
3. write a new `RootSecretStratgy` that serves our purpose better

I do think HD derivation is the way to go as far as an external composer is concerned. So I'm tempted to play within those constraints. Xprivs are 78 bytes which doesn't work with option 1. But we could only take the first 64 bytes?

I don't see how option 2 would work.

Option 3 was my initial proposal but maybe it needs to be based on something else besides xprivs. If we make `PlainRootSecretStrategy` take a vec of bytes as the secret material maybe that would serve more use cases?

**Comment by shaurya947** [comment]
Discussed offline with @justinmoon 

> What if we had a `Runtime` secret strategy that doesn't store anything and just requires caller to pass in a `DerivableSecret` themselves?


>> Interesting.. so does that mean that every time `fedimint-client` is initialized, the `DerivableSecret` would need to be provided from outside? So we're fully absolving `fedimint-client` of secret storing/generation?

> Yes. I think that makes most sense to me. If we want to generate and store 1 seed externally to `fedimint-client`, I don't think `fedimint-client` should retain any responsibities for generating and storing secrets in this usecase.

**Comment by dpc** [comment]
> make a "bring your own secret material" compatible with PlainRootSecretStrategy which means the secret material must be 64 bytes

This is always easy by either trimming or stretching (hash, then trim it to size) the existing key material. Secret material need only to be deterministic. Reversability to the original form is not strictly required.

> What if we had a Runtime secret strategy that doesn't store anything and just requires caller to pass in a DerivableSecret themselves?

I'm not sure about the details and it might need some refactoring, but yes. Fedimint client library handling persisting secrets should be an convenient options, but not a requirement.

**Comment by shaurya947** [comment]
@dpc and I had a long conversation where we decided on this approach:
- make the `ClientBuilder`'s `build()` methods take as input a `DerivableSecret`
- provide an external function on `ClientBuilder` to store the input secret material as encoded bytes in the DB
- provide an external function on `ClientBuilder` to load the decoded input secret material from the DB
- The `store/load` functions are meant to be called before `build()`
- Consumer of `fedimint-client` can decide whether it wishes to leverage `fedimint-client`'s DB for the purpose of storing the encoding input secret material
- In either case, the client is always built with `DerivableSecret` which gives consumers max flexibility
- All the different `RootSecretStrategies` then become unnecessary. They may be moved to `fedimint-cli` as reference for consumers who may wish to use the encoding types specified by those strategies.

DPC identified that the heart of the issue lies in the fact that the client, when building itself, is also attempting to generate+save/load the input secret material from its DB. This results in the `build()` methods being generic over some `S: RootSecretStrategy`. So if we can provide saving/loading the input secret material as a side-API (and not as a side-effect of calling `build`), we can remove `S` bound from the `build()` methods and make them take in a `DerivableSecret`.
