### ISSUE TITLE
Is how we test against `esplora` completley redundant?

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#3457]
Both `electrs` and `esplora-electrs` (which are a fork) implement Electrum protocol, and that's how we consume them as well.

Which begs the question: why? If Fedimint works with one, it should work with any other correct Electrum implementation. Both in tests and when selecting the blockchain backend ... we should just use `electrum` and test again any.

**Comment by justinmoon** [comment]
Esplora implements a different interface than Electrum Protocol:

- [esplora](https://github.com/Blockstream/esplora/blob/master/API.md)
- [electrum protocol](https://electrum.readthedocs.io/en/latest/protocol.html)

**Comment by dpc** [comment]
Oh, I see. Thanks.
