### ISSUE TITLE
Next Generation Lightning Integration

### ISSUE THREAD

**Issue by joschisan** [fedimint/fedimint#3467]
The current plan is to do complete rewrite of the lightning module code by creating a new module instead of updating the legacy code.
- [x] Implement threshold point encryption based on BLS cryptography, update distributed key generation to support the scheme, implement a new ServerModule.
- [x] Implement a new ClientModule
- [x] Update the Gateway

**Comment by m1sterc001guy** [comment]
I don't think we need to actually implement a new module on the client side, since the outgoing payment contract structure isn't changing. I think we just need to implement a new receive state machine on the client side and a new incoming state machine on the gateway side. That should save us some work.

**Comment by elsirion** [comment]
How would we select which one to use? If the new LN module was just a completely new module kind that would be simple. If we keep the old client lib then maybe we could use versioning? @dpc

**Comment by dpc** [comment]
@elsirion 

IIRC we could use versioning inside one codebase as well. The code can do different things depending on the module consensus version.

Which one will be easier is a hard call to make. Separate module will have a problem that both modules will be "available", and we need somehow make new Federations generate only the new one, but also handle the existing one. Doable, but worth mentioning.

With the single module we could actually try out module consensus versioning. Theoretically everything should be there to handle it already. `ServerModuleInit::versions` will return both versions, so will `ServerModuleInit::api_versions`, then `ServerModuleInit::init` will get the config (with the version to use) in `&ServerModuleInitArgs`, and then the code will be sprinkled with conditionals (shouldn't be too bad, literally an `if` in every trait function that forwards to one or the other implementation).

**Comment by m1sterc001guy** [comment]
Remaining follow up items in LNv2 integration

- [ ] Document `crypto/tpe` crate
- [ ] Gateways and lightning nodes are assumed to be 1-1, which doesn't allow for custodial LN wallets to be liquidity providers. This means the gateway takes a fee even for internal payments within the federation. Currently, internal payments do no bypass the gateway.
- [ ] CLN `create_invoice` isn't implemented yet.
- [ ] Errors do no contain any debugging information except a message
- [ ] Gateway fees are not configurable
- [ ] Gateway tests need to be re-implemented for LNv2
- [ ] `PaymentResult` that prevents the LN client from paying an invoice twice needs to be implemented
- [ ] More informative debugging when things go wrong

**Comment by elsirion** [comment]
Call: we can close this
