### ISSUE TITLE
Gateway tests for HTLC subscription assumptions

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3473]
We've been assuming that lightning nodes will cancel HTLCs if the gateway fails respond promptly. IIRC Core Lightning will cancel after 90 seconds. But we just found out today that LND isn't cancelling HTLCs at all if the gateway fails to respond. We should add tests for these assumptions.

**Comment by m1sterc001guy** [comment]
LNv2 does not use HTLC interception and will ship by default in v0.6. Closing
