### ISSUE TITLE
Port recovery tool to Aleph Bft Consensus

### ISSUE THREAD

**Issue by joschisan** [fedimint/fedimint#3482]
The current recovery tool only supports HBBFT and has therefore been disabled when we switched to Aleph Bft.

**Comment by bradleystachurski** [comment]
After a brief search I wasn't able to find any current or previous test vectors for the recovery tool. Does anyone know if tests exist for the recovery tool?

Relevant diff that commented out the logic for `TweakSource::Epochs`
https://github.com/fedimint/fedimint/pull/3313/files#diff-4b8aea85269151549702a71dd7d565c3a3311f7f172539df4293d558067dc5e6

**Comment by elsirion** [comment]
> Does anyone know if tests exist for the recovery tool?

Highly unlikely, I hacked it together in a hurry back then and I don't think many people touched it since then.
