### ISSUE TITLE
Whenever `ConfigGenApi::state` is changed, log this change at `INFO` level

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3499]
This would help with debugging

**Comment by justinmoon** [comment]
To see this in action, you could make the change in this repo and then [run through the setup ui](https://github.com/fedimint/ui) but following [these instructions](https://github.com/fedimint/ui#running-with-local-fedimint) to run it against your local checkout of fedimint.

**Comment by mayrf** [comment]
Hi, I would like to take care about this issue.
