### ISSUE TITLE
Have gateway call get_info on startup

### ISSUE THREAD

**Issue by benthecarman** [fedimint/fedimint#3526]
When debugging if the LND node is connected to the gateway it is hard to debug because once you bootup the gateway the only way to tell if you're connected is if you can sucessfully join. It should call `get_info` on startup to make sure the connection is properly configured.

This can also help if someone changes their configuration later, after they initially set it up. If their configuration is now broken there would be no indication

**Comment by benthecarman** [comment]
This was on 0.1.3

**Comment by m1sterc001guy** [comment]
I'm going to close this as I think 0.2 will address this, but feel free to reopen if it doesn't match your guys needs.
