### ISSUE TITLE
Investigate potential overpaying fees by ~4x

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#3534]

**Comment by niteshbalusu11** [comment]
This seems to be way more than 4x, I have even seen as high as 80x on signet.

**Comment by bradleystachurski** [comment]
Dev call: we'd like to have the ability for the test framework to reproduce the issue and guarantee the fix doesn't have a regression

**Comment by bradleystachurski** [comment]
Dev call: consider configurable target conf

**Comment by bradleystachurski** [comment]
@niteshbalusu11 Thanks for the additional feedback!

I was able to replicate overpaying by 4x in a regtest environment, but I haven't been able to observe overpaying by 80x. Are there any additional details you can provide about how you observed the 80x diff? Do you happen to have the results from `bitcoin-cli estimatesmartfee 10`?

**Comment by bradleystachurski** [comment]
> Dev call: consider configurable target conf

A configurable target conf is similar in nature to allowing users to define their own feerate. I'm going to tackle the question of configurable target confs in that issue https://github.com/fedimint/fedimint/issues/3180.

**Comment by elsirion** [comment]
> A configurable target conf is similar in nature to allowing users to define their own feerate.

The target conf would be configurable by the guardians and allows them to lower/increase the minimum fee indirectly. User  configurable fees will always have to meet this minimum, so related but quite different in nature.

**Comment by bradleystachurski** [comment]
@elsirion Good callout, I created a separate issue to keep track https://github.com/fedimint/fedimint/issues/3646
