### ISSUE TITLE
`devimint run-ui` doesn't use random ports

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3541]
https://github.com/fedimint/fedimint/pull/3247 modified devimint to run everything on random ports. But it seems we [forgot to do this for the `devimint run-ui` command](https://github.com/fedimint/fedimint/blob/23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b/devimint/src/main.rs#L1200-L1215).

**Comment by dpc** [comment]
Looks fixed to me, as RunUi uses same infra as everything else.
