### ISSUE TITLE
Consensus API serves `get_verify_config_hash` RPC endpoint

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3543]
[Details in ui repo](https://github.com/fedimint/ui/issues/255#issuecomment-1797002015)

**Comment by okjodom** [comment]
We already have [consensus api here](https://github.com/fedimint/fedimint/blob/23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b/fedimint-server/src/net/api.rs#L604-L610), and it matches [config api here](https://github.com/fedimint/fedimint/blob/23ee7cb6e96fce89bb024fbc1fcfccbfb3dc968b/fedimint-server/src/config/api.rs#L636-L642). Afak, the issue described in UI repo is a UI bug

**Comment by okjodom** [comment]
Got a small fix and refactor related to this

**Comment by justinmoon** [comment]
Huh. Nice observation!
