### ISSUE TITLE
Publish binairies for release branches

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3554]
Currently we only build master, so releases don't have binaries.

https://github.com/fedimint/fedimint/blob/f8c52b03268c52f434ad9998ba890f2630103c72/.github/workflows/ci-nix.yml#L337-L339

**Comment by elsirion** [comment]
There doesn't seem to be an easy way to pull artifacts from CI into a release without [creating the release from CI](https://github.com/marketplace/actions/create-release). We should consider doing that, but this will require some refactorings of out workflows imo.

**Comment by dpc** [comment]
> We should consider doing that, but this will require some refactorings of out workflows imo.

It won't be able to re-use the stuff that Nix built, and will wont to build everything on it's own, so we should make it a separate workflow that does `nix develop -c just release <$tag>` or something. It will be slow, but since it's not a common operation, it should be OK.

**Comment by elsirion** [comment]
Sorry, I wasn't talking about crates.io releases but GitHub ones, although doing it all from CI sounds great!

**Comment by dpc** [comment]
```
  pkgs:
    if: github.repository == 'fedimint/fedimint' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/releases') || github.ref_type == 'tag')
    name: "Release packages: ${{ matrix.build.flake-output }}"

```

Looks fixed?
