### ISSUE TITLE
Make client forward-compatible

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3556]
For me backwards compatibility is most relevant to clients speaking to newer/older federations, not different `fedimintd` versions. Also our internal rust interfaces are less of a concern right now, even though they will likely ossify as well as more people develop modules.

A few ideas that could make backwards compatibility easier to achieve in the future:

* Versioning of
  * Invite codes #3567
  * APIs
  * E-Cash note representations #3568
* Adding length fields to consensus items so we can ignore unknown ones (relevant for recovery where epoch history gets scanned)
  * Similar treatment might be useful for all enums? #3569
  * TLV encoding? Performance concerns?
* Make all module inputs/outputs enums with the same treatment as described above #3570
* This requires minor consensus versions #3571
* Fix #1458
* Make PoW-based DoS protection easier to introduce #3607 

*Feel free to add your ideas here.*

Things we can implement later on:
* State machine migrations #3417
* DB upgrades as needed
* Need to be able to shut down at a given block height to synchronously upgrade `fedimintd` #3572
  * Later we should be able to switch to new minor consensus version after all guardians upgraded

**Comment by justinmoon** [comment]
Switching away from x-only pubkeys is a big backwards compatibility issue https://github.com/fedimint/fedimint/issues/3168#issuecomment-1804440392

**Comment by douglaz** [comment]
+1 for TLV encoding. I've worked in the banking industry and it was widely used in smartcards, so the only performance consideration is that it's pretty fast even in small devices.
