### ISSUE TITLE
LND doesn't support multiple HTLC subscriptions

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#3596]
A known limitation for LND gateways is that gatewayd can only establish one HTLC subscription. We should try support multiple HTLC subscriptions to unblock test and deployment scenarios where multiple gatewayd need to share the same LND instance

Edit: this issue is about trying to get LND to support this in their API.

https://github.com/lightningnetwork/lnd/issues/7162

**Comment by okjodom** [comment]
related to #3209

**Comment by m1sterc001guy** [comment]
One option: We could build something similar to what the Torq guys did, and build a standalone daemon that implements the gRPC server. This daemon would then have one HTLC subscription, but multiple gatewayd's could query the gRPC server concurrently.

Obviously a big drawback is that this requires a whole new daemon, but I don't see a way around it currently with LND's API.

**Comment by justinmoon** [comment]
What are some concrete examples where we want multiple HTLC interceptors?

**Comment by justinmoon** [comment]
@okjodom bump

**Comment by okjodom** [comment]
> What are some concrete examples where we want multiple HTLC interceptors?

Theoretical examples I can cite right now is reuse of an LND node for multiple gatewayds or a gatewayd and a non-gatewayd interceptor

> One option: We could build something similar to what the Torq guys did, and build a standalone daemon that implements the gRPC server. This daemon would then have one HTLC subscription, but multiple gatewayd's could query the gRPC server concurrently.
> Obviously a big drawback is that this requires a whole new daemon, but I don't see a way around it currently with LND's API.

Proposal makes sense and I we should implement if we have pressing need and if we can not get LND to natively support multiple interceptors

**Comment by m1sterc001guy** [comment]
No longer necessary with LNv2
