### ISSUE TITLE
Allow guardians to configure estimatesmartefee conf_target

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#3646]
The wallet module currently [hardcodes](https://github.com/fedimint/fedimint/blob/01d20bb43eb137e4cb7870eb73b2a28c32df73dd/modules/fedimint-wallet-server/src/lib.rs#L886) the confirmation target to 10 blocks, which is used for reaching consensus on an estimated fee rate for constructing peg-out transactions.

We should allow the guardians to configure the confirmation target used for estimating fee rates.

**Comment by dpc** [comment]
@bradleystachurski You implemented some multipliers etc. recently w.r.t this. Can we close?

**Comment by elsirion** [comment]
IMO this should become configurable since priorities may differ for different federations, let's leave it open.

**Comment by bradleystachurski** [comment]
We can leave this issue open, but until we have other mechanisms in the wallet to reduce the risk of a stuck tx in the mempool (e.g. rbf, cpfp), I think we should prevent users from configuring.

https://github.com/fedimint/fedimint/blob/fd074f9219ca6bd7403d7be935fbdac2076c411f/modules/fedimint-wallet-common/src/lib.rs#L40-L44

**Comment by elsirion** [comment]
Given the discussion last Monday and Bradley's comment this feels like a thing for Wallet v2 and possibly won't be needed at all anymore with more sophisticated fee estimation. Closing.
