### ISSUE TITLE
`meta_override_url` is unnecessarily wrapped in quotes

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3648]
![Screenshot 2023-11-19 at 16-47-32 feat clients use vetted gateway meta field in selecting gateway by okjodom · Pull Request #3533 · fedimint_fedimint](https://github.com/fedimint/fedimint/assets/84478054/d2348b59-3d2a-40a9-aee3-000f8434753f)

See how we have to call `json!(…).to_string()` instead of writing the plain string: https://github.com/fedimint/fedimint/pull/3533

**Comment by okjodom** [comment]
We need the url to be a valid json string when we parse it later.

`"\"https://getln.xyz/fedimint/meta\"".to_string()` works just as well, but plain `"https://getln.xyz/fedimint/meta"` will fail json parse with `serde_json::from_str()`

**Comment by elsirion** [comment]
I see, so currently there are two functions `meta` and `meta_raw`, the latter returns the raw string slice. But I see that this API is confusing. The problem currently is that some string meta fields use the raw format (e.g. federation name) and others the JSON format (e.g. meta_override_url). It feels like there should be a standard?

**Comment by okjodom** [comment]
Could we standardise all meta fields as json strings?

**Comment by elsirion** [comment]
> Could we standardise all meta fields as json strings?

@wbobeirne @otech47 would you be ok with that? I guess you already need to impl JSON decoding anyway, so if e.g. the federation name was also awkwardly wrapped this wouldn't be too much of a problem from the code side (just not aesthetically pleasing when looking at the config).

**Comment by wbobeirne** [comment]
The logic I've been going with with meta is something like:
```ts
try {
  // Try to parse it as JSON, could be string | number | boolean | object
  const value = JSON.parse(meta[key])
  return value
} catch {
  // If parsing fails, return it as a plain old string | undefined
  return meta[key]
}
```
So in that case, something being extra string wrapped or just a plain string would work fine. Can't guarantee that all implementations out there will be like this, but it's definitely the safest way to do it.
