### ISSUE TITLE
Add command to list and delete Lightning gateways to CLI client

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#366]
The client remembers the first gateway it ever used. More sophisticated clients should delete malfunctioning clients automatically, but for our CLI client we want more control. The following commands would be interesting to have:

* list gateways from database
* list gateways currently registered with federation
* add gateway to database
* delete gateway from database

**Comment by okjodom** [comment]
now actively starting work on this

**Comment by justinmoon** [comment]
Sweet! For starters, try adding a single command to the CLI and make a PR.

**Comment by okjodom** [comment]
@justinmoon, I did spend sometime exploring the feature and I have some idea of what `mint-client` api changes may be needed to support the desired cli capability. I liked a draft PR from my exploration. For your review, here is an atomic change that only introduces `mint-client-cli gateways` command #407 

PS:  Please review with extra care. I'm just wrapping my head around Rust and it's richness! Fun so far

**Comment by justinmoon** [comment]
@okjodom will review today

**Comment by justinmoon** [comment]
Discussed with @okjodom on Discord.

Decided that best API would be:

- Command to list gateways currently registered with federation. We would add an `active: <bool>` field. Whichever one is currently in use by the client would be `true`, others would be `false`. Something like `mint-client-cli list-gateways`
- Command to switch the active gateway. Something like `mint-client-cli switch-gateway <node-pubkey>`

IMO there is no need to store more than the currently used gateway in the database as is the case currently. It would only prevent a round-trip to the federation. Someday this might be useful but seems like overkill now. Just need a way to manually change.

**Comment by okjodom** [comment]
PR #407 addressed the proposals in this issue in the following manner:
- `lightning-client-cli list-gateways` shows all the gateways currently registered with the federation. It also shows active state of the gateways, i.e. a gateway in the client db is marked as active. This resolves the following proposals:
   - [x] list gateways currently registered with federation
   - [x] list gateways from database
-  `lightning-client-cli switch-gateway` adds a new gateway to db, replacing any gateway that was previously saved to the db as the active gateway. This resolves:
   - [x] add gateway to database
   - [x] delete gateway from database
