### ISSUE TITLE
`test_gateway_executes_swaps_between_connected_federations` fails often

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3672]
See e.g. https://github.com/fedimint/fedimint/actions/runs/6943815403/job/18889679969#step:6:2342 and other builds from the merge queue in #3666.

**Comment by elsirion** [comment]
[I just had a failure again](https://github.com/fedimint/fedimint/actions/runs/6970673359/job/18969096990?pr=3703#step:6:2646), so I looked into the test and wondered if this `&&` shouldn't be a `||`:

https://github.com/fedimint/fedimint/blob/4c6766a2386ba0890d875fa7c76dd1b2645ccd2f/gateway/ln-gateway/tests/integration_tests.rs#L1195-L1197

Is it really enough to wait for any of the two values to change? E.g. if the second one changed, we exit the retry loop because of that (the first value is unchanged) and then check in the assertion that the first value is changed in a specific way, that sounds like it could fail.

**Comment by elsirion** [comment]
I included my suspected fix in https://github.com/fedimint/fedimint/pull/3703, seems to work but unclear if that was just luck.

**Comment by okjodom** [comment]
> [I just had a failure again](https://github.com/fedimint/fedimint/actions/runs/6970673359/job/18969096990?pr=3703#step:6:2646), so I looked into the test and wondered if this `&&` shouldn't be a `||`:
> 
> https://github.com/fedimint/fedimint/blob/4c6766a2386ba0890d875fa7c76dd1b2645ccd2f/gateway/ln-gateway/tests/integration_tests.rs#L1195-L1197
> 
> Is it really enough to wait for any of the two values to change? E.g. if the second one changed, we exit the retry loop because of that (the first value is unchanged) and then check in the assertion that the first value is changed in a specific way, that sounds like it could fail.

oh my boolean! 🤦🏿‍♂️

**Comment by elsirion** [comment]
Haven't seen it happen since my fix got merged, closing. Feel free to reopen if it happens again.
