### ISSUE TITLE
Reactivate partially disabled intermittently failing gateway test

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3679]
See #3675

**Comment by justinmoon** [comment]
This test may be intermittently failing because of https://github.com/fedimint/fedimint/issues/3682

**Comment by okjodom** [comment]
Could be! Looking at this, the gateway assertion disabled worked purely by random chance. It makes a balance request to the gateway, in hopes that the necessary consensus rounds have completed for gateway balance to be updated by `GatewayPayStateMachine` transitions.
A nice fix for the gateway test scenario would be to just have the test wait for sufficient consensus round to succeed, no matter the consensus performance.
This would make the the integraton test as slow as the perf of consensus + gateway SMs, but reliable

**Comment by okjodom** [comment]
currently, gateway `/balance` rpc abstracts away all the state machines and other details, and I'm thinking the best fix here would be to wait some expected **timeout duration** informed by expected perf of fedimint + gateway SMs, before asserting expected balance after swap
