### ISSUE TITLE
Remove workaround for `get_active_operations` returns oeprations IDs not associated with operations

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3687]
In particular caused by the special case of recovery state machines. Thx @Maan2003 for reporting :)

**Comment by dpc** [comment]
Let's keep this open and remove #3688 workaround after the reason for it are gone.

**Comment by justinmoon** [comment]
Closed by https://github.com/fedimint/fedimint/pull/3688. Not sure why it didn't auto close???
