### ISSUE TITLE
Tracing support in gateway-cln-extension

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3691]
`cln-plugin` -- which we use to create our `gateway-cln-extension` Core Lightning plugin -- doesn't support tracing. Some months ago before we extracted gateway business logic out of the plugin, @Maan2003 made a [PR](https://github.com/ElementsProject/lightning/issues/5954) to add tracing support to `cln-plugin` which is still open. Making an issue here to just track this. I don't think this is terribly useful now that the `gateway-cln-extension` doesn't run the core business logic (`gatewayd` does this) but making an issue just in case we want this in the future.

**Comment by m1sterc001guy** [comment]
Don't think this is relevant anymore. I believe the tracing from the `gateway-cln-extension` just goes to the Core Lightning log directly. Closing, can reopen if its still an issue
