### ISSUE TITLE
Idle federation uses significant amount of cpu

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#3715]
Not necessarily a bug but it is something that we could investigate to understand better. This is a local devimint:
![image](https://github.com/fedimint/fedimint/assets/163706/a45decb0-7c28-46ea-a811-69daa4d017e0)

**Comment by elsirion** [comment]
We are creating AlephBFT rounds every 50ms, these probably cause a bunch of network traffic and crypto to happen. I'm not surprised by 8% of one core being used. Is that reasonable @joschisan?

**Comment by joschisan** [comment]
Sounds reasonable to me. Every peer creates 20 signatures per seconds and verifies 20 for every of its peers.
