### ISSUE TITLE
Add repository link to `Cargo.toml`s

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3725]

**Comment by t-a-m-e** [comment]
Can someone add more context to this issue? 
Line 56 of Cargo.toml is as follows:
repository = "https://github.com/fedimint/fedimint"

Has the issue not already been solved, or am I missing something?

**Comment by elsirion** [comment]
I think it's needed in every `Cargo.toml`, e.g. `fedimintd` doesn't have a homepage/repo set: https://crates.io/crates/fedimintd

**Comment by t-a-m-e** [comment]
Am I too new to rust to understand this? It'd be helpful if you'd break it down to someone who thinks this project is cool conceptually, but has no experience with it.

**Comment by justinmoon** [comment]
> Am I too new to rust to understand this? It'd be helpful if you'd break it down to someone who thinks this project is cool conceptually, but has no experience with it.

@elsirion Described it pretty accurately. If you're new to Rust, I would encourage reading the [Rust book](https://doc.rust-lang.org/book/) to get a handle on the basics before attempting to contribute to a complex project like Fedimint. This book is probably how most of us got started with Rust 👍.
