### ISSUE TITLE
test to ensure that we all out json-serialization is snake-case

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3736]
A way to handle https://github.com/fedimint/fedimint/issues/3332 going forward. Can we tell serde to do this as a global default? Perhaps a semgrep rule? JSON schema?

**Comment by justinmoon** [comment]
Was looking around to see if there was a way to have serde do snake_case by default on enums and [doesn't look like it's available](https://www.reddit.com/r/learnrust/comments/ynpxnq/is_there_a_way_to_make_serde_generate_camelcase/).

**Comment by dpc** [comment]
No one has any ideas and this just rots in a backlog. Closing.
