### ISSUE TITLE
remove fedimint-ldk-node

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3738]
revert https://github.com/fedimint/fedimint/pull/3719 once new ldk-node version is released

**Comment by TonyGiorgio** [comment]
New version has been released: https://github.com/lightningdevkit/ldk-node/releases/tag/v0.2.0

**Comment by m1sterc001guy** [comment]
Tried to fix this for a bit today. Ran into some issues with the `std` vs `no-std` versions of the `lightning` crate. [LDK Node requires the `std` version](https://github.com/lightningdevkit/ldk-node/blob/main/Cargo.toml) but I believe that might break some of our wasm compatability.

**Comment by justinmoon** [comment]
> Tried to fix this for a bit today. Ran into some issues with the `std` vs `no-std` versions of the `lightning` crate. [LDK Node requires the `std` version](https://github.com/lightningdevkit/ldk-node/blob/main/Cargo.toml) but I believe that might break some of our wasm compatability.

AFAIK ldk-node doesnt run in WASM. It's just a fixture when running rust tests on developer machines and CI.

**Comment by m1sterc001guy** [comment]
Two things are making this difficult currently:

1) LDK Node needs `std` feature of `lightning`. As @justinmoon mentioned this might not be a problem for Fedimint currently, but if others build a WASM client and need `fedimint-ln-common` as a dependency, this might cause problems.
2) LDK Node uses the `rust-tls` feature of `reqwest`, which brings openssl as a dependency, which we have forbidden from the codebase :/

**Comment by m1sterc001guy** [comment]
> Can you not add it just as a dev-dependency instead of one that would be pulled in for others using fedimint-ln-common as a library?

Hmm unless I'm misunderstanding, I don't think this works. `fedimint-ln-common` needs to depend on the `lightning` crate

**Comment by m1sterc001guy** [comment]
LDK dependency has been removed and is going to be re-added in https://github.com/fedimint/fedimint/pull/4338. Going to close this.
