### ISSUE TITLE
Keep nix versioning in lockstep with cargo versioning

### ISSUE THREAD

**Issue by shaurya947** [fedimint/fedimint#3739]
Are we able to make it so that if other projects are pulling in inputs/outputs from `fedimint`'s flake, then the version of those inputs/outputs/packages shows up correctly? Currently it's always 0.1.0 even if, as shown in the example below, the flake actually points to fedimint 0.2. 
![Screenshot from 2023-11-24 17-51-14](https://github.com/fedimint/fedimint/assets/3454081/73f4252d-0df4-4a47-80d6-96181478499a)

**Comment by dpc** [comment]
https://github.com/fedimint/fedimint/blob/681e6cc262ef40a3a58cbb84b08cc191816a96ef/nix/flakebox.nix#L186

**Comment by dpc** [comment]
There should be a way to make Nix derivations read the version from designated Cargo.toml, but it is a bit complicated because things span across packages/workspace, so I'm not sure if it's worth it.

**Comment by shaurya947** [comment]
I'll just manually update it for now unless you have an objection 
> https://github.com/fedimint/fedimint/blob/681e6cc262ef40a3a58cbb84b08cc191816a96ef/nix/flakebox.nix#L186

**Comment by dpc** [comment]
@shaurya947 :+1:

**Comment by dpc** [comment]
I believe this has been fixed. Please reopen if not.
