### ISSUE TITLE
fedimint-client Builder is error-prone

### ISSUE THREAD

**Issue by shaurya947** [fedimint/fedimint#3748]
When attempting to add a [new function to read the federation ID](https://github.com/fedimint/fedimint/pull/3740/commits/d75e919069dea94493c2e2ac78e4174b40d624b0#diff-5c9c1d41afb86eeab67b808b3e245347ee5d1ae1e313ce358dc3c76e208fcb82R1497) from the client builder, CI tests failed because `get_config` seems to write the config to the DB. So when `get_config` is called again as part of `ClientBuilder::build()` it panicks since it wasn't expecting both a `FederationInfo` and a config stored in the DB.

`ClientBuilder` having an optional config as well as an optional db source feels quite ambiguous. Is there an invariant that must be satisfied? Must one of them be defined? Must the db source be `Reuse` is the FederationInfo is not there? Also why is the FederationInfo called `config`?

Discussed a bit with DPC and we might want to rethink this from a first principles approach.

**Comment by justinmoon** [comment]
dev call: this should be more atomic in 1 db transaction
