### ISSUE TITLE
Fix nightly clippy lints

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#378]
I had to silent one new lint in https://github.com/fedimint/fedimint/pull/377/files .

It looks like it will affect quite a few tests, so better to get consensus on it before doing the workk

**Comment by elsirion** [comment]
I don't have a strong opinion on it either way, but getting rid of `#[allow(…)]` might be worth complying with clippy here.

**Comment by dpc** [comment]
We're not using nightly RN, and who knows if this lint even hits stable, so closing for now.
