### ISSUE TITLE
Easy to mis-type RPC requests

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3805]
It's very easy to write RPC request code that compiles but doesn't work because server-side and client-side use different payload. 

For example, when Fedimint removed x-only pubkeys I tried to update a 3rd party module and forgot one place. The code compiled, but didn't work. Here's a diff of the fix to give you a better idea. Server was using traditional pubkey, client was using x-only pubkey. Ideally this wouldn't compile. Not sure if this is possible or not, but it felt like I was writing Python for a minute there!
<img width="1297" alt="image" src="https://github.com/fedimint/fedimint/assets/4335621/49ec7add-b409-42f8-9bd2-80311ad0ac3c">

**Comment by elsirion** [comment]
Short of building/using a framework that auto-generates both client and server side there's little Fedimint can do besides documenting best practices. That would be part of  #3807.
