### ISSUE TITLE
Gateway Failed to establish htlc stream (v0.2rc2)

### ISSUE THREAD

**Issue by TonyGiorgio** [fedimint/fedimint#3806]
Running through the mutinynet-tls script that sets up all of the docker containers, I'm running into an issue on first launch. This happened to me consistently 3 times in a row on v0.2

```
docker-gatewayd-1               | 2023-11-30T17:39:31.472216Z  INFO ln_gateway::lnd: Gateway configured to connect to LND LnRpcClient at 
docker-gatewayd-1               |  address: https://lnd:10009/,
docker-gatewayd-1               |  tls cert path: /lnd_data/tls.cert,
docker-gatewayd-1               |  macaroon path: /lnd_data/data/chain/bitcoin/signet/admin.macaroon 
docker-gatewayd-1               | 2023-11-30T17:39:31.477478Z  INFO ln_gateway::lnd: Gateway configured to connect to LND LnRpcClient at 
docker-gatewayd-1               |  address: https://lnd:10009/,
docker-gatewayd-1               |  tls cert path: /lnd_data/tls.cert,
docker-gatewayd-1               |  macaroon path: /lnd_data/data/chain/bitcoin/signet/admin.macaroon 
docker-gatewayd-1               | 2023-11-30T17:39:31.477497Z  INFO ln_gateway: Established HTLC stream
docker-lnd-1                    | 2023-11-30 17:39:31.478 [ERR] RPCS: [/routerrpc.Router/HtlcInterceptor]: interceptor already exists
docker-gatewayd-1               | 2023-11-30T17:39:31.479172Z ERROR ln_gateway::lnd: Failed to establish htlc stream
docker-gatewayd-1               | 2023-11-30T17:39:31.525121Z  INFO ln_gateway: Successfully loaded Gateway clients.
docker-gatewayd-1               | 2023-11-30T17:39:31.525139Z  INFO ln_gateway: Got None while handling HTLC stream, exiting from loop...
docker-gatewayd-1               | 2023-11-30T17:39:31.525144Z  WARN ln_gateway: HTLC Stream Lightning connection broken. Gateway is disconnected
docker-gatewayd-1               | 2023-11-30T17:39:31.525151Z  INFO task: Waiting for task to finish task=LND HTLC Subscription
docker-gatewayd-1               | 2023-11-30T17:39:31.525158Z  INFO task: Task finished task=LND HTLC Subscription
docker-gatewayd-1               | 2023-11-30T17:39:31.525161Z  INFO task: Waiting for task to finish task=register clients
docker-gatewayd-1               | 2023-11-30T17:39:31.525178Z  INFO ln_gateway: register clients task received shutdown signal
docker-gatewayd-1               | 2023-11-30T17:39:31.525190Z  INFO task: Task finished task=register clients
docker-gatewayd-1               | 2023-11-30T17:39:31.525195Z ERROR ln_gateway: Disconnected from Lightning Node. Waiting 5 seconds and trying again
```

The logs starts pretty recently after the docker containers start up for the first time and then repeat every 5 seconds. The gateway-ui fails to add a federation because it thinks it is not connected to LND (something like that appeared in my network responses).

Running `docker compose restart` fixes it though. The logs indicate there's something already subscribed to LND, which would cause a 2nd subscriber to fail. So possibly a runaway thread would be my guess. I'm not sure how early it is trying to connect to LND, it might not be ready. 

Similar to this, though I was running on v0.1.4 this week and didn't run into the problem: https://github.com/fedimint/fedimint/issues/3397

**Comment by justinmoon** [comment]
Yea those logs make it seems like gateway is trying to subscribe twice?

**Comment by TonyGiorgio** [comment]
> Yea those logs make it seems like gateway is trying to subscribe twice?

I think so too. I don't have the logs anymore from the initial run. But for whatever reason it doesn't think it subscribed successfully the first time.

**Comment by TonyGiorgio** [comment]
I don't have anything else on this server and no other docker containers running. Though there's potential one remained from a previous fedimint install but it's not on there now and I've been using "docker compose down" on them before starting a new one.

**Comment by douglaz** [comment]
I was able to reproduce this on v0.2.0-rc4
