### ISSUE TITLE
Getting some errors while commiting changes

### ISSUE THREAD

**Issue by 15IITian** [fedimint/fedimint#3829]
After setting up the  local environment , when I try to commit the changes -> getting some errors though the changes are successfully committed as shown ->
 
![image](https://github.com/fedimint/fedimint/assets/133089376/d45ec979-54de-450b-9101-e2de55d4088b)

System -> Linux
Please solve this issue.

**Comment by elsirion** [comment]
The output is just annoying, not a show stopper. IF you want to fix your system, please take a look at https://www.cyberciti.biz/faq/perl-warning-setting-locale-failed-in-debian-ubuntu/

**Comment by douglaz** [comment]
Warnings are not errors
