### ISSUE TITLE
`fedimint-cli spend` should have a flag to give exact change or error if it can't

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3834]
Currently `fedimint-cli spend <amount>` will give us `<amount>` if it has those notes on hand, and give more than we ask for if it doesn't.

I was just writing a test and this behavior caused my test to be flaky. It would be nice for this reason (and probably in general) to be able to request exact amounts from `fedimint-cli spend`.

**Comment by elsirion** [comment]
That should be the default behavior.
