### ISSUE TITLE
`pay_bolt11_invoice` can make 2 calls to `fetch_registered_gateways` when paying invoice

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3842]
This is an excessive amount of network requests which will slow down the UX (`select_active_gateways` can call `fetch_registered_gateways`)

https://github.com/fedimint/fedimint/blob/af69ced9118ee9a997f9ea444edb0a6b5e6beb07/modules/fedimint-ln-client/src/lib.rs#L825

https://github.com/fedimint/fedimint/blob/af69ced9118ee9a997f9ea444edb0a6b5e6beb07/modules/fedimint-ln-client/src/lib.rs#L1066

**Comment by kernelkind** [comment]
Is this still relevant? the `select_active_gateway` method was removed from `pay_bolt11_invoice` in 12d572f

**Comment by justinmoon** [comment]
https://github.com/fedimint/fedimint/pull/4427 will remove the "active gateway" concept altogether and I updated https://github.com/fedimint/fedimint/issues/3844 to track only this change. Closing.

**Comment by elsirion** [comment]
I think we still need a gateway cache. @m1sterc001guy mentioned that in #4427, so it may be fixed once that PR is merged, but this issue should stay open till then imo.

**Comment by elsirion** [comment]
I read the description again and in fact this issue was only about calling that fn twice, while I assumed it was for caching.

**Comment by m1sterc001guy** [comment]
I'm going to change this in https://github.com/fedimint/fedimint/pull/4427.

I believe we need a gateway cache, but we should be more explicit about which commands require network calls to the federation and which don't, then let integrating clients decide what is best. 

We have a tracking issue https://github.com/fedimint/fedimint/issues/3844, this can stay closed.
