### ISSUE TITLE
Remove "active gateway" concept

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3844]
### Update (March 1)

We decided to remove the "active gateway" concept so edited the title

### Old issue description

In the past, the client would try to cache one of the "gateway registration" locally and always try to use that gateway. Now it doesn't (what I was observing in https://github.com/fedimint/fedimint/issues/3479, which I'm closing and broadening the discussion here).

A benefit of this approach was that we didn't have to do a bunch of network requests to the federation while paying a lightning payment (https://github.com/fedimint/fedimint/issues/3842). It also provided a (somewhat primitive) hook for client consumers to choose which gateway the client would use.

Right now on `master` the `fedimint-cli list-gateways` doesn't even return an active gateway in mprocs:

```
$ just mprocs
$ fedimint-cli list-gateways
[
  {
    ...
    "active": false
  },
  {
    ..
    "active": false
  }
]
```

`fedimint-cli ln-pay ...` still [makes a call to select_active_gateway](https://github.com/fedimint/fedimint/blob/af69ced9118ee9a997f9ea444edb0a6b5e6beb07/fedimint-cli/src/client.rs#L242). This used to hydrate the  "active gateway cache" mentioned in the first paragraph, but now it accomplishes nothing because it doesn't write to the active gateway key so now `fedimint-cli ln-pay` makes 3 requests to fetch list of gateway (this one plus the two mentioned in https://github.com/fedimint/fedimint/issues/3842). That's 12 total websocket requests in a 3/4 federation because `list_gateways` employs the `UnionResponses` strategy.

Lastly, right now it's unclear which gateway will be used when paying or receiving lightning payment. As a result, it's unclear how a `fedimint-client` consumer should display fees that will be charged for the payment. It is possible, however, by calling `set_active_gateway`. A current downside of this is that `set_active_gateway` calls `fetch_registered_gateways` so consumers will be doing a lot of network requests just to make sure this registration is up-to-date. What happens if the registration stored in `LightningGatewayKey` get out-of-date? The `LightningGateway` struct that is stored in this key doesn't contain any registration information so I'm not even sure to tell whether it is expired or not?

To summarize:
* "active gateway" doesn't have consistent behavior
* Way too many network requests. 
  * If we want to check whether a gateway is still there, a request to the gateway itself requires less bandwidth and likely less latency than a request to the federation.
* Can be unclear which gateway will be used by client. Any random selection of a gateway inside `fedimint-ln-client` internal business logic makes it impossible to know for certain what fees will be paid, so it should be avoided.
* Unclear what happens if `LightningGatewayKey` contains expired registration.

In terms of solutions, 
* Get rid of "active gateway". The relevant public functions for `fedimint-ln-client` require consumers to pass in a gateway.
* Keep "active gateway" but ensure it's always set to the degree that's possible, minimize the number of network requests we're making, make sure it doesn't change while paying or generating invoices so consumers can present fee information, and clearly document what is expected from consumers of `fedimint-client`
* A third, better thing?

**Comment by justinmoon** [comment]
Related to https://github.com/fedimint/fedimint/discussions/2392, but I was thinking more near-term with this one.

**Comment by elsirion** [comment]
`pay_bolt11_invoice` should take an gateway as argument.

**Comment by justinmoon** [comment]
> `pay_bolt11_invoice` should take a gateway as argument.

Then we could have another method to `choose_viable_gateway` which could be used by `fedimint-client` consumers to display expected fee when paying invoices.

**Comment by justinmoon** [comment]
@elsirion @okjodom @m1sterc001guy @douglaz Should we just just remove "active gateway" altogether?

I think `fedimint-ln-client` consumers could just pass in the gateway they want to use to all top-level `fedimint-ln-client`. Then apps can get exactly they are supposed to get from "active gatway", but it will work better for reasons described above.

**Comment by m1sterc001guy** [comment]
I think we should remove the concept of an active gateway. In debugging this [flaky test](https://github.com/fedimint/fedimint/issues/4350#issue-2139759549) I noticed that since active gateways are always cached, we won't ever query for updates to the gateway. So if anything has changed, like the API endpoint or fees, the client is responsible for calling `fetch_registered_gateways` and call `set_active_gateway` again if they want the updated data.

I think we mostly did this as a performance optimization. Maybe we should just remove it entirely and always require a gateway to be explicitly passed in. If clients want to do their own caching, they can implement it themselves.

**Comment by justinmoon** [comment]
@m1sterc001guy Agreed. Let's do it!
