### ISSUE TITLE
`BYTE_LIMIT` limits number of e-cash notes per transaction

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3868]
After #3671 spending one e-cash note consumes approximately 156bytes (~92b input + 64b input signature) of transaction space. At the same time our instantiation of AlephBFT limits transactions to less than 10kb, which means even in the best case we cannot have more than 64 e-cash inputs, which severely limits the range of amounts we can encode with full precision.

As a quick fix #3867 increases said limit to 50kb, allowing us to include over 300 e-cash notes, exponentially increasing the range of amounts we can represent at full precision, making the limit a non-issue at the cost of a higher worst-case memory consumption.

Longer term we should reduce that limit again and make the client more intelligent to deal with such cases.

**Comment by joschisan** [comment]
Makes sense. Changing the byte limit requires a coordinated upgrade of guardians in a running federation.

**Comment by elsirion** [comment]
Well, or at least nobody sending oversized tx during the update :P
