### ISSUE TITLE
Gateway will timeout if someone tries to pay an invoice twice

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#3876]
If the gateway has already received a payment for an invoice, the second time someone pays it it will timeout on the LN wallet side and this is also appear on the gateway logs:
```
INFO ln_gateway: Got error intercepting HTLC: Timed out fetching the offer, will retry...
```

**Comment by elsirion** [comment]
If there is no offer we should just immediately return an unknown payment details error. This is likely the cause of #3826.

**Comment by dpc** [comment]
@m1sterc001guy Is this still the case?

**Comment by m1sterc001guy** [comment]
I believe so, but with LNv2 about to ship, I don't think its worth spending the time to fix (LNv2 does not have offers).
