### ISSUE TITLE
Gateway API versioning

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3904]
Add a gateway API version and make gateway clients aware of it. Would help with issue created when server is running https://github.com/fedimint/fedimint/pull/3847 but client is on older version.

**Comment by bradleystachurski** [comment]
Is this sufficient?

https://github.com/fedimint/fedimint/blob/07a91304f6f4bc5ec0bd9de3d98ba2afe4d8705c/gateway/ln-gateway/src/state_machine/mod.rs#L142
