### ISSUE TITLE
gatewayd can fail to connect to LND if `tls.cert` contains multiple certificates

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3915]
Described the issue in more detail [here](https://github.com/fedimint/tonic_lnd/issues/12)

**Comment by justinmoon** [comment]
[fedimint_tonic_lnd is updated](https://github.com/fedimint/tonic_lnd/issues/12). Now we just need update our dependency.

**Comment by elsirion** [comment]
We haven't published an update yet, preparing that with fedimint/tonic_lnd#19.

**Comment by elsirion** [comment]
Just published v0.2.0 to speed things up.

**Comment by elsirion** [comment]
Opened a PR to upgrade #4031
