### ISSUE TITLE
Add license and README link to each `Cargo.toml`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3924]
The workspace-wide one doesn't seem to make it into the released crates:

![Screenshot 2023-12-12 at 17-47-31 fedimint-aead - crates io Rust Package Registry](https://github.com/fedimint/fedimint/assets/84478054/0d749ded-4b5c-4003-9243-5d64055d76cd)

**Comment by elsirion** [comment]
Need to check if relative paths outside the crate but inside the workspace work.

**Comment by tvolk131** [comment]
Anything else that needs to be done for this? Looks complete.
