### ISSUE TITLE
When gateway leaves a federation, we should ensure they have no funds remaining

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3935]
https://github.com/fedimint/fedimint/pull/3636 makes no such checks

**Comment by kernelkind** [comment]
> Another idea: what happens if gateway only has dust? I think we should still be able to leave, otherwise they'd need to deposit and withdraw to get back to zero balance?

In this situation, the gateway would run the command `gateway-cli leave-fed --federation_id X --forced`

**Comment by m1sterc001guy** [comment]
I don't think this is relevant anymore, it is useful to be able to leave a federation with funds still pegged into the federation, then re-join, to force a re-registration. Closing.
