### ISSUE TITLE
Update docker description

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3945]
Is that warning still relevant for Fedimint docker containers? I'd say it's incorrect for Fedimint itself, do we have any less confidence in the dockerized version? @Kodylow, @EthnTuttle, @dpc 

![Screenshot 2023-12-14 at 14-11-27 fedimint_fedimintd Tags Docker Hub](https://github.com/fedimint/fedimint/assets/84478054/c23cb3cf-f3e6-4a5a-b995-70861b0b11e7)

**Comment by Kodylow** [comment]
No I think we should remove it. We need to go through all our warnings across docs, docker, cargo, etc and get common language for what we want the warnings on 0.2 ro be

**Comment by elsirion** [comment]
@justinmoon is this something you have to change as admin? At least I couldn't find this string in our repo.

**Comment by dpc** [comment]
@justinmoon I think you have the powers. (BTW. Maybe you should share access with Eric for redundancy).

**Comment by justinmoon** [comment]
Removed that warning https://hub.docker.com/repository/docker/fedimint/fedimintd/general 
<img width="467" alt="image" src="https://github.com/fedimint/fedimint/assets/4335621/1a8f2c66-1e8b-4e43-85e2-04aa4708408e">
