### ISSUE TITLE
Docker deployment script seems stuck on Waiting for fedimintd to be ready. Don't do anything yet...

### ISSUE THREAD

**Issue by otech47** [fedimint/fedimint#3954]
I used the tls-download-mutinynet deployment script on a digital ocean droplet everything goes perfectly smoothly except it seems to get stuck on `Waiting for fedimintd to be ready. Don't do anything yet...` and stayed there even after i waited ~30+ mins

but everything seems to be up and running just fine and i can complete guardian setup and the deployment seems totally successful

![Screenshot 2023-12-15 at 9 41 30 AM](https://github.com/fedimint/fedimint/assets/4914611/69b9543d-1785-4d64-a003-c22d84644a35)
![Screenshot 2023-12-15 at 9 42 35 AM](https://github.com/fedimint/fedimint/assets/4914611/af3ca174-2cee-49f4-b99b-0761bca24fb3)

so maybe this is just a minor bug in the deployment script waiting logic...

Note I used a slight variant of the script pointing to the new v0.2 docker images: https://github.com/setlife-network/fedimint/blob/releases/v0.2/docker/tls-download-mutinynet.sh

**Comment by otech47** [comment]
@douglaz @Kodylow

**Comment by Kodylow** [comment]
Is this running off 0.2 for everything?

**Comment by Kodylow** [comment]
Sorry my b wrong button

**Comment by otech47** [comment]
> Is this running off 0.2 for everything?

Yeah should be I updated the docker compose on that fork
https://github.com/setlife-network/fedimint/commit/72ab49b943199fc889dfacb10d7ba241d5a65f2a

**Comment by dpc** [comment]
@Kodylow I bet this is done already, so closing. Please re-open (anyone) if its still a problem.
