### ISSUE TITLE
Gateway can charge separate fee rates on different federations

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3961]
The fee charged by a gateway reflects the custodial risk the gateway operator associates with holding ecash at a given mint. Given that this risk can be very different with different mints, `gatewayd` should have a way to charge different fees for different federations.

**Comment by elsirion** [comment]
Generally how to set configuration requires an overhaul (changing the fee rate for a already-connected federation is quite broken), that's a prerequisite for fixing this issue imo.

**Comment by fparisotto** [comment]
I'll like to fix this issue, I'm building a [PR (draft for now)](https://github.com/fedimint/fedimint/pull/4679), but still missing tests (I'll add than in my next commits).
I'm 100% sure if I'm on the right track, any help is more than welcome

**Comment by m1sterc001guy** [comment]
I left some feedback, thanks for tackling it! Let me know if you have any questions

**Comment by justinmoon** [comment]
Can we close @m1sterc001guy ?

**Comment by elsirion** [comment]
Closing since the PR got merged.
