### ISSUE TITLE
Devimint backwards-compatibility tests

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#3962]
We're gonna need perhaps a devimint feature where you can replace the client or the server or any component with a different version (older or newer) then run all the tests and see if they pass.

_Originally posted by @douglaz in https://github.com/fedimint/fedimint/discussions/3950#discussioncomment-7866528_

**Comment by bradleystachurski** [comment]
Might be useful to reference bitcoin core's approach for backwards compatibility tests.

https://github.com/bitcoin/bitcoin/blob/3695ecbf680a66b718f97d504308578d001eec49/test/functional/wallet_backwards_compatibility.py

**Comment by bradleystachurski** [comment]
> run all the tests and see if they pass

What does "all" tests mean in this context? Is this all devimint tests or everything run by `just test-ci-all`? If this includes all the backend tests, we'll also need to consider how we'll use dynamic versions for clients and servers in `modules/fedimint-*-tests` instead of just devimint.

**Comment by bradleystachurski** [comment]
I haven't fully considered the implications, but one potential approach if we need to introduce clients/servers with previous versions is to reference the git tag.

```
fedimint-client-old = { git = "https://github.com/fedimint/fedimint", tag = "v0.2.0", package = "fedimint-client" }
```

This is hacky and doesn't scale well if we need to test against multiple versions, so there's likely a better solution.

**Comment by elsirion** [comment]
I think devimint should be able to instantiate different versions of federations. The binaries (`fedimintd`, `fedimint-cli`, …) should come from nix imo since then we can use caching more effectively. @dpc probably knows best how to do this.

**Comment by bradleystachurski** [comment]
Now that the initial approach in CI is merged and all broken tests are resolved, are we comfortable closing? I think we can track future improvements in separate issues.

cc: @elsirion @dpc
