### ISSUE TITLE
We are running integration tests twice

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#397]
https://github.com/fedimint/fedimint/pull/383#issuecomment-1218138538

**Comment by NicolaLS** [comment]
this also has the side-effect that CI will fail sometimes like [here](https://github.com/fedimint/fedimint/runs/7881960910?check_suite_focus=true). Because we get two `LnGateway` (and possibly others) that want to bind to the same port

**Comment by dpc** [comment]
@NicolaLS I don't understand. We run each instance of intregration test in a different job, so they should run in different containers and not conflict with each other.

**Comment by NicolaLS** [comment]
> @NicolaLS I don't understand. We run each instance of intregration test in a different job, so they should run in different containers and not conflict with each other.

Oh ok didn't knew that. Then this can't be the reason

**Comment by elsirion** [comment]
I think the problem is that coverage tests are run in parallel right now and that includes the rust in-process integration tests that don't support this. I think that's what @NicolaLS means (had a private chat earlier).

**Comment by dpc** [comment]
Oh. We need to add `--threads 1` somewhere?

**Comment by dpc** [comment]
How hard would it be to tweak the tests to run OK in parallel? Seems a bit of a waste. We could start things on test-specific ports so they don't conflict, etc.

**Comment by justinmoon** [comment]
> How hard would it be to tweak the tests to run OK in parallel? 

It might be pretty straightforward for our current tests because all the tests could probably share `bitcoind` and `lightningd` instances. I think we could get away with just having the fixtures generate random ports and retry if there's a collision. Someday individual tests may want to spawn their own bitcoind / lightningd but that might not be necessary yet ...

I try this tomorrow (if nobody tries before then)

**Comment by NicolaLS** [comment]
> I think the problem is that coverage tests are run in parallel right now and that includes the rust in-process integration tests that don't support this. I think that's what @NicolaLS means (had a private chat earlier).

(I actually thought it was because of the parallel jobs, not being aware that they're run in different containers), but yes the parallelism in the integration tests also led to problems on my machine.

**Comment by NicolaLS** [comment]
> 

for this you'll have to make the ln-gateway port configurable so it will also be a step toward #304 
imo. you can then just ask for `port 0` in the tests and if it still fails for some reason try to handle that by just waiting.
