### ISSUE TITLE
Federation might panic on '/transaction' request

### ISSUE THREAD

**Issue by NicolaLS** [fedimint/fedimint#398]
Right now the `/transaction` endpoint panics if:
- parsing the parameter fails 
- and for **any**  `TransactionSubmissionError` returned by [submit_transaction](https://github.com/fedimint/fedimint/blob/f574584e11dd81bec0b3443eaba3e92ce7314f8c/minimint/src/consensus/mod.rs#L105)

We should also investigate how interacting with the federation can lead to it crashing which should never happen. Things like that would get caught by #287 

Noticed it because I tried to peg-in and the federations wallet module was not aware of the block which I supplied in the `PegInProof` leading to a `InputPegIn(UnknownPegInProofBlock()` error. 
here the [logs](https://gist.github.com/NicolaLS/83c6d97b32819052e327a91ecc90939e).

**Comment by elsirion** [comment]
This is an oversight that happened when migrating from the HTTP API to websockets. The old server code would catch panics and return internal server errors while the current server code doesn't. I think this calls for two actions:

* Double-check all API endpoints for expects/unwraps/out-of-bounds access to prevent panics
* Build our own panic-catching wrapper just in case

**Comment by elsirion** [comment]
> Build our own panic-catching wrapper just in case

I'm working on that right now btw.

**Comment by elsirion** [comment]
Fixed in #399
