### ISSUE TITLE
Devimint supports multiple feds with shared daemons

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#3985]
We might want to run dev federations while sharing daemons like bitcoind, electrs, esplora, lightning nodes and gateways. This would be useful in a scenario like #3696

**Comment by justinmoon** [comment]
Related to https://github.com/fedimint/fedimint/issues/3209

**Comment by elsirion** [comment]
@m1sterc001guy didn't you implement this recently?

**Comment by m1sterc001guy** [comment]
Ah yes I did! Can be closed.
