### ISSUE TITLE
Deadlock somewhere on the database layer on Fedimint

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#3996]
PR that reproduces the problem: https://github.com/fedimint/fedimint/pull/3995
(originally it was reproduced by https://github.com/fedimint/fedimint/pull/3989)

Initially I thought it was related to https://github.com/fedimint/fedimint/issues/3988 but it seems to be a very different issue.

**Comment by elsirion** [comment]
@maan2003 is this still an issue? You worked on many related things recently.
