### ISSUE TITLE
Re-register gateway after updating the configuration

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#4013]
As @TonyGiorgio pointed out [here](https://github.com/fedimint/fedimint/issues/3990#issuecomment-1868214852), when updating a gateway's routing fees, the operator either needs to wait for ~10 minutes for the gateway to re-register, or leave the federation and re-join for it to show up immediately. This is a bad experience and unnecessary, config changes should just trigger re-registration with all of the connected federations.

**Comment by elsirion** [comment]
I'm not even sure if it's *only* a problem with registration. Last time I changed fee levels re-registering didn't help because the global config that can be changed via the CLI or env variables is duplicated into the per-federation client config, re-joining helped. I think the way we handle malleable gateway config has to change fundamentally.

**Comment by m1sterc001guy** [comment]
> Last time I changed fee levels re-registering didn't help because the global config that can be changed via the CLI or env variables is duplicated into the per-federation client config

Good catch, this is just a bug imo, leftover from before we had a database for the gateway. Gateway fees are a gateway-level setting, there shouldn't be any need to replicate it into each individual client db.

I think the fix is pretty easy, unfortunately it will require a database migration (currently working on this) if we want to remove it from the client databases. 

> I think the way we handle malleable gateway config has to change fundamentally

Let me know if you have additional thoughts on this. My intention with the original design was to have a simple API that stored gateway-level configs in the gateway's db, which could just be re-read at runtime. It wasn't intended for per-federation client level configs.

**Comment by elsirion** [comment]
I think long-term we will want some per-federation config options because gateway operators may charge higher fees for less-active or higher-risk federations.

**Comment by m1sterc001guy** [comment]
Sure, I think we can still support that inside `gatewayd`'s database. I don't think those kind of settings need to be replicated into each individual client's db.
