### ISSUE TITLE
`devimint_cli_test_single` fails backwards-compatibility test

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#4017]
https://github.com/fedimint/fedimint/actions/runs/7434410505/job/20228534969?pr=4010#step:11:2879

```
00:00:17 thread 'main' panicked at devimint/src/main.rs:459:9:
00:00:17 assertion failed: descriptor.contains(\"wpkh(\")
```

**Comment by elsirion** [comment]
This might be something we want to adapt in the test suite since only the test is backwards incompatible, not the code. See https://github.com/fedimint/fedimint/pull/3821.
