### ISSUE TITLE
LN: can reach pending refund state if payment succeeded

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4021]
Under really bad network conditions the LN client can go into the refund pending state even though the gateway will successfully route the payment.

We should probably use the federation as ultimate source of truth and only use direct gateway communication to speed up the success message if we get the preimage from there before the gateway claims the outgoing contract.

**Comment by m1sterc001guy** [comment]
This PR should help address this https://github.com/fedimint/fedimint/pull/4024

**Comment by m1sterc001guy** [comment]
Fixed with https://github.com/fedimint/fedimint/pull/4024
