### ISSUE TITLE
`LeaveFederation` gateway RPC should optimistically try to de-register itself from the federation

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#4027]
Rather than just rely on the TTL of a registered gateway with a federation, if the gateway operator explicitly calls `LeaveFederation`, we should try to contact the federation to remove the registration record.

**Comment by elsirion** [comment]
Deregistering should also be triggered on shutdown if the gateway is shutdown cooperatively using SIGINT. Idk what we use in other places rn, but a quick search showed [`tokio-shutdown`](https://docs.rs/tokio-shutdown/latest/tokio_shutdown/), which should probably work.

**Comment by m1sterc001guy** [comment]
The API to remove the gateway's registrations needs to be authenticated, so a rogue user can't just make API requests to the federation and delete all of the gateway registrations. One way to do this is to require the gateway to send a signature that the federation can verify. Since the `gatewayd_id` is already a `PublicKey`, the gateway can sign with this key. The main issue IMO is figuring out what to sign. If the message being signed is deterministic, the same signature can be presented to the federation multiple times, which doesn't really solve anything.

One solution is to generate some random bytes for each gateway registration, then require the gateway to sign these if it wants to remove that registration record. This seems like the most doable solution, but unfortunately requires a database migration :/

**Comment by justinmoon** [comment]
It could be challenge:response. Hit the federation to ask for some message (could be random) and gateway signs it. This message isn't a consensus thing so I think this would work.
