### ISSUE TITLE
Waiting for recovery to finish needs to wait for the current block to end which is slow.

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4043]
The recovery code needs to pesimize and assume even the current epoch (at the time the recovery started) can contain important changes. Because of that it needs to wait for the current sessions/block to finish, which can take considerable time (couple minutes). This is clearly visible in tests (run with `env RUST_LOG=debug` to see it timing out and waiting for the last block).

This could be greatly improved if we had a call that would return the current items in the current block.

**Comment by dpc** [comment]
@elsirion @joschisan thoughts? Maybe I'm doing something wrong too. We could shave 2-3 minutes from cli tests in the CI if we addressed it.

**Comment by elsirion** [comment]
That's a know trade-off and should be improved using the kind of API endpoint you envision.
