### ISSUE TITLE
`UnitSaver::flush` is using wrong `block_on`?

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4054]
[While investigating something entirely different](https://github.com/fedimint/fedimint/pull/3995#issuecomment-1897513085) I've noticed that `UnitSaver::flush` is using `futures::executor::block_on` which I don't think is entirely right thing to do when running in tokio Runtime (and thus everything hanged when `tokio::task::yield_now` was added to the mix). Unfortunately these kinds of issues require at least 200 IQ points to solve so I could use some help. :D

**Comment by Maan2003** [comment]
maybe calling tokio block_on from inside tokio spawn_blocking

ref https://docs.rs/tokio/latest/tokio/task/fn.block_in_place.html

**Comment by Maan2003** [comment]
oh this explains why #3989 is failing, because it replaces sync mutex with async mutex, so an `.await` point

**Comment by Maan2003** [comment]
yep 28b036126d361325bd9c167b96b3ad9e7cae2a1c fixes CI for #3989

**Comment by douglaz** [comment]
> yep [28b0361](https://github.com/fedimint/fedimint/commit/28b036126d361325bd9c167b96b3ad9e7cae2a1c) fixes CI for #3989

have you tried that on https://github.com/fedimint/fedimint/pull/3995? it seems it doesn't fix the problem there

**Comment by dpc** [comment]
> yep https://github.com/fedimint/fedimint/commit/28b036126d361325bd9c167b96b3ad9e7cae2a1c fixes CI for https://github.com/fedimint/fedimint/pull/3989

This might be random, and generally the whole problem is only exposed by #3995, so  I would hope/expect the proper fix to #3995 (at least stop it from hanging alephbft tasks as I described). If it isn't ... something might still be wrong.

I need to find the caller alephbft code and check how exactly is it calling blocking `Write::flush` operations. I suspect if offloaded these to blocking thread, possibly via own `block_in_place` call. So we're now in a situation where alepbft offloaded already ,we are running on blocking threads and trying to async again ... which might required something special to work.

**Comment by Maan2003** [comment]
I assume tokio::runtime::Handle::block_on also runs other tokio tasks while blocked

**Comment by Maan2003** [comment]
and futures::executor::block_on is a simple loop
https://docs.rs/futures-executor/0.3.30/src/futures_executor/local_pool.rs.html#89-101

**Comment by Maan2003** [comment]
i will try changing upstream UnitSaver to async, it looks simple.

**Comment by Maan2003** [comment]
using `tokio::task::block_in_place` with `tokio::runtime::Handle::current().block_on(..)` still deadlocks

**Comment by Maan2003** [comment]
async unit writer and unit reader for alephbft  - https://github.com/Maan2003/AlephBFT/commit/57e0cfc404454866cc4f658369810a99cbb923b6

nix build env - https://github.com/Maan2003/AlephBFT/commit/55af52d8b880467497dea94e7c76c5869c379227

**Comment by douglaz** [comment]
> async unit writer and unit reader for alephbft - [Maan2003/AlephBFT@57e0cfc](https://github.com/Maan2003/AlephBFT/commit/57e0cfc404454866cc4f658369810a99cbb923b6)
> 
> nix build env - [Maan2003/AlephBFT@55af52d](https://github.com/Maan2003/AlephBFT/commit/55af52d8b880467497dea94e7c76c5869c379227)

nice! left a small comment there

**Comment by Maan2003** [comment]
9338d99cba fixes it on top of #3995

**Comment by dpc** [comment]
Oh, so did I read it right that the old alephbft implementation  was calling a blocking io trait without offloading it from the executor? That would explain why things were weird when attempting to fix it.

**Comment by Maan2003** [comment]
> Oh, so did I read it right that the old alephbft implementation was calling a blocking io trait without offloading it from the executor?

yes, too many function colors. makes my head spin
async(aleph-bft) => sync(UnitSaver::flush) => async(db transaction) => sync (rocksdb)

**Comment by douglaz** [comment]
> EDIT: looks like i broke reconnect test (federation restarts) 😨

Probably a flake. Triggered the job again

**Comment by Maan2003** [comment]
I already restarted job once, it might be a real bug. UnitReader is used during startup

**Comment by Maan2003** [comment]
yes, I didn't copy correctly https://github.com/fedimint/fedimint/pull/4073/commits/32f9e28d5e637bc75ff31ba5dbf231d800b0a42c

**Comment by joschisan** [comment]
> @joschisan there are two issues here:
> 
> * `aleph-bft` uses the [`std::io::Write`](https://doc.rust-lang.org/std/io/trait.Write.html) trait in a very weird way. The implemented semantics are out of spec imo (switching where you write to based on flush being called …).
> * Only having a sync function to do IO isn't ideal since a lot of io is implemented as async and mixing sync+async is generally a bad idea.
> 
> I think we should upstream fixes for this, which would likely take the form of a new async trait for their writer object (same for reader too I guess).

That's what I thought as well. Did not get around to do it yet though.

**Comment by Maan2003** [comment]
https://github.com/Cardinal-Cryptography/AlephBFT/pull/399

**Comment by justinmoon** [comment]
dev call: fork for now and use upstream if / when change is upstreamed

**Comment by elsirion** [comment]
[I forked AlephBFT into fedimint](https://github.com/fedimint/fedimint-alephbft), let's create a patched version of the version we are currently using and then publish it to crates.io.

**Comment by Maan2003** [comment]
https://github.com/fedimint/fedimint-alephbft/pull/1

**Comment by elsirion** [comment]
Just published [fedimint-aleph-bft](https://crates.io/crates/fedimint-aleph-bft), last step is to switch fedimint over to it.

**Comment by joschisan** [comment]
> Just published [fedimint-aleph-bft](https://crates.io/crates/fedimint-aleph-bft), last step is to switch fedimint over to it.

I can take care of that.

**Comment by Maan2003** [comment]
most changes are already done in https://github.com/fedimint/fedimint/pull/4073
