### ISSUE TITLE
Test how client handles federations charging fees

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4060]

**Comment by elsirion** [comment]
Each module defines fees in its consensus config. Charging the fees should work, it currently only leads to the federation becoming more and more over-funded, we don't have a way of doing anything with them yet.

The main problem is charging fees for e-cash, because coin selection becomes a lot harder. One idea by @joschisan to massively simplify this was to only charge for spending e-cash, not issuing, that way the amount of change generated doesn't change the fee. I think the client should work if we charged fees on the federation level for LN contracts and deposits/withdraws, but not e-cash.

**Comment by elsirion** [comment]
@joschisan did this, it fails for e-cash charging fees but is solvable, tracked in  #4387 now

**Comment by TonyGiorgio** [comment]
I'm curious, where is this done in?

**Comment by elsirion** [comment]
I should have phrased this better: I wanted to manually test what blows up if we charge fees, we know that now and what to fix, testing that the fixes work should be part of #4387 imo.
