### ISSUE TITLE
`ConsensusApi::session_count()` is extremely CPU-intensive

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#4066]
```
$ time RUST_LOG=error ./target/debug/fedimint-cli --data-dir mutinynet-05 dev session-count
{
  "count": 27245
}

real	0m12.442s
```

The federation invite code is `fed11qgqrgvnhwden5te0v9k8q6rp9ekh2arfdeukuet595cr2ttpd3jhq6rzve6zuer9wchxvetyd938gcewvdhk6tcqqysptkuvknc7erjgf4em3zfh90kffqf9srujn6q53d6r056e4apze5cw27h75` if you'd like to verify.

CPU usage spikes to 100% when this call is active.

This causes the `status` RPC, ecash backup, recovery and perhaps other things to be slower than they should since they exercise this.

We should backport a fix for this to `releases/0.2`.

**Comment by Maan2003** [comment]
maybe this is slow part
https://github.com/fedimint/fedimint/blob/9c36777c4a0f21742bc99c29c54c12d3f74a4e52/fedimint-core/src/db/mod.rs#L999-L1004

**Comment by elsirion** [comment]
> maybe this is slow part

It is, but scanning the log instead of having a lookup key will always have bad performance after a while. So the real bug is not having a separate entry that tracks the current session.

**Comment by justinmoon** [comment]
Can we get a backport?

**Comment by elsirion** [comment]
Backported in #4089
