### ISSUE TITLE
Fedimint Http Server Typescript Client

### ISSUE THREAD

**Issue by Kodylow** [fedimint/fedimint#4067]

**Comment by bprice6** [comment]
Blocked by multispend reqs

**Comment by elsirion** [comment]
@Kodylow Does this belong here?

I know you are working on a fedimint client with a HTTP API and it might make sense to do some planning here. But for anything more detailed I'd prefer this project to move into its own repo under the fedimint organization.

**Comment by Kodylow** [comment]
No sorry, this should be a separate repo, closing.
