### ISSUE TITLE
Implement metadata consensus module

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4087]
Instead of this dance with external metadata hosting, we could just implement a proper metadata consensus module (and corresponding UI).

Metadata module stores key value pairs. Any guardian can propose a key-value, if threshold number of guardians propose the same value for the same key, it becomes approved.

An empty value means that the guardian would like to delete the key-value entirely.

Guardians can propose changes at any time, but there should be a limit for number of outstanding changes (let's say 50), to prevent malicious behavior wasting guardian's storage. After that number new key-value proposals from given peer are ignored (or replace previous ones, just to reclaim to storage?).

Clients can request a list of approved key-value pairs. Their meaning is defined by the spec and clients are free to support whichever keys make sense.

The UI for the guardians would allow:

* show current list of approved key-values, with ability to vote to delete/change them
* show current list of proposed key-values with an ability to vote for the to approve them
* allow proposing entirely new key-values

The module itself seems trivial to implement - server side just tracks who voted for what, and maybe keep a list of approved key-values to allow quick response.

Client side asks for approved metadata with a current consensus strategy.

**Comment by justinmoon** [comment]
dev call: eric would rather implement this idea on global consensus level

**Comment by dpc** [comment]
Closing as dup of #2791
