### ISSUE TITLE
fedimint-cli: No config source present

### ISSUE THREAD

**Issue by TonyGiorgio** [fedimint/fedimint#4091]
I'm using docker-compose for a federation and I can't get any of the `fedimint-cli` commands to work. 

```
fedimint-cli --data-dir /data --password 'XXX' info     
2024-01-22T12:04:59.124575Z  INFO fedimint_cli::db_locked: Acquiring database lock
{
  "error": "CliError",
  "kind": "general_failure",
  "message": "failure",
  "raw_error": "{\n  \"error\": \"CliError\",\n  \"kind\": \"general_failure\",\n  \"message\": \"No config source present\",\n  \"raw_error\": \"No config source present\"\n}"
}
```

**Comment by justinmoon** [comment]
Did you call `join-federation` yet? That's what downloads the config.

**Comment by TonyGiorgio** [comment]
This is from the docker container `fedimint/fedimintd:v0.2.0` of a federation that is already live. I am running `fedimint-cli` from inside that container. Do I still have to call `join-federation` from inside the docker image that fedimintd is already running in? Or do I have to do it somewhere else?

**Comment by justinmoon** [comment]
dev call: unclear from user POV what fedimint-cli is used for and what datadir to point it to. in this case user expected to point it at server database.

**Comment by TonyGiorgio** [comment]
I was able to do this by creating a new directory, joining my federation and using the password. Ideally the docker container configures a fedimint-cli directory to start using it right off the bat.
