### ISSUE TITLE
Don't allow LN gateways to join with 0PPM

### ISSUE THREAD

**Issue by TonyGiorgio** [fedimint/fedimint#4093]
It doesn't appear that the current LN gateways with 0PPM will do anything since it can't route payments with a max fee of 0. Disallow this in some way or warn against this since it is not transparent about what the issues are with the gateway when trying to make payments. See my confusion on this previous issue: https://github.com/fedimint/fedimint/issues/3990

**Comment by okjodom** [comment]
I'm surprised gateways default to 0PPM when [global default fee](https://github.com/fedimint/fedimint/blob/bc384160febd44152eca93a5a04f6164bc7431b8/gateway/ln-gateway/src/lib.rs#L97) has 1000PPM, 0msat base fee. Investigating

**Comment by justinmoon** [comment]
dev call: @elsirion would be better to implement this filtering on client rather than server

**Comment by TonyGiorgio** [comment]
I've implemented this on my client.
