### ISSUE TITLE
observation: rust-bitcoin does not impl `Encodable` for `Vec<T>` because they prefer `Vec<u8>` specialization for perf. reasons.

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4111]
https://github.com/rust-bitcoin/rust-bitcoin/issues/2390

You can't have both `impl Decodable for Vec<T : Decodable>` and `impl Decoable for Vec<u8>`. Implementing `Vec<u8>` in terms of reading things byte by byte is kind of slow. Not having `Vec<T>` inconvenient...

Something tells me we actually don't use `Vec<u8>` very often, but maybe I'm wrong. Something to remember, maybe we could add some workarounds in places where this matters.

**Comment by Maan2003** [comment]
we can always replace `Vec<u8>` with a custom type `Bytes` if it is a big performance issue.

**Comment by dpc** [comment]
Need to see if https://github.com/rust-bitcoin/rust-bitcoin/issues/2390#issuecomment-1906713853 works.

**Comment by elsirion** [comment]
Wait, might that be the reason for our rather poor decode performance? :grimacing: It might not have been a problem at the beginning, we mostly avoided writing variable length byte strings, but now with a lot of TLV encoding it might actually become a problem.

**Comment by dpc** [comment]
Possibly.

**Comment by dpc** [comment]
https://github.com/fedimint/fedimint/pull/4145
