### ISSUE TITLE
Go back to `aleph-bft` v0.30

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4126]
In #4116 we upgraded AlephBFT from 0.30 to 0.33 without considering that when a session is still running it has persisted data in the database. Since they changed their on-disk format and we didn't want this fix to be a consensus upgrade we need to apply @Maan2003's patch on 0.30 instead and downgrade the version we depend on again.

In the future, when we intend to upgrade AlephBFT, this will mean we need to wait for the current session to end and probably bump the minor consensus version.

**Comment by Maan2003** [comment]
backport for aleph-bft https://github.com/Maan2003/AlephBFT/commits/backport-blocking-fixes-0.30/
