### ISSUE TITLE
Create DB backup when detecting `fedimintd` got upgraded

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4127]
If there is any bug we in the upgrade flow we want to avoid messing up the production DB. We may want to do this on *any* change since not all problems might be caused by DB migrations (e.g. #4126). We can clean up these backups after the federation has been running for a bit since rollbacks become too risky anyway once real transactions happened.

**Comment by m1sterc001guy** [comment]
I think with DB checkpoints implemented we can close this, it essentially is the same thing https://github.com/fedimint/fedimint/pull/5451
