### ISSUE TITLE
Rebuild DB state from local session log

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4156]
Currently, if the Fedimint DB is corrupted due to a bug or manual edits one can rebuild it by re-syncing using the session log of a peer. This is unnecessarily bandwidth and time consuming though since the on-disk log could be used instead. It is signed, so any corruption would be detected and could trigger a re-download.

**Comment by dpc** [comment]
Honestly, looking at it RN, does not seem worth the extra complexity, and even more so prioritizing it over many other things we could be doing. Every recovering client will possibly download large chunk of history, etc. so a peer doing DR once in a blue moon is not worth worrying about.
