### ISSUE TITLE
`raw_find_by_prefix` doesn't officially guarantee ordering

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4160]
This is wrong afaik, we assume lexicographic ordering in a bunch of places. Needs docs fixes and maybe a rename.

https://github.com/fedimint/fedimint/blob/df4bd8e92ce80944625be32af00f6018bcdd39ba/fedimint-core/src/db/mod.rs#L693-L695

**Comment by m1sterc001guy** [comment]
Correct, I believe this comment is leftover from before we serialized num types using big endian https://github.com/fedimint/fedimint/pull/2131

**Comment by justinmoon** [comment]
dev call: doc issue, not a code issue. would be good to add a test for this as well.

**Comment by elsirion** [comment]
Fixed by #6003
