### ISSUE TITLE
`gatewayd` and `fedimint-cli` serialize secrets differently

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#4170]
Not sure if this is an actual problem or not, but I was surprised to find this today.

[fedimint-cli serializes secrets as <Vec\<u8\>>](https://github.com/fedimint/fedimint/blob/master/fedimint-cli/src/lib.rs#L308-L322)

[gatewayd serializes as [u8; 64]](https://github.com/fedimint/fedimint/blob/c596967feeabccd231472a93512d6c28d55f05d6/gateway/ln-gateway/src/client.rs#L76)

So even if they used the same root secret strategy (they don't), `fedimint-cli` still wouldn't be able to initialize itself from a gateway-created client database.

**Comment by m1sterc001guy** [comment]
Fixed with https://github.com/fedimint/fedimint/pull/5852
