### ISSUE TITLE
`api_endpoint!` invocation should require a version number in which an api was introduced

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4190]
This argument will be throw away normally, but it will enforce documenting introduction of every single API endpoint, so we don't drown in a mess of our own making. [Original discussion](https://github.com/fedimint/fedimint/pull/4150#issuecomment-1918605620)

There might be some ways to employ these versions (e.g. an env var that would make `fedimintd` ignore endpoints newer than X, for backward compat purposes). But that's just speculation, and the goal here RN is documentation only.

**Comment by elsirion** [comment]
I thought of that too :laughing: wasn't sure if abusing our macros like that was a good idea. But that's probably the easiest solution, so let's go with it. Now I'm wondering if this should only contain a minor version?

Is major.minor even a good idea with our compatibility guarantees? We'll have to support old APIs for a while anyway for old clients, but after that do we need to change the major version to discard them? A one version number/rolling window compatibility scheme sounds more appropriate now.

**Comment by dpc** [comment]
> Is major.minor even a good idea with our compatibility guarantees?

Since it's only for documentation, we can start with a "we've introduced it in X", and change as we go, I guess.
