### ISSUE TITLE
Collect all the env var names in one (few) modules

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4191]
[From the comment](https://github.com/fedimint/fedimint/pull/4178#discussion_r1473195190):

> Let's just move them to one (few, if there are crate-dependency needs) file:
> 
> ```
> const FM_VAR_BLAH_NAME : &str = "....";
> ```
>
> and then we can link in the docs where to find them? Least amount of hassle for the benefit given?

**Comment by elsirion** [comment]
I think this is a good first step for dev discoverability. Longer term I'm thinking of adding an interface to modules that lets them only query registered env vars (ad ban direct reading via semgrep). That way we could auto-generate help entries for these (I hope clap help can be extended like this).

**Comment by KoalaSat** [comment]
Hi @dpc I'll be preparing a draft PR for this as my first issue, can you assign it to me?

**Comment by KoalaSat** [comment]
Hi, I created an initial approach https://github.com/fedimint/fedimint/pull/4710 it's still WIP but would be great to validate it with you, thanks!
