### ISSUE TITLE
Log should tell which gateway was chosen

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#4194]
This message could be improved by giving some details about the gateway that was selected:
https://github.com/fedimint/fedimint/blob/58717cb4a08ec89dc4631251a82e96d06a7b9a9d/modules/fedimint-ln-client/src/lib.rs#L855

**Comment by 15IITian** [comment]
suggestion: In  `select_active_gateway` function -> we choose a random gateway only when there is no `vetted gateway` but we should also choose it also when there is an error in choosing a vetted gateway ?

  https://github.com/fedimint/fedimint/blob/master/modules/fedimint-ln-client/src/lib.rs#L835

**Comment by elsirion** [comment]
> suggestion: In `select_active_gateway` function -> we choose a random gateway only when there is no `vetted gateway` but we should also choose it also when there is an error in choosing a vetted gateway ?
> 
> https://github.com/fedimint/fedimint/blob/master/modules/fedimint-ln-client/src/lib.rs#L835

Choosing a vetted GW can't fail because we only attempt it if the `vetted` list is non-empty, we should make this an `expect` to make this clear:

https://github.com/fedimint/fedimint/blob/5a941b7339f332b349211a77ed8d37e4f8e611f4/modules/fedimint-ln-client/src/lib.rs#L853
