### ISSUE TITLE
Log output outcome failure

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#4196]
Without telling more about the error and what the client was trying to do this debug log is useless:

https://github.com/fedimint/fedimint/blob/58717cb4a08ec89dc4631251a82e96d06a7b9a9d/modules/fedimint-ln-client/src/pay.rs#L174

**Comment by 15IITian** [comment]
do we require same thing here ?

https://github.com/fedimint/fedimint/blob/ec2034e82e331b199859082ce6288dbc1c7d0def/modules/fedimint-wallet-client/src/withdraw.rs#L62
