### ISSUE TITLE
Fedimint git repo is getting large 

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#4209]
```
$ git clone git@github.com:fedimint/fedimint.git fedimint
Cloning into 'fedimint'...
remote: Enumerating objects: 556932, done.
remote: Counting objects: 100% (10641/10641), done.
remote: Compressing objects: 100% (2453/2453), done.
remote: Total 556932 (delta 8473), reused 9893 (delta 7899), pack-reused 546291
Receiving objects: 100% (556932/556932), 479.58 MiB | 2.61 MiB/s, done.
Resolving deltas: 100% (468768/468768), done.
```

What's causing this? In the Deep Dive we suspect the database snapshots. @dpc suggested using [Git LFS](https://git-lfs.com/) if this is the case.

**Comment by dpc** [comment]
Overall:

![image](https://github.com/fedimint/fedimint/assets/9209/c0efc4de-4bcf-4591-9fcf-a234657d6475)


Our source code is getting large, see this 62K file? :D

![image](https://github.com/fedimint/fedimint/assets/9209/4e7b1f56-0545-4d3e-a907-a48d8c30b641)

DB seems innocent:

![image](https://github.com/fedimint/fedimint/assets/9209/5f09425b-e386-427b-854d-3c9ffd02f7df)

**Comment by dpc** [comment]
Nothin to do. Seems like we're just too productive and we've created a monster.

**Comment by elsirion** [comment]
For demos where people don't do heavy git foo but mainly want the current source code it might be useful to only clone part of the history:

```bash
$ git clone --depth=100 https://github.com/fedimint/fedimint
$ du -sh fedimint/.git
21M	fedimint/.git
```

vs cloning all of it

```bash
$ git clone https://github.com/fedimint/fedimint
$ du -sh fedimint/.git
496M	fedimint/.git
```

You can even specify the branch like so:

```bash
$ git clone --depth=100 https://github.com/fedimint/fedimint --branch=releases/v0.2
```
