### ISSUE TITLE
Backwards-compatibility doesn't work on Mac

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#4218]
When I run this locally on a Mac I get:

```
  = note: ld: framework not found SystemConfiguration
          clang-11: error: linker command failed with exit code 1 (use -v to see invocation)


error: could not compile `fedimint-ldk-node` (lib) due to previous error
```

_Originally posted by @justinmoon in https://github.com/fedimint/fedimint/issues/4215#issuecomment-1922397378_

**Comment by bradleystachurski** [comment]
@justinmoon When I've previously bumped into linker errors, it's been a red herring for OOM. Any chance you saw a related OOM?

**Comment by justinmoon** [comment]
This was because I was using an old nix shell which didn't include `SystemConfiguration`. Operator error!
