### ISSUE TITLE
Quicker Lightning Invoice Generation

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#4246]
One thing that we've noticed in running our federation is that invoices sometimes take a long time to generate, contrary to other lightning applications. This is because we need to create a `IncomingContractOffer` that lists the preimage for sale, and this needs to wait for a round of consensus to complete before being confirmed. This can result in longer invoice generation times, and if the federation is having problems, I have seen it take minutes.

It occurred to me that if we want quick lightning invoice generation times, we can move the waiting of the `IncomingContractOffer` from invoice generation time to payment time. Essentially, instead waiting for the preimage to be listed for sale at invoice generation time, the gateway should wait for the contract to be available when it intercepts an HTLC. It could poll and wait for a certain amount of time, and if the `IncomingContractOffer` isn't available at that point, we can fail the payment. In practice, this hopefully won't be much of a problem because by the time the payer tries to pay the invoice, if everything is functioning properly, the `IncomingContractOffer` should be available (since it usually takes some time to give the invoice to the payer, have the payer open their lightning app, verify the details, etc).

This has the advantage that invoice generation should be completely offline which will make it fast. Lightning NG should also fix this problem, since in NG clients need to directly inform the gateways of the incoming contract (but this is still superior, since it is only waiting for a single RPC and not a round of consensus). Additionally, if we decide to let gateways generate invoices, the current architecture and lightning NG become more similar. @joschisan FYI

**Comment by elsirion** [comment]
Is this relevant for the onld LN module? Seems invoice generation is good enough and by end of the year I assume most will be running LN NG anyway.

**Comment by m1sterc001guy** [comment]
Yes I believe it is only relevant for the old LN module. I was thinking about this since we were experiencing some issues with our federation. I'll try to fix this if I have time, but otherwise will defer efforts to more pressing issues.

**Comment by m1sterc001guy** [comment]
We're getting closer to NG, I don't think this is worth pursing in the meantime.
