### ISSUE TITLE
Have CI build devcontainer

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#426]
This is low priority, since not many people are using the devcontainer introduced by @rndhouse. But this would be neat. Down the road perhaps our README could have a button to instantly setup a cloud dev environment using [GitHub CodeSpaces](https://github.com/features/codespaces).

**Comment by dpc** [comment]
Considering how long it takes to build and how heavy it is, I'm not sure how practical this is.

Since this container includes the whole source code it would change and rebuild every single time.

Something tells me we should not be building the project inside the Dockerfile to beging with:

Per https://code.visualstudio.com/docs/remote/create-dev-container:

>  It allows you to open any folder or repository inside a container and take advantage of Visual Studio Code's full feature set. 

If it will "open" (meaning volume-mount) the source code, why blow up the size and built time with stuff that is going to get invalidated the moment developer changes any rs file?

**Comment by dpc** [comment]
This docker image is almost entirely nix binaries built when executing `nix develop`. I wonder - does it really save anyone anything  if these binaries are embedded in the docker image instead on the first time this container is started?

Inferring from https://code.visualstudio.com/docs/remote/create-dev-container#_rebuild , it seems like the container are persisted. 

Chances are also that Nix is going to do a better job at compression of network transfers, making download faster for the users.

**Comment by dpc** [comment]
BTW. On my desktop this Dockerfile builds in 15-20 minutes.

**Comment by dpc** [comment]
TODO:

* [ ] just like described in https://github.com/fedimint/fedimint/issues/317#issuecomment-1221247495 - set up devcontainer to automatically use cachix fedimint cache

**Comment by rndhouse** [comment]
@dpc 

> Chances are also that Nix is going to do a better job at compression of network transfers, making download faster for the users than downloading 7GB container image

FYI, compressed on Docker Hub the image is 2.03 GB, see:

https://hub.docker.com/layers/fedimint-dev/rndhouse/fedimint-dev/latest/images/sha256-aa80cc1e54b2f814325329bd77127f3d8db07e8959b47dd3c1c7251254811717?context=explore

But your point might still stand. I don't know how much less nix downloads.

**Comment by justinmoon** [comment]
> BTW. On my desktop this Dockerfile builds in 15-20 minutes.

20 minutes is acceptable for first time wait. Especially if nix is the main recommended development environment and docker is only a backup.

**Comment by dpc** [comment]
> 20 minutes is acceptable for first time wait. 

I think the exact time is largely depending on the network download speed. I don't think much if anything was being built. That might be where are the differences in reports are coming from. 

>  I don't know how much less nix downloads.

It is going to be comparable, I think.

**Comment by elsirion** [comment]
I think we want to build the container in CI from time to time just to see it still works. And when we do so we can just upload it as well. Maybe just build it once a week or so and trigger manually when necessary?

**Comment by dpc** [comment]
I will add a a cron triggered build. It it is not running for every PR, it should be fine.
