### ISSUE TITLE
Gateway should retry if registration fails

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#4280]
The following code is run on a timer to re-register gateways with federations: https://github.com/fedimint/fedimint/blob/1738332d8e6366cfe4c44561c11189337f8f4e27/gateway/ln-gateway/src/lib.rs#L1098-L1144

The behavior is that if a federation is unreachable at the moment this timer goes off (once per 10 minutes), then your gateway won't be registered to the federation for the next 10 minutes until the timer goes off again. I think it would be better if it tried retrying, say, every 10 seconds while registration is failing.

**Comment by kernelkind** [comment]
https://github.com/fedimint/fedimint/blob/9f4926cb9cba50bb016df59a4989e62f657d01a6/gateway/ln-gateway/src/lib.rs#L1322-L1338

Is this not already happening on line 1334?

**Comment by justinmoon** [comment]
It seems like line 1334 is triggered when the gateway isn't in a "running" state. IIRC this might mean that it hasn't connected to the lightning node yet, for example. 

If `register_all_federations()` call fails, we'll sleep `GW_ANNOUNCEMENT_TTL.mul_f32(0.85)` (line 1346) which is 8.5 minutes.
