### ISSUE TITLE
Public usage hardening

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4289]
* backup limit size
  * [ ] add some backup size limit check in the backup endpoint handler, make it reasonably large for now
  * [ ] check it on the client side to surface it early
* submit_transactin hardening
  * [ ] add client side code that on transaction rejected  due to PoW, recalculates the PoW and tries again; 
  * [ ] add adaptive PoW checking in the submit_transaction endpoint handler - track number of transaction submitted in the last hour (get it from the db maybe?), if low enough, do not require PoW at all for now; this should allow older clients (with no idea about PoW) to work under normal low usage conditions; in the future we can have some baseline PoW at all times;
* backup endpoint hardening
  * [ ] add PoW to backup endpoint, similar to the submit_transaction one. Possibly make it proportional to the backup size.
  * [ ] add client code
  * [ ] make sure it's backward-compat so old clients can still make backups

**Comment by dpc** [comment]
@elsirion Wrote down quick notes after the meeting.

**Comment by elsirion** [comment]
> make sure it's backward-compat so old clients can still make backups

Probably just not require it for small-ish backups till the current version support is dropped?

**Comment by elsirion** [comment]
I had a call with @dpc and we are going with the plan laid out in #4385, so closing this.
