### ISSUE TITLE
Verify that our key shares fit to the pub key sets

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#432]
I just did some manual config migration and made my signet federation very upset by giving it a LN threshold decryption key share that didn't fit the pub key. Since I'm running a monomint right now there is no peer to ban, so it just complains that it made a faulty contribution each epoch and starts the next in the hope that it will get better (it won't).

Having #331 would be really helpful in rectifying the situation by deleting/editing a DB entry …

**Comment by jkitman** [comment]
@elsirion should it just abort on startup with an error message?

**Comment by justinmoon** [comment]
This could be part of a larger project to sanity-check the server config on startup. Good first issue.
