### ISSUE TITLE
WsFederationApi failure conditions

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#435]
[This line](https://github.com/fedimint/fedimint/blob/0d26014b57a6bd32bae690966b13176b763ee75b/client/client-lib/src/api.rs#L371) should wait for `2 * max_evil + 1` successes

Eric and I noticed while reviewing @jkitman's #434.

In particular, we were expecting connections from [this client](https://github.com/fedimint/fedimint/pull/434/files#diff-65346ef6c368a5bdd16ebdbd8c21d969117d3caf775417f5ca6b2f3c49c81045R657) to fail. It was connected to 2 peers in a 3/4 federation. 2 matching responses aren't enough to know consensus has been achieved.

**Comment by elsirion** [comment]
Fixed by #437. I opened  #449 for the more long term thoughts on consistency checks.

**Comment by jkitman** [comment]
@elsirion @justinmoon Isn't it true that if `max_evil + 1` all return the same response then you can accept that as true, since we are assuming at least one is non-evil?

If one of them replies differently then you'd need to query more.

**Comment by elsirion** [comment]
I think you are right :see_no_evil: both versions seem safe and live, yours is more efficient.
