### ISSUE TITLE
Make backport issues/PRs more descriptive

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4362]
The title should contain the truncated title of the original PR, the body should contain the full title.

**Comment by bradleystachurski** [comment]
I believe this is the first backport bot issue created since we made updates. Let me know if we want to make further tweaks.

https://github.com/fedimint/fedimint/issues/4648

**Comment by justinmoon** [comment]
Nit: I don't think we need to truncate the title quite so short. But overall a huge improvement.

**Comment by bradleystachurski** [comment]
@justinmoon needed to fix an issue bot bug and took the chance to bump from 20 to 40 chars in https://github.com/fedimint/fedimint/pull/4814
