### ISSUE TITLE
Improve `gateway-cli info` command

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#4365]
- Should report the SCID being used for each federation
- Shouldn't show `config` by default since it's huge and makes the output difficult to read

**Comment by jrakibi** [comment]
Hi @justinmoon, I'll start working on this issue

**Comment by PsychoPunkSage** [comment]
Hi @justinmoon 
I see one PR for this issue and it is open for quite some time...
I would like to work on it if no one else is working on it...

**Comment by tvolk131** [comment]
I believe Justin is busy for the next few weeks. Go for it!

**Comment by m1sterc001guy** [comment]
Fixed with https://github.com/fedimint/fedimint/pull/5803
