### ISSUE TITLE
Improve e-cash note selection to support charging fees

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4387]
This is useful for DoS prevention.

**Comment by benthecarman** [comment]
Might be worth switching to the coin select crate

https://github.com/bitcoindevkit/coin-select

**Comment by elsirion** [comment]
I think our problem space is a bit smaller since we work with fixed denominations of the form b^x, where b is typically 2. Also, @joschisan fixed this in  #4437.
