### ISSUE TITLE
Migrate wasm build to nix-ci

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#441]
I tried to attempt it in nix-ci-wasm branch (in my fork), but hit an error: 

```
wasm32-unknown-unknown/lib/self-contained" "-o" "/build/source/target/wasm32-unknown-unknown/release/deps/secp256k1_zkp-d5cc30aeeaa142a4.wasm" "--gc-sections" "--no-entry" "-O3"
mint-client>   = note: lld: error: unknown file type: secp256k1.o
mint-client>           
mint-client> error: could not compile `secp256k1-zkp` due to previous error
mint-client> warning: build failed, waiting for other jobs to finish...
error: builder for '/nix/store/sgn4vnx1s3r1sljzq86y417hxs132plr-mint-client-0.0.1.drv' failed with exit code 101;
       last 10 log lines:
       >    Compiling bitcoin v0.28.1
       >    Compiling secp256k1-zkp v0.6.0 (https://github.com/fedimint/rust-secp256k1-zkp/?branch=sanket-pr#7ac34646)
       > error: linking with `/nix/store/wf2xrpq9ygn5n1whi5j4qdkj0z2qmhk0-lld-14.0.1/bin/lld` failed: exit status: 1
```

and just couldn't get it to work.

And will need to dig deeper once I have more time to figure it out.

**Comment by justinmoon** [comment]
@wiredhikari: Did we see this error previously?

**Comment by wiredhikari** [comment]
> @wiredhikari: Did we see this error previously?

No, this is different from previous errors. I will also take a look in it.

**Comment by dpc** [comment]
Nix-provided clang seem to be ignoring `--target` argument, similarly to how it is described in https://stackoverflow.com/questions/69039082/nixs-clang-wont-build-wasm . The `.o` files are all for x64 arch.

**Comment by dpc** [comment]
After more trying it seems that:

* this would kind of work if C was not involved
* to do this properly with C code `crossSystem` facility needs to be used
* `crossSystem` facility does not seem to support `wasm32-unknown-unknown` target https://github.com/NixOS/nixpkgs/issues/89426

It's beyond my ability to get it work. I think we will have to use non-nix builds for wasm for now.

**Comment by dpc** [comment]
Done in https://github.com/fedimint/fedimint/pull/624
