### ISSUE TITLE
System to cleanup EOL version logic in devimint

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#4424]
@bradleystachurski Food for thought: we will need to deal with all sorts of incompatibilities between versions.

_Originally posted by @dpc in https://github.com/fedimint/fedimint/pull/4399#discussion_r1500054422_

See full discussion for additional context

**Comment by dpc** [comment]
I guess ...

```
// TODO(support:vX.Y.Z): blahbla
```

?

Meaning that the whole thing here is to support `vX.Y.Z` and once this version doesn't need support, something can be done (usually handling code removed).

I was thinking `compatibility` initially, but it is kind of long and easy to make a typo. Could be `support`, maybe `compat`. Or maybe someone has better ideas.

**Comment by bradleystachurski** [comment]
```
// TODO(support:vX.Y.Z)
```
That works with me. Also gives us the flexibility to exclude the patch version when grepping.

**Comment by bradleystachurski** [comment]
We've started using this approach so we're good to close this issue. If we need to consider a different system we can open a new issue.
