### ISSUE TITLE
Lightning Gateway backupability

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4446]
Do we have a common seed for all the clients in the gateway and can we export it/recover from it? If not we should.

**Comment by justinmoon** [comment]
dev call: @joschisan reports that every client different seeds. Also, we use 64 bytes which can't be represented as BIP39 seed words.

**Comment by kernelkind** [comment]
sounds related: https://github.com/fedimint/fedimint/issues/4170

**Comment by justinmoon** [comment]
Also related to https://github.com/fedimint/fedimint/issues/2652. These 3 could probably be one issue.

**Comment by Kodylow** [comment]
Working this rn with @m1sterc001guy , moving to bip39 mnemonic and reusing all dpc's fanciness in the fedimint-client with a manual migration: gateway operator moves their ecash out, leaves the federation, rejoins with the automatically created new client derived from the mnemonic

**Comment by joschisan** [comment]
If you do a manual migration you can also move all dbs into one via prefixes.

**Comment by m1sterc001guy** [comment]
> If you do a manual migration you can also move all client dbs into one via prefixes.

Yep, had the same idea, this is the plan.
