### ISSUE TITLE
`ClientHandle::restart`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4485]
Use https://crates.io/crates/arc-swap/1.7.0 on in `ClientHandleShared` and do shtudown executors + an atomic switcharoo, so we can reuse the database and save the user hasle of tracking stuff, etc.

**Comment by dpc** [comment]
@maan2003 fyi

**Comment by dpc** [comment]
After looking a bit into it and thinking about it: it seems possible, but the way it works (at least in arc-swap case) is that reads kind of get their own copy/ref that they can use, and write can finish behind their back.

So you can get two users working on two version of a Client. One would be shutting down, the other start, and they could share a DB. But that makes me worried about logical consistency. It's easy to introduce some corner case nightmarish scenario where weird things could theoretically happen.

So for similar reasons like not doing it on flight, we will just move the responsibility to the caller - they need to make sure to drop all the references to the Client&Database underneath to guarantee no two Clients ever can be touching the DB at the same time.

**Comment by elsirion** [comment]
I mean, properly supporting in-process restarts is _really good_ and thanks to @maan2003 and you it works now, but it should not be something we habitually do imo. Eventually a "recovering client" should be able to be transformed into a "normal client" either by just calling a `self`-consuming fn or even automatically once recovery finishes.

**Comment by dpc** [comment]
I was wondering if we could do a self-restart without needing to have an exclusvie handle.

A self-consuming restart on a exclusive handle seems very simple to make, and sure we should have it.

**Comment by dpc** [comment]
#4535

**Comment by maan2003** [comment]
completed in https://github.com/fedimint/fedimint/pull/4538
