### ISSUE TITLE
TaskGroup::spawn doesn't need to be async?

### ISSUE THREAD

**Issue by shaurya947** [fedimint/fedimint#4493]
https://github.com/fedimint/fedimint/blob/6cdfba8de0c37e5a8186ce529881151daa48cab4/fedimint-core/src/task.rs#L173

Need to investigate and remove `async` if unnecessary

**Comment by maan2003** [comment]
nope
https://github.com/fedimint/fedimint/blob/2a8e3b740bf09aec8643d229006fa90d3df99f06/fedimint-core/src/task.rs#L481-L488
