### ISSUE TITLE
Add our license info to Cargo.toml's

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#450]
maybe there's other useful metadata, too

**Comment by NicolaLS** [comment]
looking at [this](https://doc.rust-lang.org/cargo/reference/manifest.html), I'd say maybe `homepage` `description` `readme` would be also useful but not really important

**Comment by elsirion** [comment]
Yep, that would be good to do in one go.

**Comment by Kodylow** [comment]
How does this look?

`[package]
name = "fedimint"
version = "0.1.0"
authors = ["Fedimint Developers"]
edition = "2021"
rust-version = "1.56.0"
description = "Fedimint is a Federated Chaumian E-Cash Mint implementation, natively compatible with Bitcoin & the Lightning Network."
documentation = "https://github.com/fedimint/fedimint/tree/master/docs"
readme = "README.md"
homepage = "https://fedimint.org"
repository = "https://github.com/fedimint/fedimint"
license = "MIT"
license-file = "LICENSE"
keywords = ["bitcoin", "lightning", "chaumian", "e-cash", "federated"]`

**Comment by elsirion** [comment]
> Should we add to each subcrate's toml or just the top level repo?

Good question, from a short look at the [Cargo Reference](https://doc.rust-lang.org/cargo/reference/workspaces.html) it seems like this would need to be added to every sub-crate.

>  rust-version = "1.56.0"

Dow we know our MSRV? If so we should test with it to not break it, if not we should not include it.

> documentation = "https://github.com/fedimint/fedimint/tree/master/docs"

I think for now this is sufficient, but reminds me I have to fix docs.fedimint.org

**Comment by justinmoon** [comment]
I don't think we know our MSRV. IIRC I had problems on 1.62 but might have been my mistake.

**Comment by NicolaLS** [comment]
> How does this look? Should we add to each subcrate's toml or just the top level repo?
> 
> name = "fedimint" version = "0.0.0" authors = ["Fedimint Developers"] edition = "2021" rust-version = "1.56.0" description = "Fedimint is a prototype Federated Chaumian E-Cash Mint implementation, natively compatible with Bitcoin & the Lightning Network. This project is under heavy development, DO NOT USE WITH REAL FUNDS." documentation = "https://github.com/fedimint/fedimint/tree/master/docs" readme = "README.md" homepage = "https://fedimint.org" repository = "https://github.com/fedimint/fedimint" license = "MIT" license-file = "LICENSE" keywords = ["bitcoin", "lightning", "chaumian", "e-cash", "federated"]

We are on `edition = "2018"`  IIRC editions are breaking changes so we can`t just bump it without further investigation.
Also what does MSRV mean @elsirion ? minimum stable rust version ? (if so would this mean with what min version it compiles or with what min version its bug free (how do you ever know your project is bug free anyway..))

**Comment by elsirion** [comment]
I think the edition jump is ok. We forbid warnings in CI and single edition jumps only make warnings to errors afaik, so if you didn't have warnings before you are good. MSRV=minimum supported rust version.

**Comment by justinmoon** [comment]
Closed by #450
