### ISSUE TITLE
Improving the .expect("") messages

### ISSUE THREAD

**Issue by NicolaLS** [fedimint/fedimint#451]
We have some `foo().expect("some error")` in our project and the messages in them are not really uniform e.g. 
`'DB Error'` or `'Invalid URL in config'`
I [think](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html) it is best practice to actually communicate your assumption on why you think it can never fail in the expect messages:

_" In production-quality code, most Rustaceans choose expect rather than unwrap and give more context about why the operation is expected to always succeed. That way, if your assumptions are ever proven wrong, you have more information to use in debugging."_

I'm not sure how important something like this is so feel free to close @elsirion

**Comment by dpc** [comment]
See also #416

**Comment by elsirion** [comment]
* `'DB error'` needs a separate effort imo, see #374
* Sanity checks for configs could arguable be handled better using errors and printing them. `expect`ing was just a 80/20 solution that tells you what's wrong when you can't start anyway.
* There are probably a few places where we want `expect` and the message is bad, reporting/fixing these would be good.

**Comment by m0rtis0** [comment]
In the CLI, there the `expect()` and `unwrap()` calls around [here](https://github.com/fedimint/fedimint/blob/aedcee34fe58e00e2fa6c2c1750afe1a0024639a/client/cli/src/main.rs#L166) should probably also be replaced by proper clap errors. Currently the CLI panics at most of the command errors:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MintClientError(ApiError(RpcError(Call(Custom(ErrorObject { code: ServerError(400), message: "Input coin error: One of the supplied coins was already spent previously", data: None })))))', client/cli/src/main.rs:166:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
