### ISSUE TITLE
Allow client migration tests to write arbitrary bytes to database snapshots

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#4536]
It's currently difficult to test client state machine migrations because we want to write the old state into the database, which requires keeping extra structs and enums around to be able to do this.

If the tests could write raw bytes directly into the database, we could serialize the old bytes into a string and write that into the db, which would allow us to delete the old structs and the old enums.

**Comment by elsirion** [comment]
PRs that need cleanup once this lands:
- [ ] #4024
- [ ] #3820

Keeping these old enum variants around is very bad for maintainability.
