### ISSUE TITLE
Add string constants for gateway route names

### ISSUE THREAD

**Issue by tvolk131** [fedimint/fedimint#4545]
The route names here should be extracted to constants:

https://github.com/fedimint/fedimint/blob/043f6c3a46ddc6833621daf775bbf59fe1b75b83/gateway/ln-gateway/src/rpc/rpc_server.rs#L53-L92

And those new constants should also be used where these routes are consumed in [rpc_client.rs](https://github.com/fedimint/fedimint/blob/043f6c3a46ddc6833621daf775bbf59fe1b75b83/gateway/ln-gateway/src/rpc/rpc_client.rs).

See [here](https://github.com/fedimint/fedimint/blob/043f6c3a46ddc6833621daf775bbf59fe1b75b83/fedimint-core/src/endpoint_constants.rs) for an example where we do something similar.

**Comment by m1sterc001guy** [comment]
Fixed in the linked PRs
