### ISSUE TITLE
Upgrade all (most) dependencies before releasing 0.3

### ISSUE THREAD

**Issue by maan2003** [fedimint/fedimint#4561]
deps left:
- [x] bech32
- [x] bitcoin
- [x] bitcoincore-rpc
- [x] bitcoin_hashes
- [x] bls12_381
- [x] cln-plugin
- [x] electrum-client
- [x] esplora-client
- [x] ff
- [x] gloo-net
- [x] group
- [x] lightning
- [x] lightning-invoice
- [x] miniscript
- [x] rcgen
- [x] secp256k1
- [x] secp256k1-zkp

~tokio-rustls~ edit: this was broken off into a separate issue due to its complexity: #5793

**Comment by maan2003** [comment]
https://github.com/fedimint/fedimint/pull/4557 upgrade most of deps

**Comment by justinmoon** [comment]
Is this done?

**Comment by maan2003** [comment]
nope, all deps listed are still not upgraded

**Comment by elsirion** [comment]
Unless there's a CVE being on the latest version isn't important for 0.3 imo. It's generally a good practice to avoid huge version jumps later on, but that can also happen on master later on. Only drawback is that any change to master will make backporting harder, but that's always the case no matter the change.

**Comment by justinmoon** [comment]
dev call: let's split the alephbft ones into separate issues

**Comment by tvolk131** [comment]
Assigning to myself since I already did most of these and can wrap up the rest soon

**Comment by tvolk131** [comment]
Finished!
