### ISSUE TITLE
opentelemetry deprecated call warning 

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4591]
```
   --> fedimint-logging/src/lib.rs:125:52
    |
125 |                 let tracer = opentelemetry_jaeger::new_agent_pipeline()
    |                                                    ^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default
```

**Comment by OsauravO** [comment]
@dpc i think it should be done like this as In version 0.19.0 of the opentelemetry-jaeger crate, the new_agent_pipeline() function was deprecated.
![Screenshot from 2024-03-18 12-29-18](https://github.com/fedimint/fedimint/assets/123803605/5e641908-92c9-43a4-8afd-916a396ef74a)
But what should be agent endpoint for our setup.

**Comment by dpc** [comment]
@OsauravO We should handle it the same as other services. E.g. prometheus. See `fedimint-metrics` and grep for `bind_metrics_api`.

**Comment by harsh-ps-2003** [comment]
@dpc 
As [opentelemetry_jaeger has deprecated its exporters](https://github.com/open-telemetry/opentelemetry-rust/blob/e0bb2b6b0308b868f9139f7dcad79161cde5ed78/opentelemetry-jaeger/src/lib.rs#L4) reasoned [here](https://opentelemetry.io/blog/2022/jaeger-native-otlp/), I think we might need to move to [opentelemetry_oltp](https://crates.io/crates/opentelemetry-otlp) which involves switching the exporter and the underlying protocol for sending telemetry data. Should I attempt to solve this issue, as nobody is assigned?

**Comment by dpc** [comment]
@harsh-ps-2003 Go for it, PRs always welcome.

**Comment by PsychoPunkSage** [comment]
Hi,
Can I work on this issue?
We just need to update the deprecate calls, right?
Can I get bit more context of what we are working on to get a better understanding to solve the issue?

**Comment by dpc** [comment]
Whoever shows up with a PR first wins. :D

> Can I get bit more context of what we are working on to get a better understanding to solve the issue?

I don't understand. This issue is about doing whatever is needed to get rid of this warning.

I'm not even sure if the issue is still. I'd start by running a clean build and checking if the compilation warning for this code is still there.

**Comment by PsychoPunkSage** [comment]
Hi @dpc
I build it and I couldn't see any compilation warning even after `cargo check` and `cargo clean | cargo build`..
I think the issue is already solved.
