### ISSUE TITLE
Investigate rocskdb memory usage risks

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4600]
https://twitter.com/PavolRusnak/status/1769633022461043023

Follow-up with what's that about, and do we need to do anything about it. Better now than when people start hitting it in real life.

**Comment by dpc** [comment]
@fedimint/database

**Comment by m1sterc001guy** [comment]
fwiw I think this is the policy of a lot of dbs (I believe sql server does the same thing), since they would rather eat up memory than suffer a buffer pool miss and degrade query performance

**Comment by dpc** [comment]
> Another example is when your app uses RocksDB (statically linked), it never frees cache memory. You have to set MemoryLimit in systemd service file, otherwise it triggers OOM killer, because the process eats all of RAM. It is weird af at first sight, but very elegant on second.

The way it's phrased sounds like rocksdb relies on allocations failing or OOM? Also - there should be just a way to cap memory on the library level.

**Comment by dpc** [comment]
@m1sterc001guy I looked some more at it, and I think from our PoV, we should just customize rocksdb settings like in: https://github.com/romanz/electrs/issues/30

**Comment by dpc** [comment]
Nothing immediately to do it seems.
