### ISSUE TITLE
Track CI test performance over time

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4607]
We have different performance tests (low-level benchmarks, end-to-end latency tests) that nobody looks at, if we could visualize metrics over time we could more easily notice regressions. 

One action that does this: https://github.com/benchmark-action/github-action-benchmark

**Comment by bradleystachurski** [comment]
Perhaps this job could also run on self-hosted infra (similar to https://github.com/fedimint/fedimint/pull/4630#issuecomment-2009408637)?

I've been wanting to play with this for a while so I'd love to tackle.

**Comment by bradleystachurski** [comment]
Close by https://github.com/fedimint/fedimint/pull/5330
