### ISSUE TITLE
LN Gateway Routing Fees Not Updating

### ISSUE THREAD

**Issue by bullmoosesystems** [fedimint/fedimint#4609]
I updated the LN routing fees in docker compose after having originally launched the lightning gateway with the default fees. I re-ran docker-compose up, but the fees have not updated after 2 days.

**Comment by m1sterc001guy** [comment]
Can you post your logs from the gateway so we can debug?

**Comment by elsirion** [comment]
Last time I had to deal with changing fees (I did so via `gateway-cli`) I had to leave and re-join the federation to make it work :see_no_evil: I'm not sure if we looked into it @m1sterc001guy, even if we did we might have forgotten to backport.

**Comment by m1sterc001guy** [comment]
We added this https://github.com/fedimint/fedimint/pull/4020 awhile back to re-register the gateway when the fees are changed, which should cause it to show up immediately. I don't think this was backported to 0.2.1 though.

Although if the fees haven't updated after 2 days sounds like something else is wrong, so it would be good to see the logs.

**Comment by bullmoosesystems** [comment]
Which logs specifically? 

Interestingly, when I bash into the docker container and run gateway-cli, I get this error:

bash-5.2# gateway-cli info
Error: error sending request for url (http://127.0.0.1:8175/info): error trying to connect: tcp connect error: Connection refused (os error 111)

Caused by:
    0: error trying to connect: tcp connect error: Connection refused (os error 111)
    1: tcp connect error: Connection refused (os error 111)
    2: Connection refused (os error 111)

Maybe related?

**Comment by elsirion** [comment]
@Kodylow how do you use the CLI tools with docker? Do you have to be inside the container or set some command line options?

**Comment by justinmoon** [comment]
> Last time I had to deal with changing fees (I did so via gateway-cli) I had to leave and re-join the federation to make it work 🙈 I'm not sure if we looked into it @m1sterc001guy, even if we did we might have forgotten to backport.

I just experienced the same thing. Needed to leave and re-join in order to change the fee.

**Comment by m1sterc001guy** [comment]
This should be fixed in 0.3 https://github.com/fedimint/fedimint/pull/4020

I'm gonna close this for now, feel free to re-open if the issue persists in 0.3+
