### ISSUE TITLE
remove Database::ensure_global calls

### ISSUE THREAD

**Issue by maan2003** [fedimint/fedimint#4616]
I want to use same database(with_prefix) for different fedimint clients and fedimint code calls ensure_global and errors out.

cc @m1sterc001guy

**Comment by m1sterc001guy** [comment]
The client side migrations today assume that the global database is the db namespace where the states are stored. For any use case that needs multi-level nesting of isolated databases (e.g multiple clients within the gateway), this check doesn't make sense anymore and can be removed.
