### ISSUE TITLE
Update rust-bitcoin to 0.29.3

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4618]
Once https://github.com/rust-bitcoin/rust-bitcoin/pull/2607 is backported we should bump our rust-bitcoin minor version so that we get the DoS fix. Upgrading to >0.29 will probably take a bit longer.

**Comment by apoelstra** [comment]
Actually, looking at the source code for rust-bitcoin 0.30.x (and prior versions) I think we are okay. Prior to https://github.com/rust-bitcoin/rust-bitcoin/pull/1991 we obtained this length from `Vec::<u8>::consensus_decode` which internally has the required length check.

So fedimint is unaffected.
