### ISSUE TITLE
Flakiness in backwards compat tests

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4636]
I've seen a few flakes recently, last one here: https://github.com/fedimint/fedimint/actions/runs/8357596532/job/22877078904?pr=4634#step:6:1714

My suspicion is that we just parallelize so much that 15s isn't a sufficient timeout for DKG anymore.

**Comment by bradleystachurski** [comment]
If we merge the associated PR I'd like to keep this issue open until we've gone a while (1 week?) without seeing back-compat flakes.

**Comment by justinmoon** [comment]
dev call: looks like the flakiness has gone away. we've been keeping this open just to make sure it's gone.

**Comment by bradleystachurski** [comment]
Another flakey back-compat fix: https://github.com/fedimint/fedimint/pull/4729

**Comment by bradleystachurski** [comment]
Back compat has been stable for a while. We can open another issue if we see new flakiness.
