### ISSUE TITLE
Check docs in on PR

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#464]
I think the recent CI changes lead to a situation where the docs aren't built per PR anymore, but only once its merged. That could lead to failures on master that we can't detect before merging.

Docs should be built the same way per PR and on merge to master (in which case they'll be published to https://docs.fedimint.org):

https://github.com/fedimint/fedimint/blob/529c6d5c4401d231c44748fb243dfe0da8d96971/.github/workflows/docs.yml#L26-L30

**Comment by dpc** [comment]
Will do. Build on all branches, publish on pushes to master.

**Comment by dpc** [comment]
It seems like we are relying on nightly flags to create `index.html`, so I think for now I'll leave the non-nix workflow to build and upload it when landed in `master`.
