### ISSUE TITLE
Recalculate decoders based on DKG/config.

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4685]
Seems like currently we hardcode decoder registry on the server side by just iterating module kinds, and then we run with it.

Now that new modules were added this will not work.

We need to compose the list of Decoders after we know the configuration of the Federation - either after it's established during DKG, or loaded from the Federation config on start.

**Comment by elsirion** [comment]
I see we closed it in https://github.com/fedimint/fedimint/pull/4726
