### ISSUE TITLE
Gateway stores password in plaintext

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#4702]
Today the gateway stores the administrator password in plaintext in the database. We should instead store a hash and comparing hashes while authenticating. https://github.com/fedimint/fedimint/pull/4642#discussion_r1536659840

Main challenge will be doing this in a backwards compatible way.

**Comment by m1sterc001guy** [comment]
> Main challenge will be doing this in a backwards compatible way.

I supposed the gateway could compare the stored hash against the plaintext password and the plaintext password hashed, to provide backwards compatibility.

**Comment by dpc** [comment]
> Main challenge will be doing this in a backwards compatible way.

Make fields options, rewrite old field  on access.

BTW. Make sure to add some random generated salt.

**Comment by elsirion** [comment]
The same needs to be done for the guardian password (although there it might be simpler, just delete the file and require password on startup and keep it in memory from there on).
