### ISSUE TITLE
`just bump-version` command

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4714]
> I manually edited `flakebox.nix` manually and ran:

Wouldn't you want it as a `just` command?

_Originally posted by @dpc in https://github.com/fedimint/fedimint/issues/4711#issuecomment-2016969899_

**Comment by justinmoon** [comment]
dev call: this is for bumping the versions in our crates

**Comment by dpc** [comment]
`bump-version` seems a bit vague. Maybe we should make all release-related commands start with `release` or something like that.

**Comment by maan2003** [comment]
`cargo set-version` from `cargo-edit` is better imo
