### ISSUE TITLE
MVP Tor support in the client

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4752]
Part of #2610, but without stream separation by operation. @oleonardolima already did most of the work for an MVP version, so let's get it in. The full version can follow later.

**Comment by oleonardolima** [comment]
As I've mentioned in today's dev call, I still need to test and debug the connection to hidden services peers thoroughly, and  I think it's best to split the work done into two/three PRs:

I did update the description of #2610, extracting it from there, the current work in progress (step/milestone 2):

- **feat: add initial Tor support, without `OperationId` stream isolation:** https://github.com/fedimint/fedimint/issues/4752

    - [ ] feat: add initial Tor support, connection to `hostname` https://github.com/fedimint/fedimint/pull/5053 
    - [ ] feat: add initial Tor support, connection to `onion addresses` (hidden services)
    - [ ] feat: add initial Tor support, support for `onion addresses` into `InviteCode`

cc @elsirion (@benthecarman I'll focus the updates in this issue for now :))

**Comment by oleonardolima** [comment]
update: FWIW, I've used harbor for testing alongside the fedimint-cli, building on top of the #5443,  here is harbor's branch/PR if anyone is curious about it https://github.com/MutinyWallet/harbor/pull/89

**Comment by oleonardolima** [comment]
update: I think this initial mvp is almost there, I was able to do a test federation setup with hidden services, using the non-tls script / setup approach.

It only required to set up the hidden service beforehand, using the onion address during federation setup (the `SafeUrl`/`Url` handles it pretty well), and the onion addresses will be part of the config and returned in the api_endpoints responses, encoded in the federationId, and so on.

If some guardian wants to expose both through an onion address, it seems possible with some traefik settings, but the domain will still be exposed as it's part of the response in api_endpoints 🤔 

FYI @elsirion @benthecarman

**Comment by Kodylow** [comment]
yaaaaaaaay
