### ISSUE TITLE
Ensure that HBBFT epochs are processed in order

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#480]
It's currently possible that we receive epochs from the future (in bigger feds), but this hasn't happened in practice.  Still, we should cache those epochs and ensure that epochs are only processed in-order.

Note this is also an issue in the consensus resyncing code.

**Comment by jkitman** [comment]
Actually discovered this is handled internally by hbbft.

**Comment by justinmoon** [comment]
Can you share any links to HBBFT docs or source code about this? I'm really eager to learn more about how HBBFT actually works ...

**Comment by jkitman** [comment]
@justinmoon Sure, the code is here https://github.com/fedimint/hbbft/blob/master/src/honey_badger/honey_badger.rs#L172-L185

This gets called whenever HBBFT processes a new message, potentially producing an outcome.  The code looks like it will only produce epochs in order.

**Comment by elsirion** [comment]
@justinmoon in general such BFT consensus algos have one job: determining an order of transactions that everyone agrees on. It would be very odd if an implementation would return epochs out of order. So when we looked we found that's not the case indeed.

**Comment by justinmoon** [comment]
Thanks guys 🙏
