### ISSUE TITLE
Create new Gateway should not have side effects

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#481]
When we create a new gateway, it automatically registers with the mint. Create also has other side effects like starting of a webserver for receiving messages from clients :  [code reference](https://github.com/fedimint/fedimint/blob/2a02caab33e97895ccffc24cd2b7eb445f1daa5f/ln-gateway/src/lib.rs#L126)

We should consider moving these effects to a later step, when we have instantiated a gateway and are ready to run it

**Comment by justinmoon** [comment]
More concretely, `LnGateway::new()` probably shouldn't have side-effects. `.run()` should do things like register with the federation and run a webserver. I guess one complication is that [this](https://github.com/fedimint/fedimint/blob/54f934b6f5436c14e94e65676817b17baab990df/ln-gateway/src/lib.rs#L113) would need to become an `Option`. But that's probably acceptable.

**Comment by okjodom** [comment]
Seems the receiver should be optional as well seeing as the spawning of the sender-receiver channel server and the receiver are closely related, and a receiver is not useful until a server is spawned. Do we have direct external application of receiver from `LnGateway` instances?

**Comment by okjodom** [comment]
Running a webserver within `LnGateway::new()` is closely related to how we instantiate the `ln_client` which is currently just c-ln RPC. As part of removing this side-effect of instantiating the gateway, we can use the opportunity to decouple LnGateway from c-ln.

See comment in a larger but remotely related issue: https://github.com/fedimint/fedimint/issues/6#issuecomment-923741413

**Comment by elsirion** [comment]
I'm getting the feeling that maybe the web server shouldn't run inside this struct. The current architecture would lend itself to having a `GatewayAPI` trait that contains all the functions defined in `GatewayRequest`: https://github.com/fedimint/fedimint/blob/2a02caab33e97895ccffc24cd2b7eb445f1daa5f/ln-gateway/src/lib.rs#L52-L59

Then the main `LnGateway` struct could contain a task that runs the main loop and a `Sender<GatewayRequest>`. There'd be a second struct `LnGatewayAPI: GatewayAPI` just consisting of such a sender and a `fn LnGateway::api(&self) -> LnGatewayAPI` that clones the sender and returns an API object. 

Then there could be a function `fn run_webserver(api: LnGatewayAPI)` that spawns the web server task. 

One problem we'd run into again is that we need the `LnGatewayAPI` object to start the cln plugin but need the plugin to be started to know the cln socket address to start the main loop. Maybe `LnGateway` should contain an enum that can either be the handle of the main loop or the receiver belonging to the sender that will be used to spawn the task once the plugin is ready. This way the `LnGatewayAPI` objects can be generated to start the plugin+web server before the main loop is ready.

```rust
enum LnGatewayState {
    AwaitingLnApi(Receiver<GatewayRequest>),
    Running(JoinHandle<()>)
}

struct LnGateway {
    state: LnGatewayState,
    sender: Sender<GatewayRequest>
}

impl LnGateway {
    fn new() -> Self { … }

    fn api(&self) -> LnGatewayAPI {
        LnGatewayAPI {
            sender: self.sender.clone()
        }
    }

    /// LnApi is a trait generalizing over the underlying LN node impl (cln, lnd), providing the necessary commands (pay, get node id, …)
    fn start_main_loop(&mut self, ln_api: Box<dyn LnApi>) {
        // Start task if we are in sate AwaitingLnApi, panic otherwise
        // TODO: maybe model this transition in the type system to avoid the panic?
    }
}
```

**Comment by dpc** [comment]
It seem to me that these "not doing side effects in constructor" is a red herring. 

Constructors in Rust are just static functions, and they are not special or magical. It doesn't really matter much where are you going to start a new thread. In a way it's just a naming thing.

As a matter of fact in Rust I usually employ a pattern where "service/actor threads" **are the thread**.

So I'd have:

```rust
struct ActorsResult {
  pub something: u64,
}

pub struct SomeActor {
  join: Option<JoinHandle<ActorsResult>>, // Option just so we can `take()` in destructor.
  stop_requested: Arc<AtomicBool>,
}

impl SomeActor {
  fn new(some_params: SomeActorParams) -> Self {
     let stop_requested = Arc::new(AtomicBool::new(false));
     Self {
        stop_requested: stop_requested.clone(),
        join: thread::spawn(|| {
              while !stop_requested.fetch() {
                 keep_doing_stuff();
              }),
        }
   }
}
```

`SomeActor::new()` is all about starting a new thread. `SomeActor` in a certain sense *is the handle to the running thread*. If you don't want a thread started yet - don't call it, and only keep the `SomeActorParams` around.

Then for shutting down:


```
impl SomeActor {
   fn stop(self) -> ActorsResult {
      self.stop_request.store(true);
      self.join.take().expect("can't be stopped twice").join().expect("or handle errors or whatever")
   }
}

impl Drop for SomeActor {
   fn drop(&mut self) {
      self.stop_request.store(true);
      self.join.take(|join| join.take());
   }
}
```

It's possible to stop the service and get some result it is supposed to return, or - dropping the handle will automatically notify the service to stop and wait for it.

I've found this pattern to work perfectly for me, allowing me to effortlessly handle things like graceful shutdowns. The exact details of termination are often more complicated and include threads getting shut-down on the their input channels closing on them, and some global flags to detect panics inside services, etc.

**Comment by dpc** [comment]
An example of a project that I've been working before joining Fedi:

The `main` function comes down to calling `Node::new`:
https://github.com/rustshop/loglog/blob/7e83e4318ecd44e86335cf40546250fcba48e9d0/server/src/main.rs#L70

which is supposed to be (represent) a peer in a Raft-conensus :
which internally just starts all it's thread:

https://github.com/rustshop/loglog/blob/7e83e4318ecd44e86335cf40546250fcba48e9d0/server/src/node.rs#L176

Each of these threads is connected via channels and are passing work/messages between each other.

Note that this code is not exactly how I wanted it, but I never got to polish/refactor that part. I planed to move the `tokio_uring::spawn(Service { params }.start_some_loop())` into `new` and wrap it in a loop eventually, and tokio_uring` had other quirks I needed to address first.

There is a shared `is_node_shutting_down` flag: https://github.com/rustshop/loglog/blob/7e83e4318ecd44e86335cf40546250fcba48e9d0/server/src/node.rs#L92 that threads that don't have any better clear indication of end of their job use to stop.

Some threads finish when the recipient of their work requests is gone: https://github.com/rustshop/loglog/blob/7e83e4318ecd44e86335cf40546250fcba48e9d0/server/src/node/segment_preloading.rs#L30

Some when the sender of work is gone: https://github.com/rustshop/loglog/blob/7e83e4318ecd44e86335cf40546250fcba48e9d0/server/src/node.rs#L295

Some based on a flag: https://github.com/rustshop/loglog/blob/7e83e4318ecd44e86335cf40546250fcba48e9d0/server/src/node/request_handling.rs#L54

They are share some data that they synchronize based on the exact need: https://github.com/rustshop/loglog/blob/7e83e4318ecd44e86335cf40546250fcba48e9d0/server/src/node.rs#L69

That project is somewhat comparable to Fedimint - a peer in a distributed consensus, with network interface for clients, writing stuff to the database, trying to be high performance.

**Comment by okjodom** [comment]
> It seem to me that these "not doing side effects in constructor" is a red herring.

Great point. The real gap seems to be a need for gateway architecture with a spec loosely defined as:
- gateway instantiation without lightning rpc declaration
- support lightning rpc registration after gateway has been instantiated
- support webserver (re)start independent of the lightning rpc availability?
- support federation registration independent of gateway lightning rpc availability.

**Comment by okjodom** [comment]
> As a matter of fact in Rust I usually employ a pattern where "service/actor threads" are the thread.

Inspiring pattern that I can adopt on what I prototyped as (1)[`GatewayRpcServer`](https://github.com/fedimint/fedimint/pull/709/commits/88b595deeef24631c273e5d93e12424bd4a6fb8e#diff-927b3ed83a2978a44e247e4f5726ad058a416018504a091e1fd6a57ab02cd093R133), a unit of execution for all gateway logic. In fact, I'm renaming to GatewayActor :)

- Each federation registered would get a unique instance of this actor. Actor 1:1 maps to a federation client
- The actor receives messages from gateway webserver and gateway lightning_rpc over a channel
- (1)An actor can send messages over a channel to other actors in case of internal payments

(1) - I'm not running these actors on threads as thread spawns yet
(2) - actor-to-actor messaging is not yet part of my prototype. For now, I'm aiming at a gateway with a single actor meaning a gateway can only ever serve one federation

**Comment by okjodom** [comment]
A sketch including our actor discussion above : 
![GatewayComponentDiagram](https://user-images.githubusercontent.com/11217077/193363791-43400fc2-4a5e-42fe-baef-e50b6ae84684.png)

**Comment by okjodom** [comment]
Closed by the discussion and work that make up the entirety of #714
