### ISSUE TITLE
Baby-proof redundant consensus item handling

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4881]
It seems that in meta module I (and reviewers ;P) missed the case where redundant (changing nothing) consensus items should cause `process_consensus_item` to not store it. This was supposed to be signaled by returning an Error(?), which is not a good API, IMO, and no wonder we missed it.

We're using a language that is good at expressing non-trivial contracts like that, so we should definitely fix it.

The most obvious approach would be to use some kind of

```
enum ProcessCIOutcome {
  Redundant,
  OK
}
```

```
enum ProcessCIOutcome<T> {
  Redundant,
  OK(T),
}
```
to allow returning arbitrary `T` or flag redundant request, and make

```
    pub async fn process_consensus_item(
       // ...
    ) -> anyhow::Result<ProcessCIOutcome<()>> {
```

Someone mentioned that initially these kind of approaches seemed to generate too much noise.  I'm surprised that that's the case, as I would expect the module to quickly identify redundant case, return early and that's that. But if it is a problem, we could e.g. write a `try_ci_outcome!(...)` macro to deal with it, etc.

Another approach would be to just have a custom error type

```
    pub async fn process_consensus_item(
       // ...
    ) -> ProcessCIResult<()> {

enum ProcessCIError {
  Redundant,
  Other(anyhow::Error),
}
```

kind of thing. This at least in signature makes the redundant case more explicit. However, I think it fails to bring enough attention to this issue.

**Comment by dpc** [comment]
@joschisan @elsirion

**Comment by joschisan** [comment]
We actually had a similar design on master initially but it actually made verifying correctness of the code harder so I removed it again.
