### ISSUE TITLE
Client fails to initialize when federation is offline 

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4887]
If no API version is cached in the DB the client fails to initialize and returns an error. I wonder if it should just assume v0.0? That way no API endpoints would be missing from its PoV, it might just not be able to do much in the future, but you can still initialize its DB and hopefully the next restart after the federation is back fixes it. Thoughts @dpc?

**Comment by dpc** [comment]
@elsirion @justinmoon 

I fail to reproduce.

I made a devimint-env federation, joined it with a client, then stopped devimint-env. Now I call:

```
> ./target-nix/debug/fedimint-cli --data-dir ./tmp/testx dev wait
2024-04-17T19:30:55.837919Z  WARN fedimint_client: Failed to discover common api versions error=Federation rpc error {method => version), params => Null), general => Could not find a common core A
PI version)}
```

and while it fails to refresh the API version discovery, AFAICT it works just fine.

```
> ./target-nix/debug/fedimint-cli --data-dir ./tmp/testx info
{
  "federation_id": "1415f41b31d374d1c3187ffd636d60715917ba7c59ed0ba4901c7994ff28ec2f",
  "network": "regtest",
  "meta": {
    "federation_name": "testfed"
  },
  "total_amount_msat": 0,
  "total_num_notes": 0,
  "denominations_msat": {}
}
```


Hmmm. I guess it is possible to be in the state where one have the config in the database, but not the initial version discovery... . One peer would give you a config, but Federation as a whole is not initialized...

**Comment by dpc** [comment]
>  Hmmm. I guess it is possible to be in the state where one have the config in the database, but not the initial version discovery... . One peer would give you a config, but Federation as a whole is not initialized...

By default in devimint-env federation I can't reven repro that, because the invite code doesn't have the hash:

```
2024-04-17T20:04:01.655779Z DEBUG fedimint_api_client: Downloading client config from InviteCode([Api { url: SafeUrl(ws://127.0.0.1:10454/, has_password=false, has_username=false), peer: PeerId(0)
 }, FederationId(FederationId(9fe4da4049be422652215d8e0a1f436b1971f5b0a25fe431ef31da57bd3dd561))])
```

So trying to download the config fails in the first place, because the query strategy fails.

**Comment by justinmoon** [comment]
dev call: do we have a check that the config we re-download matches the config we originally downloaded?

**Comment by elsirion** [comment]
If it was ever an issue https://github.com/fedimint/fedimint/pull/4998 fixes this afaik
