### ISSUE TITLE
Simplify meta module CI proposal logic

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4895]
> When looking at it with @joschisan we noticed that this could be further simplified, but getting a correct version of the code was more important to me than reducing the complexity to its minimum. We can do that later since it's only the submission logic.

_Originally posted by @elsirion in https://github.com/fedimint/fedimint/pull/4836#discussion_r1558180646_

**Comment by dpc** [comment]
IMO it's not worth keeping around issues like that. Either describe the simplification so it can be done right away, or it's not actionable.

**Comment by elsirion** [comment]
The idea we had doesn't work without breaking consensus compatibility, see #4949.
