### ISSUE TITLE
Client Wallet Module redesign

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4897]
I'm going back to trying to implement wallet module recovery, as a part of #1477, and I'm going to write out some thoughts on the matter.

We have a derivation scheme, similar to ecash, where we keep track of a counter, and derive peg-in tweak, etc. for every deposit deterministically.

So on recovery we can rederive, compare with external sources (Federation history and/or Bitcoin node). The goal of the recovery is to re-create client state machines that would made sure to turn .

First observation is that unlike Ecash, this can never really going to be precise. When we create a deposit address it is not recorded anywhere in the Federation history, while the address can be given away and it's unclear when/if we can expect the Bitcoin transaction output to this address.

This fact ties back to the "historical peg-in addresses" problem. Where client ignores subsequent deposits to the same address.

OK, so it's not precise, but can be "eyeballed". There are basically two approaches:

1. We can go sequentially though derived peg-in addresses and compare against Bitcoin node to find first place where N consecutive addresses where never deposited on chain, assume this is where the Client stopped, and start peg-in state machines for around that spot (backward and forward). This is relatively fast and inexpensive, especially assuming most clients will not be doing many if any deposits, but has a disadvantage of sending out user's deposits addresses in quick succession and possibly linking them together.

2. Go through Federation history and find all the addresses in the derived deposit address chain that were used. This, just like in ecash, has to be done assuming some "N"
addresses pre-derived at any point.  The highest address that haven't had a deposit is somewhere around the place where user left off, though we might need to spawn state machines for claiming deposits on +X consecutive addresses from that point, as the user might have generated them.

Now the 1 and 2 can be combined. Recovery would first do 2. to collect all the "already claimed" addresses and place where the user probably left-off, and then scan against the Bitcoin node for for ones with still pending deposits.

Now this made me think, that the whole recovery thing here might be just a part of a bigger puzzle. To support claiming funds deposited to historical address the client wallet module will need to do some kind of "periodic checking the on chain addresses for deposits" anyway, which overlaps with recovery process. Designing for the two together might actually save us work.

The client wallet module db state could track:

* `next_pegin_address_derivation_idx : u64`
* collection of `derived_on_chain_deposit_address : bitcoin::Address` -> `{ derived_at: SystemTime, next_check_time: SystemTime }`
* `claimed_peg_ins: bitcoin::OutPoint`

This way the normal module operation could turn into a background loop, that wakes up from time to time, finds the address with a minimim `next_check_time`, quries a node if there's a deposit to an address that is not yet `claimed_peg_ins` and spawns a new SM if that's the case, otherwise just updates `next_check_time` and goes back to sleep.

The recovery would then be about following Federation history and populating the db from it. `next_pegin_address_derivation_idx` would be last claimed address' index + small constant (2?), `derived_on_chain_deposit_address` just all addresses derived from the index, with `next_check_time` set based on the "how far in the past" these addresses were. And `claimed_peg_ins` are just all the claimed deposits found already in the Federation history. 

After populating the initial db state, the recovery would just let the normal background loop of the module take the wheel.

Notably in such an arrangement, even if recovery was no-op, the client would eventually "recover" all deposits, as long as the client re-derives deposits addresses.

Module backup would contain basically whole state + session_count, making recovery from a snapshot possible.

I see 2 stages of wallet recovery implementation:

* implement the background loop along with new state tracked in the DB; this would fix claiming deposits to old addresses
* implement backup + recovery

Will let this sit for some time and gather some feedback.

**Comment by dpc** [comment]
@elsirion

**Comment by elsirion** [comment]
~Sounds reasonable.~ After writing this I actually like the idea quite a bit more :smile: 

I'm not a fan of permanently querying all old addresses for privacy reasons and would prefer a trigger-based approach where users can request checking an address again, but it's not too strong a preference (and can be addressed with this approach).

I think we'd need two new DB entries:
* `address_index -> time_of_creation, next_check_time` (defaults to time of recovery I guess)
* `address_index, btc_out_point -> ()` to know which UTXOs were claimed already

In this model we'd also only start the SM once a transaction has been detected, to avoid code duplication. We could experiment with different poll intervals and maybe drop polling altogether eventually and add a "restart polling" function for people really insistent on address reuse.

The main task of recovery would then be to re-populate these two tables for all addresses that ever saw any transactions plus gap limit many after the last one.

**Comment by dpc** [comment]
This has  all been implemented.
