### ISSUE TITLE
Gateway CLI validate the routing fees input

### ISSUE THREAD

**Issue by hensg** [fedimint/fedimint#4914]
Gateway cli could validate the input for routing-fees instead of returning a `500 Internal Server Error`

```
$ gateway-cli set-configuration --routing-fees 2000
Error: Bad status returned 500 Internal Server Error
```

```
$ gateway-cli --version
fedimint-gateway-cli 0.3.0-rc.3
```

**Comment by douglaz** [comment]
Also reproducible on `fedimint-gateway-cli 0.4.0-alpha`

**Comment by justinmoon** [comment]
Gateway should also get better at returning status codes and error messages explaining what is wrong. https://github.com/fedimint/fedimint/issues/3966 and https://github.com/fedimint/fedimint/issues/3905 are related.
