### ISSUE TITLE
Refactor mint note selection and make note selector spend excessive notes.

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#4923]
I don't know if this is going to be worth doing, since I've seen some denomination-less ecash design work, but while working on #4922 (which is more of a bandaid), it occurred to me that `NotesSelector::select_notes` has a weird interface.

It currently works taking "stream of notes" `stream: impl futures::Stream<Item = (Amount, Note)> + Send` as an input, but that's completely unnecessary and actually detrimental to trying to implement better note selection.

First - Ecash notes are fungible, so we don't need a list of notes. We just need to know how many notes in each given tier we have (aka `pub struct TieredSummary(Tiered<usize>)`), and produce how many notes of each tier we need to use (again, `TieredSummary`). This would make note selection a simple (from API perspective) function, easy to test and decoupled from database and even notes details.

Dealing with a stream might seem like an optimization, but in practice - how many notes does a client supposed to have. < 500, all sitting next to each other in sibling BTreeNodes of the database. Reading them all in is not an issue, and even if it was, it would be better to just maintain a in-memory `TieredSummary` copy and avoid reading from the db altogether.

After this is implemented, it should be easier to implement note selection that would try to spend notes from tiers with excessive amounts first, which again - requires knowing all notes upfront anyway.

**Comment by dpc** [comment]
From @elsirion 's comment

> I think to remember that the slow thing about querying notes was decoding BLS curve points (and we'd only do that for the notes we actually want ideally).

We are doing some heavy CPU processing while reading stuff from the DB? That's no great.

What if instead of complicating usage to avoid it, we just have a parallel type that decodes note details as raw bytes. We can use the real type only when we intend to need the details.

**Comment by elsirion** [comment]
Needs benchmarking. When I wrote my thesis about Fedimint ages ago I had to keep the wallet in memory for latency benchmarks. Later this was supposedly fixed by streaming notes, but I don't remember the details anymore. A lot of 1ms operations also add up.

Another clue might be that reading and decoding an entire federation DB of a few MB for analysis took a few minutes when I last did it with Fedimint 0.1, maybe we improved that though.

**Comment by dpc** [comment]
TODO:

* [ ] write deserialization of notes bench
* [ ] if indeed to slow (1ms * 100 or even 300 is too slow), make a type that skips decoding.

@elsirion Are you OK on the idea to just read counts of notes using a different type, and then just pick only the nodes we need from the DB?

**Comment by dpc** [comment]
See #4952 for the benching.

**Comment by elsirion** [comment]
Also loading from DB doesn't seem to add much overhead:

```
load 1000 e-cash notes from DB
                        time:   [104.47 ms 104.99 ms 105.58 ms]
```

**Comment by elsirion** [comment]
> @elsirion Are you OK on the idea to just read counts of notes using a different type, and then just pick only the nodes we need from the DB? Seems much flexible and robust than trying to read them in order etc.

Doesn't sound like we need that after benchmarking? Just load the notes and run whatever selection algorithm we want in memory.

**Comment by dpc** [comment]
Largely completed now. Notes are loaded without decoding them, so it's fast.
