### ISSUE TITLE
Remove `validator` dependency

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4935]
>  We can probably get rid of this dep by implementing some custom serde code. Iirc I only used it for one struct where I wanted some invariants enforced and I guess I was just too lazy to do it manually.

https://github.com/fedimint/fedimint/blob/a3b9990ebcc5690f67b6a8e8895d8a9024bab77c/modules/fedimint-wallet-common/src/txoproof.rs#L20-L31

_Originally posted by @elsirion in https://github.com/fedimint/fedimint/pull/4934#pullrequestreview-1995208073_

**Comment by Minimega12121** [comment]
can you please assign this to me I am working on fixing it by 
removing the validator dependency from the code and replacing the use of the Validate trait and ValidationError with custom validation logic.

**Comment by elsirion** [comment]
Just open a PR :)
