### ISSUE TITLE
Module-specific endpoint constants should live in their respective modules

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4936]
> Unrelated to the PR: The module-specific ones should be in the `fedimint-*-common` imo.

_Originally posted by @elsirion in https://github.com/fedimint/fedimint/pull/4930#discussion_r1561554815_

**Comment by Minimega12121** [comment]
Could you please assign this issue to me. If I am right, the main task is to move the constants or endpoints that are specific to a particular module or part of your codebase, and define them within that module itself rather than having them defined globally or in a different module.

**Comment by elsirion** [comment]
Yes, one should not have to touch `fedimint-core` to change an API endpoint in e.g. `fedimint-ln-server/client`. Instead these module specific constants should live in a new constants rust module inside e.g. `fedimint-ln-common` (in the case of the lightning module).

**Comment by tvolk131** [comment]
I believe #5048 fixed this.
