### ISSUE TITLE
`just test-upgrades "v0.3.0 current"` fails

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#4999]
`just test-upgrades "v0.3.0 current"` fails

```
Error: Polling gateways registered failed after 93 retries (timeout: 60s)

Caused by:
    assertion failed, left: 1 right: 2
```

We'll succeed if we first upgrade from an earlier version (e.g. `just test-upgrades "v0.2.2 v0.3.0 current"`)

**Comment by m1sterc001guy** [comment]
Was there any additional logs from the gateway that failed to register?
