### ISSUE TITLE
Flaky load_test_tool_test

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#5000]
Test: load_test_tool_test FM: current CLI: current GW: v0.2.1
CI failures: https://github.com/fedimint/fedimint/actions/runs/8727469044/job/23945038328

```
00:00:38     Error: Insufficient balance: requested 1024 msat but only 512 msat available
```

**Comment by dpc** [comment]
Dup #4917 possibly.

**Comment by bradleystachurski** [comment]
Ahh yep, looks like a dup. Closing in favor the original.
