### ISSUE TITLE
Token? Coin? Note?

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#501]
We say a fedimint wallet owns "ecash". That works pretty well as a plural word.

But what to call the singluar? Coin? Token? Note?

**Comment by dpc** [comment]
From the meeting:

* ecash - blinded aggregated tokens from them mint
* (ecash) note - single nonce with a given denomination; `note = nonce + signature`
* `BlindNonce` - just blinded message, unsigned yet by the mint

**Comment by dpc** [comment]
We landed the rename, and I think we will just keep renaming stuff as we go.
