### ISSUE TITLE
Extract protobuf definition and generated code into separate crate

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#5057]
We stuffed the protocol buffer definition into the Lightning Gateway crate and never moved it. Ideally this would be inside a lightweight crate by itself so only crates that need gRPC/protocol buffers depend on it. Currently anything that depends on `ln-gateway`, such as `fedimint-testing` needs to have `protoc` defined, which makes it hard for downstream crates to integrate `fedimint-testing`

**Comment by justinmoon** [comment]
dev call: we could check-in protobuf definitions, but need CI to check it and just command to update.

Could also switch away from protobuf towards JSON-RPC which is used elsewhere (should be separate issue)
