### ISSUE TITLE
Don't split e-cash when aborting OOB spends

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#5069]
After splitting e-cash inputs into single notes cancelling offline sends leads to each of the original notes to be split into smaller ones due to how our output generation algorithm works. This leads to slowdowns and enormous inefficiency.

**Comment by bprice6** [comment]
Just one thing we've noticed - this could help the Fedi app by improving performance / reduce slowness any time someone wants to re-issue notes to themselves.
