### ISSUE TITLE
Backward compat againg `v0.3.0-rc.1` is failing due to unavailable dkg cli

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#5145]
Backward compat againg `v0.3.0-rc.1` is failing, as it seems to try to use new `dkg` cli, which is not in this version. The condition in the code code is:

```
            if fedimint_cli_version >= *VERSION_0_3_0_ALPHA {
                run_cli_dkg(params, endpoints).await?;
            } else {
                // TODO(support:v0.2): old fedimint-cli can't do DKG commands. keep this old DKG
                // setup while fedimint-cli <= v0.2.x is supported
                run_client_dkg(admin_clients, params).await?;
            }
```

But that doesn't seem right.

```
00:00:02 2024-04-28T07:00:06.209208Z DEBUG spawn{task_name="JitTry alloc::sync::Arc<devimint::federation::Federation> value"}: fm::devimint: stderr output=error: unrecognized subcommand 'dkg'
00:00:02
00:00:02 Usage: fedimint-cli admin <COMMAND>
00:00:02
00:00:02 For more information, try '--help'.
```

```
00:17:24 dpc in 🌐 ren in …lab/fedimint/fedimint-wrk-1  24-04-27-0.2-was-supa-slow [$!?] is 📦 v0.4.0-alpha 🦀v1.77.2 ❄️
> /nix/store/6m5nkg73a1ziqhk8k3imixvz2wrbdh9y-fedimint-cli/bin/fedimint-cli --version
fedimint-cli 0.3.0-rc.1
00:17:28 dpc in 🌐 ren in …lab/fedimint/fedimint-wrk-1  24-04-27-0.2-was-supa-slow [$!?] is 📦 v0.4.0-alpha 🦀v1.77.2 ❄️
> /nix/store/6m5nkg73a1ziqhk8k3imixvz2wrbdh9y-fedimint-cli/bin/fedimint-cli admin
Usage: fedimint-cli admin <COMMAND>

Commands:
  status                  Show the status according to the `status` endpoint
  audit                   Show an audit across all modules
  guardian-config-backup  Download guardian config to back it up
  help                    Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```

**Comment by bradleystachurski** [comment]
What is this failing against? It looks like the PR that bumped to `v0.3.1-rc.1` passed back-compat.

https://github.com/fedimint/fedimint/pull/5030
https://github.com/fedimint/fedimint/actions/runs/8757485989/job/24036190539

Also, the output from above shows `0.3.0-rc.1` for the version

```
00:17:24 dpc in 🌐 ren in …lab/fedimint/fedimint-wrk-1  24-04-27-0.2-was-supa-slow [$!?] is 📦 v0.4.0-alpha 🦀v1.77.2 ❄️
> /nix/store/6m5nkg73a1ziqhk8k3imixvz2wrbdh9y-fedimint-cli/bin/fedimint-cli --version
fedimint-cli 0.3.0-rc.1
```

**Comment by bradleystachurski** [comment]
I verified locally `just test-compatibility` passes against `v0.3.1-rc.1` (https://github.com/fedimint/fedimint/commit/a12af373eca15f62eff90cd17521aa827bf3bfa2)

**Comment by dpc** [comment]
@bradleystachurski In the output I did v0.3.0-rc.1, so I guess I misstyped it.


Can you try

```
./scripts/tests/test-ci-all-backcompat.sh v0.3.0-rc.1
```

?

**Comment by dpc** [comment]
v0.3.0 passes, so I guess it might not be worth to fix.

**Comment by bradleystachurski** [comment]
Ahh yep, I'm also getting failures vs `v0.3.0-rc.1`

**Comment by bradleystachurski** [comment]
Shoot, I'm getting a failure running `just test-compatibility v0.3.0` against master (https://github.com/fedimint/fedimint/commit/0d95d32bec03bcc578debcd34e63422809ca1f99). The failure is the same as https://github.com/fedimint/fedimint/issues/4999, so perhaps the root issue is the same.

**Comment by bradleystachurski** [comment]
Tracking in https://github.com/fedimint/fedimint/issues/5156

**Comment by dpc** [comment]
> Shoot, I'm getting a failure running `just test-compatibility v0.3.0` against master (https://github.com/fedimint/fedimint/commit/0d95d32bec03bcc578debcd34e63422809ca1f99). The failure is the same as https://github.com/fedimint/fedimint/issues/4999, so perhaps the root issue is the same.

I thought I tried it and it passed but I was distracted.

**Comment by bradleystachurski** [comment]
> I thought I tried it and it passed but I was distracted.

No worries! I observed flakiness on the failures with `just test-upgrades "v0.3.0 current"`, so it's possible it was successful on your end but flaked on my end.
