### ISSUE TITLE
Remove usage of `assume_checked()`

### ISSUE THREAD

**Issue by tvolk131** [fedimint/fedimint#5203]
Follow-up to #2356

Bitcoin v30 introduced the concept of checked and unchecked addresses. While migrating over from v0.29 to v0.30, I called `assume_checked()` wherever necessary to make the compiler happy. Now that the migration is complete, we should remove these calls and instead use [`require_network()`](https://docs.rs/bitcoin/0.30.2/bitcoin/address/struct.Address.html#method.require_network).

Edit: See [this comment](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/CHANGELOG.md#changes-to-and-involving-the-network-type) in the changelog for `bitcoin` v0.32.0 which indicates that the work here might not be that important.

**Comment by mubarak23** [comment]
@tvolk131 can you add more context to this, i want to work on it,

kindly assign

**Comment by tvolk131** [comment]
> can you add more context to this

Sure! We currently rely on the rust [`bitcoin` crate v0.30.2](https://crates.io/crates/bitcoin/0.30.2). In this version and all newer versions (for now), the [`Address`](https://docs.rs/bitcoin/0.30.2/bitcoin/address/struct.Address.html) type has a [`NetworkValidation`](https://docs.rs/bitcoin/0.30.2/bitcoin/address/trait.NetworkValidation.html) generic parameter attached. The purpose of this is to ensure that bitcoin addresses from the wrong network are used (e.g. we don't want to accidentally send mainnet funds to a testnet address). Whenever addresses are deserialized (received over the wire, loaded from disk, etc...) they are unchecked. They can become checked either by calling [`assume_checked()`](https://docs.rs/bitcoin/0.30.2/bitcoin/address/struct.Address.html#method.assume_checked) or [`require_network()`](https://docs.rs/bitcoin/0.30.2/bitcoin/address/struct.Address.html#method.require_network). Currently we're calling `assume_checked()` everywhere since it's easier. But it's unsafe since we're not actually verifying that the address belongs to the correct network. We should instead call `require_network()` to assert that all bitcoin addresses used belong to the same network that the federation is running on.

Let me know if there's any else I can help you with!

**Comment by mubarak23** [comment]
awesome, where is the require_network() function coming from ?

**Comment by tvolk131** [comment]
I linked to it in my earlier comment

**Comment by mubarak23** [comment]
i completed the work, everytime i try to add a commit message i get the following error 

`
.git/hooks/pre-commit: line 170: parallel: command not found`


@tvolk131  can you help here

**Comment by tvolk131** [comment]
> i completed the work

Awesome, thank you!

> everytime i try to add a commit message i get the following error

It looks like your command terminal isn't running in Nix. Have you taken a look at the [Local Development](https://github.com/fedimint/fedimint?tab=readme-ov-file#local-development) section in the README? You'll need to install Nix if you haven't already:

`curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install`

Then anytime you open up a command terminal you'll run `nix develop` to enter the nix environment in that terminal. The first time you run this will take a while (~1 hour IIRC).

Let me know if you run into any trouble. I'm happy to jump into a voice call and help debug!

**Comment by mubarak23** [comment]
@tvolk131 what does this mean

```
Skipping semgrep check: not available
     Locking 0 packages to latest compatible versions
note: pass `--verbose` to see 257 unchanged dependencies behind latest
Diff in /Users/macbookpro/Documents/bitcoin-open-source/fedimint/devimint/src/external.rs at line 221:
         let tx = self
             .wallet_client()
             .await?
-            .send_to_address(&bitcoin::Address::from_str(&addr)?.require_network(), amount)
+            .send_to_address(
+                &bitcoin::Address::from_str(&addr)?.require_network(),
+                amount,
+            )
             .await?;
         Ok(tx)
     }
```

the precommit stop at the first first file changes

**Comment by tvolk131** [comment]
The git precommit hook checks to see if the rust code is formatted properly. It's suggesting you turn the line with the `-` into the several lines with the `+`s. Likely you can run `cargo fmt` to fix this.

**Comment by mubarak23** [comment]
oh
cargo fmt

i see

**Comment by mubarak23** [comment]
@tvolk131 

`require_network()`

require network to be pass as an argument in the function

can you point me to the Enum that contain all the different network, we currently support

**Comment by mubarak23** [comment]
> @tvolk131
> 
> `require_network()`
> 
> require network to be pass as an argument in the function
> 
> can you point me to the Enum that contain all the different network, we currently support

i found this helpful

https://docs.rs/bitcoin/0.30.2/bitcoin/address/struct.Address.html#parsing-addresses

**Comment by mubarak23** [comment]
am getting the following errors when i ran 

just check command

```

error[E0658]: use of unstable library feature 'lazy_cell'
  --> fedimint-bitcoind/src/lib.rs:14:22
   |
14 | use std::sync::{Arc, LazyLock, Mutex};
   |                      ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> fedimint-bitcoind/src/lib.rs:50:30
   |
50 | static BITCOIN_RPC_REGISTRY: LazyLock<Mutex<BTreeMap<String, DynBitcoindRpcFactory>>> =
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> fedimint-bitcoind/src/lib.rs:51:5
   |
51 |     LazyLock::new(|| {
   |     ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> fedimint-bitcoind/src/lib.rs:51:5
   |
51 |     LazyLock::new(|| {
   |     ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

```

@tvolk131

**Comment by elsirion** [comment]
Are you using an [up to date (master) nix dev shell](https://github.com/fedimint/fedimint/blob/master/docs/dev-env.md#use-nix-shell)? The dev shell contains the rust toolchain of the correct version and a bunch of native dependencies and helper programs you'll need. This sounds a lot like you are using some other rust toolchain that you manually installed via rustup or your OS's package manager.
