### ISSUE TITLE
Remove tracing chrome

### ISSUE THREAD

**Issue by maan2003** [fedimint/fedimint#5253]
We just don't use it.

_Originally posted by @elsirion in https://github.com/fedimint/fedimint/pull/5008#discussion_r1572345907_

**Comment by PsychoPunkSage** [comment]
Hi,
I'm interested in solving this issue.
Can you give more info about what exactly one should do?
Thank You

**Comment by maan2003** [comment]
just remove tracing chrome and all reference to it
