### ISSUE TITLE
Mobile issue

### ISSUE THREAD

**Issue by bullmoosesystems** [fedimint/fedimint#5254]
![signal-2024-05-10-121638](https://github.com/fedimint/fedimint/assets/156983044/4bcbf981-72b9-463b-81a8-b149f3e3d3cf)

I encountered a bug and now the screen is stuck here. I've tried to restart the app, restart my phone, and clear the app cache, but nothing works. I'm also unable to install the new version of the Fedi app (fedi bravo) as there's a bug about incompatibility

**Comment by maan2003** [comment]
not a fedimint issue, report to [fedi](https://support.fedi.xyz/)
