### ISSUE TITLE
Modules should return assets and liabilities through admin routes

### ISSUE THREAD

**Issue by Kodylow** [fedimint/fedimint#5314]
We're currently returning net_assets to the admin routes we use for the guardian UIs, modules should return assets and liabilities and any net calculations can be done client side.

<img width="630" alt="image" src="https://github.com/fedimint/fedimint/assets/74332828/5c8834cf-af11-4cea-8c1a-584dac8338ea">

**Comment by bradleystachurski** [comment]
Thanks for flagging 👍 

We should consider this as part of https://github.com/fedimint/fedimint/issues/4283

**Comment by elsirion** [comment]
Imo we should just require modules to either hold assets or liabilities (for one asset type, if we implemented multi-asset support modules could hold assets of one type and liabilities of another), then we can just use the sign on the amount to distinguish.
