### ISSUE TITLE
Clean up/unify all the retry logic

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#5323]
We have a lot of loops with timeouts, in tests we already have the `poll*` function family, but in the main code base we still write a lot of custom code.

**Comment by maan2003** [comment]
we also have `fedimint_core::util::retry` (the best one :))

**Comment by dpc** [comment]
I suspect @tvolk131 might have largely taken care of it by now. Not sure if it's worth keeping around if we never actually get to it.
