### ISSUE TITLE
Client: Exponential back-off when waiting for on-chain confirmations

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#5353]
Right now we are spamming the blockchain API once a second once we recognized a transaction, spamming logs on error.

https://github.com/fedimint/fedimint/blob/683411413eaea4a7879b170efd9029d3636a2761/modules/fedimint-wallet-client/src/deposit.rs#L198-L267

We already do the right thing when waiting for a transaction to be recognized:

https://github.com/fedimint/fedimint/blob/683411413eaea4a7879b170efd9029d3636a2761/modules/fedimint-wallet-client/src/deposit.rs#L100-L155

Although we'd probably want to use [`fedimint_core::util::retry`](https://docs.fedimint.org/fedimint_core/util/fn.retry.html) now in line with #5323.

I think you'll touch this code anyway @bradleystachurski while working on #5274 so I assigned it to you :)

**Comment by dpc** [comment]
As `deposit.rs` is being phased out, this is probably not worth doing anymore.
