### ISSUE TITLE
Checkpoint database when completing an AlephBFT session

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#5450]
[Rocksdb has the ability to create database checkpoints in a separate directory](https://docs.rs/rocksdb/latest/rocksdb/checkpoint/struct.Checkpoint.html)

We could use this to create a checkpoint of the database when an AlephBFT session is completed. This way, if there is ever a consensus failure, guardians can recover by wiping their database and restarting from the last checkpoint where they were in consensus.

We'll want to limit the number of checkpoints retained to save on disk space. This should probably be an optional feature configurable by an environment variable in case the checkpoint operation is too heavy/expensive.

**Comment by elsirion** [comment]
To be clear: rolling back to an old DB snapshot is a last-resort operation that can allow double-spends and mess up client state in some cases (depending on the module, e.g. suddenly missing LN contracts). So any such rollback should only be available to expert users.
