### ISSUE TITLE
Exponential back-off when connecting to guardians

### ISSUE THREAD

**Issue by benthecarman** [fedimint/fedimint#5460]
I found this is where the back off happens, it seems it is linear with a max wait time of 5 seconds. Seems this can end up being pretty aggressive. In mutiny I can find if one of the guardians is down in a federation, my logs are filled with trying to connect to that guardian

https://github.com/fedimint/fedimint/blob/99b7fa570929429fd3f32dac5109092c109fdc72/fedimint-api-client/src/api.rs#L1139

**Comment by Kodylow** [comment]
@tvolk131 todo: info log on first attempt connect + successful reconnect, debug log tries
