### ISSUE TITLE
add backoff to FederationPeer::request

### ISSUE THREAD

**Issue by maan2003** [fedimint/fedimint#5489]
https://github.com/fedimint/fedimint/blob/22663ff31d80f0614bfea8ef5803508744ea2ae3/fedimint-api-client/src/api.rs#L1424

it is hammering the browser and crashed the app.

**Comment by tvolk131** [comment]
@maan2003 I tried to dig into this today but the link you put here isn't working - do you mind updating it?

**Comment by maan2003** [comment]
updated

there is no backoff in reconnect triggered by multiple concurrent requests to federation peer.

cc @dpc

**Comment by dpc** [comment]
@maan2003 I did a test. `just devimint-env`, then `killall fedimintd`, then I run `env RUST_LOG=fm::client::net=debug fedimint-cli dev api status` and see that timeouts are indeed increasing (thought I do see we need a fix).

> there is no backoff in reconnect triggered by multiple concurrent requests to federation peer.

Hmm... I don't see how this could be happening. Multiple requests to `FederationPeer<C>::request` will synchronize on `self.client.read()` and `self.client.write()`, and trigger only one reconnect, then block and synchronize again on `rclient.client.get_try()`.


So before I connect, can we confirm which version are we talking about here @maan2003 . These recent reconnection improvements are not part of 0.3.x and were unreleased yet.

**Comment by dpc** [comment]
> Also, worth mentioning that reconnection tracking is part of a `PeerClient<WsClient>` and is not persisted anywhere. If the end application was somehow re-creating `PeerClient<WsClient>` it would keep getting reset.

Oh. I think I've found something.

**Comment by dpc** [comment]
> Oh. I think I've found something.

Actually, https://github.com/fedimint/fedimint/pull/5587 is an improvement, but given it has backoff logic on its own, it shouldn't lead to hammering peers.

**Comment by dpc** [comment]
FYI. From my perspective everything looks good, after I've fixed the above issues. We had a call today where I showed more people what I looked at and why everything LGTM now.

Until there is more concrete details with latest code, I consider this fixed.

**Comment by maan2003** [comment]
I am going to close this for now, will reopen if we hit this again.
