### ISSUE TITLE
LNV2 Test Coverage

### ISSUE THREAD

**Issue by joschisan** [fedimint/fedimint#5490]
LNV2 is still missing the following tests. For the devimint tests to work we need to enable lnv2 in devimint.

- [x] (devimint) gateway registration sanity test: https://github.com/fedimint/fedimint/pull/5488
- [x] (devimint) self payment of a client with two one gateway (direct swap): https://github.com/fedimint/fedimint/pull/5500
- [x] (devimint) self payment of a client with two gateways (lightning swap) - @m1sterc001guy 
- [x] (modular) malicious incoming contract gets refunded: https://github.com/fedimint/fedimint/pull/5556
- [x] (modular) expired incoming contract cannot be decrypted and payment fails: https://github.com/fedimint/fedimint/pull/5556
- [x] (modular) expired outgoing contract is refunded unilaterally by the client - @joschisan 
- [x] (modular) incoming contract is verified - @joschisan

**Comment by m1sterc001guy** [comment]
Some additional ideas. We have coverage for most of these in v1 already.

 - (devimint): Fedimint-LN payment to LND HOLD invoice
 - (devimint): Payment from LND/CLN into Fedimint via one gateway
 - (modular): Cannot pay expired invoice
 - (devimint): change gateway federation fees, outgoing/incoming payment and verify that gateway takes correct fees
 - (devimint): payment between two federations with two separate gateways
 - (devimint): payment between two federations with one gateway
 - (modular): Can receive Pay-To-Pubkey
 - (modular): cannot pay invoice from another network (e.g signet)
 - (modular): try to pay an invoice without attaching gateway fees, verify gateway rejects it.

**Comment by joschisan** [comment]
@m1sterc001guy with Pay-To-Pubkey I assume you mean receiving to someone else's pub key? If so that does not need to be testes as every regular receive is just a pay to pub key with your own key.

**Comment by m1sterc001guy** [comment]
Perhaps we could add a test that uses a tweaked public key, like we do for v1

**Comment by Kodylow** [comment]
Closing this, @m1sterc001guy reopening issue with remaining ideas / tests
