### ISSUE TITLE
Investigate outgoing LN payments error log

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#550]
When testing #533 I got the following log from the gateway in cln:

```
2022-09-10T13:18:36.937Z **BROKEN** plugin-ln_gateway: error=Federation client operation error: MintApiError(CoreError(MismatchingVariant(\"ln::outgoing\", \"other\")))
```

Everything seems to have worked, the GW paid the recipient and also received the money from the outgoing contract.

**Comment by justinmoon** [comment]
Yea this one is really weird. I spent a couple hours debugging this a week ago but didn't figure it out ...

**Comment by justinmoon** [comment]
Closing this one. So much has changed with the gateway since september that we should just re-open if we see it again.
