### ISSUE TITLE
gateway-cli backup and restore not implemented, bad error messages

### ISSUE THREAD

**Issue by Kodylow** [fedimint/fedimint#5567]
These are exposed in the gateway cli for all gateay types but all unsupported, the error gets eaten by the gateway and not surfaced through the cli:

https://github.com/fedimint/fedimint/blob/df1540cfd39373f492eefbe3c5556f99b4ac3996/gateway/ln-gateway/src/lib.rs#L1155-L1171

![image](https://github.com/fedimint/fedimint/assets/74332828/8b27822f-3c7f-470a-9e99-f127ca2d8b6a)

![image](https://github.com/fedimint/fedimint/assets/74332828/57c1fcff-0747-4d3a-a2f3-6a9729b85fdf)

**Comment by elsirion** [comment]
Related to #4446.

**Comment by Kodylow** [comment]
closing
