### ISSUE TITLE
Idea: do not put bitcoin transaction into fedimint peg-in input

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#5585]
Maximum Fedimint consensus item is 64K (or something like it), and we would even want it smaller. In peg-in inputs, we need to embeed the whole bitcoin transaction, which can be even almost 1MB in size. These two things don't square.

Here is the scheme that would restore the order in the wallet module galaxy:

* Client submits peg-in proof (txproof + transaction) via a new api endpoint.
* Upon verifing the correctness of the proof and the fact that it does belong to the federation wallet, the peer submits a new module wallet consensus item that given txid in fact correctly pegs in X amount.
* Once client verifies (via same/another call) that *threshold* amount of peers processed *threshold* amount of votes approving a given tx, the client is free to actually submit a tx with a wallet peg-in input, which now only needs to contain txid, amount and signature.

It's a big of a complication, but it reliably gets rid of onchain tx bloat and possibility of hitting the constrain. As far as I understand the client code, it should fit quite well into it. Everything here is possible to do in a backward-compat way.

**Comment by bradleystachurski** [comment]
High level I think this is a good approach. The UX remains the same for peg-ins and doesn't materially change requirements for running fedimintd.

I'm curious if there's a solution that will allow us to prune the proof after the input is claimed while preserving the ability for a node to resync. I don't believe we can prune using this approach since the module consensus item is in a signed session outcome.

**Comment by dpc** [comment]
> I'm curious if there's a solution that will allow us to prune the proof after the input is claimed while preserving the ability for a node to resync.

I don't understand @bradleystachurski . In the method described above the proof is never added to consensus history. So there is nothing to prune.

**Comment by bradleystachurski** [comment]
> Upon verifing the correctness of the proof and the fact that it does belong to the federation wallet, the peer submits a new module wallet consensus item that given txid in fact correctly pegs in X amount.

Oh gotcha, I misinterpreted this as submitting the proof as a module consensus item, but a peer only submits that they've verified the proof for a tx outpoint and amount without persisting the proof.

I think that solves exactly what I was hoping 🙂

**Comment by benthecarman** [comment]
if using bitcoind you would probably need to enable txindex=1, however, many applications require this already so probably not a huge ask

**Comment by dpc** [comment]
> if using bitcoind you would probably need to enable txindex=1, however, many applications require this already so probably not a huge ask

@benthecarman 
Nothing need to change in this area. Right now we rely on client submitting txproof and transaction. They would still do that, except in the federation history we wouldn't put the whole thing, but attestations of guardians that they verified it.

This is inspire by Segwit - observation is that once actually verified, the proof (witness) is no longer all that useful. In our case any 3rd party can verify independently after the fact that the peg-in indeed occur, using their own node. In the Federation history we only need to ensure *threshold* of peers verified it.

**Comment by bradleystachurski** [comment]
@dpc do you think this work is blocked by consensus version votes (https://github.com/fedimint/fedimint/pull/5568)? Also, would you be okay if I tackle this or were you hoping to work on it?

**Comment by joschisan** [comment]
This does not require consensus version votes

**Comment by dpc** [comment]
> This does not require consensus version votes, merely one additional consensus item and input variant.

And a synchronized shutdown.

> Also, would you be okay if I tackle this or were you hoping to work on it?

Honestly, I always hope somebody else is going to do the actually hard part. :)

**Comment by bradleystachurski** [comment]
@joschisan mentioned out-of-band interest and bandwidth to tackle this, so I'm assigning your way. Thanks!

**Comment by joschisan** [comment]
This is resolved and will be shipped in 0.6. Not It will not possible to exceed it as the only information included in the Fedimint transaction is the bitcoin outpoint.
