### ISSUE TITLE
Backport coordinated shutdown to v0.3

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#5601]
* [x] Backport API endpoint PR (https://github.com/fedimint/fedimint/pull/5194)
* [x] Create CLI tool to call the API and backport that too

**Comment by bradleystachurski** [comment]
Both the endpoint and admin cli have been backported to `releases/v0.3` and we cut `v0.3.3-rc.0` that includes these changes.

I'm tracking upgrade paths in https://github.com/fedimint/fedimint/issues/5649
