### ISSUE TITLE
Test v0.3.3 and v0.4.0 upgrade paths

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#5649]
## v0.3.3-rc.0 and v0.4.0-rc.0

- [x] v0{2.1 .. 3.2} -> v0.3.3-rc.0
- [x] v0.3.3-rc.0 -> v0.4.0-rc.0

## v0.3.3-rc.1 and v0.4.0-rc.1

- [x] v0{2.1 .. 3.2} -> v0.3.3-rc.1
- [x] v0.3.3-rc.1 -> v0.4.0-rc.1

## v0.3.3-rc.2 and v0.4.0-rc.2
- [x] v0{2.1 .. 3.2} -> v0.3.3-rc.2
- [x] v0.3.3-rc.2 -> v0.4.0-rc.2

## v0.3.3-rc.2 and v0.4.0-rc.3
Only bumping v0.4.0-rc.3, so only need to test upgrade path from v0.3.3-rc.2
- [x] v0.3.3-rc.2 -> v0.4.0-rc.3
---

Since tests aren't currently running in CI, I'm persisting the logs on my fork starting with `*-rc.2`. Separate branches are needed until the coordinated shutdown logic is merged to master.

https://github.com/bradleystachurski/fedimint/tree/upgrade-tests/to-0.3.3rcs
https://github.com/bradleystachurski/fedimint/tree/upgrade-tests/0.3.3-to-0.4.0

**Comment by elsirion** [comment]
Do we know what's wrong with `v0.2.1 -> v0.3.3-rc.0`? Any test failure that relates to it? Not super critical to support, but might be indicative of other problems.

**Comment by bradleystachurski** [comment]
Nothing wrong, I just haven't run the upgrade test for `v0.2.1 -> v0.3.3-rc.0`.

I needed to refactor the upgrade tests to run in sequence since running in parallel was causing flakiness on my local env. Running the upgrade tests in sequence takes a long time and I wanted to switch focus to testing the coordinated shutdown logic for `v0.3.3-rc.0 -> v0.4.0-rc.0`, which passes 🎉 

I kicked off the test for `v0.2.1 -> v0.3.3-rc.0` and should have results a bit later this morning.

**Comment by bradleystachurski** [comment]
For simplicity, I'm changing this issue to track all release candidates for v0.3.3 and v0.4.0. I'll continue editing the description as upgrade paths are verified.

**Comment by bradleystachurski** [comment]
Seeings errors running upgrades tests for fedimint-cli v0.3.3-rc.1 -> v0.4.0-rc.1

```
Error: Polling trying-to-connect-to-peers failed after 110 retries (timeout: 60s)
```

Stil investigating

**Comment by bradleystachurski** [comment]
All upgrade tests for `*-rc.2` pass. We'll need to cut another release candidate once we backport a fix for https://github.com/fedimint/fedimint/issues/5706

More context in [discord](https://discord.com/channels/990354215060795454/990354215878688860/1263909869786890394)

**Comment by bradleystachurski** [comment]
CI passing for the latest release candidates: https://github.com/fedimint/fedimint/pull/5752

**Comment by bradleystachurski** [comment]
`v0.4.0` is released so we can close
