### ISSUE TITLE
migration complete log after every client command

### ISSUE THREAD

**Issue by Kodylow** [fedimint/fedimint#5657]
this info log shows up after every client command after migrating client to v1:

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/d58fa862-eb18-450b-82e4-54bbb00a63c8">

**Comment by Kodylow** [comment]
@dpc

**Comment by dpc** [comment]
@Kodylow I checked out current `master`. I start `just devimint-env` and run `fedimint-cli` commands and I see no messages.
