### ISSUE TITLE
Get Scheduled shutdown and cancel scheduled shutdown

### ISSUE THREAD

**Issue by Kodylow** [fedimint/fedimint#5669]
me and @bradleystachurski are adding the scheduled shutdown to the UI, we need to be able to see our scheduled shutdown info after we've scheduled it, and we need to see the other guardians' scheduled shutdowns. Recommend we stick this info in `PeerStatus` similar to how we handle `flagged`

**Comment by elsirion** [comment]
Fixed in #5684 afaik
