### ISSUE TITLE
Payment history

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#569]
Client library should be able to produce an array of payments.

I have a [branch](https://github.com/fedimint/fedimint/compare/master...justinmoon:fedimint:history) that implements a very simple version of this for [Fluttermint](https://github.com/futurepaul/fluttermint). But we should probably store more metadata than just `paid` e.g. "timestamp" or perhaps "description"? Should also think about how to include on-chain payments.

@your-sudden-death is going to take this one. Could you reply here so I can assign it to you?

**Comment by elsirion** [comment]
I think we can close this now that we have the operation log.
