### ISSUE TITLE
Bumping cargo version fails for dev dependencies

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#5699]
```
error: failed to select a version for the requirement `fedimint-dummy-common = "=0.4.0-rc.1"`
candidate versions found which didn't match: 0.4.0-rc.2
location searched: /home/nix/fedimint/modules/fedimint-dummy-common
required by package `fedimint-server v0.4.0-rc.2 (/home/nix/fedimint/fedimint-server)`
if you are looking for the prerelease package it needs to be specified explicitly
    fedimint-dummy-common = { version = "0.4.0-rc.2" }
```

This only happens for `[dev-dependencies]` in the workspace. For now, I'm manually bumping the version, however we should find a better long term solution. A simple fix is switching to `sed`.

@dpc and I spent a chunk of time on this already and it appears to be a limitation of the `cargo-workspaces` crate (https://github.com/pksunkara/cargo-workspaces).

**Comment by bradleystachurski** [comment]
Interesting note from the cargo-workspaces readme

https://github.com/pksunkara/cargo-workspaces#publish

> Note: dev-dependencies are not taken into account when building the dependency graph used to determine the proper publishing order. This is because dev-dependencies are ignored by cargo publish - as such, a dev-dependency on a local crate (with a path attribute), should not have a version field.

**Comment by dpc** [comment]
I used `sed -i 's/=0.4.0-alpha/=0.5.0-alpha/g' **.toml` to bump the version. I don't see a reason to use anything more fancy.

The comment about dev dependencies not needing version seems completely wrong to me.

**Comment by bradleystachurski** [comment]
Capturing chat with @dpc: we should consider making versions across all projects in the workspace use `{ workspace = true }`, so bumping only requires updating the root Cargo.toml

**Comment by bradleystachurski** [comment]
`sed **.toml` didn't seem to find all the Cargo.toml files recursively. This worked for me locally

```
find . -name 'Cargo.toml' -exec sed -i 's/0.4.0-rc.6/0.4.1-rc.0/g' {} +
```

**Comment by dpc** [comment]
> `sed **.toml` didn't seem to find all the Cargo.toml files recursively.

That works in fish, maybe in some other shells that support better globing, but not in bash.
