### ISSUE TITLE
incorrect assumption about empty database

### ISSUE THREAD

**Issue by maan2003** [fedimint/fedimint#5706]
https://github.com/fedimint/fedimint/blob/50e895058b2e01b95df39a0439b19dd06dd6a0d7/fedimint-core/src/db/mod.rs#L1934-L1937

this is incorrect because external application (client integrators) may store data in the database ExternalReservedStart)

**Comment by dpc** [comment]
We should probably filter only non-external prefixes here.

**Comment by dpc** [comment]
Hmm... The client side should be going through:

https://github.com/fedimint/fedimint/blob/50e895058b2e01b95df39a0439b19dd06dd6a0d7/fedimint-client/src/db.rs#L458

?

**Comment by dpc** [comment]
Actually, no, it does not.
