### ISSUE TITLE
Idea: long-lived federations in staging environment for testing upgrades

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#5727]
Once we have a release candidate that passes all upgrade tests, it would be useful to attempt upgrading a long-lived federation in a staging environment.

**Comment by bradleystachurski** [comment]
@dpc Assigned you since you started setting up the hetzner boxes today

**Comment by dpc** [comment]
Status update: the boxes are set up and deployed: https://github.com/fedimint/fedimint-infra/blob/main/hosts/fedimintd/fedimintd.nix , but I was unable to pass DKG. Might try again with more stable version of the ui that is entirely client-side.

**Comment by dpc** [comment]
DKG passed. 

Invite code: fed11qgqzjfmhwden5te0vejkg6tdd9h8gepdxq6zuer9wchxvetyd9kkjmn59ehhyee0waej7qgpyq2hex742xy9vvt757jzv5ehm4zpw3w5ss66zs0lxpt50e6n0y8wx3gfep0

![image](https://github.com/user-attachments/assets/b8f5dcba-da77-4fbe-ac8e-a2dd84516172)
