### ISSUE TITLE
Add perfit for upgrade tests

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#5736]
Once we migrate self-hosted runners we should add perfit to the upgrade tests workflow.

https://github.com/fedimint/fedimint/pull/5731#discussion_r1690821380

**Comment by elsirion** [comment]
Perfit migration is complete.

**Comment by bradleystachurski** [comment]
@dpc do you need to be the one to create a new `MetricId` for the upgrade tests?

https://github.com/rustshop/perfit/blob/7e9407b788063d454abed02e19315d544ca840dd/src/routes/metric.rs#L54

**Comment by dpc** [comment]
@bradleystachurski `5pReH96mSsqIeh513jJQGg`
