### ISSUE TITLE
Dependency version tracking issue

### ISSUE THREAD

**Issue by NicolaLS** [fedimint/fedimint#577]
This Issue tracks the crates we need to wait for to bump the rust-bitcoin version in our project (dependencies)
We are on `bitcoin v0.29.1` now
### Currently waiting for:
~~- [miniscript](https://github.com/rust-bitcoin/rust-miniscript) v7.0.0 with bitcoin v0.28.1~~

**Comment by NicolaLS** [comment]
### bitcoincore-rpc-json v0.15.0

**Comment by NicolaLS** [comment]
### miniscript v7.0.0

**Comment by NicolaLS** [comment]
> ### [bitcoincore-rpc-json](https://github.com/rust-bitcoin/rust-bitcoincore-rpc/tags)

 v0.15.0 with bitcoin v0.28.1

**Comment by NicolaLS** [comment]
> > ### [bitcoincore-rpc-json](https://github.com/rust-bitcoin/rust-bitcoincore-rpc/tags)
> 
> v0.15.0 with bitcoin v0.28.1

v0.16.0 with bitcoin v0.29.0

**Comment by NicolaLS** [comment]
> ### miniscript v7.0.0

v7.0.0 with bitcoin v0.28.1

**Comment by NicolaLS** [comment]
> ### [lightning](https://github.com/lightningdevkit/rust-lightning/tags)

v0.0.110 with bitcoin v0.28.1
v0.0.111 with bitcoin v0.29.0

**Comment by justinmoon** [comment]
I think it might be better to just keep notes about which crates we're waiting for updates from (e.g. miniscript for the past month or so ...)

**Comment by NicolaLS** [comment]
> 

yes you re right, felt very cumbersome like this in the first place @justinmoon

**Comment by justinmoon** [comment]
Should also mention that we're still waiting on https://github.com/ElementsProject/rust-secp256k1-zkp/pull/48 in order to get off our fork of rust-secp256k1-zkp
