### ISSUE TITLE
Investigate pending peg outs

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#5849]
Discovered while parsing utxo sets of federations in `fedimint-observer`.

https://github.com/elsirion/fedimint-observer/pull/32

Might indicate another wallet bug so I'll do some investigation.

**Comment by Kodylow** [comment]
Brad: We should panic in fedimintd if we haven't discovered a new block after some threshold
Dpc: why is not finding a new block a breaking change, the federation should sync higher as they get there and be stuck in the past temporarily
Brad: we're trying to sync to a consensus height we don't know about yet, change outputs
elsirion: this is just not the case dpc

**Comment by bradleystachurski** [comment]
Closed since the investigation is complete.

One of the takeaways that would have made investigation easier: https://github.com/fedimint/fedimint/issues/5866
