### ISSUE TITLE
LDK node returns network as `main` instead of `bitcoin` on mainnet

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#5879]
This makes the `parsed_node_info` function fail. Testnet is likely also affected. I don't see the reason for this since LDK uses the same network enum as us internally afaik.

https://github.com/fedimint/fedimint/blob/1b3fca48499793196e322734bdc48c4e84a6f0b8/gateway/ln-gateway/src/lightning/mod.rs#L206-L221

**Comment by tvolk131** [comment]
Strange... I'll dig into this tomorrow or Monday

**Comment by Kodylow** [comment]
Probably being treated like LND
