### ISSUE TITLE
Expose ability to set lightning invoice expiry

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#588]
Right now it just defaults to 1 hour.

[Here's the hook to set a custom expiry](https://docs.rs/lightning-invoice/0.19.0/lightning_invoice/struct.InvoiceBuilder.html#method.expiry_time).

**Comment by elsirion** [comment]
We should also encode the expiry in the Offer so that users can't circumvent client side checks.

**Comment by justinmoon** [comment]
> We should also encode the expiry in the Offer so that users can't circumvent client side checks.

Complication is that lightning invoices use wall clock time, but federation currently only have consensus on block height.

Perhaps we could add consensus item for wall clock time, too?

**Comment by wilfredallyn** [comment]
Can you assign this to me?
