### ISSUE TITLE
Add flag in gateway to specify whether to register to LNv1

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#5884]
`Gatewayd` currently supports running the LNv2 module and LNv1 module. This introduces a new user-facing painpoint, where an LNv2 invoice from a federation is no longer payable by an LNv1 client. One way to fix this is to enforce that gateways either run as LNv2 or LNv1. To support backwards compatibility in devimint, we'd ideally like the way to run both modules at the same time, to not increase our devimint complexity.

**Comment by Kodylow** [comment]
https://github.com/fedimint/fedimint/issues/6072
