### ISSUE TITLE
Websocket Secure (`wss://...`) doesn't work on Android

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#589]
This is the root issue https://github.com/paritytech/subxt/issues/563

Assigning this to you @elsirion

**Comment by justinmoon** [comment]
[This change](https://github.com/fedimint/fedimint/commit/736d86a82d5fbd24f8f0c767346ace372600d686) does indeed fix it on Android. Not sure about security implications ...

**Comment by elsirion** [comment]
736d86a82d5fbd24f8f0c767346ace372600d686 seems perfectly sound. Is there a PR for this already?
