### ISSUE TITLE
Wallet module should endure limited `bitcoind` outages

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#590]
Working with @Kodylow on the setup UI we noticed that `fedimintd` panics when `bitcoind` isn't running:

```
thread 'main' panicked at 'Bitcoind returned an error: JsonRpc(Transport(Timeout))', modules/fedimint-wallet/src/bitcoincore_rpc.rs:25:14
```

**Comment by elsirion** [comment]
What is your proposed alternative action? Crashing might be the right thing to do (although maybe with better logging/error reporting) to tell people to set up `bitcoind` first. Alternatively we could try to wait, but what are the chances that a wild `bitcoind` will suddenly appear? For `systemd` deployments `fedimintd` should depend on `bitcoind` anyway and not start before it.

**Comment by justinmoon** [comment]
I don't think this is much of a problem for the initial setup experience because `bitcoind` needs to run for `fedimintd` to run.

My concern is more when `fedimintd` is already running, and `bitcoind` has some downtime. Should `fedimintd` also crash?

For example, try running `./scripts/tmuxinator.sh`. Once it's up and running, `pkill bitcoind`. `fedimintd` will crash. IMO it shouldn't crash. `wallet` module should probably return error messages, but mint module should continue to operate.

**Comment by justinmoon** [comment]
Related to https://github.com/fedimint/fedimint/issues/37#issuecomment-1044491283
