### ISSUE TITLE
Flaky `bckn_electrs`

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#5917]
We recently enabled `bckn_electrs` to use the electrum backend, but it's causing flaky tests in hourly runs.

https://github.com/fedimint/fedimint/actions/runs/10538652163/job/29201381921#step:7:1708
https://github.com/fedimint/fedimint/actions/runs/10534704117/job/29192736976#step:7:4775

A quick glance seems like it's taking too long to complete

```
fedimint-test-all-wasm32-unknown-unknown-ci> 00:01:20      TIMEOUT [  60.059s] fedimint-wallet-tests::fedimint_wallet_tests on_chain_peg_in_and_peg_out_happy_case
```
https://github.com/fedimint/fedimint/actions/runs/10534704117/job/29192736976#step:7:4294

**Comment by dpc** [comment]
Haven't seen it in a while.
