### ISSUE TITLE
CLI `spend` command should make exact change

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#592]
I have a single 1000 sat note:

```
$ ./target/release/mint-client-cli ./configs info
{
  "info": {
    "total_amount": 100000,
    "total_num_notes": 1,
    "details": {
      "100000": 1
    }
  }
}
```

In this scenario, I would expect calling `spend 10` to make change and print out a 10 sat note, leaving 990 sats change in my wallet. But it just spits out the 1000 sat note:

```
$ ./target/release/mint-client-cli ~/configs spend 10
{
  "spend": {
    "token": "AQAAAAAAAACghgEAAAAAAAEAAAAAAAAAIAAAAAAAAABZ2mgoDmfyhltF12HjlSaELgtg/862n8PXpKNRjgcHqzAAAAAAAAAAmADEQmzJfuLy57wVBAJ11ys+Xm35CZ18mszDvm/sifoZgX9L5Yd+j8YM4L0ZKd8vgHPFnanhjrFjvwxldIFZFrRHx1h4mPVzsvLLqZRJh5g="
  }
}

$ ./target/release/mint-client-cli ~/configs info
{
  "info": {
    "total_amount": 0,
    "total_num_notes": 0,
    "details": {}
  }
}
```

**Comment by justinmoon** [comment]
Question: if it can't make exact change, should it fail or make change with the federation? Perhaps we should have 2 separate commands? Or 1 command and a flag?

**Comment by NicolaLS** [comment]
> Question: if it can't make exact change, should it fail or make change with the federation? Perhaps we should have 2 separate commands? Or 1 command and a flag?

A flag for that feels more appropriate than a new command, but why would we ever want to fail on this ?
