### ISSUE TITLE
LDK Gateway spamming esplora and killing ldk-node

### ISSUE THREAD

**Issue by Kodylow** [fedimint/fedimint#5965]
Found while trying to run a mainnet ldk gateway:

```
gatewayd-1    | 2024-09-03T20:54:20.699562Z  WARN ln_gateway: Failed to retrieve Lightning info: LightningRpcError(FailedToGetNodeInfo { failure_reason: "Failed get chain tip block summary: Reqwest(reqwest::Error { kind: Status(429), url: Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"blockstream.info\")), port: None, path: \"/api/blocks\", query: None, fragment: None } })" })
gatewayd-1    | 2024-09-03T20:54:20.701770Z  INFO ln_gateway::lightning::ldk: Stopping LDK Node...
gatewayd-1    | thread 'tokio-runtime-worker' panicked at /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:86:9:
gatewayd-1    | Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
gatewayd-1    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Need to set the esplora calls to something reasonable when not on regtest, add a backoff, and not kill the ldk-node if the esplora calls fail

**Comment by elsirion** [comment]
Is it about retries or the rate limits of e.g. mempool.space? I ended up using https://mempool.emzy.de/ for my LDK node GW and also set up https://mempool.sirion.io/ in the meantime to not be constrained by API rate limits anymore.

**Comment by Kodylow** [comment]
I think it's both, blockstream's api limit + we're not doing any backoff / retry logic around it

**Comment by oleonardolima** [comment]
It hasn't landed on master or any release yet, but this PR covers this problem: https://github.com/bitcoindevkit/rust-esplora-client/pull/71. It could be useful as a starting point.

**Comment by oleonardolima** [comment]
Another reference that has just been posted @ https://github.com/bitcoindevkit/bdk/issues/1120#issuecomment-2331794726

> FYI
>
> LWK is just waiting 2^(#times_it_returns_429-1) and it reliably scan on rating limited publics server such as blockstream.info and mempool.space https://github.com/Blockstream/lwk/blob/0533774f8d9b3fef2d579ad5b9bdd497ffa74165/lwk_wollet/src/clients/esplora_wasm_client.rs#L511

**Comment by Kodylow** [comment]
TODO: check if @tvolk131 mprocs speed up PR fixes this behavior

**Comment by oleonardolima** [comment]
FYI the latest release of `esplora-client` has added a retryable logic (check https://github.com/bitcoindevkit/rust-esplora-client/pull/98), in case it's helpful.

**Comment by Kodylow** [comment]
Close to being fixed, still in play @tvolk131

**Comment by tvolk131** [comment]
Re-opening since we reverted #6037
