### ISSUE TITLE
Make `recoverytool` always run in read-only mode

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#5966]
This will prevent accidentally creating an empty DB if the DB path is incorrect and we only read anyway.

**Comment by dpc** [comment]
```
    /// Open the database in read-only mode, useful for debugging, should not be
    /// used in production
    #[arg(long)]
    readonly: bool,
```

Added in 

```
commit f08256f2bfcf347cfa0266963cc105429f664823
Author: Allan Douglas <allandouglas@gmail.com>
Date:   Tue Nov 28 22:32:35 2023 +0000

    feat: added recoverytool tests
```

No idea why RO wouldn't be suitable for "production".

**Comment by elsirion** [comment]
@douglaz any idea why you left that comment there?

**Comment by douglaz** [comment]
> @douglaz any idea why you left that comment there?

Not sure. I guess the is a risk of getting a inconsistent state from the DB?

**Comment by m1sterc001guy** [comment]
Reads should always be consistent when using snapshot isolation. I think its fine to remove the comment. Not sure why the recoverytool would ever need to write into the db.
