### ISSUE TITLE
Why do we have `sqlite` in the `fedimintd` container?

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#5977]
https://github.com/fedimint/fedimint/blob/de0eced901cde24f930069f3148bcfe80edcf433/nix/flakebox.nix#L605-L613

**Comment by oleonardolima** [comment]
I might've added to it by mistake, it's only required by others that end up using `fedimint-api-client` or `ldk-gateway`. I'll take another look.

**Comment by elsirion** [comment]
Right, but guardians do use the API client too, so might be required. I'm curious if it needs to be added explicitly though, shouldn't the `fedimintd` package pull it in automatically?

**Comment by oleonardolima** [comment]
AFAIK it still requires the native linkers, at least I was getting errors running locally and in a VM. But I might be wrong and I can test it again in a clean box 🤔.

**Comment by elsirion** [comment]
I think that would mean our nix package definition is wrong, because every install of `fedimintd` needs that, not only the docker version. @dpc thoughts?

**Comment by dpc** [comment]
Adding `sqlite` to `content` will probably only result in the `sqlite` being available in the PATH. Being linked in libsqlite is taken care of elsewhere (fedimintd derivation, etc.).

**Comment by elsirion** [comment]
> Adding `sqlite` to `content` will probably only result in the `sqlite` being available in the PATH. Being linked in libsqlite is taken care of elsewhere (fedimintd derivation, etc.).

Sounds like we can just remove it then?
