### ISSUE TITLE
`GatewayBalances` should include inbound liquidity

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#5980]
This is arguably just as important as the `lightning_balance_msats`, since it determines if the gateway is able to service incoming payments. This can be deduced from `ListActiveChannels` but I think it would be useful to have an "at a glance" value like we do for `lightning_balance_msats`

```
#[derive(serde::Serialize, serde::Deserialize)]
pub struct GatewayBalances {
    pub onchain_balance_sats: u64,
    pub lightning_balance_msats: u64,
    pub ecash_balances: Vec<FederationBalanceInfo>,
}
```

**Comment by m1sterc001guy** [comment]
Just send out a PR when you have something working. Be sure to test it locally using mprocs to make sure it works.

**Comment by mubarak23** [comment]
@m1sterc001guy what is mprocs
