### ISSUE TITLE
Support LND

### ISSUE THREAD

**Issue by Kixunil** [fedimint/fedimint#6]
LND is too popular to be ignored at this point. For a while I was thinking about creating a crate with set of types and traits common to all LN implementations, which could abstract over them. I'm interested in collaborating here.

I made [`tonic_lnd`](crates.io/crates/tonic_lnd) crate but it's unfortunately for `tokio` only and this crate uses `async_std`. Maybe finally a motivation to create a unified trait for them. :D

Priority: medium

**Comment by justinmoon** [comment]
Closed by https://github.com/fedimint/fedimint/pull/1907 🎉
