### ISSUE TITLE
Panic in LN update stream

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#6000]
A user hit this panic in the wild:

https://github.com/fedimint/fedimint/blob/6e552f42657474325cc4b4980d21e577adbd5fd1/modules/fedimint-ln-client/src/lib.rs#L1223-L1231

It's unclear to me why there'd suddenly be a state that isn't expected (we check that we are dealing with the correct operation kind earlier), but fundamentally we should likely not panic on non-critical client programmer errors. Logging an error and returning none would be better here imo.

I still think that panics are great for critical code paths where broken invariants can cause loss of funds, but e.g. update streams are purely informational and inconsistencies are preferable to crashing the whole application.

**Comment by maan2003** [comment]
this was in fedi code and we fixed it

**Comment by maan2003** [comment]
also btw https://docs.rs/ra_ap_stdx/latest/ra_ap_stdx/macro.always.html

**Comment by elsirion** [comment]
> this was in fedi code and we fixed it

What are your thoughts on not panicking in such cases? At least there should be early detection of the incompatibility so we can return an error. Panicking for such a minor problem seems suboptimal.

**Comment by maan2003** [comment]
agreed, ideally fedimint-client should never panic
