### ISSUE TITLE
Self-hosted runner lost communication with server

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#6021]
Might not be worth spending much time investigating unless we start to notice this more frequently.

> Cross-compile on macos to aarch64-android
The hosted runner: GitHub Actions 9 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

https://github.com/fedimint/fedimint/actions/runs/10892012135?pr=6019

**Comment by bradleystachurski** [comment]
Seeing other occurrences https://github.com/fedimint/fedimint/actions/runs/10892017269?pr=6004

**Comment by dpc** [comment]
Could have been GHA issue, and is now 2 weeks old. Unless it re-occurs, not actionable.
