### ISSUE TITLE
Standard Preimage Definition

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#605]
[Incoming contracts define Preimages as pub keys](https://github.com/fedimint/fedimint/blob/master/modules/fedimint-ln/src/contracts/incoming.rs#L96), while [Outgoing contracts define Preimages as a 32 random bytes](https://github.com/fedimint/fedimint/blob/884206fb9d43542559c28c6ee3d143a6a50d9fd8/modules/fedimint-ln/src/contracts/outgoing.rs#L28).
Core lightning RPC plugin expects a pubkey preimage on handling `htlc_accepted` messages.

While pubkey preimages are serializable into 32 bytes, we lose guarantee of validity with the serialization, i.e. deserializing and creating a pubkey from a 32-bit slice is 'chancy' with guarantee we get a valid pubkey.

This tracks discussions and attempts at standardizing Preimage definition within Fedimint

**Comment by elsirion** [comment]
Is it really worth unifying these? Could better naming and easy conversion functions solve the problem as well?

**Comment by okjodom** [comment]
Thought I might try fix it, particularly if it makes understanding incoming vs outgoing contract interaction boundaries easier.

More importantly, I learned that `Preimage` validity is key in determining success outcome of executing a contract, but this is not explicit when we have two definitions:
- `Preimage([u8;32])` - anything goes. if it's 32 bytes of randomness, we accept it
- `Preimage(XOnlyPubKey)` - well now we care about it's validity as a pubkey. But we still call it a preimage (?)
    - this should be a restriction on the set of preimages we consider valid. _"In fedimint, we expect all preimages we use to be convertible to pubkeys?"_ <- Btw, @justinmoon is this only because cln_rpc expects a pubkey in response to `htlc_accepted`?

As for better naming, we should simply have a "pubkey" variable in all scenarios where we currently have `Preimage(XOnlyPubKey)`

With easy convertibility between `Preimage([u8;32])` and `XOnlyPubkey` especially if the type conversion helper clearly tells you that 'o hey, we have an invalid preimage here!"

My [proposal in this PR](https://github.com/fedimint/fedimint/pull/505) looks to drop `Preimage(XOnlyPubKey)` definition, while introducing `Preimage([u8;32]).to_public_key()` conversion function

**Comment by elsirion** [comment]
> is this only because cln_rpc expects a pubkey in response to `htlc_accepted`?

No, this requirement comes from how our incoming contract is constructed.

https://github.com/fedimint/fedimint/blob/d6d4e5cf52cb0842542716989a11b65630867802/modules/fedimint-ln/src/contracts/incoming.rs#L42-L44

Lightning expects it to be just some random bytes but we kinda abuse it to hide a pub key in there since it's close enough to a public key. We could totally make it a `[u8;32]` and just convert to a pub key when validating spends (maybe by having a convenient conversion function/`TryFrom` impl).

**Comment by okjodom** [comment]
> We could totally make it a [u8;32] and just convert to a pub key when validating spends from the contract (maybe by having a convenient conversion function/TryFrom impl)

Nice. You could review my (surprisingly large) PR in that light
