### ISSUE TITLE
Sort `info` results by magnitude

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#606]
Would be nice if these amounts were in order.
```
cargo run --bin mint-client-cli federations/testfed info
{
  "info": {
    "total_amount": 951520,
    "total_num_notes": 22,
    "details": {
      "10": 2,
      "1000": 1,
      "10000": 5,
      "100": 5,
      "100000": 9
    }
  }
}

```

**Comment by elsirion** [comment]
Probably easy to solve by replacing a `HashMap` with a `BTreeMap`.

**Comment by wilfredallyn** [comment]
I can do this while I'm working on  https://github.com/fedimint/fedimint/issues/591. Can you assign this to me?

**Comment by wilfredallyn** [comment]
Closed by https://github.com/fedimint/fedimint/pull/694
