### ISSUE TITLE
Mint client will try to pay a paid invoice

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#608]
```
% cargo run --release --bin mint-client-cli federations/testfed ln-pay <invoice>
{
  "ln_pay": {
    "contract_id": "c6bf42c2bd0afe5c9c51a2a179cb2494f2ef11afcad88974c14b916d478ad893"
  }
}

% cargo run --release --bin mint-client-cli federations/testfed info 
{
  "info": {
    "total_amount": 929320,
    "total_num_notes": 25,
    "details": {
      "10": 2,
      "10000": 2,
      "100": 3,
      "1000": 9,
      "100000": 9
    }
  }
}

% cargo run --release --bin mint-client-cli federations/testfed ln-pay <invoice>
{
  "ln_pay": {
    "contract_id": "5d865102339f51aaba1a08a8109413589b3806463186b229398f07b330f47d27"
  }
}

% cargo run --release --bin mint-client-cli federations/testfed info 
{
  "info": {
    "total_amount": 919220,
    "total_num_notes": 23,
    "details": {
      "10000": 1,
      "100000": 9,
      "100": 2,
      "10": 2,
      "1000": 9
    }
  }
}
```

**Comment by justinmoon** [comment]
From @elsirion: client could just keep track of invoices of every paid invoice or invoice which has a pending payment currently. This is a bit of a hack because the server doesn't enforce it. Would be better if server didn't let you try to pay a paid invoice.

**Comment by elsirion** [comment]
I think client side filtering is reasonable since it doesn't put any additional index burdens on the federation and invoices should generally only be given to a single person. If the GW can't pay the invoice (because a third party already did) the normal refund logic should apply (although you messed up already and nothing is guaranteed since *someone* got the preimage already).

**Comment by jp1ac4** [comment]
I won't be able to look at this until possibly next week so unassigning from myself for now in case someone else wants to work on it in the meanwhile.

**Comment by jp1ac4** [comment]
I've assigned this back to myself now.

@justinmoon I was able to reproduce this, although I encountered a timeout error on the second `ln-pay`. I ran the following steps after using `just tmuxinator`:
```
$ fedimint-cli ln-invoice 100 "foo"   
{                         
  "invoice": "<invoice>"
}          

$ fedimint-cli info
{          
  "federation_id": "b7e545d8330f15b616b17155b61f9b3f07190910a7fbc24197d1082ca4e53b118247ef191d195dba1859ee13f3126c0d",
  "network": "regtest",
  "meta": { 
    "federation_name": "Hals_trusty_mint"
  },         
  "total_amount": 10000000,
  "total_num_notes": 52,
  "details": {
    ...                                                                                  
  }
}

$ fedimint-cli ln-pay <invoice>
{
  "contract_id": "28f42e15f4419a1b110d2003ce68325cd90bef50f07a8884dac5ad439d024f31"
}

$ fedimint-cli info                   
{
  "federation_id": "b7e545d8330f15b616b17155b61f9b3f07190910a7fbc24197d1082ca4e53b118247ef191d195dba1859ee13f3126c0d",
  "network": "regtest",
  "meta": {
    "federation_name": "Hals_trusty_mint"
  },
  "total_amount": 9999899,
  "total_num_notes": 48,
  "details": {
    ...
  }
}

$ fedimint-cli ln-pay <invoice>
{
  "error": "CliError",
  "kind": "GeneralFederationError",
  "message": "gateway failed to execute contract", 
  "raw_error": "Outgoing payment timeout"
}

$ fedimint-cli info
{
  "federation_id": "b7e545d8330f15b616b17155b61f9b3f07190910a7fbc24197d1082ca4e53b118247ef191d195dba1859ee13f3126c0d",
  "network": "regtest",
  "meta": {
    "federation_name": "Hals_trusty_mint"
  },
  "total_amount": 9999798,
  "total_num_notes": 44,
  "details": {
    ...
  }
}
```

**Comment by jp1ac4** [comment]
For client-side filtering, will additional data need to be saved to the DB or will it be enough to use existing data? E.g. in the function `create_outgoing_output` an `OutgoingPayment` entry is inserted for the contract so perhaps this could be used for filtering if we can relate it back to the invoice.

**Comment by justinmoon** [comment]
> ... perhaps this could be used for filtering if we can relate [`OutgoingPayment`] back to the invoice.

One nuance here is that we want to be able to try an outgoing payment with gateway A, and if it fails retry with gateway B. So if we just used the `OutgoingPaymentKey` then we wouldn't know if that previous attempt succeeded or failed unless we update that key in the database after the payment succeeds or fails. Another problem here is that it doesn't seem like we can produce a `contract_id` from a given `invoice`, so I don't think we could look that key up currently.

So somehow we'll need a mapping from "invoice" -> "have we already paid?"

Ideally we could store a [payment history](https://github.com/fedimint/fedimint/issues/569) and then look this information up there. But designing that API is kind of a hairy task. It's sort of a modularization question, too. Would we want to be able to produce some kind of payment history across all modules? Not sure how feasible that is ...

A simpler alternative would be to just have a key prefix where we store payment hashes of invoices we've paid. Then we can just check whether an invoice's payment hash is in there every time we try to pay an invoice, and refuse if it is.

Make sense?

**Comment by jp1ac4** [comment]
OK thanks for explaining that. Yes I think the simpler alternative makes sense. I'll give it a try and will let you know if I have any further questions (I'll probably not have much time to work on this for another week or so).

**Comment by jkitman** [comment]
Is this required for the alpha release?

**Comment by jp1ac4** [comment]
In case you'd like this included in the alpha release, please note I might need some feedback on my draft PR before I can proceed further. Thanks.

**Comment by justinmoon** [comment]
I was just talking to @elsirion, and it sounds like this will be fixed in the new client automatically by using the payment hash as operation id: https://github.com/fedimint/fedimint/blob/77276886d8cbd3787d3dc941c9a1616e8a6c85d3/fedimint-client/src/lib.rs#L349-L351

Let's just close this as "won't fix" and focus on the new client for the alpha release.
