### ISSUE TITLE
Get rid of DATABASE_VERSION

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#6108]
It just occurred to me that one could add a db migration, and then forget to increment `DATABASE_VERSION`. Why have both? A database version could be defined just as number of defined migrations? We could just have `fn database_version` that generically calls `get_database_migrations` and counts them, and checks if its contiguous.

**Comment by dpc** [comment]
@m1sterc001guy  WDYT?

**Comment by elsirion** [comment]
I'd just go with the max key, we already just warn if a key is missing. But agree with the general idea.

**Comment by m1sterc001guy** [comment]
If I recall correctly, the original idea was that we could remove old db migrations for versions that we no longer maintain. In that case, `DATABASE_VERSION` would not be equal to the number of defined migrations. But that's such a small thing, and if we're cool with keeping that code around, then I see no problem with removing it.

**Comment by dpc** [comment]
@m1sterc001guy In that case we could require that migrations are contiguous, but do not need to start at 0.
