### ISSUE TITLE
CLN gateway connection should be authenticated

### ISSUE THREAD

**Issue by Kodylow** [fedimint/fedimint#6110]
Currently it's unauthenticated so the gateway can only run on the same local network

**Comment by Kodylow** [comment]
Might need to use certificates for this, would be ideal to just use straight password auth though.

**Comment by vincenzopalazzo** [comment]
@Kodylow you may want consider to use rune and commando, or move it to the grpc API of cln, but idk if it is a good move

**Comment by Kodylow** [comment]
1. CoreLN currently broken on macOS. Bumped last week to 0.28.1, there's some incompatibility for mac specifically.
2. Plugin is currently un-authed, removing grpc entirely and just using axum and we can use passwords + jwts. PR incoming @m1sterc001guy

**Comment by vincenzopalazzo** [comment]
>CoreLN currently broken on macOS. 

Uh, really? what is the problem on macOS?

**Comment by m1sterc001guy** [comment]
> Uh, really? what is the problem on macOS?

We reverted the change that bumped CLN to 24.08.1, so it is no longer broken, but we won't be able to increase the version in the meantime,
https://github.com/fedimint/fedimint/issues/6193#event-14770204564

Let's tackle authentication after https://github.com/fedimint/fedimint/pull/6197

**Comment by vincenzopalazzo** [comment]
>We reverted the change that bumped CLN to 24.08.1, so it is no longer broken, but we won't be able to increase the version in the meantime,
https://github.com/fedimint/fedimint/issues/6193#event-14770204564

I see, sorry about that. I have no a osx env, so I could not reproduce it :/ otherwise I could try to patch it

**Comment by elsirion** [comment]
Made obsolete by #6218 :cry:
