### ISSUE TITLE
Coordinated shutdown sanity check

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#6113]
Was discussing the coordinated shutdown mechanism with @bradleystachurski. I know we would like to prevent needing it from being used in the future, but in the event that it does need to be used, I think we should add a sanity check for auto-restarts (unless something like this already exists).

I was thinking that on a "clean" coordinated shutdown, each guardian could write an entry into their database. On the next startup, the guardian could check for the database entry and also verify that the version of the binary != to the previous version (ensuring that the user upgraded the binary and it did not just auto-restart due to systemd or docker-compose). If it is the same version as before, just kill fedimintd before spawning consensus.

Thoughts?

**Comment by elsirion** [comment]
We don't ever want to use it again ideally (just not practical for federations to coordinate, most are still on 0.3), so not worth investing into. If we are force to for some reason we can improve it.

**Comment by m1sterc001guy** [comment]
Sounds good, will close
