### ISSUE TITLE
devimint and gateway-pkgs should be pinned 

### ISSUE THREAD

**Issue by maan2003** [fedimint/fedimint#6167]
because need it in other repos that use devimint for testing

**Comment by Kodylow** [comment]
pinned on cachix

**Comment by dpc** [comment]
`gateway-pkgs` already are.

**Comment by maan2003** [comment]
we were having issues with one of fedimint-pkgs or gateway-pkgs not being pinned

**Comment by dpc** [comment]
https://github.com/fedimint/fedimint/blob/a01427b928a811d2df280abf997fe40850177a2f/.github/workflows/ci-nix.yml#L531 is the place that is supposed to pin releases in cachix

**Comment by elsirion** [comment]
This PR probably fixed it https://github.com/fedimint/fedimint/pull/6171
