### ISSUE TITLE
Make `list_operations` impl efficient

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#6191]
I left this comment a long time ago that we rediscovered it today:

https://github.com/fedimint/fedimint/blob/6249552fd55d599a4972d4c1e2bd8028e8c75b4b/fedimint-client/src/oplog.rs#L71-L78

The pagination of operation listing is horribly broken and requires a rewrite. Luckily, the second point is now possible after @dpc implemented `find_by_range` in https://github.com/fedimint/fedimint/pull/6005

**Comment by elsirion** [comment]
From deep dive (@dpc): maybe we can change the data model to make querying n entries afyer a given entry easier. Basically make the key and auto-incrementing integer.

**Comment by dpc** [comment]
@elsirion After looking a bit longer into it:

We can quickly get and cache in the memory the timestamp of the first entry in the oplog to bound the search.

Afterwards we can just fetch using forward range, e.g. `last_ts-period..=last_ts`, filter and until we have `limit`. By avoiding iterating backwards, we should get much better performance anyway. The `period` could be proportional  `period = expect_avg * limit`.
