### ISSUE TITLE
Backport bot bad credentials

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#6234]
The backport bot run fails early with `Bad credentials`

```
Retrieve pull request data for #6233
Bad credentials
Error: Bad credentials
```

https://github.com/fedimint/fedimint/actions/runs/11550958538/job/32146986382

I'd assume this is due to an expired token for `secrets.BACKPORT_TOKEN`. I don't have access to check. @dpc when you have a chance, can you please take a look?

**Comment by elsirion** [comment]
I generated a new token and updated the env var. Re-running the action worked. Thx for letting me know, I missed the email about token expiry.
