### ISSUE TITLE
Update crates.io permissions

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#6242]
Publishing to crates.io is part of the release process. Currently there are two owners, @elsirion and @dpc. I'm currently running many of the steps of the release process but unable to publish. @elsirion  when you have a chance, can you please update the permissions so I can also publish?

**Comment by elsirion** [comment]
How to automate it once I have @bradleystachurski's crates.io user name:

```bash
cargo workspaces list --json | jq -r ".[] | select(.private == false) | .location" | sed 's/Cargo.toml//' | while read CRATE_DIR; do pushd $CRATE_DIR; cargo owner --list; popd; done
```
