### ISSUE TITLE
Consider publishing to crates.io from GH workflow

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#6243]
Publishing to crates.io as part of the automated release process streamlines the workflow, however it's a potential security risk.

Thoughts @elsirion @dpc?

**Comment by dpc** [comment]
In the past we've hit bunch of issues that required manually interventions etc. . Due to cargo bugs w.r.t handling cyclic dev dependencies etc. I'm not sure if it will even work in practice.

**Comment by bradleystachurski** [comment]
Interesting, do you have any concerns about the security of automating publishing or just the potential clunkiness?

**Comment by dpc** [comment]
Security would probably be slightly better, since we would avoid dev's desktop machines. I'm only worried about clunkiness.

**Comment by bradleystachurski** [comment]
> Security would probably be slightly better, since we would avoid dev's desktop machines.

That's a great point :+1: 

> I'm only worried about clunkiness.

The benefit of automating might not be worth the headache right now, so perhaps we should close this issue and reopen if it becomes a major pain point. Does that work on your end @elsirion?

**Comment by bradleystachurski** [comment]
Dev call: Let's close and revisit if we think automating is a good idea later.
