### ISSUE TITLE
Likely memory leak

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#6334]
Fedi discovered a likely memory leak after upgrading an internal testing federation from 0.3 to 0.4. It looks very logarithmic, so it might not be a memory leak, but just a data structure with this behavior (some rocksdb in-memory index?). 

![fedi-internal](https://github.com/user-attachments/assets/902d63d6-8f8e-4696-90a7-cac2cffe9bbc)

In general this shouldn't be a huge problem for setups with automatic restart: the OOM killer will kill the process and systemd will restart it. Might still lead to wonky behavior.

Some starting points for debugging:

> 1. **Valgrind:**
> 
>    - Although Valgrind is primarily a tool for C/C++ programs, it can still be used with Rust programs to detect memory leaks. Compile your program with debuginfo and run it with Valgrind:
>      ```bash
>      cargo build --release
>      valgrind --leak-check=full ./target/release/your_program
>      ```
> 
> 2. **Heaptrack:**
> 
>    - Heaptrack tracks all memory allocations and can give detailed insights into which parts of your code are causing memory issues.
>    - To use it, install heaptrack and run it with your Rust executable:
>      ```bash
>      heaptrack ./target/debug/your_program
>      heaptrack_gui heaptrack.your_program.<timestamp>.gz  # Use GUI to analyze
>      ```
> 
> 3. **AddressSanitizer:**
> 
>    - You can compile your Rust program with AddressSanitizer to detect memory errors. Set the RUSTFLAGS environment variable:
>      ```bash
>      export RUSTFLAGS="-Zsanitizer=address"
>      export RUSTDOCFLAGS="-Zsanitizer=address"
>      cargo +nightly build
>      ./target/debug/your_program
>      ```
> 
>    - Note that AddressSanitizer support might require a nightly compiler and additional setup.

**Comment by dpc** [comment]
Heaptrack

![image](https://github.com/user-attachments/assets/13dd3000-3412-4ba0-8bd5-e8eafefd0d92)

**Comment by dpc** [comment]
Looks like a typical case of C++ developer deluding themselves that they can keep track of allocations manually.

**Comment by dpc** [comment]
![image](https://github.com/user-attachments/assets/408a2d79-b685-4f52-b2e6-d2c04c029fa3)

**Comment by dpc** [comment]
Looking more into it ... it might just be a block cache.

**Comment by dpc** [comment]
Ehh, without the same workload, this is all kind of pointless.

**Comment by elsirion** [comment]
Lots of progress in #6347
