### ISSUE TITLE
Add alternative fee estimators

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#6378]
Bitcoin core is very bad at estimating fees and will, from time to time, vastly overestimate.

![IMG_20241116_101254_515](https://github.com/user-attachments/assets/8e9158a8-4dfd-42cc-830a-b2c5e866777a)
![IMG_20241116_101359_544](https://github.com/user-attachments/assets/6fba6943-e746-4b69-afa4-6c6c716bc6ea)

**Comment by FediNihal** [comment]
A Fedian recently reported the issue above with the following description: 
"I made a transfer of $8 and he deducted $85 in commission Is that possible"

**Comment by elsirion** [comment]
Also, we should not fall back to 1sat/vbyte if the fee rate service is down.

**Comment by dpc** [comment]
Done.

**Comment by elsirion** [comment]
Was fixed in https://github.com/fedimint/fedimint/pull/6512
