### ISSUE TITLE
Get feerates from somewhere that doesn't suck (like bitcoind)

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#6425]
`bitcoind`'s fee estimation is bad, and it often leads us to multiply inflated feerates even more, and sky-high peg-in/peg-out tx fee-rates.

We should probably collect recommended fee-rates from multiple sources and take a median of them, with some ability to disable some of these if needed.

**Comment by elsirion** [comment]
Dup https://github.com/fedimint/fedimint/issues/6378
