### ISSUE TITLE
Make gateway password required on first startup

### ISSUE THREAD

**Issue by tvolk131** [fedimint/fedimint#6427]
When starting the gateway, we call `Gateway::get_gateway_configuration()` which loads the `GatewayConfiguration` from the DB if it exists, and attempts to create one and save it to the DB if it doesn't exist yet:

https://github.com/fedimint/fedimint/blob/c660335d1e48f1d0909d66b4aaf0ac68731638a5/gateway/ln-gateway/src/lib.rs#L1737-L1772

It can return `None`, but only if a gateway config isn't present in the DB _and_ a password is not provided in the `GatewayParameters`:

https://github.com/fedimint/fedimint/blob/c660335d1e48f1d0909d66b4aaf0ac68731638a5/gateway/ln-gateway/src/lib.rs#L1749

If we instead panicked on this condition, requiring the gateway operator to provide a password when starting up a brand new gateway for the first time, we would be able to significantly simplify the gateway, including removing the [`GatewayState::Configuring`](https://github.com/fedimint/fedimint/blob/c660335d1e48f1d0909d66b4aaf0ac68731638a5/gateway/ln-gateway/src/lib.rs#L173) state and changing the type of [`Gateway::gateway_config`](https://github.com/fedimint/fedimint/blob/c660335d1e48f1d0909d66b4aaf0ac68731638a5/gateway/ln-gateway/src/lib.rs#L212) from `Arc<RwLock<Option<GatewayConfiguration>>>` to `Arc<RwLock<GatewayConfiguration>>` which allows for lots of downstream simplifications.

**Comment by m1sterc001guy** [comment]
Historically, the gateway did not have a database so the only way to provide the password was via an environment variable. When we added a database, we wanted to maintain backwards compatibility and allow devimint to still provide the password via the environment variable. That's how we ended up here, which I agree is not super clean.

I would actually be more in favor of not allowing the user to specify the password via an environment variable at all and require them to do set it the first time the gateway boots, which would then get persisted in the database. We would still keep the `Configuring` state, but I believe a lot of the other simplifications mentioned here can also be done if we do that.

I don't really like forcing the user to set the password via an environment variable that then gets persisted to the database. Because after the first boot of the gateway, that environment variable is now useless which I think is confusing to the operator (i.e they might think it still does something).

**Comment by elsirion** [comment]
> I don't really like forcing the user to set the password via an environment variable that then gets persisted to the database. Because after the first boot of the gateway, that environment variable is now useless which I think is confusing to the operator (i.e they might think it still does something). 

One problem the gateway has that `fedimintd` doesn't is that it might already be connected to a funded LN node on startup, so it's not safe to stay in an "uninitialized" state, where anyone can just set a password and become admin. Even for `fedimintd` that's not ideal.

I like how for example Nodana generates a random password for you when setting up a gateway ([gateway service](https://nodana.io/services/gatewayd) not publicly announced and broken right now, but [guardians](https://nodana.io/services/fedimintd) work great!). That's a use case we should still support imo, the way we do it might not be env vars though and should make clear it's only an initial thing (or we pull the password out of the config and just always use the supplied one).

One thing we could improve is allowing the password to be supplied pre-hashed. That way the password env var could be safely set in config that is world-readable (e.g. nix config).

**Comment by tvolk131** [comment]
> One thing we could improve is allowing the password to be supplied pre-hashed

We salt passwords before hashing to prevent rainbow table attacks, so allowing pre-hashed passwords would require the user to do the salting and hashing themselves, then provide the salt and the hash. Do we want to allow for the offloading of password salting to the gateway operator/service provider?

**Comment by elsirion** [comment]
Deep dive call:

* We can reduce complexity by now by removing the "set password" functionality and just setting the password hash via an env variable
* The password hash should use a common format that includes the algorithm, salt and hashed password
* Manmeet: the server-side password hashing might be a DoS vector
  * Eric: JWT authentication (#6147) and rate limiting should fix this

**Comment by m1sterc001guy** [comment]
> The password hash should use a common format that includes the algorithm, salt and hashed password

How is this enforced if the password hash is just supplied via an environment variable?

**Comment by tvolk131** [comment]
> How is this enforced if the password hash is just supplied via an environment variable?

Bcrypt defines a [format ](https://en.wikipedia.org/wiki/Bcrypt#Description) for hash strings that includes a configurable hash algorithm, hashing cost, and the salt in addition to the raw password hash. Accepting a bcrypt hash as an env var should give is everything we need, while outsourcing the decision of hash cost and hash algorithm to the gateway operator.

**Comment by tvolk131** [comment]
Chatted with @m1sterc001guy offline. Here are the auth options we discussed:

* Password provided through env var only, remove gateway db password. Gateway panics if env var not provided. This is what we're doing in #6482
* Password always stored in gateway db. Can be provided by env var or API on initial boot. After being written to gateway db, env var is ignored and the password can only be modified through the API, by providing current password. Lightning credentials _must_ be provided alongside initial password, whether through env vars or the API.
* Password can come from gateway db or env var. Default to gateway db if both are present. This is what we're currently doing on master.

@elsirion thoughts?

**Comment by elsirion** [comment]
I think for the next year we don't really need the password changing functionality. The benefit of only having one way of setting the password (i.e. the pure env var variant) is reduced code complexity, reduced confusion when deploying which password is actually in use and it's also easily changeable by someone with access to the machine where the gw is deployed (i.e. without manually writing to the gateway DB).

**Comment by m1sterc001guy** [comment]
Haha I don't think there's much use in disagreeing here, I see this as a minor issue, so I will relent :)

Let's go with the first approach that is implemented in @tvolk131's PR.
