### ISSUE TITLE
`nix flake show --all-systems --json --show-trace` fails

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#6428]
https://github.com/fedimint/fedimint/actions/runs/11942412321/job/33289396131

A `cross` dev shell on a aarch64-linux system fails to evaluate because we're missing something w.r.t cross-compiling to x86_64-android on that platform...

**Comment by elsirion** [comment]
Weird, we [are able to build these targets in CI](https://github.com/fedimint/fedimint/actions/runs/11941435473/job/33286387424), but somehow can't create a dev shell for them? Any idea what the reason could be (you mention fixing it in flakebox)?

**Comment by elsirion** [comment]
I got nerd-sniped into debugging this and came up with one possible solution. Still not the most elegant, but pragmatic imo.
