### ISSUE TITLE
`find_by_range` improvements

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#6431]
We recently discussed the order of elements returned by `find_by_range`, when thinking about #6191 it occurred to me though that we also need a way to use half-open ranges.

My first instinct was to make both the lower and the upper bound optional:

```rust
    async fn find_by_range<K>(
        &mut self,
        start_inclusive: Option<K>,
        end_exclusive: Option<K>,
        direction: IterationDirection, // optionally also make direction configurable
    ) -> Pin<Box<maybe_add_send!(dyn Stream<Item = (K, K::Value)> + '_)>>
    where
        K: DatabaseKey + DatabaseRecord + MaybeSend + MaybeSync,
        K::Value: MaybeSend + MaybeSync;
```

but then it occurred to me that the only thing you really need is a function that *always* has a start element and from that we can build anything:

* The case where we want to start from the beginning/end is covered by `find_by_prefix[_rev]`
* The case where we want to start from a specific element is covered by `find_by_range`
* By default, there is no defined end
* If a defined end is required we can use [`take_while`](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.take_while) to limit the stream (or `take` if we want a certain number of elements)

The new API taking this into account looks as follows:

```rust
    async fn find_by_range<K>(
        &mut self,
        start_inclusive: K,
        direction: IterationDirection,
    ) -> Pin<Box<maybe_add_send!(dyn Stream<Item = (K, K::Value)> + '_)>>
    where
        K: DatabaseKey + DatabaseRecord + MaybeSend + MaybeSync,
        K::Value: MaybeSend + MaybeSync;
```

Thoughts @dpc, @m1sterc001guy?

**Comment by dpc** [comment]
https://docs.rs/redb/latest/redb/trait.ReadableTable.html#tymethod.range prior work

**Comment by elsirion** [comment]
Deep dive: Can be avoided through a data model change for now.
