### ISSUE TITLE
Back-compat failing gateway ecash balance check

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#6461]
Back-compat vs v0.4.4 fails the balance check after paying an invoice with the following error

```
1368   │ 00:01:04 Error: Client balance changed by 2020000 on LND outgoing payment, expected 2_000_000
1369   │ ## FAIL: devimint_cli_test (FM: current, CLI: current, GW: v0.4.4)
```

To reproduce, checkout [`2024-11-gw-balance-back-compat-failure`](https://github.com/bradleystachurski/fedimint/tree/2024-11-gw-balance-back-compat-failure) then run

```
FM_DEVIMINT_DISABLE_MODULE_LNV2=1 just test-compatibility
```

This is the line with the failing check

https://github.com/bradleystachurski/fedimint/commit/aa9824b09b2634ca22d24cf89dc7be40efdde3b6#diff-75cef4315751be4fa6703860684a38e9c382d522c05f6df275846e94a373562dR980

The difference is off by exactly 1%, which seems notable. We also have the same failing check for other invoice payments in `cli_tests`.

The branch is configured to run only the `devimint_cli_test` for FM: current, CLI: current, GW: v0.4.4. To change the versions, please refer to this diff

https://github.com/bradleystachurski/fedimint/commit/20c20a2f50419b058029d4c7480cea9c093683bc#diff-6f67d3a8330a3c924847c4e3e44fa893ed4178fee92b9bfeba68fd6fdbaff5ecR198

@tvolk131 thanks for volunteering to continue the investigation! Please feel free to reach out with any questions.

**Comment by m1sterc001guy** [comment]
Discussed offline and @bradleystachurski discovered that this was due to an environment variable name change, which made it the gateway defaulted back to fees of 1%. Setting the environment variable correctly fixes the issue

**Comment by bradleystachurski** [comment]
Fixed by https://github.com/fedimint/fedimint/pull/6525
