### ISSUE TITLE
Check if we can move off forked deps

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#65]
Some of the changes MiniMint needs have landed upstream by now, check if we can get rid of some of our forks of:

* rust-secp256k1[-zkp]
* bitcoin_hashes

**Comment by justinmoon** [comment]
I attempted this and failed. 

- secp256k1_zkp still needs to merge https://github.com/ElementsProject/rust-secp256k1-zkp/pull/48
- bitcoin_hashes needs to release another version containing https://github.com/rust-bitcoin/bitcoin_hashes/commit/f1084bf63b518f76d1f77abe7709ceabd4ef65ee

Pushed my incomplete changes to [a branch](https://github.com/justinmoon/minimint/tree/upgrades)

**Comment by dpc** [comment]
Closing as done long time ago.
