### ISSUE TITLE
Separate perfit metrics for back-compat merge queue and PR push

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#6545]
We're now running back-compat vs one version on PR push and three versions in the merge queue. We should add an additional perfit metric to track these runs separately, otherwise reusing the single metric will appear noisy.

@dpc if you have bandwidth to generate the perfit id I'll put up a PR to conditionally use the correct perfit metric.

**Comment by dpc** [comment]
@bradleystachurski `90S3yoXDQ-SXB0UbXG4qHQ`
