### ISSUE TITLE
Generic `await` bash function

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#665]
See https://github.com/fedimint/fedimint/pull/661#discussion_r979843619

By my count our [lib.sh](https://github.com/fedimint/fedimint/blob/master/scripts/lib.sh) has 5 separate `until ... do sleep $POLL_INTERVAL done` blocks. We could write a single `await <condition>` function which does the sleeping and call this directly in these 5 cases.

**Comment by blakejakopovic** [comment]
I've taken a stab at this and have a forked [commit](https://github.com/blakejakopovic/fedimint/commit/c714189ca87142626db5a2e9eae1916c5e8c47dc) ([patch](https://github.com/blakejakopovic/fedimint/commit/c714189ca87142626db5a2e9eae1916c5e8c47dc.patch)) pending feedback before I submit a PR here. Was this is intended approach? Do we know why a mix of single and double square brackets were used for the conditions? - happy to standardise on either.

I've tested it a few ways in isolation, however I don't have full fedimint dev environment setup - so it would benefit from further testing. The following scripts (possibly incomplete) appear to be impacted by the following `lib.sh` refactor - I'd be grateful if anyone can assist in testing while I get a dev environment setup.

```
scripts/cli-test.sh
scripts/clientd-tests.sh
scripts/setup-tests.sh
scripts/tmux-user-shell.sh
```

**Comment by dpc** [comment]
We're rewriting in Rust, we can have a real `await` now.
