### ISSUE TITLE
Fixture Builder

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#666]
@jkitman, @NicolaLS and @okjodom had a discussion about using the "builder pattern" to build fixtures in this way:

```
Fixtures::new()
  .with_mint(<denominations>)
  .with_lightning()
  ...
```

We decided to defer until we have a better idea idea of exactly how this should work. We're going to use methods inside `UserTest`, `LightningTest`, etc to change behavior of the fixtures during tests.

**Comment by dpc** [comment]
This has been iterated over since the issue was created. Closing as not actionable.
