### ISSUE TITLE
tmuxinator should have millisat denominations

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#674]
Tmuxinator stops at 1 sat as minimum denomination. In the interest of not confusing new users, we should probably have 1, 10, and 100 millisat denominations. Errors about "unbalanced transactions" will confuse new people.

**Comment by elsirion** [comment]
There should probably be a check when generating config that you need `1msat` as a denomination since we assume that each amount can be constructed without change (so just having -2 and 3 to construct 1 wouldn't work with our coin selection).
