### ISSUE TITLE
Add way to generate JSON schema for all API/DB structs

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#700]
Once there are real deployments we will have to write migrations and keep the API versioned/consistent. To make sure no changes happened or to see when/what happened it would be good if we could generate schemas for all our DB persisted and API transmitted structs.

Probably easiest via [`schemars`](https://docs.rs/schemars/latest/schemars/).

**Comment by justinmoon** [comment]
Closing this for now
