### ISSUE TITLE
Workshop / demo tooling

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#710]
We'll be giving workshops at a handful of conferences in the coming months.

Participants should be able to run `fedimintd` on separate hosts and connect to eachother and form a federation.

There needs to be at least one `bitcoind` node running which all participant `fedimintd` instances can do JSON-RPC with. 

There needs to be one lightning node running a gateway, and another node that's a [faucet](https://github.com/fedimint/faucet) which people can send and receive lightning. There should also be some kind of bitcoin faucet so people can get some sats and do pegins / pegouts.

These tools should overlap as much as possible with existing signet deployment so that they're easier to maintain.

Ideally, people don't have to install nix, build a nix environment, and compile everything themselves. For HCPP we tried using Docker, but perhaps just starting to share releases of `fedimintd`, `ln_gateway`, and `mint-client-cli` would be better?

**Comment by NicolaLS** [comment]
I think setting it up with Docker/Docker-Compose is a good idea. We can take inspiration from the [lnbook](https://github.com/lnbook/lnbook/tree/develop/code/docker).

**Comment by dpc** [comment]
We have OCI (aka Docker) container builds, and a lot of improvements have been made.

Closing as nothing distinctly actionable.
