### ISSUE TITLE
Gateway Design Proposal

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#714]
We have a working gateway based on CLN plugin and assumptions of serving a single federation. However, to open ground for further development of the gateways, I believe we need to re-architect the gateway primarily to open ground for resolving the issues below:

- [ ] #699 
- [ ] #6 
- [ ] #664 
- [ ] #481 
- [ ] #310 
- [ ] #524 

cc @justinmoon , @elsirion , @dpc , @NicolaLS

**Comment by okjodom** [comment]
In leading this discussion, I propose a new gateway component architecture with details below:
![GatewayComponentDiagram](https://user-images.githubusercontent.com/11217077/193366211-caac6425-d147-4880-8e20-04149503007a.png)

**Comment by okjodom** [comment]
## LnGateway
As the main gateway structure, it comprises of the following components
- **LnRpc**  lightning rpc - agnostic of implementation
- **webserver** - A webserver with REST api to perform some gateway actions. Currently this is a single `/pay_invoice`
- **gateway actor** - A task executioner that reacts and responds to requests from  the *ln rpc**, **webserver** or direct actor API calls. See details on the gateway actor below

### LnGateway API
- `register_ln_rpc(rpc_factory)` - instructs the gateway instance to
   - create and register an **ln rpc**. Assuming the gateway can only support a single **ln rpc** at a time, the new instance would replace any old instances.
   - start a **webserver** at  a port binding known to the ln rpc.
- `register_federation(config)` - instructs the gateway to register an federation, the same way other clients do. Under the hood we,
   - create a new federation client with these configs. The client is created within the dedicated scope of a  new **gateway actor**
   - call `register_with_federation()` on the new gateway client to complete gateway registration

**Comment by okjodom** [comment]
## Gateway Actor
This is the execution unit containing all gateway business logic. Specs:
- Each actor has a 1:1 mapping with a federation that the gateway serves
- Groups of actors can coordinate to complete a Gateway "self payment" scenario

### Gateway Actor API
It has the following API (currently defined)
- `pay_invoice()` - pay invoice to complete an outgoing contract
- `buy_preimage_offer()` - buy preimage to complete an incoming contract
- `await_preimage_decryption()`
- `await_outgoing_contract_claimed()`

**Comment by okjodom** [comment]
## Data flows within the Gateway

Data flows between discrete gateway components over messaging channels.  There are three messaging scenarios as follows:

- LnRpc [Plugin]       <---> Gateway Actor
- Webserver             ---> Gateway Actor
- Gateway Actor (A) ---> Gateway Actor (B)

### Selecting Actors when Messaging
With support for multiple actors, a challenge exists in determining which actor to talk to. For this, LnGateway could include a **message router** messaging module, functioning to select which actor to direct a message at.

* NOTE: The messaging challenge only exists in one direction, when messaging from any component into an actor.

**Comment by NicolaLS** [comment]
Very nice!

**Comment by justinmoon** [comment]
Another question is what happens when the plugin is restarted. Will it remember the federations it was connected to or won't it? Currently it only knows which federations it's connected to because a config is passed as a CLI argument.

Again, I would err on the side of simplicity. Perhaps we could pass multiple config files to the CLN? This way it wouldn't be stateful.

**Comment by okjodom** [comment]
>  don't see the point of having multiple GatewayActor threads running concurrently. I think it would be better to just have one, but have it maintain a map of federation id -> GatewayActorCore { ln_client, federation_client }. Then it could route messages itself without any need to send across a channel to another thread.
I think this is conceptually simpler and does everything we need.

I'm also leaning towards this. So will look into simplifying the implementation

**Comment by okjodom** [comment]
> Another question is what happens when the plugin is restarted. Will it remember the federations it was connected to or won't it? Currently it only knows which federations it's connected to because a config is passed as a CLI argument.

Config persistence is a reasonable spec. A restart should result in the gateway building clients/actors representing previously registered federations. Presently I'm thinking the gateway can persist to a local storage or db of some sort What do user client applications use for state persistence?

This is a follow up task

**Comment by justinmoon** [comment]
I guess a more fundamental question than persistence is how to tell the CLN plugin about multiple federation configs in the first place. Perhaps the `--fedimint-cfg` argument to the CLN plugin can take comma-separated list of paths?

**Comment by okjodom** [comment]
closed!
After #869 , the major pieces of this design proposal are in, with some gaps for improvement :) 🥳
