### ISSUE TITLE
Spend (via sigpay.sirion.io): Invoice expired but fm-sats deducted from fluttermint wallet

### ISSUE THREAD

**Issue by yojoe** [fedimint/fedimint#720]
Everytime I spend fm-sats to pay sigpay.sirion.io invoices, the fm-sats are immediately deducted from my fluttermint wallet, but never seem to reach the BTCPay Server (sigpay.sirion.io). How is that even possible? I thought the LN Gateway can only redeem the fm-sats once it received the payment hash from the target (BTCPay Server)?

 
<img width="365" src="https://user-images.githubusercontent.com/58518123/193410862-1370162c-f9b6-46ad-b04c-2d5135162830.jpg"> <img width="365" src="https://user-images.githubusercontent.com/58518123/193410746-c8892b77-d5a3-486a-9650-eae1b96c5904.png">

**Comment by justinmoon** [comment]
Transferring issue to fluttermint repo https://github.com/futurepaul/fluttermint/issues/91

**Comment by justinmoon** [comment]
Reopening because I can replicate on command line.

```
$ git fetch origin

# this is the branch that the signet deployment is using
$ git checkout hcpp 

$ cargo run --bin fedimint-cli faucet join-federation '{"members":[[0,"wss://fm-signet.sirion.io:443"]]}'

$ run --bin fedimint-cli faucet ln-invoice 1000 foo

# pay this invoice on faucet.sirion.io

$ cargo run --bin mint-client-cli faucet wait-invoice <invoice>

$ cargo run --bin mint-client-cli faucet fetch

# generate invoice on faucet's BTCPay, attempt to pay it
$ cargo run --bin mint-client-cli faucet ln-pay <btcpay-invoice>
{
  "ln_pay": {
    "contract_id": "6777ff8a78cb752841be55e78087bf8dfe703d872d543c3a6cd8617bcb36c24a"
  }
}
```

**Comment by justinmoon** [comment]
This should fix it https://github.com/fedimint/fedimint/pull/722

Basically what's happening is that you have ecash tokens in an "outgoing contract". They're waiting for gateway to claim them. We had a bug in our client library function which tells the gateway about this outgoing contract which returned `Ok` when it shouldn't have. Fluttermint should refund you these sats after a 300 block timeout from when you first attempted to pay. The UI doesn't explain what's going on very well, yet.

**Comment by justinmoon** [comment]
Related problem, signet deployment currently reporting the wrong hostname for it's gateway:

```
$ cargo run --bin fedimint-cli faucet list-gateways   
{
  "list_gateways": {
    "num_gateways": 1,
    "gateways": [
      {
        "active": true,
        "api": "http://127.0.0.1:8080/",
        "mint_pub_key": "eeb7d84a33f22cd994b77aa4227612aa521e17b940bfa781907f9a22f372b7a0",
        "node_pub_key": "0307238136c48cd35084c4efadc486143a7e8a7acd8ff8ac053fdab4efabc551c4"
      }
    ]
  }
}
```

**Comment by elsirion** [comment]
Fixed.

```
{
  "list_gateways": {
    "num_gateways": 1,
    "gateways": [
      {
        "active": true,
        "api": "https://fm-signet-gateway.sirion.io/",
        "mint_pub_key": "eeb7d84a33f22cd994b77aa4227612aa521e17b940bfa781907f9a22f372b7a0",
        "node_pub_key": "0307238136c48cd35084c4efadc486143a7e8a7acd8ff8ac053fdab4efabc551c4"
      }
    ]
  }
}
```

**Comment by justinmoon** [comment]
This was fixed by https://github.com/fedimint/fedimint/pull/722 and re-deploying signet federation
