### ISSUE TITLE
Ability to set a rust log level of core-lightning gateway plugin 

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#721]
For signet deployment @elsirion is using the following shell script as the actual plugin in order to set a log level. There must be a better way!

<img width="585" alt="image" src="https://user-images.githubusercontent.com/4335621/193422268-be41f7cb-4002-42f2-bc2c-9102488c88ef.png">

**Comment by elsirion** [comment]
Some ideas to improve debugability:
* CLN config flag for log level
* API call to set log level on the fly (needs to be protected somehow, so maybe as CLN command?)
* Log to file
* Log to Jäger via Open Telemetry

**Comment by okjodom** [comment]
We only need to use the [CLN plugins logger](https://github.com/ElementsProject/lightning/blob/bc9333ac1e317a2baf3e595b2475963c86768b23/plugins/src/logging.rs#L40) which can be turned on via `CLN_PLUGIN_LOG` env variable
