### ISSUE TITLE
Look into telemetry reprting with `tracing`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#74]
We already use [`tracing`](https://docs.rs/tracing/latest/tracing/) for logging, but could be producing more structured and thus useful data that could be displayed in e.g. OpenTelemetry "clients". This could significantly improve debugging, especially performance.

**Comment by elsirion** [comment]
Relevant presentation https://www.youtube.com/watch?v=6iz9xCCPNPA

**Comment by justinmoon** [comment]
@Maan2003 Could you give us an update on progress here?

**Comment by Maan2003** [comment]
It is mostly implemented: server has open telemetry support, and integration tests has chrome tracing support. The instructions are documented in `docs/telemetry.md`.

Regarding structured logging, it is pretty decent now. But I improve the structure whenever I see issues (like #1357)

**Comment by justinmoon** [comment]
OK let's just close this and re-open more specific issues as we go 👍
