### ISSUE TITLE
Gateway Testing

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#742]
Kicking off an issue to track integration and unit tests for more resilient and performant gateways.

We could improve test coverage by adding tests in the following high-level categories:
- [x] Gateway validation of transaction outcomes: _validate gateway does not lose funds_
- [ ] Gateway + federation integration: _validate gateways integrate with one or more federations_
- [x] Gateway + LN integration: _validate gateway can use any ln implementation_
- [ ] Gateway performance: _gateway are performant when executing functions_
- [ ] Gateway reliability: _gateways can reliably handle load from one or more federations_
- [x] Gateway security: _gateway webserver authentication infra is locked down tight, providing above board security by default to the funds held by the gateway in federations_

**Comment by okjodom** [comment]
At present, we have the following integration tests

1. `lightning_gateway_pays_internal_invoice` - [ **disabled** ]
  - category: *gateway behavioural*
  - validates implementation of internal payment within the gateway
  - internal payments should be shifted to client side, as discussed in #613 

2. `lightning_gateway_pays_outgoing_invoice`
  - category: *gateway + lightning behavioural*
  - validates gateway use of a lightning node to pay outgoing invoice

3. `lightning_gateway_claims_refund_for_internal_invoice`
  - category: *gateway behavioural*, status: *unfinished*
  - validates that a gateway claims refunds when it fails to buy preimage offer.
  - assert?: gateway should not lose money

4. `receive_lightning_payment_valid_preimage`
  - category: *gateway + lightning + fed behavioural*
  - validates gateway can receive a lightning payment on behalf of fed user, when preimage is valid
  - assert?: gateway should not lose money

5. `receive_lightning_payment_invalid_preimage`
  - category: *gateway + lightning + fed behavioural*
  - validates gateway rejects request to pay a lightning payment on behalf of fed user, when preimage is invalid
  - assert?: gateway should not lose money

6. `lightning_gateway_cannot_claim_invalid_preimage`
  - category: *gateway + fed behavioural*
  - validates the federation rejects request by federation client to be paid for an outgoing contract when the preimage presented is invalid
  - assert?: gateway cannot cheat the federation
  - implement?: same, redundant test from federation's perspective

7. `lightning_gateway_can_abort_payment_to_return_user_funds`
  - category: *gateway behavioral*
  - validates gateway cancellation of an outgoing invoice, and returning funds to user
  - assert?: user should not lose funds

**Comment by justinmoon** [comment]
A lot of this is done. Closing. We should create more targeted issues for future improvements.
