### ISSUE TITLE
`cln-rpc` improvements

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#748]
https://github.com/ElementsProject/lightning/pull/5258 just landed, I should look into where this will help us and prepare a PR for when the next version is released.

**Comment by justinmoon** [comment]
Related to #199

**Comment by m1sterc001guy** [comment]
Closing this since I don't think its relevant anymore. @elsirion feel free to re-open if you think this is still applicable after the migration to `gatewayd`
