### ISSUE TITLE
Enforce offer expiry

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#749]
https://github.com/fedimint/fedimint/pull/727#discussion_r989130513

**Comment by elsirion** [comment]
@joschisan does your LN NG protocol have a way to limit the lifetime of offers?

**Comment by joschisan** [comment]
> @joschisan does your LN NG protocol have a way to limit the lifetime of offers?

Not yet. However it would be simple to bind an expiration time (in blocks) to a encrypted preimage so the federation will only decrypt it before the expiration.

**Comment by elsirion** [comment]
Yes, please add that, otherwise the GW could receive money on behalf of the user after the user isn't checking for the contract anymore because they think the invoice expired.

**Comment by m1sterc001guy** [comment]
Fixed with LNv2. Expiration is bound in the commitment.
