### ISSUE TITLE
Update `rand` to common version

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#75]
We currently mostly use rand `0.6` and `0.8` for `bls12-381`, ideally we could switch to a common, up to date version. For this we need to:

- [ ] investigate why [`rust-bitcoin`](https://github.com/rust-bitcoin/) is still on `0.6`, probably MSRV but maybe `rand-core` can fix some problems
- [ ] update [`hbbft`](https://github.com/fedimint/hbbft) which entails upgrading their whole crypto ecosystem

**Comment by dpc** [comment]
I tried and:

> Unfortunately seems blocked on `bitcoincore-rpc` pulling in previous `bitcoin` version, which pull in old `secp256k1` which is still on `rand = 0.6`

**Comment by dpc** [comment]
Seems there's already a PR for that: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/234

**Comment by tcharding** [comment]
later version of rand require MSRV bump in `rust-bitcoin` stack, all of which have been done except `rust-bitcoincore-rpc`, open PR: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/222
