### ISSUE TITLE
Stable federation identity

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#754]
Talking with @okjodom and @jkitman about #664, when a gateway recieves a new message from either CLN or the webserver, it needs to figure out which federation to attempt this action with. Currently there are 2 options:

1) Attempt to do this for every federation they're attached to. 
2) Use a threshold pubkey to identify which federation this action is targeting.

(1) is wasteful and the pubkey in (2) changes when federation guardian is added or removed. It would be good to have a way to identify a federation that was stable across guardian set changes.

**Comment by elsirion** [comment]
Stability on guardian set changes seems like premature optimization to me right now. There are still many things to figure out, adding one to the list won't hurt too much.

**Comment by yojoe** [comment]
My initial thought is: "stable" federation identity is an illusion when the guardian set is allowed to change. What could be achieved is that a remaining majority of guardians could re-sign the federation "contract" und publish/push an update to the gateway to let them know: "Hey, our federation id changed and is now: <MultiSig-PubKey>".

**Comment by elsirion** [comment]
Right, one could also include the hash of the previous config. If you have the full config chain from genesis to current and each step is signed you know that at each step the transition was at least ok with the guardians. That doesn't mean one should trust it, but it's probably best we can do. I still consider this to be a future problem to solve, not a current one.

**Comment by yojoe** [comment]
> If you have the full config chain from genesis to current and each step is signed you know that at each step the transition was at least ok with the guardians.

That would be similar to what RGB tries to accomplish using "single use seals":
https://www.rgbfaq.com/glossary/single-use-seals
https://petertodd.org/2016/commitments-and-single-use-seals
https://github.com/LNP-BP/LNPBPs/blob/master/lnpbp-0001.md

**Comment by jkitman** [comment]
It might be acceptable to simply treat guardian membership changes as a new federation.  During a membership change there will probably be a period of time when old and new signing keys are in effect, so a user might want to spend ecash from an "old" federation while other users are spending from the "new" federation, even though it's mostly the same peers handling either request.

**Comment by dpc** [comment]
It would make a lot of things more future proof if we just had something reasonable implemented here.

How about generating another N-M threshold key for the sole purpose of being identity key for the federation. The public key will be used as stable identity, and we will never be rotated Thanks to being a public key, the federation can prove who they claim they are by signing some challenge / connection string.

**Comment by elsirion** [comment]
@dpc I like that approach, we shouldn't worry about DynaFed for now imo. Not sure if we want more use of `threshold_crypto` for such things where we could use secp in theory, but might be easiest for now and we can get rid of it in a 2.0.

**Comment by dpc** [comment]
I grew to enjoy `threshold_crypto` crate. (:

We don't have to implement anything about dynafeds, but ideally we should have a sane future upgrade path.

@okjodom You seem to have the most pressing need for stable FedID - do you want to give this a shot? I might get to it later myself, as we need to key federations by something in the multi-fed end user apps.

**Comment by okjodom** [comment]
> @okjodom You seem to have the most pressing need for stable FedID

From the Gateway's perspective, we are **assuming `FederationID` as presently defined is already stable**. We can build a lot on that, with readiness for minor refactors in gateway should the type change it's shape.

@dpc If no-one gets to it, I could pick this up in 3/4 weeks after landing higher priority gateway stuff - because we want to move from assumption to assured stability on the ID

**Comment by jkitman** [comment]
@dpc I like the idea of using a new threshold key to sign updates to the consensus configs that clients can validate.  The signing process could be done as part of consensus.  I guess the only attack vector is we cannot assure the availability of the full history of threshold keys unless the client can reach at least one honest server.

**Comment by justinmoon** [comment]
Really happy to see this issue get closed!
