### ISSUE TITLE
Is struct `FundChannelFixed` still relevant?

### ISSUE THREAD

**Issue by Maaxxs** [fedimint/fedimint#785]
Is this struct still relevant? I don't see it used in the code base.
https://github.com/fedimint/fedimint/blob/c28b5abf03e8dd110603ecb15b062dd88595ad59/integrationtests/tests/fixtures/real.rs#L77

```rs
// FIXME workaround for bad RPC API, should replace when cln_rpc gets updated
#[derive(Debug, Clone, Serialize)]
struct FundChannelFixed<'a> {
    pub id: &'a str,
    pub amount: u64,
}
```

**Comment by dpc** [comment]
Delete, if it compiles please submit a PR. :)

**Comment by Maaxxs** [comment]
It does compile :)
