### ISSUE TITLE
Remove `RngGenerator`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#79]
This was a hack when RNGs were needed during parallel processing of transactions. We can get rid of it either by having a central RNG if no parallel usage occurs anymore after #50 or replace it with `thread_rng` that, as I found out, also appears to be a `CryptoRng`.

**Comment by dpc** [comment]
I don't think we are even passing these rngs anymore so probably no longer applicable.

**Comment by elsirion** [comment]
There still
