### ISSUE TITLE
Authenticate Gateway Webserver

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#807]
By design, the gateway runs a public webserver that supports federation or cli functions like pay-invoice, deposit and withdraw, etc.
These functions are critical, and should be secured before we can release the gateway for mainnet use.

Here are the endpoints currently implemented:
- [ ] `/info` - source general information about the gateway
- [ ] `/balance` - source the current fedimint tokens held by the gateway
- [ ] `/address` - source a bitcoin address usable by the gateway to deposit funds into a federation
- [ ] `/deposit` - deposit funds into a federation
- [ ] `/withdraw` - withdraw the gateways funds from a federation
- [ ] `/pay_invoice` - pay a lightning invoice : usually on behalf of a federation user

**Comment by elsirion** [comment]
To preserve previous semantics everything except `/pay_invoice` should be authenticated. The easiest fix would probably be requiring a bearer token (some sufficiently long random string). [You could use axum-auth for that.](https://docs.rs/axum-auth/latest/axum_auth/struct.AuthBearer.html)

**Comment by okjodom** [comment]
> everything except `/pay_invoice` should be authenticated

makes sense
