### ISSUE TITLE
E2E test lighting receive from Rust integration tests

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#813]
Currently we don't test the CLN plugin at all from Rust. `cli-test.sh` is the only thing that tests it. 

I see 2 options:

- Reload the plugin with new federation configs at runtime. All that would be needed is to translate our [gw-reload.sh](https://github.com/fedimint/fedimint/blob/master/scripts/gw-reload.sh) script to Rust. It just (1) stops the gateway plugin (ignoring error if it isn't running) and (2) loads the plugin passing in the path to our config. The Rust code could either save the config somewhere in `/tmp` or add separate CLI / RPC command to the plugin which takes the raw JSON as an argument.
- Alternatively, we could add an authenticated call to the webserver to do this which would work with LND, too.

This would help move us towards https://github.com/fedimint/fedimint/issues/812

**Comment by elsirion** [comment]
After the migration to the new architecture by @okjodom we should be able to test the functionality of the GW without actually spawning it with a node. We should be able to mock out the LN node and the web server.

**Comment by justinmoon** [comment]
True, but I think it would still be nice to get rid of the shell scripts and have total end-to-end tests

**Comment by justinmoon** [comment]
Closing this because it's kind of outdated. @okjodom doing new gateway tests and we can work this in that effort.
