### ISSUE TITLE
Persist gateway configurations

### ISSUE THREAD

**Issue by okjodom** [fedimint/fedimint#817]
We need a way to persist Gateway configuration beyond restarts.

In particular, #714 proposes a way to register federations on a running gateway. The gateway needs to store any such registrations such that it can restart and resume service to previously registered Federations

**Comment by justinmoon** [comment]
I think the way to do this for now is to assume that the `lightningd` or LND HTLC interceptor CLI arguments include all this information.

For example, `--fedimint-cfgs=<federation 1 config dir>,<federation 2 config dir>` or `--fedimint-cfg=<federation 1 config dir> --fedimint-cfg=<federation 2 config dir>`.

Maybe in the future this could live in the database, but I would just keep it simple for now.

**Comment by elsirion** [comment]
Why the separate config dirs instead of a base dir and sub directories for each federation? The name could be a counter or the hash of e.g. all the pub keys of the members.
