### ISSUE TITLE
Coin selection is inefficient for large wallets

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#82]
While benchmarking I noticed that coin selection is a bottle neck since we load all coins into memory first and then run our algorithm. Coins should probably be saved by denomination instead and retrieved only on demand to increase efficiency. Should be considered in #25 too (prefix search/RocksDB families).

**Comment by NicolaLS** [comment]
I think there would be two approaches: 
1. Reserve const prefixes for a set of (abstract) tiers. Like tier A,B,C users could then specify the tiers when creating the fed but only could use 3 in this example. In this approach there would be very little refactoring needed (just add a "tier" to mint/mod::coins() to specify which prefix to search and a few other things)
2. Have a CoinsByTier(pub Amount) key which can be used to get_value(&CoinsByTier(tier)) to always get/set a list of coins of that specific tier. This approach would be more work to implement imo.

**Comment by NicolaLS** [comment]
(with "users could specify" I don't mean that they would need to do additional stuff but the tiers they set for example 1 10 100 would be mapped A < B < C)

**Comment by justinmoon** [comment]
@jkitman @elsirion What's the status here?

**Comment by jkitman** [comment]
No change afaik, but a lot of time has passed since these benchmarks.

**Comment by elsirion** [comment]
It's not really a problem in practice afaik. I just ran into it when getting benchmarks for my thesis and it turned out the client became the bottle neck instead of the federation. Would still be nice to fix.

**Comment by justinmoon** [comment]
I think https://github.com/fedimint/fedimint/pull/2183 improved this enough to warrant closing this issue. Feel free to re-open @douglaz if you think further improvements are needed.
