### ISSUE TITLE
Make `NotEnoughCoins` error more desriptive

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#847]
When the client can't fund a certain transaction it returns this error (this is from the gateway when trying to withdraw):

```
Federation client operation error: MintClientError(NotEnoughCoins)
```

Two problems:

1. It's inaccurate. Back in the days you might have had enough balance but not enough coins of the right denomination. This hasn't been a problem for a while now so the error should be renamed to `InsufficientBalance`.
2. It doesn't include helpful information like how much was missing or how much value was needed and how much we can afford.

**Comment by vnprc** [comment]
I just submitted a PR to address this issue. I am very new to rust so I welcome constructive criticism. :)

https://github.com/fedimint/fedimint/pull/1067
