### ISSUE TITLE
Investigate adding support for `tokio-console` and `tokio-backtrace`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#865]
* https://tokio.rs/blog/2022-10-announcing-async-backtrace
* https://docs.rs/tokio-console/latest/tokio_console/

Both could help debugging issues and optimizing code.

**Comment by elsirion** [comment]
For Jäger see also: #107

**Comment by ngutech21** [comment]
Support for Jäger and tokio-console has been added. Can this issue be closed or are we still waiting for adding async-backtrace?
