### ISSUE TITLE
Parallelize `rejoin_consensus`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#866]
```rust
    pub async fn rejoin_consensus(&self) {
        for server in &self.servers {
            let mut s = server.borrow_mut();
            s.fedimint
                .rejoin_consensus(Duration::from_secs(1), &mut rng())
                .await;
        }
    }
```

Seems like it could happen in parallel for all servers.

**Comment by joschisan** [comment]
Is that part of the rejoining logic in case a peer has been offline for a prolonged period of time? If so don't bother this will be handled internally by the new broadcast abstraction in the future

**Comment by justinmoon** [comment]
Should we just close this @joschisan @elsirion? IIRC this code gets deleted by AlephBFT change?
