### ISSUE TITLE
CI: Check that LN Gateway receives funds

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#89]
The integration test should wait for the LN Gateway to actually receive the e-cash tokens for its LN payment. This probably requires creating a new (authenticated) API endpoint for LN Gateway operators to query its balance.

**Comment by matthiasdebernardini** [comment]
You are referring to this integration test right?
https://github.com/fedimint/minimint/blob/0a2b472440e9226c15d7828f069f68c290a74506/scripts/integrationtest.sh

**Comment by matthiasdebernardini** [comment]
https://github.com/fedimint/minimint/tree/master/integrationtests

because there is also this

**Comment by matthiasdebernardini** [comment]
https://nigiri.vulpem.com I think we should make use of this, very nice way to run nodes

**Comment by elsirion** [comment]
> You are referring to this integration test right? https://github.com/fedimint/minimint/blob/0a2b472440e9226c15d7828f069f68c290a74506/scripts/integrationtest.sh

Correct, the other one is really new, ideally both would test this.

> https://nigiri.vulpem.com/ I think we should make use of this, very nice way to run nodes

I'm not sure how well it works for automated testing, I kinda hope that @wiredhikari's nix-bitcoin integration project will eventually make other orchestration tools (like the current hacky bash script) obsolete for our CI.

**Comment by justinmoon** [comment]
I think @elsirion is talking about adding an API endpoint [here](https://github.com/fedimint/minimint/blob/21be38357248c162ad3d940810fc73499a065d6d/ln-gateway/src/bin/ln_gateway.rs#L63)

After thinking about this a bit, it might be best to just add unauthenticated ` /balance` to the gateway http server for now. Then we can add authentication in the future once we define how a lightning node can enroll itself as a gateway for a federation. They'd get credentials here, provide an email or something for account recovery, and the federation would save all the public information about the users can find the node. But I don't think authenticating the API makes much sense until that point.

**Comment by justinmoon** [comment]
Regarding the broader question of how to authenticate a gateway HTTP request, maybe we could just have they node pubkey sign the HTTP request or something. Then we don't have to worry about recovering credentials. (idea inspired by this recent conference talk https://twitter.com/skwp/status/1534265886005248006 by @ skwp).

**Comment by matthiasdebernardini** [comment]
I am trying to get ln gateway configgen to run but it gets stuck in this function

https://github.com/fedimint/minimint/blob/35e67eeec220f4ba0ef8b8364d85b5a662f8d73d/minimint-core/src/config.rs#L28

What is the file I am supposed to give look like?

The path that its being given ends with federation_client.json but I dont know what they are supposed to be. Any tips?

Also how does the integration test work without this file?

**Comment by elsirion** [comment]
Cannot reproduce. Are you sure you didn't generate the `federation_client.json` with a different version of MiniMint than when you ran `gw_configgen`? That could explain the error (mismatching config structs between versions). Just try to run `configgen` again to get a `federation_client.json` of the right version/schema.

**Comment by matthiasdebernardini** [comment]
sorry for the radio silence, @elsirion I can now begin with this

**Comment by justinmoon** [comment]
There is now a `lightning-cli gw-balance` command that is added to core-lightning by the gateway core-lightning plugin. You should be able to call that to check that the gateway gets paid.

**Comment by matthiasdebernardini** [comment]
this was closed with https://github.com/fedimint/fedimint/pull/553#event-7362101210

**Comment by justinmoon** [comment]
🎉
