### ISSUE TITLE
Sanity check version numbers and configs when connecting

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#950]
Peers need to be running same software version with compatible configs.

When establishing a new connection, we should do a handshake which checks that:
- We're using same version of software
- Hashes of consensus-relevant parts of server configs (e.g. denominations, threshold pubkey) are the same. This would exclude things like bind addresses which would be different for different peers.
- Crash if any differences detected

**Comment by jkitman** [comment]
We can return consensus config via an API (we need support returning client config as well for handling changes on the client-side).  Upon startup, peers can confirm their consensus config matches other peers.

**Comment by elsirion** [comment]
I think ideally we could calculate a hash from both the `ServerConsensusConfig` and the `ClientConfig` that is guaranteed to be the same for a matching config pair. Then we could just expose that hash via the API and clients as well as other federation members can validate it. Maybe it would also become part of a handshake on the p2p level.

**Comment by justinmoon** [comment]
https://github.com/fedimint/fedimint/pull/1281 was reverted so re-opening until it gets merged again

**Comment by jkitman** [comment]
Fixed by https://github.com/fedimint/fedimint/pull/1388
