### ISSUE TITLE
Split configs into keys, local, and consensus

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#960]
We should split the existing config file into 3 different files:
- keys.conf - encrypted private key material
- local.conf - editable by the user
- consensus.conf - controls the consensus config (will need another PR to use only during consensus upgrades)

We should consider removing unnecessary config values from the command-line config gen (denominations, federation_name, etc) and instead have users edit the relevant files (or provide a generic way to pass in changes via command line).

**Comment by elsirion** [comment]
Maybe have some utility that first creates default `consensus.conf` and `local.conf`, which users then edit and finally call keygen? We'd also need to figure out interactions with the web setup tool.

**Comment by jkitman** [comment]
I think it could work like this:
1. Running DKG via the setup UI would generate all 3 files with default values
2. User could edit the files manually (or eventually through a UI)
3. User starts server which reads from the edited files
4. Federation does a sanity check to confirm consensus values are equal
