### ISSUE TITLE
Introduce coin selection policies

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#962]
Currently our coin selection algorithm always tries to minimize the number of ecash notes in the client database.

But if we wanted to support a feature where, say, people can send ecash notes p2p *offline* with some amount of trust that the other person won't double-spend them, then we might want to keep more coins on-hand because you can't go to the federation to make change when you're offline.

We should introduce some notion of coin selection policies that can achieve this.

**Comment by jkitman** [comment]
Couldn't the sender sign a transaction that pays the other user but also includes change outputs to themselves?

I'm not sure if there is any existing schemes for offline spending of ecash but I wonder if this could work:
- Sender submits a tx to the fed locking up ecash for a period
- Sender gives the receiver an offline tx that spends ecash, but with a special clause pointing at the locked-up ecash
- If when submitting the tx the coins were already spent then the fed revokes the locked-up coins as punishment

Kind of like a fidelity bond with ecash.  The receiver isn't guaranteed to get paid, but can at least punish the sender for at least as much as the payment was supposed to be.

**Comment by elsirion** [comment]
Ideally the scheme would be non-interactive. Scanning one QR code is bad enough already.

**Comment by jkitman** [comment]
> Ideally the scheme would be non-interactive. Scanning one QR code is bad enough already.

Wonder if NFC would be better then?

**Comment by jkitman** [comment]
So I'm thinking the algorithm would try to maximize the sets of notes of every denomination, starting at the smallest.  If we use powers-of-2 denominations then we could always make change so long as we have one note of every denomination.  We could reuse the strategy for LN gateways or gaurdians who need ecash in order to help build the anonymity sets.
