### ISSUE TITLE
"Too many connections" error

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#983]
I just saw this in the logs on testfed:

```
Nov 25 14:17:29 fedimint fedimintd[3866331]: 2022-11-25T14:17:29.479385Z  WARN jsonrpsee_ws_server::server: Too many connections. Try again in a while
```

Responded with a 429 error ...

* We're currently limiting to [100 connections](https://docs.rs/jsonrpsee-server/0.16.1/jsonrpsee_server/struct.ServerBuilder.html#method.max_connections) which is arbitrarily low.
* I don't have nearly 100 different clients. Why aren't connections getting closed?

**Comment by elsirion** [comment]
We need a way to close connections that are idle imo, it's quite possible that these were opened by random bots scanning web servers.
