### ISSUE TITLE
`fedimint-cli` should be able to directly interact with all API endpoints

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#990]
E.g. fetch a LN contract.

**Comment by jkitman** [comment]
Do you think we should expose `QueryStrategy` to be passed into the `WsFederationApi`?  If so, how would the CLI command look?

**Comment by elsirion** [comment]
Right, ideally the CLI tool could actually query single guardians, that would require a query strategy that can be passed to API functions for that use case (I think that would be beneficial either way).

**Comment by elsirion** [comment]
Turns out I had just forgotten about `mint-rpc-client`. I wonder if this functionality should just become part of `fedimint-cli`? Also using it for the use case I opened #991 for doesn't really work:

```
~/projects/minimint$ cargo run --bin mint-rpc-client api-call wss://alpha.demo.sirion.io /ln/account 5b9ac32ee9a75a4581395a99ba745bf735202950b3eb5dac0356a79965703042
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/mint-rpc-client api-call 'wss://alpha.demo.sirion.io' /ln/account 5b9ac32ee9a75a4581395a99ba745bf735202950b3eb5dac0356a79965703042`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("trailing characters", line: 1, column: 2)', client/cli/src/bin/mint-rpc-client.rs:37:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jkitman** [comment]
@NicolaLS do you think making `mint-rpc-client` just another call on `fedimint-cli` makes sense?  Also do you know if we still have tests for it?

**Comment by NicolaLS** [comment]
> 

Would definitely make sense, @elsirion what do you think ? could open a quick/small PR (we already use the `WsFederationApi` in the cli anyway. What do you mean with do we still have tests for it ? the `mint-rpc-client` ?

**Comment by jkitman** [comment]
@NicolaLS Yeah, I thought we created shell script tests for it at one point.
