### ISSUE TITLE
`spend_ecash`  fails if DB tx fails

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#995]
> > Client loses money. https://github.com/fedimint/fedimint/actions/runs/3543886489/jobs/5950840882
> 
> @elsirion Any insight into how this happens or whether it's a real bug?

The `spend_ecash` function seems faulty, `let mut tx = TransactionBuilder::default(); ` should be inside the loop imo so we don't issue the same e-cash token twice if the DB tx fails for some reason (why it would, idk):

https://github.com/fedimint/fedimint/blob/13a0e24e902f63fae682c4e4af6e02069621086a/client/client-lib/src/lib.rs#L460-L499

_Originally posted by @elsirion in https://github.com/fedimint/fedimint/issues/222#issuecomment-1328129597_

**Comment by jkitman** [comment]
Do you know how to recreate this bug?

**Comment by elsirion** [comment]
No, it's more a theoretical concern imo (if you can make the DB tx fail). Looking at it with fresh eyes I'd say it actually doesn't burn the money because the resulting tx after the first round in the loop will be invalid (same coins added as input multiple times).

**Comment by jkitman** [comment]
Where does the magic number 5 come from in `failed_tx_attempts >= 5`?

**Comment by elsirion** [comment]
> Where does the magic number 5 come from in `failed_tx_attempts >= 5`?

Introduced by @m1sterc001guy in 952fb50a6f300f79894f4a918cc6e93a6a3c1c2d.

As a connoisseur of magic numbers I have to say it should have been three though :zany_face: 

> Then shalt thou count to three, no more, no less. Three shall be the number thou shalt count, and the number of the counting shall be three. Four shalt thou not count, neither count thou two, excepting that thou then proceed to three. *Five is right out.*

**Comment by dpc** [comment]
This will get address by switching to a new client model.
